force-app/main/default/objects/Campaign/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <description>Approval status of campaign</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>Objectives of the campaign</description>
    <label>Objective</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateCampaignStatusBatch_Test.cls
@isTest 
public class UpdateCampaignStatusBatch_Test{

    @testsetup
    static void setupData() {
    
    	List<Campaign> campList = new List<Campaign>();

    	//Create a Planned Campaign
    	Campaign camp1 = new Campaign();
    	camp1.Name = CommonConstant.TESTCAMPAIGN;
    	camp1.Status = CommonConstant.PLANNED;
    	camp1.StartDate = Date.today();
    	camp1.EndDate = Date.today().addDays(7);
    	camp1.ApprovalStatus__c = CommonConstant.APPROVED;
        camp1.Market__c = CommonConstant.MARKET_VN;
        camp1.Objective__c = CommonConstant.MARKET_VN;
    	campList.add(camp1);

    	//Create a In Progress Campaign
    	Campaign camp2 = new Campaign();
    	camp2.Name = CommonConstant.TESTCAMPAIGN2;
    	camp2.Status = CommonConstant.IN_PROGRESS;
    	camp2.StartDate = Date.today().addDays(-7);
    	camp2.EndDate = Date.today();
        camp2.Market__c = CommonConstant.MARKET_VN;
        camp2.Objective__c = CommonConstant.MARKET_VN;
    	campList.add(camp2);
    	
    	insert campList;
    }

    public static testMethod  void testUpdate() {
    	System.Test.startTest();
    		UpdateCampaignStatusBatch ucs = new UpdateCampaignStatusBatch();
    		Database.executeBatch(ucs, 200);

    		UpdateCampaignStatusSchedule job = new UpdateCampaignStatusSchedule();
    		String sch = '0 0 23 * * ?'; 
    		system.schedule('Test Campaign Status Batch Job', sch, job);
    		
    	System.Test.stopTest();

    	List<Campaign> inProgressCampaignList = [SELECT Id FROM Campaign WHERE Status = 'In Progress'];
    	List<Campaign> completedCampaignList = [SELECT Id FROM Campaign WHERE Status = 'Completed'];

    	System.assertEquals(1, inProgressCampaignList.size(), 'Campaign with Planned Status should be updated to In Progress.');
    	System.assertEquals(1, completedCampaignList.size(), 'Campaign with In Progress Status should be updated to Completed.');

   	}
}