force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdatePromotionStatusBatch_Test.cls
@isTest
public class UpdatePromotionStatusBatch_Test {

    @testsetup
    static void setupData() {
    
    	List<Promotion__c> promList = new List<Promotion__c>();

    	//Create a Planned Campaign
    	Promotion__c prom1 = new Promotion__c();
    	prom1.Name = 'Test Promotion - A';
    	prom1.Status__c = 'Planned';
    	prom1.StartDate__c = Date.today();
    	prom1.EndDate__c = Date.today().addDays(7);
        prom1.Market__c = 'VN';
    	promList.add(prom1);

    	//Create a In Progress Campaign
    	Promotion__c prom2 = new Promotion__c();
    	prom2.Name = 'Test Promotion - B';
    	prom2.Status__c = 'In Progress';
    	prom2.StartDate__c = Date.today().addDays(-7);
    	prom2.EndDate__c = Date.today();
        prom2.Market__c = 'VN';
    	promList.add(prom2);
    	
    	insert promList;
    }

    public static testMethod  void testUpdate() {
    	System.Test.startTest();
    		UpdatePromotionStatusBatch ucs = new UpdatePromotionStatusBatch();
    		Database.executeBatch(ucs, 200);

    		UpdatePromotionStatusSchedule job = new UpdatePromotionStatusSchedule();
    		String sch = '0 0 23 * * ?'; 
    		system.schedule('Test Promotion Status Batch Job', sch, job);
    		
    	System.Test.stopTest();

    	List<Promotion__c> inProgressPromotionList = [SELECT Id FROM Promotion__c WHERE Status__c = 'In Progress'];
    	List<Promotion__c> completedPromotionList = [SELECT Id FROM Promotion__c WHERE Status__c = 'Completed'];

    	System.assertEquals(1, inProgressPromotionList.size(), 'Promotion with Planned Status should be updated to In Progress.');
    	System.assertEquals(1, completedPromotionList.size(), 'Promotion with In Progress Status should be updated to Completed.');

   	}
    
}