force-app/main/default/objects/Case/fields/CallRegarding__c.field-meta.xml
<CustomField>
    <fullName>CallRegarding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filter to show only Contacts within the Case Contact&apos;s Household</description>
    <label>Call Regarding</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Call Regarding)</relationshipLabel>
    <relationshipName>CallRegarding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/MedicalDiagnosis__c.field-meta.xml
<CustomField>
    <fullName>MedicalDiagnosis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nutrition History</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.CallRegarding__c</field>
            <operation>equals</operation>
            <valueField>Medical_Diagnosis__c.Contact__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Medical_Diagnosis__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Medical_Diagnosis__c/Medical_Diagnosis__c.object-meta.xml
<CustomObject>
    <label>Nutrition History</label>
    <nameField>
        <displayFormat>MD-{000000000}</displayFormat>
        <label>Nutrition History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nutrition Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Diagnosis__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Medical_Diagnosis</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Diagnosis__c/fields/CreatedforIntegration__c.field-meta.xml
<CustomField>
    <fullName>CreatedforIntegration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created for Integration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medical_Diagnosis__c/fields/Medical_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Medical_Diagnosis__c</fullName>
    <label>Medical Diagnosis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bed Ridden- Old Age</fullName>
            </value>
            <value>
                <fullName>Cancer (All types of Cancer)</fullName>
            </value>
            <value>
                <fullName>Child with Special Needs</fullName>
            </value>
            <value>
                <fullName>Constipation</fullName>
            </value>
            <value>
                <fullName>Crying</fullName>
            </value>
            <value>
                <fullName>C-section</fullName>
            </value>
            <value>
                <fullName>Diarrhea</fullName>
            </value>
            <value>
                <fullName>Eye, Ears, Nose, Throat Condition</fullName>
            </value>
            <value>
                <fullName>Family History of Diabetes</fullName>
            </value>
            <value>
                <fullName>Flatulence</fullName>
            </value>
            <value>
                <fullName>For Normal &amp; healthy person</fullName>
            </value>
            <value>
                <fullName>Gastrointestinal Disease</fullName>
            </value>
            <value>
                <fullName>Geriatric Conditions (Alzheimer/Parkinson Disease)</fullName>
            </value>
            <value>
                <fullName>Gestational diabetes</fullName>
            </value>
            <value>
                <fullName>Haemotological Diseases</fullName>
            </value>
            <value>
                <fullName>Heart Disease</fullName>
            </value>
            <value>
                <fullName>Hypercholesterolemia (High Cholestrol)</fullName>
            </value>
            <value>
                <fullName>Hypertension (High Blood pressure)</fullName>
            </value>
            <value>
                <fullName>Insulin Dependant (Type 1 Diabetes)</fullName>
            </value>
            <value>
                <fullName>Muscle Disease</fullName>
            </value>
            <value>
                <fullName>Muscle Mass Loss</fullName>
            </value>
            <value>
                <fullName>Neurological Disease</fullName>
            </value>
            <value>
                <fullName>Non-Insulin Dependant (Type 2 Diabetes)</fullName>
            </value>
            <value>
                <fullName>Osteopenia</fullName>
            </value>
            <value>
                <fullName>Osteoporosis</fullName>
            </value>
            <value>
                <fullName>Post- Surgery</fullName>
            </value>
            <value>
                <fullName>Prediabetes</fullName>
            </value>
            <value>
                <fullName>Renal Disease (CAPD)</fullName>
            </value>
            <value>
                <fullName>Renal Disease (Hemodialysis)</fullName>
            </value>
            <value>
                <fullName>Renal Disease (Pre-Dialysis)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Diagnosis__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Nutrition History</relationshipLabel>
    <relationshipName>Nutrition_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseNutritionHistoryBatch.cls
/*
Author: Frank Gomendoza
Description: Batch job that creates MD (Nutritional History) records to be scheduled hourly daily
*/
global class CaseNutritionHistoryBatch implements Database.Batchable<sObject>, Schedulable{

    global Database.QueryLocator start(Database.BatchableContext BC) {
        Id callRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Call').getRecordTypeId();
        String query = 'SELECT Id, CallRegarding__c, ContactId '
            + 'FROM Case '
            + 'WHERE Market__c = \'' + CommonConstant.MARKET_TW + '\' '
            + 'AND CreatedDate = Today '
            + 'AND RecordTypeId =: callRTId '
            + 'AND MedicalDiagnosis__c = null '
            + 'Order By CaseNumber ';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Case> scope) {
    	if(!scope.isEmpty()){
            List<Medical_Diagnosis__c> createMDRecordsList = new List<Medical_Diagnosis__c>();
            for(Case c : scope){
                Medical_Diagnosis__c md = new Medical_Diagnosis__c();
                if(c.CallRegarding__c != null){
                    md.Contact__c = c.CallRegarding__c;
                }else{
                    md.Contact__c = c.ContactId;
                }
                md.Related_Case__c = c.Id;
                md.CreatedforIntegration__c = true ;
                createMDRecordsList.add(md);
            }
            if(!createMDRecordsList.isEmpty()) UtilityClass.insertList(createMDRecordsList);
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :BC.getJobId()]; 
        System.debug('>>>> finish ' + job.Status);
    }
    
    global void execute(SchedulableContext sc) {
        CaseNutritionHistoryBatch batch = new CaseNutritionHistoryBatch(); 
        Database.executebatch(batch, 1);
    }
}