force-app/main/default/objects/Case/fields/CallTransferReason__c.field-meta.xml
<CustomField>
    <fullName>CallTransferReason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Transfer Reason</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Call Transfer Reason</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Cases (Call Transfer Reason)</relationshipLabel>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CaseAccepted__c.field-meta.xml
<CustomField>
    <fullName>CaseAccepted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Case Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/IsSocialCase__c.field-meta.xml
<CustomField>
    <fullName>IsSocialCase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Social Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AcceptSocialCaseController.cls
public class AcceptSocialCaseController {
    
	@AuraEnabled
    public static String acceptSocialCase(String caseId) {
        if(caseId != null) {
            List<Case> caseRec = [select Id, OwnerId, CallTransferReason__c, CaseAccepted__c, Status from Case where Id = :caseId];
            
            if(!caseRec.isEmpty()) {
                if(caseRec[0].CaseAccepted__c) {
                    return 'Case is already accepted';
                } else {
                	caseRec[0].OwnerId = userInfo.getUserId();
                    caseRec[0].CaseAccepted__c = true;
                    caseRec[0].Status = 'First Level Investigation';
                    update caseRec;
                    return 'case accepted';
                }
            }
        }
        
        return null;
    }
    
    @AuraEnabled
    public static Boolean isSocial(String caseId) {
        if(caseId != null) {
            List<Case> caseRec = [select Id, IsSocialCase__c from Case where Id = :caseId];
            
            if(!caseRec.isEmpty()) {
                return caseRec[0].IsSocialCase__c;
            }
        }
        
        return false;
    }
}