force-app/main/default/objects/Case/fields/CaseAccepted__c.field-meta.xml
<CustomField>
    <fullName>CaseAccepted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Case Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/IsSocialCase__c.field-meta.xml
<CustomField>
    <fullName>IsSocialCase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Social Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Feedback.recordType-meta.xml
<RecordType>
    <fullName>Feedback</fullName>
    <active>true</active>
    <businessProcess>Feedback</businessProcess>
    <description>Cases for customers who have raised feedback or a grievance requiring action by one or more Abbott teams</description>
    <label>Feedback</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Inquiry.recordType-meta.xml
<RecordType>
    <fullName>Inquiry</fullName>
    <active>true</active>
    <businessProcess>Inquiry</businessProcess>
    <description>Cases for customers who have raised an inquiry or question requiring a response by one or more Abbott teams</description>
    <label>Inquiry</label>
</RecordType>

force-app/main/default/classes/AcceptSocialCaseControllerTest.cls
@isTest
private class AcceptSocialCaseControllerTest {
	public static Id fbRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Feedback').getRecordTypeId();
    public static Id iqRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Inquiry').getRecordTypeId();
    
    @testsetup
    static void setupData() {
        List<Account> accList = TestDataFactory.createTestHousehold(1);
		List<Contact> conList = TestDataFactory.createTestAdultContact(1, accList.get(0).Id);
    }
    
    @isTest
    static void testForAcceptCase() {
        List<Account> accList = [select Id from Account limit 1];
		List<Contact> conList = [select Id from Contact where AccountId = :accList.get(0).Id limit 1];
        
        Case c1 = new Case(RecordTypeId = fbRTId, AccountId = accList[0].Id, ContactId = conList[0].Id, Status = 'New', Origin = 'Facebook', IsSocialCase__c = true);
        insert c1;
        Case c2 = new Case(RecordTypeId = iqRTId, AccountId = accList[0].Id, ContactId = conList[0].Id, Status = 'New', Origin = 'Facebook', IsSocialCase__c = true, CaseAccepted__c = true);
        insert c2;
        
        AcceptSocialCaseController.acceptSocialCase(c1.Id);
        AcceptSocialCaseController.isSocial(c1.Id);
        String retVal = AcceptSocialCaseController.acceptSocialCase(c2.Id);
        AcceptSocialCaseController.acceptSocialCase(null);
        AcceptSocialCaseController.isSocial(null);
        
        Case c3 = [select Id, CaseAccepted__c, Status from Case where Id = :c1.Id];
        
        System.assertEquals(true, c3.CaseAccepted__c);
        System.assertEquals('First Level Investigation', c3.Status);
        System.assertEquals('Case is already accepted', retVal);
    }
}