force-app/main/default/objects/Case/fields/ChannelType__c.field-meta.xml
<CustomField>
    <fullName>ChannelType__c</fullName>
    <formula>TEXT(Channel__r.Type__c)</formula>
    <label>Channel Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/recordType__c.field-meta.xml
<CustomField>
    <fullName>recordType__c</fullName>
    <formula>RecordType.Name</formula>
    <label>recordType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/LeadScoring__c.object-meta.xml
<CustomObject>
    <description>Lead Scoring Setting Table</description>
    <label>Lead Scoring</label>
    <nameField>
        <label>Lead Scoring Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Scoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LeadScoring__c/fields/Binary_Value__c.field-meta.xml
<CustomField>
    <fullName>Binary_Value__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The Binary Value of the field related to the score</description>
    <label>Binary Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Comparison__c.field-meta.xml
<CustomField>
    <fullName>Comparison__c</fullName>
    <description>The comparison to be used for scoring</description>
    <label>Comparison</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Less Than</fullName>
            </value>
            <value>
                <fullName>Greater Than</fullName>
            </value>
            <value>
                <fullName>Number Range</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Is Null</fullName>
            </value>
            <value>
                <fullName>Text Mid</fullName>
            </value>
            <value>
                <fullName>Text Equals</fullName>
            </value>
            <value>
                <fullName>Text Mid List</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>The Field related to the scoring</description>
    <label>Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>The score Is Active for scoring or not</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <description>The Key Brand related to the scoring</description>
    <label>Key Brand</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>The Market related to the scoring</description>
    <label>Market</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Number_Value__c.field-meta.xml
<CustomField>
    <fullName>Number_Value__c</fullName>
    <description>The Number Value for field of related scoring</description>
    <label>Number Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>The Object related to the scoring</description>
    <label>Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Range_Max__c.field-meta.xml
<CustomField>
    <fullName>Range_Max__c</fullName>
    <description>The number range max value of related scoring</description>
    <label>Range Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Range_Min__c.field-meta.xml
<CustomField>
    <fullName>Range_Min__c</fullName>
    <description>The range min of number value for field related to scoring</description>
    <label>Range Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <description>The RecordType of the Object related to the score</description>
    <label>RecordType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>The Score for the related attributes</description>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Stackable__c.field-meta.xml
<CustomField>
    <fullName>Stackable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The score is stackable or not</description>
    <label>Stackable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Text_Value__c.field-meta.xml
<CustomField>
    <fullName>Text_Value__c</fullName>
    <description>The text value of the field related to scoring</description>
    <label>Text Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadScoring__c/fields/Trigger_Field__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Field__c</fullName>
    <description>The Trigger Field of the history record. Only fill in when the Trigger Field is not the same as the score Field</description>
    <label>Trigger Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadScoringCriteria__c/LeadScoringCriteria__c.object-meta.xml
<CustomObject>
    <description>Criteria to match with the right CR and BR</description>
    <label>Lead Scoring Criteria</label>
    <nameField>
        <label>Lead Scoring Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Scoring Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LeadScoringCriteria__c/fields/Channel_Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Channel_Ref_No__c</fullName>
    <label>Channel Ref No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadScoringCriteria__c/fields/ChannelCategory__c.field-meta.xml
<CustomField>
    <fullName>ChannelCategory__c</fullName>
    <description>The category for the channel related to CR</description>
    <label>Channel Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LeadScoringCriteria__c/fields/ChannelType__c.field-meta.xml
<CustomField>
    <fullName>ChannelType__c</fullName>
    <description>Channel Type of the CR</description>
    <label>Channel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Other - Online</fullName>
            </value>
            <value>
                <fullName>Other - Offline</fullName>
            </value>
            <value>
                <fullName>MMC</fullName>
            </value>
            <value>
                <fullName>MKT</fullName>
            </value>
            <value>
                <fullName>Ethical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LeadScoringCriteria__c/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <description>The Key Brand related to the BR</description>
    <label>Key Brand</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadScoringCriteria__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market related to CR and BR</description>
    <label>Market</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadScoringCriteria__c/fields/Medium__c.field-meta.xml
<CustomField>
    <fullName>Medium__c</fullName>
    <description>The Medium used related to the CR</description>
    <label>Medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactLeadScoreBatch_Sched.cls
public class ContactLeadScoreBatch_Sched implements Schedulable {
   
    public void execute(SchedulableContext sc) {
        List<LeadScoringCriteria__c> leadScoreCriteriaList = [SELECT Id,Market__c, KeyBrand__c, ChannelCategory__c, ChannelType__c, Medium__c,Channel_Ref_No__c FROM LeadScoringCriteria__c
                                                         WHERE Is_Active__c=true];
        
        Map<String, List<LeadScoringCriteria__c>> marketBrandLeadScoreCriteriaMap = new Map<String, List<LeadScoringCriteria__c>>();
        Map<String, List<LeadScoring__c>> marketBrandLeadScoreMap = new Map<String, List<LeadScoring__c>>();
        List<String> marketList = new List<String>();
        List<String> brandList = new List<String>();
        for(LeadScoringCriteria__c lcs: leadScoreCriteriaList){
            String keyMarket = lcs.Market__c;
            String keyBrand = lcs.KeyBrand__c;
            brandList.add(keyBrand);
            marketList.add(keyMarket);
        }
        
        Map<String, Set<String>> keybrandObjectMap = new Map<String, Set<String>>();
        //Get Lead Score for all Objects based on Market and Key Brand SOQL-1
        for(LeadScoring__c leadScore: [SELECT Id,Field__c,Market__c, Comparison__c,Text_Value__c,
                                       Range_Min__c,Range_Max__c,Number_Value__c,KeyBrand__c,
                                       Object__c, Score__c, Stackable__c, Binary_Value__c,RecordType__c,
                                       Trigger_Field__c,Name FROM LeadScoring__c 
                                       WHERE Is_Active__c=true]){
            String keyMarket = leadScore.Market__c;
            String keyBrand = leadScore.KeyBrand__c;
            String mapKey = keyMarket+'::'+keyBrand;
            Set<String> leadScoreObjectTempSet = new Set<String>();
            
            if(keybrandObjectMap.containsKey(mapKey)){
            	leadScoreObjectTempSet.addAll(keybrandObjectMap.get(mapKey));                       
            }
            String objectNameTemp = leadScore.Object__c;
            if(leadScore.Object__c.equalsIgnoreCase('Contact')){
                      objectNameTemp = objectNameTemp+'-'+leadScore.RecordType__c;                    
            }                          
            leadScoreObjectTempSet.add(objectNameTemp);
            keybrandObjectMap.put(mapKey,leadScoreObjectTempSet);                             
        }
      	Integer leadScoreBatchSize = Integer.valueof(Label.LeadScoreBatchSize);
        if(!leadScoreCriteriaList.isEmpty()){
            // Make sure you're not exceeding the governor limits
            if (Limits.getLimitAsyncCalls() > Limits.getAsyncCalls()) {
                for(LeadScoringCriteria__c l : leadScoreCriteriaList){
                    String keyMarket = l.Market__c;
                    String keyBrand = l.KeyBrand__c;
                    String mapKey = keyMarket+'::'+keyBrand;
                    List<String> objectList = new List<String>();
                    objectList.addAll(keybrandObjectMap.get(mapKey));
                    database.executebatch(new LeadScoreBatch(l,objectList),leadScoreBatchSize);  
                }
            } else {
                // Handle the case when the limit is reached
                system.debug('Current Limit:' + Limits.getAsyncCalls() + ' Limit:' + Limits.getLimitAsyncCalls());
            } 
        }
    }

}