force-app/main/default/objects/Case/fields/ReminderStatus__c.field-meta.xml
<CustomField>
    <fullName>ReminderStatus__c</fullName>
    <label>Reminder Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Response</fullName>
            </value>
            <value>
                <fullName>First Reminder</fullName>
            </value>
            <value>
                <fullName>Second Reminder</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Pending - Uncontactable</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Reassigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailToCaseSpamCleanup_Batch.cls
/*
Author: Jericson Mercado
Description: Deletes all Case with Reminder Status "Closed - Reassigned" for they are spam emails'
*/
public with sharing class EmailToCaseSpamCleanup_Batch implements Database.Batchable<sObject>, Database.Stateful {

    private String market;
    public EmailToCaseSpamCleanup_Batch(String m) { market = m; }

    public Database.QueryLocator start(Database.BatchableContext BC){
        Set<String> statusList = new Set<String> {'Closed - Reassigned'};

        String queryStr = 'SELECT Id'
                        +  ' FROM Case'
                        + ' WHERE ReminderStatus__c IN: statusList'
                        +   ' AND Market__c =: market';

        return Database.getQueryLocator(queryStr);
    }
    
    public void execute(Database.BatchableContext BC, List<Case> cList){
        DELETE cList;
    }

    public void finish(Database.BatchableContext BC){}
}