force-app/main/default/objects/Asset_Service__c/Asset_Service__c.object-meta.xml
<CustomObject>
    <label>Asset Service</label>
    <nameField>
        <label>Asset Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Service__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Services</relationshipLabel>
    <relationshipName>Asset_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Follow Up 1</fullName>
            </value>
            <value>
                <fullName>Follow Up 2</fullName>
            </value>
            <value>
                <fullName>Follow Up 3</fullName>
            </value>
            <value>
                <fullName>Written Follow Up</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Unserviceable</fullName>
            </value>
            <value>
                <fullName>Classified</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetServiceTriggerHelper.cls
/*------------------------------------------------------------
Author:      Lee Santos
Description: Helper class for AssetService object

History
04/16/2021
-------------------------------------------------------------------------------------------*/

public class AssetServiceTriggerHelper {
    
    
    public static void updateRelatedAsset(List<Asset_Service__c> assetServiceList, Map<Id, sObject> oldAssetServiceMap){
                  
        List<Asset> assetListToUpdate = new List<Asset>();
        
        Set <String> assetIds = new Set <String>();
        Set <String> locationIds = new Set <String>();
        
        for(Asset_Service__c assetService : assetServiceList){
            if(assetService.Status__c == 'Completed'){
            	assetIds.add(assetService.Asset__c);
            }
        }
        
        for(Asset asset : [SELECT Id, AccountId, ContactId FROM Asset WHERE Id IN : assetIds]){
            asset.AccountId = null;
            asset.ContactId = null;
            assetListToUpdate.add(asset);
        }
        
        update assetListToUpdate;
        
       
    }
    
}