force-app/main/default/objects/Asset_Service__c/Asset_Service__c.object-meta.xml
<CustomObject>
    <label>Asset Service</label>
    <nameField>
        <label>Asset Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Service__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Asset Services</relationshipLabel>
    <relationshipName>Asset_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Service__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Services</relationshipLabel>
    <relationshipName>Asset_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Service__c/fields/AssetServiceRegarding__c.field-meta.xml
<CustomField>
    <fullName>AssetServiceRegarding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Service Regarding</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Asset Services</relationshipLabel>
    <relationshipName>Asset_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Follow Up 1</fullName>
            </value>
            <value>
                <fullName>Follow Up 2</fullName>
            </value>
            <value>
                <fullName>Follow Up 3</fullName>
            </value>
            <value>
                <fullName>Written Follow Up</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Unserviceable</fullName>
            </value>
            <value>
                <fullName>Classified</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetServiceTriggerHelperTest.cls
@isTest
private class AssetServiceTriggerHelperTest {
    
    @isTest
    static void testUpdateRelatedAsset() {
        User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'ANZ');
        insert sysad;
        
        System.runAs(sysad) {    
            Asset_Service__c assetService = TestDataFactory.createAssetService();
            
            Test.startTest();{
                assetService.Status__c = 'Completed';
                update assetService;
            }
            Test.stopTest();
            
            Asset_Service__c assetServiceTest = [SELECT Id, Asset__c, AccountId__c, AssetServiceRegarding__c FROM Asset_Service__c WHERE Name = 'TestAssetService'];
            Asset asset = [SELECT Id, AccountId, ContactId FROM Asset WHERE Id =: assetServiceTest.Asset__c];
            System.assertEquals(null, asset.AccountId );
            System.assertEquals(null, asset.ContactId );
        }
    }
    
}