force-app/main/default/objects/AbbottPartner__c/AbbottPartner__c.object-meta.xml
<CustomObject>
    <label>Abbott Partner</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Abbott Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abbott Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AbbottPartner__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AffiliateMetadata__mdt/AffiliateMetadata__mdt.object-meta.xml
<CustomObject>
    <label>Affiliate Metadata</label>
    <pluralLabel>Affiliate Metadatas</pluralLabel>
</CustomObject>

force-app/main/default/objects/AffiliateMetadata__mdt/fields/MilkCodeRestrictionPeriod__c.field-meta.xml
<CustomField>
    <fullName>MilkCodeRestrictionPeriod__c</fullName>
    <label>Milk Code Restriction Period (in Months)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AffiliateMetadata__mdt/fields/PeriodtRequest__c.field-meta.xml
<CustomField>
    <fullName>PeriodtRequest__c</fullName>
    <label>Sample Ineligibility Period (in Months)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AffiliateMetadata__mdt/fields/SampleRequestPricebook__c.field-meta.xml
<CustomField>
    <fullName>SampleRequestPricebook__c</fullName>
    <label>Sample Request Pricebook</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <label>Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/DeliveryAddress__c.field-meta.xml
<CustomField>
    <fullName>DeliveryAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>ChannelResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>155</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[1-Sep-21 Khai] This field is for troubleshooting by extracting out the market of the Contact</description>
    <formula>Contact__r.Market__c</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/PromoterCode__c.field-meta.xml
<CustomField>
    <fullName>PromoterCode__c</fullName>
    <label>Promoter Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/SampleGivenOnGround__c.field-meta.xml
<CustomField>
    <fullName>SampleGivenOnGround__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sample Given On-Ground</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/SampleProductCode__c.field-meta.xml
<CustomField>
    <fullName>SampleProductCode__c</fullName>
    <formula>ProductSampleRequested__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Verified__c.field-meta.xml
<CustomField>
    <fullName>Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/ChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>ChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Response</label>
    <referenceTo>ChannelResponse__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderedBy__c.field-meta.xml
<CustomField>
    <fullName>OrderedBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordered By</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Adult</value>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/PromoterCode__c.field-meta.xml
<CustomField>
    <fullName>PromoterCode__c</fullName>
    <formula>Abbott_Partner_Code__r.PartnerCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Promoter Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[22-Sep-21 Khai] This is a debug field to query the OrderItem market based on the product selected</description>
    <formula>TEXT(Product2.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[25-Jul-21 Khai] To extract out the product market for troubleshooting purposes</description>
    <formula>TEXT( Product2.Market__c )</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AvailableForSample__c.field-meta.xml
<CustomField>
    <fullName>AvailableForSample__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available for Sample</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Stage1PaidSample__c.field-meta.xml
<CustomField>
    <fullName>Stage1PaidSample__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stage 1 Paid Sample</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Stage3PaidSample__c.field-meta.xml
<CustomField>
    <fullName>Stage3PaidSample__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stage 3 Paid Sample</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ANZ</fullName>
    </customValue>
    <customValue>
        <fullName>HK</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
    </customValue>
    <customValue>
        <fullName>TW</fullName>
    </customValue>
    <customValue>
        <fullName>VN</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
        <isActive>false</isActive>
        <label>NZ</label>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
        <isActive>false</isActive>
        <label>AU</label>
    </customValue>
    <masterLabel>Market</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/CreateSampleOrder.cls
public class CreateSampleOrder {
     
    public static void executeSampleCreation(List<ChannelResponse__c> newList) {            
        List<AffiliateMetadata__mdt> am = [Select MasterLabel, SampleRequestPricebook__c , PeriodtRequest__c, MilkCodeRestrictionPeriod__c
                                            From AffiliateMetadata__mdt Where SampleRequestPricebook__c != null];
        List<Product2> stgProdList = [SELECT Id, Stage1PaidSample__c, Stage3PaidSample__c, AvailableForSample__c, IsActive
                                      FROM Product2 
                                      WHERE (Stage1PaidSample__c = TRUE OR Stage3PaidSample__c = TRUE) AND AvailableForSample__c = TRUE AND IsActive = TRUE];

        Map<String, String> affiliatePeriodMap = UtilityClass.convertObjToMap(am, CommonConstant.AFFILIATE_MASTERLABEL , CommonConstant.AFFILIATE_MONTHPERIODREQUEST);        
        Map<String, String> affiliatePricebookMap = UtilityClass.convertObjToMap(am,  CommonConstant.AFFILIATE_MASTERLABEL , CommonConstant.AFFILIATE_SAMPLEPRICEBOOK);
        Map<String, String> affiliateMilkRestriction = UtilityClass.convertObjToMap(am, CommonConstant.AFFILIATE_MASTERLABEL , CommonConstant.AFFILIATE_MILKRESTRICTION);
        Map<String, String> channelMarketMap = new Map<String, String>();
        Set<String> abbottPartnerSet = new Set<String>();
        Map<Id, ChannelResponse__c> channelResponseMap = new Map<Id, ChannelResponse__c>();
        
        Set<Id> orderBySet = new Set<Id>();
        Set<String> pricebookSet = new Set<String>();
        Set<Id> stg1PrdIdSet = new Set<Id>();
        Set<Id> stg3PrdIdSet = new Set<Id>();
        
        if(!stgProdList.isEmpty()) {
            for(Product2 prd : stgProdList) {
                if(prd.Stage1PaidSample__c) {
                    stg1PrdIdSet.add(prd.Id);
                }
                else if(prd.Stage3PaidSample__c) {
                    stg3PrdIdSet.add(prd.Id);
                }
            }
        }

        for(ChannelResponse__c cr : newList) {
            //orderBySet - used in the query to get only order item that belongs to the contact in the list            
            orderBySet.add(cr.BrandRelationship__r.PrimaryContact__c);
            //pricebookSet - in the metadata query to get only related market 
            pricebookSet.add(  affiliatePricebookMap.get(cr.BrandRelationship__r.PrimaryContact__r.Market__c)  );
            //channelMarketMap - used to get the market when the order item is being created, order has no market field
            channelMarketMap.put(cr.Id, cr.BrandRelationship__r.PrimaryContact__r.Market__c);
            abbottPartnerSet.add(cr.PromoterCode__c);
            channelResponseMap.put(cr.Id, cr);
        }  
        if(System.Test.isRunningTest()) { 
            pricebookSet.add('Standard Price Book');
        }
        //check if there are already sample order created on the contact
        List<OrderItem> currentOrderList  = [Select Order.EffectiveDate, Product2Id, OrderId, Product2.ProductCode, Order.OrderedBy__c
                                            From OrderItem where Order.OrderedBy__c IN: orderBySet AND Order.Type IN (:CommonConstant.ORDER_TYPE_SAMPLEREQUEST, :CommonConstant.ORDER_TYPE_OTHER)];

        Map<String, String> chanelProductMap = new Map<String, String>();
        //channelToUpdateList - need to update the channel status
        List<ChannelResponse__c> channelToUpdateList = new List<ChannelResponse__c>();
        List<Order> orderList = new List<Order>();
        //order creation
        Map<String, AbbottPartner__c> abbottPartnerMap = new Map<String, AbbottPartner__c>();
        for(AbbottPartner__c ap : [SELECT Id, External_Id__c FROM AbbottPartner__c WHERE External_Id__c IN: abbottPartnerSet]){
            abbottPartnerMap.put(ap.External_Id__c, ap);
        }
        //get the unit price and pricebook id
        List<PricebookEntry> pricebookentryList = [Select Id, Product2Id, Pricebook2Id, Pricebook2.Market__c, UnitPrice, ProductCode , CurrencyIsoCode
                                                    From PricebookEntry 
                                                    Where Pricebook2.Name IN: pricebookSet AND Product2.IsActive = true AND Product2.AvailableForSample__c = true AND Pricebook2.IsActive = true];
        //Map<market , map<productid, pricebookentry>> pricebookUnitPriceMap
        Map<String, Map<String, PricebookEntry>> pricebookUnitPriceMap = createUnitPriceMap(pricebookentryList);
        //Map<CR ID, cr.br.user__c>
        Map<Id, Id> brandEndUserMap = new Map<Id, Id>();
        Set<String> uniqueOrderSet = new Set<String>();

        for(ChannelResponse__c cr : newList) {
            if ((cr.BrandRelationship__r.PrimaryContact__r.Verified__c && cr.BrandRelationship__r.PrimaryContact__r.Market__c != CommonConstant.MARKET_TW) || cr.BrandRelationship__r.PrimaryContact__r.Market__c == CommonConstant.MARKET_TW) {
                Integer period = 0; 
                if (affiliatePeriodMap.containsKey(cr.BrandRelationship__r.PrimaryContact__r.Market__c)) {
                    period =  Integer.valueOf( affiliatePeriodMap.get(cr.BrandRelationship__r.PrimaryContact__r.Market__c) ); 
                }
                String orderKeyName = cr.BrandRelationship__r.PrimaryContact__c + cr.SampleProductCode__c;

                if (cr.DeliveryAddress__c == null && !cr.SampleGivenOnGround__c) {
                    cr.OrderCreationStatus__c = CommonConstant.CHANNELRESPONSE_ORDERSTATUS_MISSINGADDRESS;
                    channelToUpdateList.add(cr); 
                } else if(cr.BrandRelationship__r.User__c != null
                          && cr.BrandRelationship__r.User__r.RecordType.DeveloperName == CommonConstant.CONTACT_CHILD_RECORDTYPE
                          && (cr.BrandRelationship__r.PrimaryContact__r.Market__c == 'SG' || cr.BrandRelationship__r.PrimaryContact__r.Market__c == 'TH')
                          && cr.BrandRelationship__r.User__r.MilkCodeRestriction__c == true) { //TKT-001614
                    cr.OrderCreationStatus__c = CommonConstant.CHANNELRESPONSE_ORDERSTATUS_PENDINGMILKCODE;
                    channelToUpdateList.add(cr);
                } else if(!stg1PrdIdSet.isEmpty() && cr.BrandRelationship__r.PrimaryContact__r.Market__c == CommonConstant.MARKET_TW && cr.ProductSampleRequested__r.Stage1PaidSample__c
                          && validateStageProducts(currentOrderList, cr.SampleProductCode__c, cr.BrandRelationship__r.PrimaryContact__c, stg1PrdIdSet)) {
                    cr.OrderCreationStatus__c = CommonConstant.CHANNELRESPONSE_ORDERSTATUS_INELIGBLE;
                    channelToUpdateList.add(cr);
                } else if(!stg3PrdIdSet.isEmpty() && cr.BrandRelationship__r.PrimaryContact__r.Market__c == CommonConstant.MARKET_TW && cr.ProductSampleRequested__r.Stage3PaidSample__c
                          && validateStageProducts(currentOrderList, cr.SampleProductCode__c, cr.BrandRelationship__r.PrimaryContact__c, stg3PrdIdSet)) {
                    cr.OrderCreationStatus__c = CommonConstant.CHANNELRESPONSE_ORDERSTATUS_INELIGBLE;
                    channelToUpdateList.add(cr); 
                } else if (validateExistingOrder(currentOrderList,  cr.SampleProductCode__c, cr.BrandRelationship__r.PrimaryContact__c, period, cr.SampleGivenOnGround__c) && !uniqueOrderSet.contains(orderKeyName)) {
                    Order order = new Order();
                    //if product on CR has  Stage3PaidSample__c or Stage1PaidSample__c =true for TW Market,Order Type should be others
                    if((cr.ProductSampleRequested__r.Stage3PaidSample__c || cr.ProductSampleRequested__r.Stage1PaidSample__c) &&  cr.BrandRelationship__r.PrimaryContact__r.Market__c == CommonConstant.MARKET_TW){                        
                        order.Type = CommonConstant.ORDER_TYPE_OTHER; //added by Monika for story 3273
                        order.PaymentMethod__c = CommonConstant.ORDER_PAYMENT_METHOD_CASH; //added by Sean for TKT-005973

                        Date d = Date.today();
                        DateTime dt = (DateTime) d;
                        String day = dt.format('E');
            
                        if(day == 'Fri') {
                            order.PreferredDeliveryDate__c = d.addDays(3);
                        }
                        else if (day == 'Sat') {
                            order.PreferredDeliveryDate__c = d.addDays(2);
                        }
                        else {
                            order.PreferredDeliveryDate__c = d.addDays(1);
                        }
                    }else{
                        order.Type = CommonConstant.ORDER_TYPE_SAMPLEREQUEST; //default logic
                        order.PaymentMethod__c = ''; //added by Sean for TKT-005973
                    }
                    order.EffectiveDate = Date.today();
                    order.OrderedBy__c = cr.BrandRelationship__r.PrimaryContact__c;
                    order.ChannelResponse__c = cr.Id;
                    order.ShippingAddress__c = cr.DeliveryAddress__c;
                    // order.PaymentMethod__c = '';
                    order.RelatedCampaign__c = cr.Campaign__c;
                    order.VAT__c = CommonConstant.ORDER_VAT;//VAT required on order,validation rule
                    //cannot change to another status beside draft because there is no order item in the order
                    order.Status = CommonConstant.ORDER_STATUS_DRAFT;
                    order.CreatedFromCRRecord__c = true;
                    order.Abbott_Partner_Code__c = abbottPartnerMap.containsKey(cr.PromoterCode__c) ? abbottPartnerMap.get(cr.PromoterCode__c).Id : null;
                    order.Abbott_Sales_Person__c = abbottPartnerMap.containsKey(cr.PromoterCode__c) ? abbottPartnerMap.get(cr.PromoterCode__c).Id : null;
                    
                    brandEndUserMap.put(cr.Id, cr.BrandRelationship__r.User__c);
                    if (pricebookUnitPriceMap.containsKey(cr.BrandRelationship__r.PrimaryContact__r.Market__c)) {
                        Map<String, PricebookEntry> pricebookEntryMap = pricebookUnitPriceMap.get(cr.BrandRelationship__r.PrimaryContact__r.Market__c);
                        if (pricebookEntryMap.containsKey(cr.SampleProductCode__c)) {
                            //change from ProductSampleRequested__c to SampleProductCode__c
                            PricebookEntry currentPrice = pricebookEntryMap.get(cr.SampleProductCode__c);

                            order.Pricebook2Id = currentPrice.Pricebook2Id;
                            order.CurrencyIsoCode = currentPrice.CurrencyIsoCode;

                            orderList.add(order);
                            uniqueOrderSet.add(orderKeyName);
                        } else {
                            cr.OrderCreationStatus__c = CommonConstant.CHANNELRESPONSE_ORDERSTATUS_PRODUCTUNAVAILABLE;
                            channelToUpdateList.add(cr); 
                        }
                    } else {
                        cr.OrderCreationStatus__c = CommonConstant.CHANNELRESPONSE_ORDERSTATUS_PRODUCTUNAVAILABLE;
                        channelToUpdateList.add(cr); 
                    }
                    
                    //the product will be used in creating an order item
                    //we are iterating order and not the channel when creating an order item, not possible to get the product code from the order
                    //change from ProductSampleRequested__c to SampleProductCode__c
                    chanelProductMap.put(cr.Id, cr.SampleProductCode__c);
                } else {
                    cr.OrderCreationStatus__c = CommonConstant.CHANNELRESPONSE_ORDERSTATUS_INELIGBLE;
                    channelToUpdateList.add(cr); 
                }

           }
        }
        //order product creation
        if(!orderList.isEmpty()) {
            insert orderList;
            List<OrderItem> orderItemList = new List<OrderItem>();
            List<Order> orderToUpdateList = new List<Order>();
            for(Order order : orderList) {
                OrderItem item = new OrderItem();
                item.OrderId = order.Id;
                //item.Product2Id = chanelProductMap.get(order.ChannelResponse__c);
                item.ServiceDate = Date.today();
                item.Quantity = 1;
                //possible multiple market
                String channelMarket = channelMarketMap.get(order.ChannelResponse__c);
                Map<String, PricebookEntry> pricebookEntryMap = pricebookUnitPriceMap.get(channelMarket);
                //chanelProductMap - to get the product code value stored in the channel response record
                PricebookEntry currentPrice = pricebookEntryMap.get(chanelProductMap.get(order.ChannelResponse__c));
                item.PricebookEntryId = currentPrice.Id;
                item.UnitPrice = currentPrice.UnitPrice;                
                item.Category__c = CommonConstant.ORDERITEM_CATEGORY_TRIAL;
                item.OrderedFor__c = brandEndUserMap.get(order.ChannelResponse__c);
                orderItemList.add(item);
                //update the status of the order
                ChannelResponse__c cr = new ChannelResponse__c();
                if(channelResponseMap.get(order.ChannelResponse__c).SampleGivenOnGround__c){
                    order.Status = CommonConstant.ORDER_STATUS_SAMPLEGIVENONGROUND;
                    cr.Id = order.ChannelResponse__c;
                    cr.OrderCreationStatus__c = CommonConstant.CHANNELRESPONSE_ORDERSTATUS_SUCCESSFULSAMPLEGIVENONGROUND;
                }
                else{
                    order.Status = CommonConstant.ORDER_STATUS_SUBMITTED;
                    cr.Id = order.ChannelResponse__c;
                    cr.OrderCreationStatus__c = CommonConstant.CHANNELRESPONSE_ORDERSTATUS_SUCCESSFUL;
                }
                orderToUpdateList.add(order);
                channelToUpdateList.add(cr);
            }

            if(!orderItemList.isEmpty()) {
                insert orderItemList;
                update orderToUpdateList;
            }
        }  

        if (!channelToUpdateList.isEmpty()) {
            update channelToUpdateList;
        }
    }
    
    public static Map<String, Map<String, PricebookEntry>> createUnitPriceMap(List<PricebookEntry> priceBookList) {
        Map<String, Map<String, PricebookEntry>> priceMap = new Map<String, Map<String, PricebookEntry>>();
        for (PricebookEntry entry : priceBookList) {
            if (priceMap.containsKey(entry.Pricebook2.Market__c)) {
                Map<String, PricebookEntry> currentPriceMap = priceMap.get(entry.Pricebook2.Market__c);
                //change from Product2Id to ProductCode
                currentPriceMap.put(entry.ProductCode, entry);
            } else {
                Map<String, PricebookEntry> currentPriceMap = new Map<String, PricebookEntry>();
                //change from Product2Id to ProductCode
                currentPriceMap.put(entry.ProductCode, entry);
                priceMap.put(entry.Pricebook2.Market__c, currentPriceMap);
            }
        }
        return priceMap;
    }

    public static Boolean validateExistingOrder(List<OrderItem> orderItemList, String productCode, Id orderBy, Integer validMonths, Boolean isSampleGivenOnGround) {
        Boolean isValid = true;
        if(!isSampleGivenOnGround){
            for (OrderItem item : orderItemList) {
                if (item.Product2.ProductCode == productCode && item.Order.OrderedBy__c ==  orderBy && item.Order.EffectiveDate.addMonths(validMonths) >= Date.today()){
                    isValid = false;
                }
            }
        }

        return isValid;
    }
    
    public static Boolean validateStageProducts (List<OrderItem> orderItemList, String productCode, Id orderBy, Set<Id> stgPrdIdSet) {
        Boolean isInvalid = false;

        if(!orderItemList.isEmpty()) {
            for (OrderItem item : orderItemList) {
                if(stgPrdIdSet.contains(item.Product2Id) && item.Product2.ProductCode == productCode && item.Order.OrderedBy__c ==  orderBy) {
                    isInvalid = true;
                }
            }
        }

        return isInvalid;
    }
}