force-app/main/default/objects/AbbottPartner__c/AbbottPartner__c.object-meta.xml
<CustomObject>
    <label>Abbott Partner</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Abbott Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abbott Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AbbottPartner__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AbbottPartner__c/recordTypes/Dietician.recordType-meta.xml
<RecordType>
    <fullName>Dietician</fullName>
    <active>true</active>
    <label>Dietician</label>
</RecordType>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>72</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Channel_Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Channel_Ref_No__c</fullName>
    <externalId>true</externalId>
    <label>Channel Ref No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[1-Sep-21 Khai] This field is for troubleshooting by extracting out the market of the Contact</description>
    <formula>Contact__r.Market__c</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/PricebookEntry/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[25-Jul-21 Khai] To extract out the product market for troubleshooting purposes</description>
    <formula>TEXT( Product2.Market__c )</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>72</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ParentBrand__c.field-meta.xml
<CustomField>
    <fullName>ParentBrand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Brand</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND ((3 OR 4) OR (5 AND 6))</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.ProductHierarchyLevel__c</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Parent Brand)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/VN_contact_manual__c.object-meta.xml
<CustomObject>
    <label>VN contact manual</label>
    <nameField>
        <label>VN contact manual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VN contact manuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_contact_manual__c/fields/contact_mobilephone__c.field-meta.xml
<CustomField>
    <fullName>contact_mobilephone__c</fullName>
    <label>Contact MobilePhone</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ANZ</fullName>
    </customValue>
    <customValue>
        <fullName>HK</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
    </customValue>
    <customValue>
        <fullName>TW</fullName>
    </customValue>
    <customValue>
        <fullName>VN</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
        <isActive>false</isActive>
        <label>NZ</label>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
        <isActive>false</isActive>
        <label>AU</label>
    </customValue>
    <masterLabel>Market</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/DeleteRecordsBatchTest.cls
@isTest
public class DeleteRecordsBatchTest {
    @testSetup
    static void setup(){
        User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'VN');
        insert sysad;
        
        System.runAs(sysad) {
            List<Product2> lProduct = TestDataFactory.createTestBrandProduct(1);
            lProduct.get(0).Market__c = 'VN';
            lProduct.get(0).ProductCode = '123';
            Update lProduct;
            
            List<Channel__c>  lChannel = TestDataFactory.createTestChannel(1);
            lChannel.get(0).Market__c = 'VN';
            lChannel.get(0).Channel_Ref_No__c = 'FB';
            lChannel.get(0).Name = 'FB';
            lChannel.get(0).RecordTypeId = Schema.SObjectType.Channel__c.getRecordTypeInfosByName().get(CommonConstant.CHANNEL_OTHER_ONLINE_RECORDTYPE).getRecordTypeId();
            update lChannel;
            
            TestDataFactory.createAffiliate('VN','English');
            TestDataFactory.createAffiliate('VN','Malay');
            
            Campaign cam = TestDataFactory.createCampaign('Cam','Similac','VN');
            cam.ExternalId__c = '123';
            Insert cam;
            
            List<Affiliate_Value__c> lCity = TestDataFactory.createTestCity(1);
            lCity.get(0).Market__c = 'VN';
            update lCity;
            
            List<Affiliate_Value__c> lRegion = TestDataFactory.createTestRegion(1);
            lRegion.get(0).Market__c = 'VN';
            update lRegion;
            
            TestDataFactory.createTestWard(1, 'VN');
            TestDataFactory.createTestDistrict(1, 'VN');
            TestDataFactory.createTestEthnicity(1, 'VN');
            TestDataFactory.createTestSwitchReason(1, 'VN');
            
            VN_contact_manual__c vnCon1 = TestDataFactory.createVNContactManual('VN', 'Street', 'Test City', '123', 'ProductName -1', 'User', 'New', 'LastName', 'test@test.com', '0911111111', 'FB', 'FB', '10/10/2022', '123');
            VN_contact_manual__c vnCon2 = TestDataFactory.createVNContactManual('VN', 'Street', 'Test City', '123', 'ProductName -1', 'User', 'New', 'LastName', 'test@test.com', '0911111112', 'FB', 'FB', '10/10/2022', '123');
            VN_contact_manual__c vnCon3 = TestDataFactory.createVNContactManual('VN', 'Street', 'Test City', '123', 'ProductName -1', 'User', 'New', 'LastName', 'test@test.com', '0911111113', 'FB', 'FB', '10/10/2022', '123');
            List<VN_contact_manual__c> vnConList = new List<VN_contact_manual__c>{vnCon1, vnCon2, vnCon3};
            insert vnConList;
        }
    }
    
    static testmethod void test_validObjectName(){
        Test.startTest();
        DeleteRecordsBatch batch = new DeleteRecordsBatch('VN_contact_manual__c', 0, null, 0, 20);
        Database.executebatch(batch, 20);
        Test.stopTest();
        List<VN_contact_manual__c> vnConCheck = [SELECT Id FROM VN_contact_manual__c];
        System.assertEquals(vnConCheck.size(), 0);
    } 
    static testmethod void test_invalidObjectName(){
        Test.startTest();
        DeleteRecordsBatch batch = new DeleteRecordsBatch('VN_contact_manual', 0, null, 0, 20);
        Database.executebatch(batch, 20);
        Test.stopTest();
        List<VN_contact_manual__c> vnConCheck = [SELECT Id FROM VN_contact_manual__c];
        System.assertEquals(vnConCheck.size(), 3);
    }
    static testmethod void test_validFieldName(){
        Test.startTest();
        Map<String,String> fieldFilterMap = new Map<String,String>();
        fieldFilterMap.put('contact_mobilephone__c','0911111111');
        DeleteRecordsBatch batch = new DeleteRecordsBatch('VN_contact_manual__c', 0, fieldFilterMap, 0, 20);
        Database.executebatch(batch, 20);
        Test.stopTest();
        List<VN_contact_manual__c> vnConCheck = [SELECT Id FROM VN_contact_manual__c];
        System.assertEquals(vnConCheck.size(), 2);
    } 
    static testmethod void test_invalidFieldName(){
        Test.startTest();
        Map<String,String> fieldFilterMap = new Map<String,String>();
        fieldFilterMap.put('contact_mobilephone','0911111111');
        DeleteRecordsBatch batch = new DeleteRecordsBatch('VN_contact_manual__c', 0, fieldFilterMap, 0, 20);
        Database.executebatch(batch, 20);
        Test.stopTest();
        List<VN_contact_manual__c> vnConCheck = [SELECT Id FROM VN_contact_manual__c];
        System.assertEquals(vnConCheck.size(), 0);
    } 
    static testmethod void test_schedule(){
        Test.startTest();
        System.schedule('DeleteRecordsBatch', '0 0 13 * * ?', new DeleteRecordsBatch('', 0, null, 0, 100));
        Test.stopTest();
    }
    static testmethod void test_deleteOtherObject(){
        Account a = TestDataFactory.createTestHousehold(1, 'ID')[0];
        Contact adult = TestDataFactory.createContact(true, a.Id, null, Date.parse('01/01/1990'), '0912345678');
        Contact child = TestDataFactory.createContact(false, a.Id, adult.Id, Date.parse('01/01/2022'), '');
        Affiliate_Value__c cityDefault = TestDataFactory.createAffiliateValue('City', 'TEST_CITY_DEFAULT', 'ID', null);
        Affiliate_Value__c districtDefault = TestDataFactory.createAffiliateValue('District', 'TEST_DISTRICT_DEFAULT', 'ID', cityDefault.Id);
        String streetNameDefault = 'TEST_STREET_DEFAULT';
		Address__c addressDefault = TestDataFactory.createAddress(true, adult.Id, 'Indonesia', cityDefault.Id, districtDefault.Id, null, streetNameDefault);
        AbbottPartner__c ap = TestDataFactory.createAbbottPartner('ID', 'Dietician', 'AA');
        PricebookEntry pbe = TestDataFactory.createPricebookEntry('ID', 'IDR');
        PricebookEntry pbe1 = TestDataFactory.createProductAndPricebookEntryDiffBrand('ID', 'IDR', pbe.Pricebook2Id, 'Pediasure');
        Product2 prod1 = [SELECT Id, ParentBrand__c FROM Product2 WHERE Id =: pbe1.Product2Id];
        Channel__c channel = TestDataFactory.createTestChannel(1, 'ID', 'TEST_CHANNEL')[0];
        Campaign campPed = TestDataFactory.createCampaignInsert('ID1.0_Pediasure_Call1_Verificationcall', 'Pediasure', 'ID', prod1.ParentBrand__c);
        BrandRelationship__c br1 = TestDataFactory.createTestBrandRelationShipwithUser(1, adult.Id, child.Id, prod1.Id)[0];
        ChannelResponse__c cr1 = TestDataFactory.createTestChannelResponseMultiple(1, br1, channel, addressDefault, prod1, true, 'Pending')[0];
        
        Test.startTest();
        Map<String,String> fieldFilterMap1 = new Map<String,String>();
        fieldFilterMap1.put('OrderCreationStatus__c','Pending');
        DeleteRecordsBatch batch = new DeleteRecordsBatch('ChannelResponse__c', 0, fieldFilterMap1, 100, 20);
        Database.executebatch(batch, 20);
        Map<String,String> fieldFilterMap2 = new Map<String,String>();
        fieldFilterMap2.put('Market__c','ID');
        DeleteRecordsBatch batch1 = new DeleteRecordsBatch('Account', 0, fieldFilterMap2, 5, 20);
        Database.executebatch(batch1, 20);
        Map<String,String> fieldFilterMap3 = new Map<String,String>();
        fieldFilterMap3.put('Market__c','ID');
        fieldFilterMap3.put('Phone','0912345678');
        fieldFilterMap3.put('RecordType.Name','Adult');
        DeleteRecordsBatch batch2 = new DeleteRecordsBatch('Contact', 0, fieldFilterMap3, 1, 20);
        Database.executebatch(batch2, 20);
        Test.stopTest();
        /*List<ChannelResponse__c> crCheck = [SELECT Id FROM ChannelResponse__c WHERE OrderCreationStatus__c = 'Pending'];
        System.assertEquals(crCheck.size(), 0);
        List<Account> acctCheck = [SELECT Id FROM Account WHERE Market__c = 'ID'];
        System.assertEquals(acctCheck.size(), 1);
        List<Contact> conCheck = [SELECT Id FROM Contact WHERE Market__c = 'ID' AND Phone = '0912345678' AND RecordType.Name = 'Adult'];
        System.assertEquals(conCheck.size(), 0);*/
    }
}