force-app/main/default/objects/AbbottPartner__c/AbbottPartner__c.object-meta.xml
<CustomObject>
    <label>Abbott Partner</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Abbott Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abbott Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AbbottPartner__c/recordTypes/Dietician.recordType-meta.xml
<RecordType>
    <fullName>Dietician</fullName>
    <active>true</active>
    <label>Dietician</label>
</RecordType>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/City.recordType-meta.xml
<RecordType>
    <fullName>City</fullName>
    <active>true</active>
    <description>Defines cities within a given market, to be selected during address creation and updates for a contact</description>
    <label>City</label>
</RecordType>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/District.recordType-meta.xml
<RecordType>
    <fullName>District</fullName>
    <active>true</active>
    <description>Defines the districts within a given market (usually defined by city), used during address creation and updates for a contact</description>
    <label>District</label>
</RecordType>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <formula>TEXT(BrandRelationship__r.KeyBrand__c)</formula>
    <label>Key Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <label>Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/Product2/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <label>Key Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abbott General</fullName>
            </value>
            <value>
                <fullName>Abound</fullName>
            </value>
            <value>
                <fullName>Alitraq</fullName>
            </value>
            <value>
                <fullName>Bonesure</fullName>
            </value>
            <value>
                <fullName>Bright Choice</fullName>
            </value>
            <value>
                <fullName>Caltrate</fullName>
            </value>
            <value>
                <fullName>Diabetamill</fullName>
            </value>
            <value>
                <fullName>Elecare</fullName>
            </value>
            <value>
                <fullName>Ensure</fullName>
            </value>
            <value>
                <fullName>Ensure Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Flexiflo</fullName>
            </value>
            <value>
                <fullName>Freego</fullName>
            </value>
            <value>
                <fullName>Glucerna</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Isomil</fullName>
            </value>
            <value>
                <fullName>Jevity</fullName>
            </value>
            <value>
                <fullName>Kidneysure</fullName>
            </value>
            <value>
                <fullName>Nepro</fullName>
            </value>
            <value>
                <fullName>Nutr Accessories</fullName>
            </value>
            <value>
                <fullName>Osmolite</fullName>
            </value>
            <value>
                <fullName>Other MND</fullName>
            </value>
            <value>
                <fullName>Pediasure</fullName>
            </value>
            <value>
                <fullName>Polycose</fullName>
            </value>
            <value>
                <fullName>Prosure</fullName>
            </value>
            <value>
                <fullName>Pulmocare</fullName>
            </value>
            <value>
                <fullName>RCF</fullName>
            </value>
            <value>
                <fullName>Similac</fullName>
            </value>
            <value>
                <fullName>Similac Core</fullName>
            </value>
            <value>
                <fullName>Similac Mom</fullName>
            </value>
            <value>
                <fullName>Similac Total Comfort</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ParentBrand__c.field-meta.xml
<CustomField>
    <fullName>ParentBrand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Brand</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND ((3 OR 4) OR (5 AND 6))</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.ProductHierarchyLevel__c</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Parent Brand)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FixCasesIDBatchTest.cls
@isTest
public class FixCasesIDBatchTest {
    @testSetup
    static void setup(){
        User u = TestDataFactory.createUser('System Administrator', 'mcid', 'ID', 'MC', 'Connect-CRM ID');
        insert u;
        Account a = TestDataFactory.createTestHousehold(1, 'ID')[0];
        Contact adult = TestDataFactory.createContact(true, a.Id, null, Date.parse('01/01/1990'), '0912345678');
        Contact child = TestDataFactory.createContact(false, a.Id, adult.Id, Date.parse('01/01/2022'), '');
        Affiliate_Value__c cityDefault = TestDataFactory.createAffiliateValue('City', 'TEST_CITY_DEFAULT', 'ID', null);
        Affiliate_Value__c districtDefault = TestDataFactory.createAffiliateValue('District', 'TEST_DISTRICT_DEFAULT', 'ID', cityDefault.Id);
        String streetNameDefault = 'TEST_STREET_DEFAULT';
		Address__c addressDefault = TestDataFactory.createAddress(true, adult.Id, 'Indonesia', cityDefault.Id, districtDefault.Id, null, streetNameDefault);
        
        AbbottPartner__c ap = TestDataFactory.createAbbottPartner('ID', 'Dietician', 'AA');
        PricebookEntry pbe = TestDataFactory.createPricebookEntry('ID', 'IDR');
        PricebookEntry pbe1 = TestDataFactory.createProductAndPricebookEntryDiffBrand('ID', 'IDR', pbe.Pricebook2Id, 'Pediasure');
        PricebookEntry pbe2 = TestDataFactory.createProductAndPricebookEntryDiffBrand('ID', 'IDR', pbe.Pricebook2Id, 'Ensure');
        PricebookEntry pbe3 = TestDataFactory.createProductAndPricebookEntryDiffBrand('ID', 'IDR', pbe.Pricebook2Id, 'Pediasure');
        Product2 prod1 = [SELECT Id, ParentBrand__c FROM Product2 WHERE Id =: pbe1.Product2Id];
        Product2 prod2 = [SELECT Id, ParentBrand__c FROM Product2 WHERE Id =: pbe2.Product2Id];
        Product2 prod3 = [SELECT Id, ParentBrand__c FROM Product2 WHERE Id =: pbe3.Product2Id];

        Channel__c channel = TestDataFactory.createTestChannel(1, 'ID', 'TEST_CHANNEL')[0];
        Campaign campPed = TestDataFactory.createCampaignInsert('ID1.0_Pediasure_Call1_Verificationcall', 'Pediasure', 'ID', prod1.ParentBrand__c);
        Campaign campEns = TestDataFactory.createCampaignInsert('ID2.0_Ensure_Call1_Verificationcall', 'Ensure', 'ID', prod2.ParentBrand__c);
        Campaign campRet = TestDataFactory.createCampaignInsert('ID1.2_Pediasure_Offline_Call2_Strike', 'Pediasure', 'ID', prod3.ParentBrand__c);
        
        BrandRelationship__c br1 = TestDataFactory.createTestBrandRelationShipwithUser(1, adult.Id, child.Id, prod1.Id)[0];
        BrandRelationship__c br2 = TestDataFactory.createTestBrandRelationShipwithUser(1, adult.Id, child.Id, prod2.Id)[0];
        BrandRelationship__c br3 = TestDataFactory.createTestBrandRelationShipwithUser(1, adult.Id, child.Id, prod3.Id)[0];
        ChannelResponse__c cr1 = TestDataFactory.createTestChannelResponseMultiple(1, br1, channel, addressDefault, prod1, true, 'Pending')[0];
        ChannelResponse__c cr2 = TestDataFactory.createTestChannelResponseMultiple(1, br2, channel, addressDefault, prod2, true, 'Pending')[0];
        ChannelResponse__c cr3 = TestDataFactory.createTestChannelResponseMultiple(1, br3, channel, addressDefault, prod3, true, 'Pending')[0];
    }
    static testmethod void missingCase(){
        Test.startTest();
        ChannelResponse__c crEns = [SELECT Id, Name FROM ChannelResponse__c WHERE BrandRelationship__r.KeyBrand__c = 'Ensure' LIMIT 1][0];
        ChannelResponse__c crPed = [SELECT Id, Name FROM ChannelResponse__c WHERE BrandRelationship__r.KeyBrand__c = 'Pediasure' LIMIT 1][0];
        List<String> crNames = new List<String>{crEns.Name, crPed.Name};
            
        FixCasesIDBatch batch = new FixCasesIDBatch(crNames, 'Missing', ''); 
        Database.executebatch(batch, 200);
        Test.stopTest();
    }
    static testmethod void retentionCase(){
        Test.startTest();
        List<String> crNames = new List<String>();
        for(ChannelResponse__c cr : [SELECT Id, Name FROM ChannelResponse__c WHERE BrandRelationship__r.KeyBrand__c = 'Pediasure']){
            crNames.add(cr.Name);
        }
        
        FixCasesIDBatch batch = new FixCasesIDBatch(crNames, 'Retention', 'ID1.2_Pediasure_Offline_Call2_Strike'); 
        Database.executebatch(batch, 200);
        Test.stopTest();
    }
    static testmethod void noCR(){
        List<String> crNames = new List<String>();
            
        Test.startTest();
        FixCasesIDBatch batch = new FixCasesIDBatch(crNames, 'Missing', ''); 
        Database.executebatch(batch, 200);
        Test.stopTest();
    }
}