force-app/main/default/objects/AbbottPartner__c/AbbottPartner__c.object-meta.xml
<CustomObject>
    <label>Abbott Partner</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Abbott Partner</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abbott Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AbbottPartner__c/fields/PartnerName__c.field-meta.xml
<CustomField>
    <fullName>PartnerName__c</fullName>
    <label>Partner Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AbbottPartner__c/recordTypes/Dietician.recordType-meta.xml
<RecordType>
    <fullName>Dietician</fullName>
    <active>true</active>
    <label>Dietician</label>
</RecordType>

force-app/main/default/objects/AbbottWorkplace__c/AbbottWorkplace__c.object-meta.xml
<CustomObject>
    <label>Abbott Workplace</label>
    <nameField>
        <displayFormat>WP-{000000000}</displayFormat>
        <label>Abbott Workplace Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Abbott Workplaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AbbottWorkplace__c/fields/AbbottPartner__c.field-meta.xml
<CustomField>
    <fullName>AbbottPartner__c</fullName>
    <label>Abbott Partner</label>
    <referenceTo>AbbottPartner__c</referenceTo>
    <relationshipLabel>Abbott Workplace</relationshipLabel>
    <relationshipName>Abbott_Workplace</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AbbottWorkplace__c/fields/EmailOptOut__c.field-meta.xml
<CustomField>
    <fullName>EmailOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AbbottWorkplace__c/fields/EmailOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptOutDate__c</fullName>
    <label>Email Opt Out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AbbottWorkplace__c/fields/InstitutionEmail__c.field-meta.xml
<CustomField>
    <fullName>InstitutionEmail__c</fullName>
    <label>Institution Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AbbottWorkplaceTriggerHandlerTest.cls
@isTest
public class AbbottWorkplaceTriggerHandlerTest {
    
    static testmethod void testOnInsert(){
        AbbottPartner__c ap = new AbbottPartner__c();
        ap.RecordTypeId = Schema.SObjectType.AbbottPartner__c.getRecordTypeInfosByDeveloperName().get('Dietician').getRecordTypeId();
        ap.PartnerName__c = 'Test Abbott Partner';
        ap.Active__c = true;
        insert ap;
        
        List<AbbottWorkplace__c> awpNewList = new List<AbbottWorkplace__c>();
        AbbottWorkplace__c awp1 = new AbbottWorkplace__c();
        awp1.AbbottPartner__c = ap.Id;
        awp1.InstitutionEmail__c = 'test@test.com';
        awpNewList.add(awp1);        
        AbbottWorkplace__c awp2 = new AbbottWorkplace__c();
        awp2.AbbottPartner__c = ap.Id;
        awp2.InstitutionEmail__c = 'test@sample.com';
        awpNewList.add(awp2);
        insert awpNewList;
        
        Test.startTest();
        AbbottWorkplace__c awp3 = new AbbottWorkplace__c();
        awp3.AbbottPartner__c = ap.Id;
        awp3.InstitutionEmail__c = 'test@test.com';
        awp3.EmailOptOut__c = true;
        awp3.EmailOptOutDate__c = Date.today();
        insert awp3;
        Test.stopTest();
        
        List<AbbottWorkplace__c> awpList = new List<AbbottWorkplace__c>([SELECT EmailOptOut__c, EmailOptOutDate__c FROM AbbottWorkplace__c]);
        System.assertEquals(true, awpList[0].EmailOptOut__c);
        System.assertEquals(false, awpList[1].EmailOptOut__c);
        System.assertEquals(true, awpList[2].EmailOptOut__c);
        System.assertEquals(awpList[0].EmailOptOutDate__c, awpList[2].EmailOptOutDate__c);        
        System.assertNotEquals(awpList[1].EmailOptOutDate__c, awpList[2].EmailOptOutDate__c);
       
    }
    static testmethod void testOnUpdate(){
        AbbottPartner__c ap = new AbbottPartner__c();
        ap.RecordTypeId = Schema.SObjectType.AbbottPartner__c.getRecordTypeInfosByDeveloperName().get('Dietician').getRecordTypeId();
        ap.PartnerName__c = 'Test Abbott Partner';
        ap.Active__c = true;
        insert ap;
        
        List<AbbottWorkplace__c> awpNewList = new List<AbbottWorkplace__c>();
        AbbottWorkplace__c awp1 = new AbbottWorkplace__c();
        awp1.AbbottPartner__c = ap.Id;
        awp1.InstitutionEmail__c = 'test@test.com';
        awpNewList.add(awp1);
        AbbottWorkplace__c awp2 = new AbbottWorkplace__c();
        awp2.AbbottPartner__c = ap.Id;
        awp2.InstitutionEmail__c = 'test@sample.com';
        awpNewList.add(awp2);
        AbbottWorkplace__c awp3 = new AbbottWorkplace__c();
        awp3.AbbottPartner__c = ap.Id;
        awp3.InstitutionEmail__c = 'test@test.com';
        awpNewList.add(awp3);
        insert awpNewList;
        
        Test.startTest();
        awp3.EmailOptOut__c = true;
        awp3.EmailOptOutDate__c = Date.today();
        update awp3;
        Test.stopTest();
        
        List<AbbottWorkplace__c> awpList = new List<AbbottWorkplace__c>([SELECT EmailOptOut__c, EmailOptOutDate__c FROM AbbottWorkplace__c]);
        System.assertEquals(true, awpList[0].EmailOptOut__c);
        System.assertEquals(false, awpList[1].EmailOptOut__c);
        System.assertEquals(true, awpList[2].EmailOptOut__c);
        System.assertEquals(awpList[0].EmailOptOutDate__c, awpList[2].EmailOptOutDate__c);        
        System.assertNotEquals(awpList[1].EmailOptOutDate__c, awpList[2].EmailOptOutDate__c);       
    }

}