force-app/main/default/objects/OrderItem/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[22-Sep-21 Khai] This is a debug field to query the OrderItem market based on the product selected</description>
    <formula>TEXT(Product2.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Max_Birth_Month__c.field-meta.xml
<CustomField>
    <fullName>Product_Max_Birth_Month__c</fullName>
    <label>Product Max Birth Month</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Product_Min_Birth_Month__c.field-meta.xml
<CustomField>
    <fullName>Product_Min_Birth_Month__c</fullName>
    <label>Product Min Birth Month</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Max_Birth_Month__c.field-meta.xml
<CustomField>
    <fullName>Max_Birth_Month__c</fullName>
    <description>Identifies the maximum age of the child for eligible first purchase promo.</description>
    <label>Max Birth Month</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Min_Birth_Month__c.field-meta.xml
<CustomField>
    <fullName>Min_Birth_Month__c</fullName>
    <description>Identifies the minimum age of the child for eligible first purchase promo.</description>
    <label>Min Birth Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/classes/ProductTriggerHelper.cls
/*------------------------------------------------------------
Author:      Jennifer Alviz
Description: Helper class for Product object
             
History
07/25/2019   malviz   Created
14/09/2021   mparihar  add null and blank check 
-------------------------------------------------------------------------------------------*/
public class ProductTriggerHelper {
    public static void checkDuplicateProductCode(List<Product2> productList, Map<id, sObject> oldProductMap){
        
        Map<String, Product2> productCodeMap = new Map<String, Product2>(); 
        
        for(Product2 p : productList){ 
            String oldProductCode;
            String oldMarket;
            if(Trigger.IsUpdate && oldProductMap.containsKey(p.Id)){
                Product2 oldProduct = (Product2) oldProductMap.get(p.Id);
                oldProductCode = oldProduct.ProductCode;
                oldMarket = oldProduct.Market__c;
            }
            
            if((Trigger.IsInsert && p.ProductCode != null) || 
               (Trigger.IsUpdate && p.ProductCode != null && p.ProductCode != oldProductCode) || ( Trigger.IsUpdate && p.Market__c != null && p.Market__c != oldMarket)){
                productCodeMap.put(p.ProductCode, p);
            }
        }
        
        List<Product2> duplicateList = [Select Name, ProductCode, Market__c FROM Product2 WHERE ProductCode IN :productCodeMap.Keyset()];
        if(!duplicateList.isEmpty()){//added by Monika /***emptycheck***/
            for(Product2 p :  duplicateList){
                Product2 newProduct = productCodeMap.get(p.ProductCode);
                if(p.Market__c != null && newProduct.Market__c != null && p.Market__c == newProduct.Market__c){//added by Monika /***nullcheck***/
                    system.debug('Error: ' + p.Name + ' ' + p.ProductCode);
                    newProduct.ProductCode.addError('There is already an existing product with the same Product Code. Please update the Product Code before saving.');
                }
            }
        }
                
    }
    
    public static void updateMinMaxBirthMonth(Map<Id, SObject> newProductMap, Map<Id, SObject> oldProductMap){
        Map<Id, List<OrderItem>> productToOrderItemListMap = new Map<Id, List<OrderItem>>();
        List<OrderItem> updateOrderItemList = new List<OrderItem>();

        for(OrderItem o : [SELECT Id, Product2Id, Product_Min_Birth_Month__c, Product_Max_Birth_Month__c FROM OrderItem WHERE Product2Id IN: newProductMap.keySet()]){
            if(!productToOrderItemListMap.isEmpty() && productToOrderItemListMap.containsKey(o.Product2Id)){   
                productToOrderItemListMap.get(o.Product2Id).add(o);
            }
            else{
                productToOrderItemListMap.put(o.Product2Id, new List<OrderItem>{o});
            }
        }
        
        for(Product2 p : (List<Product2>) newProductMap.values()){
            Product2 oldProduct = (Product2) oldProductMap.get(p.Id);
            Boolean maxBirthMonthChanged = p.Max_Birth_Month__c != oldProduct.Max_Birth_Month__c;
            Boolean minBirthMonthChanged = p.Min_Birth_Month__c != oldProduct.Min_Birth_Month__c;
            if(maxBirthMonthChanged || minBirthMonthChanged){
                if(productToOrderItemListMap.containsKey(p.Id)){
                    List<OrderItem> orderItemList = productToOrderItemListMap.get(p.Id);
                    for(OrderItem oi : orderItemList){
                        if(maxBirthMonthChanged) oi.Product_Max_Birth_Month__c = p.Max_Birth_Month__c == null ? 0 : p.Max_Birth_Month__c;
                        if(minBirthMonthChanged) oi.Product_Min_Birth_Month__c = p.Min_Birth_Month__c == null ? 0 : p.Min_Birth_Month__c;
                        updateOrderItemList.add(oi);
                    }
                }
            }
        }
		
        if(!updateOrderItemList.isEmpty()){
            update updateOrderItemList;
        }
    }
    
}