force-app/main/default/objects/OrderItem/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PromotionItem__c.field-meta.xml
<CustomField>
    <fullName>PromotionItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Item</label>
    <referenceTo>PromotionItem__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionItem__c/PromotionItem__c.object-meta.xml
<CustomObject>
    <label>Promotion Item</label>
    <nameField>
        <displayFormat>PI-{000000000}</displayFormat>
        <label>Promotion Item Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionItem__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Promotion Items</relationshipLabel>
    <relationshipName>Promotion_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderProductBatch.cls
// for deletion
public class OrderProductBatch {} /* implements Database.Batchable<sObject> {
	
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		String query = 'SELECT ID , PromotionItem__c, Promotion__c'                           
            + ' FROM OrderItem'
            + ' WHERE'
            + ' (CreatedDate = TODAY OR CreatedDate = YESTERDAY)';
        return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<OrderItem> scope) {
		Set<Id> promoItedIdSet = new Set<Id>();
        List<OrderItem> orderItemList =  new List<OrderItem>();
        for(OrderItem oi : scope) {
            if(oi.PromotionItem__c != null) {
                promoItedIdSet.add(oi.PromotionItem__c);
                orderItemList.add(oi);
            }
        }
        
        if (!promoItedIdSet.isEmpty()) {
        	Map<Id,PromotionItem__c> promoItemMap = new Map<Id,PromotionItem__c>([Select Promotion__c
                                                            FROM PromotionItem__c
                                                            WHERE Id IN :promoItedIdSet ]);

        	for(OrderItem oi : orderItemList) {
	            if(promoItemMap.containsKey(oi.PromotionItem__c)) {
	                oi.Promotion__c = promoItemMap.get(oi.PromotionItem__c).Promotion__c;
	            }
        	}

        	Update orderItemList;
        }
 
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}*/