force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/External_Call_Execution__c.field-meta.xml
<CustomField>
    <fullName>External_Call_Execution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>External Call Execution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/External_Call_Execution__c.field-meta.xml
<CustomField>
    <fullName>External_Call_Execution__c</fullName>
    <formula>Campaign__r.External_Call_Execution__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External Call Execution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/ExtractedFlag__c.field-meta.xml
<CustomField>
    <fullName>ExtractedFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ExtractedFlag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CallRelatedListControllerTest.cls
/*
* @author        Rey Austral
* @date          1.28.2019
* @description   Test class for ExportOrderSGBatch and ExportOrderSGBatchScheduler
* @revision(s) 
*/
@isTest
private class CallRelatedListControllerTest {
    @testsetup
    static void setupData() {
    	User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'VN');
        insert sysad;
        
	    System.runAs(sysad) {
	        List<Campaign> campList = new List<Campaign>();
	        List<Account> accList = TestDataFactory.createTestHousehold(1);
	        accList.get(0).Market__c = 'VN';
			Update accList;

			List<Contact> conList = TestDataFactory.createTestAdultContact(1, accList.get(0).Id);			

			Campaign cam = TestDataFactory.createCampaign('Test Campaign 1', 'Similac', 'VN');
			cam.External_Call_Execution__c = true;
			Insert cam;

	        Case call = TestDataFactory.createCaseCall(accList.get(0).Id, conList.get(0).Id );
	        call.Market__c = 'VN';	       
	        call.ExtractedFlag__c = false;
            call.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Call').getRecordTypeId();
	        Update call;
	     
		}
    }
    
    @isTest
    static void test_queryCallRecord() {
        User sysad = [Select id from User where Alias='tstSysAd' Limit 1];
        System.runAs(sysad) {           
            System.Test.startTest();
                Id contactId = [Select Id from Contact limit 1].Id;
                
                List<Case> orderList = CallRelatedListController.getCall(1,1,contactId);
                orderList = CallRelatedListController.queryCall(contactId);
                Integer totalCount = CallRelatedListController.getTotalCount(contactId);
                String recordTypeId = CallRelatedListController.getCallRecordType();
               
            System.Test.stopTest();
        

            System.assertEquals(1 , orderList.size());
            System.assert(String.isNotEmpty(recordTypeId));
        }
    }
}