force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/AutoAssignCalls__c.field-meta.xml
<CustomField>
    <fullName>AutoAssignCalls__c</fullName>
    <formula>Campaign__r.AutoAssignCalls__c</formula>
    <label>Auto-Assign Calls</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FirstRepeatOrderName__c.field-meta.xml
<CustomField>
    <fullName>FirstRepeatOrderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[9-Jul-21 KSK] Used in TW Market Data Migration; Dynamics CRM</description>
    <label>First Repeat Order Name</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (First Repeat Order Name)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderedBy__c.field-meta.xml
<CustomField>
    <fullName>OrderedBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordered By</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Adult</value>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderMonitoring.cls
/*
Monitors if there is an order that has been cancelled - abandoned.
Update case' skill requirement so omni channel can reroute it to correct agent
*/
public class OrderMonitoring implements Database.Batchable<sObject>{

    Id callRecordType;

    public OrderMonitoring() {
        callRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Call').getRecordTypeId();
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        String f = 'Status';
        Datetime dt = Datetime.Now().addHours(-1);

        String queryStr = 'SELECT Order.OrderedBy__c, OldValue, NewValue'
                        + ' FROM OrderHistory'
                        + ' WHERE Field =: f'
                        + ' AND Order.Account.Market__c = \'PH\''
                        + ' AND CreatedDate >=: dt';

        return Database.getQueryLocator(queryStr);
    }
    
    public void execute(Database.BatchableContext BC, List<OrderHistory> orderHistories){

        String newVal = 'Cancelled - Abandoned';
        Set<Id> contactIds = new Set<Id>();
        for(OrderHistory oh: orderHistories){
            if(oh.NewValue == newVal){
                contactIds.add(oh.Order.OrderedBy__c);
            }
        }
        
        if(!contactIds.isEmpty()) process(contactIds);
    }
    public void finish(Database.BatchableContext BC){}

    public void process(Set<Id> contactIds){
        List<Id> caseIds = new List<Id>();
        for(Contact con: [SELECT (SELECT Id FROM Orders__r),
                                 (SELECT Id FROM Cases
                                   WHERE Status = 'New'
                                     AND RecordTypeId =: callRecordType
                                     AND AutoAssignCalls__c = true)
                          FROM Contact
                         WHERE Id IN: contactIds]){
            if(con.Orders__r.size() == 1) {
                for(Case c: con.Cases){
                    caseIds.add(c.Id);
                }
            }
        }

        if(!caseIds.isEmpty()){
            Delete [SELECT id FROM PendingServiceRouting WHERE WorkItemId IN: caseIds];
            SkillsBasedRouting.routeUsingSkills(caseIds);
        }
    }
    
}