force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/IsFromTW__c.field-meta.xml
<CustomField>
    <fullName>IsFromTW__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is From TW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[22-Sep-21 Khai] This is a debug field to query the OrderItem market based on the product selected</description>
    <formula>TEXT(Product2.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OrderProductTrigger_DummyBatch.cls
public class OrderProductTrigger_DummyBatch implements Database.Batchable<sObject>, Database.Stateful {
    public OrderProductTrigger_DummyBatch(){}

    public Database.QueryLocator start(Database.BatchableContext BC){
        String queryStr = 'SELECT Id, Status FROM Order WHERE Account.Market__c = \'TW\' AND Status = \'Completed\'';

        return Database.getQueryLocator(queryStr);
    }

    public void execute(Database.BatchableContext BC, List<Order> oList){
        Set<Id> orderIds = new set<Id>();
        List<OrderItem> oiRecordsToUpdate = new List<OrderItem>();

        for(Order o: oList) {
            orderIds.add(o.Id);
        }

        List<OrderItem> oiList = [SELECT Id, IsFromTW__c FROM OrderItem WHERE OrderId IN :orderIds AND Product_Family__c = :CommonConstant.ANDPRODUCT];
        
        for(OrderItem oi: oiList) {
            oi.IsFromTW__c = true;

            oiRecordsToUpdate.add(oi);
        }
        
        if(!oiRecordsToUpdate.isEmpty()) Utilityclass.updateList(oiRecordsToUpdate);
    }

    public void finish(Database.BatchableContext BC){}
}