force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <label>Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/DiceEcardStatus__c.field-meta.xml
<CustomField>
    <fullName>DiceEcardStatus__c</fullName>
    <description>Status that being returned once Dice e-card creation API triggered</description>
    <label>DiceECardStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed-BrandError</fullName>
            </value>
            <value>
                <fullName>Failed-LimitExceeded</fullName>
            </value>
            <value>
                <fullName>Failed-ECardsNotAvailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[1-Sep-21 Khai] This field is for troubleshooting by extracting out the market of the Contact</description>
    <formula>Contact__r.Market__c</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ChildrenUnderMilkCodeRestriction__c.field-meta.xml
<CustomField>
    <fullName>ChildrenUnderMilkCodeRestriction__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Children Under Milk Code Restriction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SMSOptOut__c.field-meta.xml
<CustomField>
    <fullName>SMSOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dice_Custom_Setting__c/Dice_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Dice Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/classes/DiceMembershipCreation_Test.cls
/*------------------------------------------------------------
Author      : Mario Christ
Description : Test class for Dice Membership Creation

History
22-Nov-2022   Mario Christ   Created class
-------------------------------------------------------------------------------------------*/
@isTest
public class DiceMembershipCreation_Test {
    @testsetup
    static void setup() {
    	User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'PH');
        insert sysad;

        Dice_Custom_Setting__c setting = new Dice_Custom_Setting__c();
        setting.Key__c = 'DiceEcardAPIDate';
        setting.Value__c = '2022-11-15';
        insert setting;

        
        System.runAs(sysad) {
            //create Household
			List<Account> lAccount = TestDataFactory.createTestHousehold(1);
            lAccount[0].Market__c = 'PH';
            update lAccount;

            //create Contact
            List<Contact> lContact = TestDataFactory.createTestAdultContact(5, lAccount[0].Id);

            for(Contact contactRec : lContact){
                contactRec.ChildrenUnderMilkCodeRestriction__c = 0;
                contactRec.SMSOptOut__c = false;
                contactRec.DoNotCall = false;
                contactRec.Active__c = true;
            }

            update lContact;
            

            //create Product
            List<Product2> lProduct = TestDataFactory.createTestBrandProduct(1);

            //create BR
            BrandRelationship__c lBr1 = TestDataFactory.createTestBrandRelationShip(1, lContact[0].Id,lProduct[0].Id)[0];
            lBr1.FirstTransactionDate__c = null;
            update lBr1;

            //create Channel
            Channel__c lChannel = TestDataFactory.createTestChannel(1, 'PH', 'Test Facebook')[0];

            //create CR
            ChannelResponse__c crRec1 = TestDataFactory.createTestChannelResponse(lBr1, lChannel);

            System.debug(crRec1);
            
		}
    }

    public static testMethod void executeBatchFailed() {
        User sysad = [SELECT Id FROM User WHERE Alias = 'tstSysAd' LIMIT 1];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DiceHTTPCalloutMockFailed());
		System.runAs(sysad) {
			DiceMembershipCreation_Batch diceBatch = new DiceMembershipCreation_Batch();
            Database.executeBatch(diceBatch, 200);
    	}
    	Test.stopTest();
    	
        ChannelResponse__c crRec1Test =[SELECT Id, DiceEcardStatus__c FROM ChannelResponse__c LIMIT 1];
        System.debug(crRec1Test);
    	
    	System.assertEquals('Failed', crRec1Test.DiceEcardStatus__c);
    }

    public static testMethod void executeBatchFailed2() {
        User sysad = [SELECT Id FROM User WHERE Alias = 'tstSysAd' LIMIT 1];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DiceHTTPCalloutMockFailed2());
		System.runAs(sysad) {
			DiceMembershipCreation_Batch diceBatch = new DiceMembershipCreation_Batch();
            Database.executeBatch(diceBatch, 200);
    	}
    	Test.stopTest();
    	
        ChannelResponse__c crRec1Test =[SELECT Id, DiceEcardStatus__c FROM ChannelResponse__c LIMIT 1];
        System.debug(crRec1Test);
    	
    	System.assertEquals('Failed-BrandError', crRec1Test.DiceEcardStatus__c);
    }

    public static testMethod void executeBatchFailed3() {
        User sysad = [SELECT Id FROM User WHERE Alias = 'tstSysAd' LIMIT 1];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DiceHTTPCalloutMockFailed3());
		System.runAs(sysad) {
			DiceMembershipCreation_Batch diceBatch = new DiceMembershipCreation_Batch();
            Database.executeBatch(diceBatch, 200);
    	}
    	Test.stopTest();
    	
        ChannelResponse__c crRec1Test =[SELECT Id, DiceEcardStatus__c FROM ChannelResponse__c LIMIT 1];
        System.debug(crRec1Test);
    	
    	System.assertEquals('Failed-LimitExceeded', crRec1Test.DiceEcardStatus__c);
    }

    public static testMethod void executeBatchFailed4() {
        User sysad = [SELECT Id FROM User WHERE Alias = 'tstSysAd' LIMIT 1];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DiceHTTPCalloutMockFailed4());
		System.runAs(sysad) {
			DiceMembershipCreation_Batch diceBatch = new DiceMembershipCreation_Batch();
            Database.executeBatch(diceBatch, 200);
    	}
    	Test.stopTest();
    	
        ChannelResponse__c crRec1Test =[SELECT Id, DiceEcardStatus__c FROM ChannelResponse__c LIMIT 1];
        System.debug(crRec1Test);
    	
    	System.assertEquals('Failed-ECardsNotAvailable', crRec1Test.DiceEcardStatus__c);
    }

    public static testMethod void executeBatchSuccess() {
        User sysad = [SELECT Id FROM User WHERE Alias = 'tstSysAd' LIMIT 1];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new DiceHTTPCalloutMockSuccess());
		System.runAs(sysad) {
			DiceMembershipCreation_Batch diceBatch = new DiceMembershipCreation_Batch();
            Database.executeBatch(diceBatch, 200);
    	}
    	Test.stopTest();
    	
        ChannelResponse__c crRec1Test =[SELECT Id, DiceEcardStatus__c FROM ChannelResponse__c LIMIT 1];
        System.debug(crRec1Test);
    	
    	System.assertEquals('Created', crRec1Test.DiceEcardStatus__c);
    }
}