force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/fields/ParentAffiliateValue__c.field-meta.xml
<CustomField>
    <fullName>ParentAffiliateValue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Affiliate Value</label>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Affiliate Values</relationshipLabel>
    <relationshipName>Affiliate_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/City.recordType-meta.xml
<RecordType>
    <fullName>City</fullName>
    <active>true</active>
    <description>Defines cities within a given market, to be selected during address creation and updates for a contact</description>
    <label>City</label>
</RecordType>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/District.recordType-meta.xml
<RecordType>
    <fullName>District</fullName>
    <active>true</active>
    <description>Defines the districts within a given market (usually defined by city), used during address creation and updates for a contact</description>
    <label>District</label>
</RecordType>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/classes/AddressCustomLookupControllerTest.cls
/*
* @author        Rey Austral
* @date          8.19.2019
* @description   Test class for AddressCustomLookupController
* @revision(s) 
*/
@isTest
private class AddressCustomLookupControllerTest {
    @testsetup
    static void setupData() {
    	User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'VN');
        insert sysad;
        
	    System.runAs(sysad) {
	        List<Campaign> campList = new List<Campaign>();
	        List<Account> accList = TestDataFactory.createTestHousehold(1);
	        accList.get(0).Market__c = 'VN';
			Update accList;

			List<Contact> conList = TestDataFactory.createTestAdultContact(15, accList.get(0).Id);	
            Affiliate_Value__c avCity = TestDataFactory.createAffiliateValue('City', 'Test City', 'VN', null);
            Affiliate_Value__c avDistrict =TestDataFactory.createAffiliateValue('District', 'Test District', 'VN', avCity.Id);
		}
    }
    
    @isTest
    static void test_fetchRecords() {
        User sysad = [Select id from User where Alias='tstSysAd' Limit 1];
        Affiliate_Value__c city = [SELECT Id FROM Affiliate_Value__c WHERE RecordType.Name = 'City' AND Name = 'Test City'][0];
        System.runAs(sysad) {           
            System.Test.startTest();    
                //LastName is the actual name of the contact person
                List<AddressCustomLookupController.RecordsData> contactList = AddressCustomLookupController.fetchRecords('Contact','Name','LastName','','','Adult');   
            	List<AddressCustomLookupController.RecordsData> district = AddressCustomLookupController.fetchRecords('Affiliate_Value__c','Name','Test','ParentAffiliateValue__c',city.Id,'District');
            try{
                List<AddressCustomLookupController.RecordsData> districtErr = AddressCustomLookupController.fetchRecords('Affiliate_Value__c','Names','Test','ParentAffiliateValue__c',city.Id,'District');
            }catch(Exception e){
                System.debug('Error--'+e.getMessage());
            }
        	
            
            System.Test.stopTest();

            System.assertEquals(15 , contactList.size());
            System.assertEquals('Test District' , district[0].label);
        }
    }

    @isTest
    static void test_fetchTopRecords() {
        User sysad = [Select id from User where Alias='tstSysAd' Limit 1];
        Affiliate_Value__c city = [SELECT Id FROM Affiliate_Value__c WHERE RecordType.Name = 'City' AND Name = 'Test City'][0];
        System.runAs(sysad) {           
            System.Test.startTest();    
                //LastName is the actual name of the contact person
                List<AddressCustomLookupController.RecordsData> contactList = AddressCustomLookupController.fetchTopRecords('Contact','Name','LastName','','','Adult');   
            	List<AddressCustomLookupController.RecordsData> district = AddressCustomLookupController.fetchTopRecords('Affiliate_Value__c','Name','Test','ParentAffiliateValue__c',city.Id,'District');
            try{
                List<AddressCustomLookupController.RecordsData> districtErr = AddressCustomLookupController.fetchTopRecords('Affiliate_Value__c','Names','Test','ParentAffiliateValue__c',city.Id,'District');
            }catch(Exception e){
                System.debug('Error--'+e.getMessage());
            }
            
            System.Test.stopTest();
            //only 10 result will be retrieved even if the total contact records is 15
            System.assertEquals(10 , contactList.size());
            System.assertEquals('Test District' , district[0].label);
        }
    }
}