force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandOptOut__c.field-meta.xml
<CustomField>
    <fullName>BrandOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Brand Opt-Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestMilestone__c.field-meta.xml
<CustomField>
    <fullName>LatestMilestone__c</fullName>
    <label>Latest Milestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Loyalty_Length_in_Months__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Length_in_Months__c</fullName>
    <formula>MONTH(LatestTransactionDate__c) + (12*(YEAR(LatestTransactionDate__c)-YEAR(FirstTransactionDate__c))) - MONTH(FirstTransactionDate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loyalty Length (in Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/MilestoneStatus__c.field-meta.xml
<CustomField>
    <fullName>MilestoneStatus__c</fullName>
    <label>Milestone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Send</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Milestone</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Cases (Milestone)</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/WeeksofPregnancy__c.field-meta.xml
<CustomField>
    <fullName>WeeksofPregnancy__c</fullName>
    <formula>CallRegarding__r.WeeksOfPregnancy__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weeks of Pregnancy</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AgeinMonths__c.field-meta.xml
<CustomField>
    <fullName>AgeinMonths__c</fullName>
    <formula>IF(NOT(ISBLANK(Birthdate)),
        IF(DAY(Birthdate) &lt;= DAY(TODAY()),
        (YEAR( TODAY())*12+MONTH(TODAY())) - (YEAR(Birthdate)*12+MONTH(Birthdate)),
        (YEAR( TODAY())*12+MONTH(TODAY())) - (YEAR(Birthdate)*12+MONTH(Birthdate))-1
        ),
        0
        )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age (in Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Brand_Relationship_EndUser_Child_Count__c.field-meta.xml
<CustomField>
    <fullName>Brand_Relationship_EndUser_Child_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Custom rollup field for counting BRs related to Contact through BR EndUser field</description>
    <label>Brand Relationship EndUser Child Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BrandRelationshipCount__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationshipCount__c</fullName>
    <label>Brand Relationship Count</label>
    <summaryFilterItems>
        <field>BrandRelationship__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>BrandRelationship__c.User__c</field>
        <operation>notEqual</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>BrandRelationship__c.PrimaryContact__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Fill in the Main Contact for this person (e.g. child or elderly person) under the main contact&apos;s care. This field is not required if this person is a Primary Contact.</inlineHelpText>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WeeksOfPregnancy__c.field-meta.xml
<CustomField>
    <fullName>WeeksOfPregnancy__c</fullName>
    <formula>IF (FLOOR( (TODAY() - (EstimatedDueDate__c  - 280) )/7 ) &gt;= 0 ,
FLOOR( (TODAY() - (EstimatedDueDate__c  - 280) )/7 ),
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weeks of Pregnancy</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Used to track age milestones to trigger different marketing cloud journeys</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/MilestoneValue__c.field-meta.xml
<CustomField>
    <fullName>MilestoneValue__c</fullName>
    <inlineHelpText>Input whole numbers only</inlineHelpText>
    <label>Milestone Value</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone__c/recordTypes/AgeInMonths.recordType-meta.xml
<RecordType>
    <fullName>AgeInMonths</fullName>
    <active>true</active>
    <description>Used to track Child&apos;s Age in Months</description>
    <label>Age In Months</label>
</RecordType>

force-app/main/default/objects/Milestone__c/recordTypes/LoyaltyLength.recordType-meta.xml
<RecordType>
    <fullName>LoyaltyLength</fullName>
    <active>true</active>
    <description>Customer&apos;s Loyalty Length in Months</description>
    <label>Loyalty Length</label>
</RecordType>

force-app/main/default/objects/Milestone__c/recordTypes/WeeksofPregnancy.recordType-meta.xml
<RecordType>
    <fullName>WeeksofPregnancy</fullName>
    <active>true</active>
    <description>Used to track Mother&apos;s Weeks of  Pregnancy</description>
    <label>Weeks of Pregnancy</label>
</RecordType>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ANZ</fullName>
    </customValue>
    <customValue>
        <fullName>HK</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
    </customValue>
    <customValue>
        <fullName>TW</fullName>
    </customValue>
    <customValue>
        <fullName>VN</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
        <isActive>false</isActive>
        <label>NZ</label>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
        <isActive>false</isActive>
        <label>AU</label>
    </customValue>
    <masterLabel>Market</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/MC_Milestones.cls
/*
Author: Jericson Mercado
Description: updates the record just to change modified date so SC and MC will sync, because marketing cloud was not able to pick up changes in formula field.
NOTE: if there is a scheduled job for the country but there is no active filter specified in the milestone object, this job will just throw an error.
This is designed to handle 1 milestone at a time, salesforce is unable to handle too many records
*/
public class MC_Milestones implements Database.Batchable<sObject>, Database.Stateful {
    
    /* UPDATE THIS IN CASE THERE IS A NEW RECORD TYPE */
    Static Id RTAgeInMonths = Schema.SObjectType.Milestone__c.getRecordTypeInfosByDeveloperName().get('AgeInMonths').getRecordTypeId();
    Static Id RTWeeksofPregnancy = Schema.SObjectType.Milestone__c.getRecordTypeInfosByDeveloperName().get('WeeksofPregnancy').getRecordTypeId();
    Static Id RTLoyaltyLength = Schema.SObjectType.Milestone__c.getRecordTypeInfosByDeveloperName().get('LoyaltyLength').getRecordTypeId();
    Static Id conAdultRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Adult').getRecordTypeId();
    Static Id conChildRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Child').getRecordTypeId();
    
    Map<Id, String> apiMap = new Map<Id, String>();
    
    String queryParam;
    String Market;
    
    Map<String, List<Milestone__c>> milestoneMap;
    Map<String, Set<String>> milestoneNames;
    
    public MC_Milestones(Set<Id> ids){
        
        // set field map
        apiMap.put(RTAgeInMonths, 'User__r.AgeinMonths__c');
        apiMap.put(RTWeeksofPregnancy, 'User__r.WeeksOfPregnancy__c');
        apiMap.put(RTLoyaltyLength, 'Loyalty_Length_in_Months__c');
        
        milestoneMap = new Map<String, List<Milestone__c>>();
        milestoneNames = new Map<String, Set<String>>();
        
        for(Milestone__c ms: [SELECT Name, MilestoneValue__c, RecordTypeId, Market__c
                              FROM Milestone__c
                              WHERE Id IN: ids])
        {
            if(!milestoneMap.containsKey(ms.Market__c)){
                milestoneMap.put(ms.Market__c, new List<Milestone__c>());
                milestoneNames.put(ms.Market__c, new Set<String>());
            }
            milestoneMap.get(ms.Market__c).add(ms);
            milestoneNames.get(ms.Market__c).add(ms.Name);
        }
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        
        Boolean isFirst = true;
        String queryStr2 = '';
        DateTime todaysDate = System.today();
        String todaysDateStr = todaysDate.format('yyyy-MM-dd');
        List<String> conQueryStringList = new List<String>();
        Map<Id,String> mileStoneConQueryMap = new Map<Id,String>();
        Map<Id,List<Contact>> mileStoneConListMap = new Map<Id,List<Contact>>();
        List<Contact> msConQueryList1 = new List<Contact>();
        List<Contact> msConQueryList2 = new List<Contact>();

        //Contact Query - TW Market not optimized due to PrimaryContact__c in filter
        for(String market: milestoneMap.keySet()){
            if(market != CommonConstant.MARKET_TW){
                for(Milestone__c m: milestoneMap.get(market)){
                    // precaution not to break the query incase a new recordtype suddenly pops up
                    String conQueryString;
                    if(apiMap.containsKey(m.RecordTypeId)) {
                        if(apiMap.get(m.RecordTypeId).contains('User__r')){
                            conQueryString = 'SELECT Id FROM Contact WHERE Active__c = true'
                                + ' AND Account.Market__c = \'' + market + '\'';
                            if(apiMap.get(m.RecordTypeId).contains('AgeinMonths__c')){
                                conQueryString += ' AND RecordTypeId =: conChildRecType'
                                    + ' AND Parent__r.Active__c = true'
                                    + ' AND (Brand_Relationship_EndUser_Child_Count__c > 0 OR BrandRelationshipCount__c > 0)'
                                    + ' AND AgeinMonths__c = ' + m.MilestoneValue__c;
                            }
                            else{
                                conQueryString += ' AND RecordTypeId =: conAdultRecType'
                                    + ' AND WeeksOfPregnancy__c = ' + m.MilestoneValue__c;
                            }
                        }
                    }
                    if(conQueryString != null){
                        mileStoneConQueryMap.put(m.Id, conQueryString);
                    }
                }
            }
        }
        
        if(!mileStoneConQueryMap.keySet().isEmpty()){
            for(Id msId : mileStoneConQueryMap.keySet()){
                System.debug(mileStoneConQueryMap.get(msId));
                List<Contact> msConList = new List<Contact>();
                msConList = Database.query(mileStoneConQueryMap.get(msId));
                if(!msConList.isEmpty()){
                    mileStoneConListMap.put(msId, msConList); 
                }
            }
        }
        
        String queryStr = 'SELECT Id'
            + ' FROM BrandRelationship__c'
            + ' WHERE Active__c = true'
            + ' AND BrandRelationship__c != null'
            + ' AND BrandOptOut__c = false';
        
        //BR Query
        for(String market: milestoneMap.keySet()){
            
            for(Milestone__c m: milestoneMap.get(market)){
                
                // precaution not to break the query incase a new recordtype suddenly pops up
                if(apiMap.containsKey(m.RecordTypeId)) {
                    if(market == CommonConstant.MARKET_TW){
                        if(queryStr2 != ''){
                            queryStr2 += ' OR ';
                        }
                        if(queryStr2 == ''){
                            queryStr2 += ' AND (';
                        }
                        queryStr2 += '( Household__r.Market__c = \'' + market + '\'';
                        if(apiMap.get(m.RecordTypeId).contains('User__r')){
                            if(apiMap.get(m.RecordTypeId).contains('AgeinMonths__c')){
                                queryStr2 += ' AND User__r.RecordTypeId =: conChildRecType AND User__r.Birthdate < '+todaysDateStr+' ';
                            }
                            else{
                                queryStr2 += ' AND User__r.RecordTypeId =: conChildRecType AND User__r.Birthdate > '+todaysDateStr+' ';
                            }
                            
                            if(apiMap.get(m.RecordTypeId).contains('AgeinMonths__c')){
                                queryStr2 += ' AND ' + apiMap.get(m.RecordTypeId) + ' = ' + m.MilestoneValue__c + ' AND (NOT LatestMilestone__c LIKE \'%' + String.escapeSingleQuotes(m.Name) + '%\')';
                            }
                            else{
                                queryStr2 += ' AND PrimaryContact__r.WeeksOfPregnancy__c = ' + m.MilestoneValue__c + ' AND (NOT LatestMilestone__c LIKE \'%' + String.escapeSingleQuotes(m.Name) + '%\')';
                            }
                        }
                        queryStr2 += ')';
                    }
                    else{
                        if(apiMap.get(m.RecordTypeId).contains('User__r')){
                            if(!mileStoneConListMap.keySet().isEmpty() && mileStoneConListMap.containsKey(m.Id)){
                                if(queryStr2 != ''){
                                    queryStr2 += ' OR ';
                                }
                                if(queryStr2 == ''){
                                    queryStr2 += ' AND (';
                                }
                                //Placeholder variables for Contact query (2 milestone at a time)
                                if(msConQueryList1.isEmpty()){
                                    msConQueryList1 = mileStoneConListMap.get(m.Id);
                                    queryStr2 += '( User__c IN: msConQueryList1';
                                }
                                else if(msConQueryList2.isEmpty()){
                                    msConQueryList2 = mileStoneConListMap.get(m.Id);
                                    queryStr2 += '( User__c IN: msConQueryList2';
                                }
                                queryStr2 += ' AND (NOT LatestMilestone__c LIKE \'%' + String.escapeSingleQuotes(m.Name) + '%\') )';
                            }
                        }
                    }
                    
                }
            }
        }
        if(queryStr2 != ''){
            queryStr2 += ')';
            queryStr += queryStr2;
            System.debug(queryStr);
            return Database.getQueryLocator(queryStr);
        }
        else{
            return Database.getQueryLocator('SELECT Id FROM BrandRelationship__c LIMIT 0');
        }
    }
    
    public void execute(Database.BatchableContext BC, List<BrandRelationship__c> brList){
        Map<Id, Set<String>> milestoneHistoryMap = new Map<Id, Set<String>>();
        
        List<BrandRelationship__c> execBRList = [SELECT Id, PrimaryContact__c, PrimaryContact__r.WeeksOfPregnancy__c, Household__r.Market__c, User__c, 
                                                 User__r.AgeinMonths__c, User__r.WeeksOfPregnancy__c, User__r.Birthdate, User__r.RecordType.Name, 
                                                 Loyalty_Length_in_Months__c, LatestMilestone__c FROM BrandRelationship__c WHERE Id IN: brList AND Household__r.Market__c != null];
        if(!execBRList.isEmpty()){
            // create map of all the milestone that has already been sent for the last 2 months
            // changed to last 7 days, EDD/Birthdate can change and may need to revert to old milestone value
            for(BrandRelationship__History history: [SELECT ParentId, NewValue, Field FROM BrandRelationship__History
                                                     WHERE Field =: 'LatestMilestone__c'
                                                     AND ParentId IN: execBRList
                                                     AND CreatedDate = LAST_N_DAYS:1])
            {
                if(history.NewValue != null){
                    if(!milestoneHistoryMap.containsKey(history.ParentId)){
                        milestoneHistoryMap.put(history.ParentId, new Set<String>());
                    }
                    milestoneHistoryMap.get(history.ParentId).add( (String) history.NewValue);
                }
            }
            
            Map<Id, BrandRelationship__c> brForUpdate = new Map<Id, BrandRelationship__c>();
            for(BrandRelationship__c br: execBRList){
                // check milestones being tracked in the market
                for(Milestone__c m: milestoneMap.get(br.Household__r.Market__c)){
                    
                    // check if milestone not yet set before
                    if( !milestoneHistoryMap.containsKey(br.Id)
                       || (milestoneHistoryMap.containsKey(br.Id)
                           && !milestoneHistoryMap.get(br.Id).contains(m.Name)) ){
                               
                               // get field to check
                               String fieldToCheck = apiMap.get(m.RecordTypeId);
                               String fieldToCheck2 = 'PrimaryContact__r.WeeksOfPregnancy__c';
                               Double brValue;
                               Double brValue2;
                               
                               if(fieldToCheck.contains('.')){
                                   brValue = (Double) br.getSobject(fieldToCheck.split('\\.')[0]).get(fieldToCheck.split('\\.')[1]);
                               }
                               else {
                                   brValue = (Double) br.get(fieldToCheck);
                               }
                               
                               if(brValue < 0 && m.RecordTypeId == RTAgeInMonths) {
                                   continue;
                               }
                               
                               if(fieldToCheck2.contains('.')){
                                   brValue2 = (Double) br.getSobject(fieldToCheck2.split('\\.')[0]).get(fieldToCheck2.split('\\.')[1]);
                               }
                               else {
                                   brValue2 = (Double) br.get(fieldToCheck2);
                               }
                               
                               // compare fields
                               if(m.MilestoneValue__c == brValue || m.MilestoneValue__c == brValue2) {
                                   Boolean isForUpdate = false;
                                   if(br.Household__r.Market__c == CommonConstant.MARKET_TW){
                                       if(br.User__r.RecordType.Name == CommonConstant.CONTACT_CHILD_RECORDTYPE) {
                                           if(m.MilestoneValue__c == brValue2
                                              && Date.today() < br.User__r.Birthdate
                                              && m.RecordTypeId == RTWeeksofPregnancy) {
                                                  isForUpdate = true;
                                              }
                                           else if(m.MilestoneValue__c == brValue
                                                   && Date.today() >= br.User__r.Birthdate
                                                   && m.RecordTypeId == RTAgeInMonths) {
                                                       isForUpdate = true;
                                                   }
                                       }
                                       else {
                                           isForUpdate = true;
                                       }
                                   }
                                   else {
                                       isForUpdate = true;
                                   }
                                   
                                   if(isForUpdate){
                                       br.LatestMilestone__c = m.Name;
                                       br.MilestoneStatus__c = 'Ready to Send';
                                       brForUpdate.put(br.Id, br);
                                       break;
                                   }
                               }
                           }
                    else {
                        // get field to check
                        String fieldToCheck = apiMap.get(m.RecordTypeId);
                        String fieldToCheck2 = 'PrimaryContact__r.WeeksOfPregnancy__c';
                        Double brValue;
                        Double brValue2;
                        
                        if(fieldToCheck.contains('.')){
                            brValue = (Double) br.getSobject(fieldToCheck.split('\\.')[0]).get(fieldToCheck.split('\\.')[1]);
                        }
                        else {
                            brValue = (Double) br.get(fieldToCheck);
                        }
                        
                        if(brValue < 0 && m.RecordTypeId == RTAgeInMonths) {
                            continue;
                        }
                        
                        if(fieldToCheck2.contains('.')){
                            brValue2 = (Double) br.getSobject(fieldToCheck2.split('\\.')[0]).get(fieldToCheck2.split('\\.')[1]);
                        }
                        else {
                            brValue2 = (Double) br.get(fieldToCheck2);
                        }
                        
                        if(m.MilestoneValue__c == brValue || m.MilestoneValue__c == brValue2){
                            Boolean isForUpdate = false;
                            if(br.Household__r.Market__c == CommonConstant.MARKET_TW){
                                if(br.User__r.RecordType.Name == CommonConstant.CONTACT_CHILD_RECORDTYPE) {
                                    if(m.MilestoneValue__c == brValue2
                                       && Date.today() < br.User__r.Birthdate
                                       && m.RecordTypeId == RTWeeksofPregnancy) {
                                           isForUpdate = true;
                                       }
                                    else if(m.MilestoneValue__c == brValue
                                            && Date.today() >= br.User__r.Birthdate
                                            && m.RecordTypeId == RTAgeInMonths) {
                                                isForUpdate = true;
                                            }
                                }
                            }
                            else {
                                isForUpdate = true;
                            }
                            
                            if(isForUpdate){
                                br.LatestMilestone__c = m.Name;
                                br.MilestoneStatus__c = 'Ready to Send';
                                brForUpdate.put(br.Id, br);
                                break;
                            }
                        }
                    }
                }
            }
            
            if(!brForUpdate.isEmpty()) Utilityclass.updateList(brForUpdate.values());
        }
    }
    
    public void finish(Database.BatchableContext BC){}
}