force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Brand_Relationship_EndUser_Child_Count__c.field-meta.xml
<CustomField>
    <fullName>Brand_Relationship_EndUser_Child_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Custom rollup field for counting BRs related to Contact through BR EndUser field</description>
    <label>Brand Relationship EndUser Child Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/classes/UpdateChildEndUserCountBatch.cls
global class UpdateChildEndUserCountBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    String market;
    Integer startRange;
    Integer endRange;
    
    global UpdateChildEndUserCountBatch (String inputMarket, Integer inputStartRange, Integer inputEndRange){
        if(!String.isBlank(inputMarket)) market = inputMarket;
        if(inputStartRange != null) startRange = inputStartRange;
        if(inputEndRange != null) endRange = inputEndRange;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Id conChildRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Child').getRecordTypeId();
        String query = 'SELECT Id'
            + ' FROM Contact'
            + ' WHERE Active__c = true AND RecordTypeId =: conChildRecType';   
        if(!String.isBlank(market)){
            query += ' AND Account.Market__c = \'' + market + '\'';
        }
        if(endRange != null && startRange != null){
            query += ' AND (CreatedDate >= LAST_N_DAYS: ' + endRange
                + ' AND CreatedDate <= LAST_N_DAYS: ' + startRange +') ';
        }
        else {
            if(endRange != null){
                query += ' AND (CreatedDate >= LAST_N_DAYS: ' + endRange +') ';
            }
            else if(startRange != null){
                query += ' AND (CreatedDate <= LAST_N_DAYS: ' + startRange +') ';
            }
        }
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        Map<Id, Contact> conUpdateMap = new Map<Id, Contact>();
        if(!scope.isEmpty()){
            for(Contact con : [SELECT Id, Brand_Relationship_EndUser_Child_Count__c, (SELECT Id FROM BrandRelationships__r WHERE Active__c = true) FROM Contact WHERE Id IN: scope]){
                if(!con.BrandRelationships__r.isEmpty()){
                    Contact conRec = new Contact();
                    conRec.Id = con.Id;
                    conRec.Brand_Relationship_EndUser_Child_Count__c = con.BrandRelationships__r.size();
                    conUpdateMap.put(con.Id, conRec);
                }
            }
            
            if(!conUpdateMap.keySet().isEmpty()) UtilityClass.updateList(conUpdateMap.values());
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :BC.getJobId()]; 
        System.debug('>>>> finish ' + job.Status);
    }
    
    global void execute(SchedulableContext sc) {
        UpdateChildEndUserCountBatch batch = new UpdateChildEndUserCountBatch(market, startRange, endRange); 
        Database.executebatch(batch, 50);
    }
    
}