force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/fields/AffiliateValue__c.field-meta.xml
<CustomField>
    <fullName>AffiliateValue__c</fullName>
    <externalId>true</externalId>
    <label>Affiliate Value Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/Successful_Reason.recordType-meta.xml
<RecordType>
    <fullName>Successful_Reason</fullName>
    <active>true</active>
    <description>Defines the reason a call outcome was successful (e.g. converted sale)</description>
    <label>Successful Reason</label>
</RecordType>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CallCompletedDate__c.field-meta.xml
<CustomField>
    <fullName>CallCompletedDate__c</fullName>
    <label>Call Completed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/CallOutcome__c.field-meta.xml
<CustomField>
    <fullName>CallOutcome__c</fullName>
    <label>Call Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Uncontactable</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CallRegarding__c.field-meta.xml
<CustomField>
    <fullName>CallRegarding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filter to show only Contacts within the Case Contact&apos;s Household</description>
    <label>Call Regarding</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Call Regarding)</relationshipLabel>
    <relationshipName>CallRegarding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of Awareness will capture as campaign as well</description>
    <label>Call Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SuccessfulReason__c.field-meta.xml
<CustomField>
    <fullName>SuccessfulReason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Successful Reason</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Successful Reason</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Cases (Successful Reason)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Contact/fields/FirstCallDate__c.field-meta.xml
<CustomField>
    <fullName>FirstCallDate__c</fullName>
    <label>First Call Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LastCallDate__c.field-meta.xml
<CustomField>
    <fullName>LastCallDate__c</fullName>
    <label>Latest Call Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseTriggerBatchTest.cls
// @isTest for deletion
public class CaseTriggerBatchTest {} /*
	
	@testsetup
    static void setupData() {
    	List<User> usrList =  [Select Id From User where LastName = 'Migration'];
    	User sysad = new User();
    	if (usrList.isEmpty()) {
	    	sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'PH');
	    	sysad.FirstName = 'Data';
	    	sysad.LastName = 'Migration';
	        insert sysad;
    	} else {
    		sysad = usrList.get(0);
    	}

        System.runAs(sysad) {	
	        List<Campaign> campList = new List<Campaign>();
	        List<Account> accList = TestDataFactory.createTestHousehold(1);
			List<Contact> conList = TestDataFactory.createTestAdultContact(1, accList.get(0).Id);
	        campList.add(TestDataFactory.createCampaign('Test Campaign 1', 'Similac', 'PH'));
	        insert campList;
    	}
    }
    
    @isTest
    static void testForCompleteDate() {
        Id callRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Call').getRecordTypeId();
        Id srRTId = Schema.SObjectType.Affiliate_Value__c.getRecordTypeInfosByDeveloperName().get('Successful_Reason').getRecordTypeId();
        
        List<Case> caseList = new List<Case>();
        List<Case> updatedCaseList = new List<Case>();
        List<Case> caseListToUpdate = new List<Case>();
        List<Case> caseListToAssert = new List<Case>();
        List<Contact> conList2 = new List<Contact>();
        
        Account a1 = [select Id from Account limit 1];
        List<Contact> conList = [select Id, FirstCallDate__c, LastCallDate__c from Contact limit 1];
        conList[0].FirstCallDate__c = System.today() + 5;
        conList[0].LastCallDate__c = System.today() - 5;
        update conList;
        
		Campaign camp1 = [select Id from Campaign where Name = 'Test Campaign 1'];
        
        User sysad = [Select Id From User where LastName = 'Migration'];
		System.runAs(sysad) {  
	        Affiliate_Value__c af1 = new Affiliate_Value__c();
	        af1.Name = 'Success Test';
	        af1.AffiliateValue__c = 'Success Test';
	        af1.Market__c = 'PH';
	        af1.Active__c = true;
	        insert af1;
	        
	        Case ca1 = new Case();
	        ca1.RecordtypeId = callRTId;
	        ca1.ContactId = conList[0].Id;
	        ca1.CallType__c = 'Outbound';
	        ca1.Status = 'Completed';
	        ca1.AccountId = a1.Id;
	        ca1.CallRegarding__c = conList[0].Id;
	        ca1.Campaign__c = camp1.Id;
	        ca1.CallOutcome__c = 'Successful';
	        ca1.SuccessfulReason__c = af1.Id;
	        
	        insert ca1;
	        ca1.CallCompletedDate__c = Date.today().adddays(-15);
	        update ca1;
	        Test.setCreatedDate(ca1.Id, DateTime.newInstance(2019,06,08));

	        Case ca2 = new Case();
	        ca2.RecordtypeId = callRTId;
	        ca2.ContactId = conList[0].Id;
	        ca2.CallType__c = 'Outbound';
	        ca2.Status = 'Completed';
	        ca2.AccountId = a1.Id;
	        ca2.CallRegarding__c = conList[0].Id;
	        ca2.Campaign__c = camp1.Id;
	        ca2.CallOutcome__c = 'Successful';
	        ca2.SuccessfulReason__c = af1.Id;
	        
	        insert ca2;
	        ca2.CallCompletedDate__c = Date.today().adddays(20);
	        update ca2;
	        Test.setCreatedDate(ca2.Id, DateTime.newInstance(2019,06,09));

	        System.Test.startTest();
	        	CaseTriggerBatch umd = new CaseTriggerBatch();
	        	Database.executeBatch(umd, 200);
	        System.Test.stopTest();
	        
	        
	        caseListToAssert = [select Id, CallCompletedDate__c, CallOutcome__c, SuccessfulReason__c from Case where Id =: ca1.Id or Id=:ca2.Id];
	        
	        System.assertEquals(true, caseListToAssert[0].CallCompletedDate__c != null);
    	}
    }
	
} */