force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderExport2__c/OrderExport2__c.object-meta.xml
<CustomObject>
    <label>Order Export</label>
    <nameField>
        <displayFormat>OE2-{000000000}</displayFormat>
        <label>Order Export Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Exports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderExport2__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Order__r.Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[22-Sep-21 Khai] This is a debug field to query the OrderItem market based on the product selected</description>
    <formula>TEXT(Product2.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[25-Jul-21 Khai] To extract out the product market for troubleshooting purposes</description>
    <formula>TEXT( Product2.Market__c )</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExportSampleRequestOrderBatchTest.cls
/*
* @author        Crissar Ibarra
* @date          8.27.2021
* @description   Test class for ExportSampleRequestOrderBatchScheduler and ExportSampleRequestOrderBatch
* @revision(s) 
*/
@isTest
private class ExportSampleRequestOrderBatchTest {
  
  @testsetup
    static void setupData() {
      User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'SG');
        insert sysad;
        
        System.runAs(sysad) {                       
            List<Account> lAccount = TestDataFactory.createTestHousehold(1);
            lAccount.get(0).Market__c = 'SG';
            Update lAccount;

            List<Contact> lContact = TestDataFactory.createSGTestAdultContact(1, lAccount.get(0).Id);
            PricebookEntry entry = TestDataFactory.createPricebookEntry('SG');
            Insert entry;

            List<Order> lOrder = TestDataFactory.createOrder(1, lAccount.get(0).Id, lContact.get(0).Id, Test.getStandardPricebookId());
            Insert lOrder;   
            Test.setCreatedDate(lOrder.get(0).Id, DateTime.now().addDays(-1));       
            
            OrderItem item = TestDataFactory.createOrderItem(lOrder.get(0).Id, entry.Id);
            insert item;

            lOrder.get(0).Status = CommonConstant.ORDER_STATUS_SUBMITTED;
            update lOrder;
            
            List<OrderExport2__c> oeList = TestDataFactory.createOE(1, lOrder);
            insert oeList;
        }
    }

  @isTest static void test_exportBatch() {    
    
    List<OrderExport2__c> oeList = [SELECT ID FROM OrderExport2__c];
    
    Datetime yesterday = DateTime.now().addDays(-1);
    
    for(OrderExport2__c oe : oeList){
        Test.setCreatedDate(oe.id,yesterday);
    }
    
    System.Test.startTest();
        ExportSampleRequestOrderBatch ucs = new ExportSampleRequestOrderBatch();
        Database.executeBatch(ucs, 200);
    System.Test.stopTest();

      List<ContentVersion> contentList = [SELECT Id, ContentDocumentId FROM ContentVersion];
        //txt file and csv
      System.assertEquals(1, contentList.size());      
  }
  
  @isTest static void test_scheduler() {
    // Implement test code
    ExportSampleRequestOrderBatchScheduler job = new ExportSampleRequestOrderBatchScheduler();
    String sch = '0 0 23 * * ?'; 
    Id scID = System.schedule('Test Export Order Batch Job', sch, job);

    CronTrigger ct = [SELECT Id,
                          CronExpression,
                          TimesTriggered,
                          NextFireTime                          
                          FROM CronTrigger
                          WHERE Id = : scID];
       
        
  }
  
}