force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Will Buy</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Non_User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EstimatedBirthdate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedBirthdate__c</fullName>
    <label>Estimated Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EstimatedDueDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDueDate__c</fullName>
    <label>Estimated Due Date (EDD)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MilkCodeRestriction__c.field-meta.xml
<CustomField>
    <fullName>MilkCodeRestriction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milk Code Restriction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Fill in the Main Contact for this person (e.g. child or elderly person) under the main contact&apos;s care. This field is not required if this person is a Primary Contact.</inlineHelpText>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>72</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/classes/ContactEstimatedDueDateBatch.cls
/**
* @author        Rey Austral
* @date          1.14.2019
* @description   Batch job to run daily to create child record in the contact
* @revision(s)
                 1.30.2019 - update estimated due date to null 
                 1.31.2019 - add milk code restriction field
                 5.27.2019 - change the condition of the main query to include also record that has been created before
                 8.11.2020 - TKT-002360 exclude VN on clearing EDD
                 3.20.2023 - TKT-012178 For SG - create BR upon creation of child EDD
*/
global class ContactEstimatedDueDateBatch Implements Database.Batchable<sObject> {
    
    //TKT-012178 - Product to be used for child EDD
    Product2 simMomChildProduct = [SELECT Id FROM Product2 WHERE ExternalId__c =: System.Label.ContactEDDBatch_Product AND Market__c = 'SG' AND IsActive = true][0];

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT ID , EstimatedDueDate__c, AccountId, OwnerId'                           
            + ' FROM Contact'
            + ' WHERE'
            + ' EstimatedDueDate__c <= TODAY'
            + ' AND PrimaryContact__c = true'
            + ' AND Market__c != \'TW\'';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        List<Contact> lScope = [SELECT ID , EstimatedDueDate__c, AccountId, Account.Market__c, OwnerId, Market__c, (Select Id, Birthdate from Parents__r) 
                                FROM Contact Where ID IN: scope];

        List<Contact> toInsert = new List<Contact>();
        List<BrandRelationship__c> brToInsert = new List<BrandRelationship__c>();
        Map<String, String> accountMarketMap = new Map<String, String>();

        Id childRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(CommonConstant.CONTACT_CHILD_RECORDTYPE).getRecordTypeId();
        for(Contact con : lScope) {
            //TKT-012178 - Map for getting Market from Account
            if(con.AccountId != null && con.Account.Market__c != null && !accountMarketMap.containsKey(con.AccountId)){
                accountMarketMap.put(con.AccountId, con.Account.Market__c);
            }

            if (con.Parents__r.isEmpty()) {           
                Contact childContact = createChild(con, childRecordTypeId);
                toInsert.add(childContact);
            } else {
                //Nemo can create the child even if the child has not been born
                //check if there is already existing child with the birthdate is the same as the estimateduedate
                Boolean existingChild = false;
                for (Contact child : con.Parents__r) {
                    if (child.Birthdate == con.EstimatedDueDate__c) {
                        existingChild = true;
                    }
                }
                //only create a child if no existing child found
                if (existingChild == false) {
                    Contact childContact = createChild(con, childRecordTypeId);
                    toInsert.add(childContact);
                }
            }
            //estimated due date will still be updated even if no child was created
            //dont clear EDD for VN Contacts with 40 weeks milestone
            if(con.Market__c != 'VN'){
                con.EstimatedDueDate__c = null;
            }
        }

        if (!toInsert.isEmpty()) {
            Insert toInsert;

            //TKT-012178 -Logic for SG Contact EDD - insert new Child BR
            for(Contact createdChild : toInsert){
                if(accountMarketMap.get(createdChild.AccountId) == 'SG'){
                    BrandRelationship__c childBR = createBR(createdChild);
                    brToInsert.add(childBR);
                }
            }
            if(!brToInsert.isEmpty()){
                insert brToInsert;
            }
        }        

        if (!lScope.isEmpty()) {
            // Update lScope;
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.allowSave = true;
            dml.DuplicateRuleHeader.runAsCurrentUser = true; 
            
            List<Database.SaveResult> sr = Database.update(lScope, dml);
        }
    }

    public Contact createChild(Contact con, String childRecordTypeId) {
        Contact childContact = new Contact();
        childContact.AccountId = con.AccountId;
        childContact.Birthdate = con.EstimatedDueDate__c;
        childContact.LastName = CommonConstant.CONTACT_CHILD_LASTNAME;
        childContact.Type__c = CommonConstant.CONTACT_CHILD_TYPE;
        childContact.RecordTypeId = childRecordTypeId;
        childContact.Parent__c = con.Id;
        childContact.MilkCodeRestriction__c = true;
        childContact.EstimatedBirthdate__c = con.EstimatedDueDate__c;
        childContact.OwnerId = con.OwnerId;

        return childContact;
    }

    //TKT-012178 - Child EDD BR mapping
    public BrandRelationship__c createBR(Contact child) {
        BrandRelationship__c br = new BrandRelationship__c();
        br.BrandRelationship__c = simMomChildProduct.Id;
        br.PrimaryContact__c = child.Parent__c;
        br.Household__c = child.AccountId;
        br.User__c = child.Id;
        br.Type__c = 'Lead';
        br.Status__c = 'Uncontacted';
        br.Active__c = true;
        
        return br;
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}