force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/ParentHousehold__c.field-meta.xml
<CustomField>
    <fullName>ParentHousehold__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Online Payment - FPX</fullName>
            </value>
            <value>
                <fullName>E-Wallet</fullName>
            </value>
            <value>
                <fullName>Third Party Payment Vendor</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>No Charge Order</fullName>
            </value>
            <value>
                <fullName>EFT</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>MoneyOrder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/RelatedCampaign__c.field-meta.xml
<CustomField>
    <fullName>RelatedCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[25-Jul-21 Khai] To extract out the product market for troubleshooting purposes</description>
    <formula>TEXT( Product2.Market__c )</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateOrderFromContactControllerTest.cls
@isTest
public class CreateOrderFromContactControllerTest {
    
    @isTest
    static void pageLoad () {
        Test.startTest();
        CreateOrderFromContactController.CreateOrderElements elem = CreateOrderFromContactController.pageOnInit('', NULL, '', NULL, '', '','');
        Test.stopTest();
        
        System.Assert(elem != NULL, 'Page elements not loaded properly');
    }
    
    @isTest
    static void fetchContacts () {
        Account acc 	= TestDataFactory.createTestHousehold(1)[0];
        acc.Market__c = 'SG';
        update acc;
        
        Contact con		= TestDataFactory.createSGTestAdultContact(1, acc.Id)[0];
        Product2 prod 	= TestDataFactory.createTestBrandProduct(1)[0];
        
        Address__c add = TestDataFactory.createTestDefaultAddress(1, con.Id, NULL, null)[0];
        add.ParentHousehold__c = acc.Id;
        update add;
        
        TestDataFactory.createTestBrandRelationShip(1, con.Id, prod.Id);
        
        Test.startTest();
        List<CreateOrderFromContactController.ContactForOrder> conList = CreateOrderFromContactController.getContacts('', NULL, '', NULL, '', '','');
        Test.stopTest();
                
        System.Assert(conList.size() > 0, 'No list returned');
    }

    @isTest
    static void createOrder () {
        
        Account acc 	= TestDataFactory.createTestHousehold(1)[0];
        acc.Market__c	= 'SG';
        update acc;
        
        Contact con				= TestDataFactory.createSGTestAdultContact(1, acc.Id)[0];
    
        PricebookEntry pbEntry 	= TestDataFactory.createPricebookEntry('SG');
        insert pbEntry;
        
        String orderStr = '{"Type":"Telesales - Outbound","Status":"Draft","EffectiveDate":"2021-04-27","CurrencyIsoCode":"MYR","Pricebook2Id":"' + pbEntry.Pricebook2Id + '","RelatedCampaign__c":null,"PaymentMethod__c":"None"}';
        
        Map<Object, Object> objCon = new Map<Object, Object>();
        objCon.put('campaignNames', 'Test, Test, Test Campaign!');
        objCon.put('householdId', acc.Id);
        objCon.put('id', con.Id);
        objCon.put('market', 'PH');
        objCon.put('name', 'Eligibility PH');
        List<Object> objList = new List<Object>{(Object)objCon};
        
        Test.startTest();
        CreateOrderFromContactController.createOrder(orderStr, objList);
        Test.stopTest();
    }
    
    @isTest
    static void createOrderProd () {
        
        Account acc 	= TestDataFactory.createTestHousehold(1)[0];
        acc.Market__c = 'SG';
        update acc;
        
        Contact con				= TestDataFactory.createSGTestAdultContact(1, acc.Id)[0];
        PricebookEntry pbEntry 	= TestDataFactory.createPricebookEntry('SG');
        insert pbEntry;
        
        Order ord = TestDataFactory.createOrder(1, acc.Id, con.Id, pbEntry.Pricebook2Id)[0];
        insert ord;
        
        String orderStr = '{"Product2Id":"' + pbEntry.Product2Id + '","Category__c":null, "Quantity":1}';
        
        Map<Object, Object> objCon = new Map<Object, Object>();
        objCon.put('householdId', acc.Id);
        objCon.put('id', con.Id);
        objCon.put('market', con.Market__c);
        objCon.put('name', con.Name);
        objCon.put('orderId', ord.Id);
        objCon.put('pricebookId', pbEntry.Pricebook2Id);
        List<Object> objList = new List<Object>{(Object)objCon};
        
        Test.startTest();
        CreateOrderFromContactController.createOrderProd(orderStr, objList);
        Test.stopTest();
    }
    
}