force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Affiliate Values (Product)</relationshipLabel>
    <relationshipName>Affiliate_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/City.recordType-meta.xml
<RecordType>
    <fullName>City</fullName>
    <active>true</active>
    <description>Defines cities within a given market, to be selected during address creation and updates for a contact</description>
    <label>City</label>
</RecordType>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/District.recordType-meta.xml
<RecordType>
    <fullName>District</fullName>
    <active>true</active>
    <description>Defines the districts within a given market (usually defined by city), used during address creation and updates for a contact</description>
    <label>District</label>
</RecordType>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND ((3 OR 4) OR (5 AND 6))</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.ProductHierarchyLevel__c</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Cases (Channel)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[1-Sep-21 Khai] This field is for troubleshooting by extracting out the market of the Contact</description>
    <formula>Contact__r.Market__c</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Fill in the Main Contact for this person (e.g. child or elderly person) under the main contact&apos;s care. This field is not required if this person is a Primary Contact.</inlineHelpText>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/PricebookEntry/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[25-Jul-21 Khai] To extract out the product market for troubleshooting purposes</description>
    <formula>TEXT( Product2.Market__c )</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ParentBrand__c.field-meta.xml
<CustomField>
    <fullName>ParentBrand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Brand</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND ((3 OR 4) OR (5 AND 6))</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.ProductHierarchyLevel__c</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Parent Brand)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SGSimilacMomBatchTest.cls
@isTest
public class SGSimilacMomBatchTest {
    @testSetup
    static void setup(){
        Account a = TestDataFactory.createTestHousehold(1, 'SG')[0];
        Contact adult = TestDataFactory.createContact(true, a.Id, null, Date.parse('01/01/1990'), '09123456');
        Contact child = TestDataFactory.createContact(false, a.Id, adult.Id, Date.today().addMonths(-8), '09110011');
        Contact child1 = TestDataFactory.createContact(false, a.Id, adult.Id, Date.today().addMonths(-8), '09000000');
        Affiliate_Value__c cityDefault = TestDataFactory.createAffiliateValue('City', 'TEST_CITY_DEFAULT', 'SG', null);
        Affiliate_Value__c districtDefault = TestDataFactory.createAffiliateValue('District', 'TEST_DISTRICT_DEFAULT', 'SG', cityDefault.Id);
        String streetNameDefault = 'TEST_STREET_DEFAULT';
        Address__c addressDefault = TestDataFactory.createAddress(true, adult.Id, 'Singapore', cityDefault.Id, districtDefault.Id, null, streetNameDefault);
        PricebookEntry pbe = TestDataFactory.createPricebookEntry('SG', 'SGD');
        Product2 prod1 = TestDataFactory.createProductDiffBrand('SG', 'SGD', pbe.Pricebook2Id, 'Similac', 'SIMILAC MOM');
        Product2 prod2 = TestDataFactory.createProductDiffBrand('SG', 'SGD', pbe.Pricebook2Id, 'Similac', 'SIMILAC MOM');
        Channel__c channel = TestDataFactory.createTestChannel(1, 'SG', 'TEST_CHANNEL')[0];
        Campaign campSim = TestDataFactory.createCampaignInsert('SG-SimilacMum-Con&Ren-Call', 'Similac', 'SG', prod1.ParentBrand__c);
    }
    static testmethod void test_schedule(){
        Test.startTest();
        System.schedule('SGSimilacMomBatch', '0 0 3 1,20 * ?', new SGSimilacMomBatch());
        Test.stopTest();
    }
    static testmethod void testSuccess(){
        Account a = [SELECT Id FROM Account WHERE Market__c = 'SG'][0];
        Contact child = [SELECT Id, Parent__c FROM Contact WHERE AccountId =: a.Id AND RecordType.Name = 'Child' AND Phone = '09000000'][0];
        Contact child1 = [SELECT Id, Parent__c FROM Contact WHERE AccountId =: a.Id AND RecordType.Name = 'Child' AND Phone = '09110011'][0];
        Campaign campaign = [SELECT Id, Product__c, Product__r.Name FROM Campaign WHERE Name = 'SG-SimilacMum-Con&Ren-Call'][0];
        Channel__c channel = [SELECT Id FROM Channel__c WHERE Name = 'TEST_CHANNEL'][0];
        List<Product2> prodList = [SELECT Id, Name, ParentBrand__c FROM Product2 WHERE Name = 'SIMILAC MOM' AND Keybrand__c = 'Similac' AND ParentBrand__c != null LIMIT 2];
        Address__c addr = [SELECT Id FROM Address__c WHERE Country__c = 'Singapore'][0];
        Test.startTest();
        BrandRelationship__c br1 = TestDataFactory.createTestBrandRelationShipwithUser(1, child.Parent__c, child.Id, prodList[0].Id)[0];
        ChannelResponse__c cr1 = TestDataFactory.createTestChannelResponseMultiple(1, br1, channel, addr, prodList[0], true, 'Pending')[0];
        BrandRelationship__c br2 = TestDataFactory.createTestBrandRelationShipwithUser(1, child.Parent__c, child.Id, prodList[1].Id)[0];
        ChannelResponse__c cr2 = TestDataFactory.createTestChannelResponseMultiple(1, br2, channel, addr, prodList[1], true, 'Pending')[0];
        BrandRelationship__c br3 = TestDataFactory.createTestBrandRelationShipwithUser(1, child1.Parent__c, child1.Id, prodList[0].Id)[0];
        ChannelResponse__c cr3 = TestDataFactory.createTestChannelResponseMultiple(1, br3, channel, addr, prodList[0], true, 'Pending')[0];
        Case c = TestDataFactory.createCall('New', a.Id, child.Parent__c, child.Id, 'SG Similac Mom Maternal Con and Ret Call', campaign.Id, 'Outbound', channel.Id, 'SG');
        SGSimilacMomBatch batch = new SGSimilacMomBatch(); 
        Database.executebatch(batch, 20);
        Test.stopTest();
        List<Case> caseCheck = [SELECT Id FROM Case WHERE ContactId =: child1.Parent__c AND CallRegarding__c =: child1.Id AND Subject = 'SG Similac Mom Maternal Con and Ret Call'];
        System.assertEquals(caseCheck.size(), 1);
    }
    
    static testmethod void testError(){
        Account a = [SELECT Id FROM Account WHERE Market__c = 'SG'][0];
        Contact child = [SELECT Id, Parent__c FROM Contact WHERE AccountId =: a.Id AND RecordType.Name = 'Child' AND Phone = '09000000'][0];
        Contact child1 = [SELECT Id, Parent__c FROM Contact WHERE AccountId =: a.Id AND RecordType.Name = 'Child' AND Phone = '09110011'][0];
        Campaign campaign = [SELECT Id, Product__c, Product__r.Name FROM Campaign WHERE Name = 'SG-SimilacMum-Con&Ren-Call'][0];
        Channel__c channel = [SELECT Id FROM Channel__c WHERE Name = 'TEST_CHANNEL'][0];
        List<Product2> prodList = [SELECT Id, Name, ParentBrand__c FROM Product2 WHERE Name = 'SIMILAC MOM' AND Keybrand__c = 'Similac' AND ParentBrand__c != null LIMIT 2];
        Address__c addr = [SELECT Id FROM Address__c WHERE Country__c = 'Singapore'][0];
        Test.startTest();
        BrandRelationship__c br1 = TestDataFactory.createTestBrandRelationShipwithUser(1, child.Parent__c, child.Id, prodList[0].Id)[0];
        ChannelResponse__c cr1 = TestDataFactory.createTestChannelResponseMultiple(1, br1, channel, addr, prodList[0], true, 'Pending')[0];
        BrandRelationship__c br2 = TestDataFactory.createTestBrandRelationShipwithUser(1, child.Parent__c, child.Id, prodList[1].Id)[0];
        ChannelResponse__c cr2 = TestDataFactory.createTestChannelResponseMultiple(1, br2, channel, addr, prodList[1], true, 'Pending')[0];
        BrandRelationship__c br3 = TestDataFactory.createTestBrandRelationShipwithUser(1, child1.Parent__c, child1.Id, prodList[0].Id)[0];
        ChannelResponse__c cr3 = TestDataFactory.createTestChannelResponseMultiple(1, br3, channel, addr, prodList[0], true, 'Pending')[0];
        Case c = TestDataFactory.createCall('New', a.Id, child.Parent__c, child.Id, 'SG Similac Mom Maternal Con and Ret Call', campaign.Id, 'Outbound', channel.Id, 'SG');
        Test.stopTest();
        child.DoNotCall = true;
        child1.DoNotCall = true;
        Contact parent = new Contact(Id = child.Parent__c, DoNotCall = true);
        List<Contact> conUpdate = new List<Contact>{child, child1, parent};
        update conUpdate;
        SGSimilacMomBatch batch = new SGSimilacMomBatch(); 
        Database.executebatch(batch, 20);
        List<Case> caseCheck = [SELECT Id FROM Case WHERE ContactId =: child1.Parent__c AND CallRegarding__c =: child1.Id AND Subject = 'SG Similac Mom Maternal Con and Ret Call'];
        System.assert(caseCheck.isEmpty());
    }
}