force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of Awareness will capture as campaign as well</description>
    <label>Call Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Order/fields/OrderedBy__c.field-meta.xml
<CustomField>
    <fullName>OrderedBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordered By</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Adult</value>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderCleanup.cls
// for deletion
public class OrderCleanup {} /* implements Database.Batchable<sObject>, Database.Stateful {
    
    User datamigration;
    Id callRecordType;

    public OrderCleanup(){
        String dataStr = Test.isRunningTest() ?  'datamigration@tigerani.abbott.comtest' : 'datamigration@tigerani.abbott.com';
        datamigration = [SELECT Id FROM User WHERE Username =: dataStr];
        callRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Call').getRecordTypeId();
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        String market = 'PH';
        String queryStr = 'SELECT Status, OrderedBy__c'
                        + ' FROM Order'
                        + ' WHERE Account.Market__c =: market';
        if(!Test.isRunningTest()){
            queryStr += ' AND CreatedById =\'' + datamigration.Id + '\'' ;
        }
        return Database.getQueryLocator(queryStr);
    }
    
    public void execute(Database.BatchableContext BC, List<Order> orderList){

        Set<Id> contactIds = new Set<Id>();
        for(Order o: orderList){
            o.Type = 'Trade';
            if(o.Status == 'Draft') {
                o.Status = 'Completed';
                contactIds.add(o.OrderedBy__c);
            }
            system.debug('Order: ' + o.Id);
        }

        Database.update(orderList, true);
        String newuser = '%New User Call 1%';
        String reactivationUser = '%Reactivation Call 1%';

        List<Case> caseList = new List<Case>([SELECT Id
                                                FROM Case
                                               WHERE RecordTypeId =: callRecordType
                                                 AND Status = 'New'
                                                 AND ContactId IN: contactIds
                                                 AND (Campaign__r.Name LIKE: newuser
                                                  OR Campaign__r.Name LIKE: reactivationUser)]);
        
        for(case c: caseList){
            system.debug('case: ' + c);

        }
        if(!caseList.isEmpty()){
            Database.delete(caseList, false);
        }
    }
    public void finish(Database.BatchableContext BC){}
} */