force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CallRegarding__c.field-meta.xml
<CustomField>
    <fullName>CallRegarding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filter to show only Contacts within the Case Contact&apos;s Household</description>
    <label>Call Regarding</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Call Regarding)</relationshipLabel>
    <relationshipName>CallRegarding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of Awareness will capture as campaign as well</description>
    <label>Call Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/RelatedBrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>RelatedBrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Contact/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/ServiceResource/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateConversionSkillDailyBatchTest.cls
@isTest
public class UpdateConversionSkillDailyBatchTest {
    
    @testSetup
    static void setup(){
        
        // create PH Admin and PH Call Center Agent
        User agentUser = TestDataFactory.createUser('ANI Call Center Agent', 'PHAgent1', 'PH');
        insert agentUser;
        User sysAdmin = TestDataFactory.createUser('System Administrator', 'PHAdmin' , 'PH');
        insert sysAdmin;
        
        // create PH Account, Contact, Call Campaign, Product, and Brand Relationship
        Account testAcc = TestDataFactory.createTestHousehold(1, 'PH')[0];
        Contact testCon = TestDataFactory.createTestAdultContact(1, testAcc.Id)[0];
        Campaign testCampaign = TestDataFactory.createCampaign('Test Campaign 1', 'Glucerna', 'PH');
        insert testCampaign;
        Product2 testProd = TestDataFactory.createTestBrandProduct(1)[0];
        BrandRelationship__c testBR = TestDataFactory.createTestBrandRelationShip(1, testCon.Id, testProd.Id)[0];
        testBr.FirstTransactionDate__c = Date.today();
        update testBR;
        
        // create PH Call Case
        Id callRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Call').getRecordTypeId();
        Case caseRec = new Case();
        caseRec.RecordtypeId = callRecordTypeId;
        caseRec.ContactId = testCon.Id;
        caseRec.CallType__c = 'Outbound';
        caseRec.Status = 'New';
        caseRec.AccountId = testAcc.Id;
        caseRec.CallRegarding__c = testCon.Id;
        caseRec.Campaign__c = testCampaign.Id;
        caseRec.RelatedBrandRelationship__c = testBR.Id;
        caseRec.Market__c = 'PH';
        insert caseRec;
        
        Map<String, Id> skillMap = new Map<String, Id>();
        
        // create Service Resource and Service Resource Skill
        System.runAs(sysAdmin){
            List<ServiceResourceSkill> srsList = new List<ServiceResourceSkill>();
            
            ServiceResource srRec = new ServiceResource();
            srRec.Name = agentUser.FirstName + agentUser.LastName;
            srRec.RelatedRecordId = agentUser.Id;
            srRec.ResourceType = 'A';
            srRec.IsActive = true;
            insert srRec;
            
            for(Skill skillRec : [SELECT Id, MasterLabel, DeveloperName FROM Skill]){
                skillMap.put(skillRec.DeveloperName, skillRec.Id);
                ServiceResourceSkill srs = new ServiceResourceSkill();
                srs.ServiceResourceId = srRec.Id;
                srs.SkillId = skillRec.Id;
                System.debug('Skill Id: ' + srs.SkillId);
                srs.EffectiveStartDate = System.today() - 5;
                
                srsList.add(srs);
            }
            insert srsList;
        }
        
        // query Service Channel
        ServiceChannel sc = [SELECT Id, RelatedEntity FROM ServiceChannel WHERE RelatedEntity = 'Case'];
            
        // create Pending Service Routing
        PendingServiceRouting psrRec = new PendingServiceRouting();
        psrRec.CapacityWeight = 1;
        psrRec.IsReadyForRouting = False;
        psrRec.RoutingModel  = 'MostAvailable';
        psrRec.RoutingPriority = 1;
        psrRec.RoutingType = 'SkillsBased';
        psrRec.ServiceChannelId = sc.Id;
        psrRec.WorkItemId = caseRec.Id;
        psrRec.PushTimeout = 36000;
        insert psrRec;
        
        // create Skill Requirements
        List<SkillRequirement> srList = new List<SkillRequirement>();
        SkillRequirement srBrandGlucerna = new SkillRequirement();
        srBrandGlucerna.RelatedRecordId = psrRec.Id;
        srBrandGlucerna.SkillId = skillMap.get('Brand_Glucerna');
        srList.add(srBrandGlucerna);
 
        SkillRequirement srConversionConversion = new SkillRequirement();
        srConversionConversion.RelatedRecordId = psrRec.Id;
        srConversionConversion.SkillId = skillMap.get('Conversion_Conversion');
        srList.add(srConversionConversion);
        
        SkillRequirement srMarketPH = new SkillRequirement();
        srMarketPH.RelatedRecordId = psrRec.Id;
        srMarketPH.SkillId = skillMap.get('Market_PH');
        srList.add(srMarketPH);

        insert srList;	
    }
    
    static testmethod void executeTest(){
        Test.startTest();
        UpdateConversionSkillDailyBatch updateConversionSkillBatch= new UpdateConversionSkillDailyBatch();
        String cronExpr = '0 0 5 ? * * *';
        String jobId = System.schedule('PH - Update Conversion Skill Batch', cronExpr, updateConversionSkillBatch);
        updateConversionSkillBatch.execute(null);
        Test.stopTest();
    }
}