force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AgeinMonths__c.field-meta.xml
<CustomField>
    <fullName>AgeinMonths__c</fullName>
    <formula>IF(NOT(ISBLANK(Birthdate)),
        IF(DAY(Birthdate) &lt;= DAY(TODAY()),
        (YEAR( TODAY())*12+MONTH(TODAY())) - (YEAR(Birthdate)*12+MONTH(Birthdate)),
        (YEAR( TODAY())*12+MONTH(TODAY())) - (YEAR(Birthdate)*12+MONTH(Birthdate))-1
        ),
        0
        )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age (in Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EstimatedDueDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDueDate__c</fullName>
    <label>Estimated Due Date (EDD)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WeeksOfPregnancy__c.field-meta.xml
<CustomField>
    <fullName>WeeksOfPregnancy__c</fullName>
    <formula>IF (FLOOR( (TODAY() - (EstimatedDueDate__c  - 280) )/7 ) &gt;= 0 ,
FLOOR( (TODAY() - (EstimatedDueDate__c  - 280) )/7 ),
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weeks of Pregnancy</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Used to track age milestones to trigger different marketing cloud journeys</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ANZ</fullName>
    </customValue>
    <customValue>
        <fullName>HK</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
    </customValue>
    <customValue>
        <fullName>TH</fullName>
    </customValue>
    <customValue>
        <fullName>TW</fullName>
    </customValue>
    <customValue>
        <fullName>VN</fullName>
    </customValue>
    <customValue>
        <fullName>NZ</fullName>
        <isActive>false</isActive>
        <label>NZ</label>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
        <isActive>false</isActive>
        <label>AU</label>
    </customValue>
    <masterLabel>Market</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/MC_Milestones_Test.cls
@isTest
public class MC_Milestones_Test {

    @testSetup
    static void setup(){
        
        // create household
        Account acctPH = TestDataFactory.createTestHousehold(1, 'PH')[0];
        Account acctTW = TestDataFactory.createTestHousehold(1, 'TW')[0];

        // create mother and child contacts
        List<Contact> contactList = new List<Contact>();
        Contact adultContactPH = TestDataFactory.createTestAdultContact(1, acctPH.Id)[0];
        List<Contact> childContactPH = TestDataFactory.createTestChildContact(2, acctPH.Id);
        
        Contact adultContactTW = TestDataFactory.createTestAdultContact(1, acctTW.Id)[0];
        List<Contact> childContactTW = TestDataFactory.createTestChildContact(2, acctTW.Id);        

        adultContactPH.EstimatedDueDate__c = Date.Today().addMonths(9).addDays(-5);
        childContactPH[0].BirthDate = Date.Today().addMonths(-1);
        childContactPH[1].BirthDate = Date.Today().addMonths(1);

        adultContactTW.EstimatedDueDate__c = Date.Today().addMonths(9).addDays(-5);
        childContactTW[0].BirthDate = Date.Today().addMonths(-1);
        childContacttw[1].BirthDate = Date.Today().addMonths(1);
        
        contactList.add(adultContactPH);
        contactList.add(childContactPH[0]);
        contactList.add(childContactPH[1]);
        
        contactList.add(adultContactTW);
        contactList.add(childContactTW[0]);
        contactList.add(childContactTW[1]);

        UtilityClass.updateList(contactList);

        // create product
        Product2 prod = TestDataFactory.createTestBrandProduct(1)[0];

        // create BR for mother
        BrandRelationship__c brandRelationshipPH = TestDataFactory.createTestBrandRelationShip(1, adultContactPH.Id, prod.Id)[0];  
        BrandRelationship__c brandRelationshipTW = TestDataFactory.createTestBrandRelationShip(1, adultContactTW.Id, prod.Id)[0];  
        
        Datetime yesterday = Datetime.now().addDays(-1);
        Test.setCreatedDate(brandRelationshipPH.Id, yesterday);
        Test.setCreatedDate(brandRelationshipTW.Id, yesterday);
        // create BR for child
        TestDataFactory.createTestBrandRelationShipwithUser2(2, adultContactPH.Id, childContactPH, prod.Id);
        TestDataFactory.createTestBrandRelationShipwithUser2(2, adultContactTW.Id, childContactTW, prod.Id);
     
        List<BrandRelationship__c> brList = new List<BrandRelationship__c>();
        brandRelationshipPH.Household__c = acctPH.Id;
        brandRelationshipTW.Household__c = acctTW.Id;
        update brList;
        
        System.debug([SELECT Id,Active__c,Account.Market__c,RecordType.Name,PrimaryContact__c, AgeinMonths__c,WeeksOfPregnancy__c FROM Contact WHERE Id =: adultContactPH.Id]);
        System.debug([SELECT Id,Active__c,Account.Market__c,RecordType.Name,PrimaryContact__c, AgeinMonths__c,WeeksOfPregnancy__c FROM Contact WHERE Id =: adultContactTW.Id]);
        System.debug([SELECT Id,Active__c,Account.Market__c,RecordType.Name,PrimaryContact__c, AgeinMonths__c,WeeksOfPregnancy__c FROM Contact WHERE Id =: childContactPH]);
        System.debug([SELECT Id,Active__c,Account.Market__c,RecordType.Name,PrimaryContact__c, AgeinMonths__c,WeeksOfPregnancy__c FROM Contact WHERE Id =: childContactTW]);
    }
    
    static testMethod void milestoneTest1(){
        TestDataFactory.createMilestone('TW', 'Weeks of Pregnancy', '1');
        TestDataFactory.createMilestone('TW', 'Age In Months', '1');
        Test.startTest();
        System.enqueueJob(new MC_Milestones_Queueable(true, null));
        Test.stopTest();
    }
    
    static testMethod void milestoneTest2(){
        TestDataFactory.createMilestone('TW', 'Age In Months', '1');
        TestDataFactory.createMilestone('TW', 'Age In Months', '-1');
        Test.startTest();
        System.enqueueJob(new MC_Milestones_Queueable(true, null));
        Test.stopTest();
    }
    
    static testMethod void milestoneTest3(){
        TestDataFactory.createMilestone('PH', 'Weeks of Pregnancy', '1');
        TestDataFactory.createMilestone('PH', 'Age In Months', '1');
        Test.startTest();
        System.enqueueJob(new MC_Milestones_Queueable(true, null));
        Test.stopTest();
    }
    
    static testMethod void milestoneTest4(){
        TestDataFactory.createMilestone('PH', 'Age In Months', '1');
        TestDataFactory.createMilestone('PH', 'Age In Months', '-1');
        Test.startTest();
        System.enqueueJob(new MC_Milestones_Queueable(true, null));
        Test.stopTest();
    }
    
    static testMethod void milestoneTest5(){
        TestDataFactory.createMilestone('PH', 'Weeks of Pregnancy', '1');
        TestDataFactory.createMilestone('TW', 'Age In Months', '1');
        Test.startTest();
        System.enqueueJob(new MC_Milestones_Queueable(true, null));
        Test.stopTest();
    }
    
    static testMethod void milestoneTest6(){
        TestDataFactory.createMilestone('PH', 'Age In Months', '-1');
        TestDataFactory.createMilestone('TW', 'Weeks of Pregnancy', '1');
        Test.startTest();
        System.enqueueJob(new MC_Milestones_Queueable(true, null));
        Test.stopTest();
    }
    
    static testMethod void milestoneTest7(){
        TestDataFactory.createMilestone('PH', 'Age In Months', '-1');
        TestDataFactory.createMilestone('TW', 'Weeks of Pregnancy', '1');
        TestDataFactory.createMilestone('TW', 'Age In Months', '1');
        Test.startTest();
        System.enqueueJob(new MC_Milestones_Queueable(true, null));
        Test.stopTest();
    }

    static testMethod void runPHMilestonesSchedulable(){
        Test.startTest();
            String cronStr = '0 0 0 3 9 ? 2050';
            String jobId2 = System.schedule('MCTRiggerTest', cronStr, new MC_Milestones_Sched());
        Test.stopTest();
    }

    static testMethod void runBatch() {
        TestDataFactory.createMilestone('PH', 'Age In Months', '1');
        TestDataFactory.createMilestone('PH', 'Age In Months', '-1');
        Map<Id, Milestone__c> milestoneMap = new Map<Id, Milestone__c>([SELECT Id FROM Milestone__c]);
        Set<Id> mIds = milestoneMap.keySet();
        
        Test.startTest();
            Database.executebatch(new MC_Milestones(mIds));
        Test.stopTest();
    }
}