force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Purchase_Amount_Adult_Brand__c.field-meta.xml
<CustomField>
    <fullName>Total_Purchase_Amount_Adult_Brand__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Total Purchase Amount Adult Brand</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BirthdayPromoBatchTest.cls
@isTest 
public class BirthdayPromoBatchTest {
    static testMethod void testMethod1() 
    {
         List<Account> account = TestDataFactory.createTestHousehold(1);
         account.get(0).Market__c = 'TW';
         update account;
        
         Datetime lastYear = Datetime.now().addDays(-365);
        

         List<Contact> contact = TestDataFactory.createTestAdultContact(1, account.get(0).Id);
         contact[0].Total_Purchase_Amount_Adult_Brand__c = 400000;
         contact[0].Birthdate = system.today();
         Test.setCreatedDate(contact[0].Id, lastYear); 
         update contact;
            
        
        Test.startTest();

            BirthdayPromoBatch obj = new BirthdayPromoBatch();
            DataBase.executeBatch(obj); 
            
        Test.stopTest();
    }
    public static testMethod void testschedule() {

        Test.StartTest();
        BirthdayPromoBatchScheduler sh1 = new BirthdayPromoBatchScheduler();
        
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test Territory Check', sch, sh1); 
        Test.stopTest(); 
    }
}