force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/AbbottAwarenessDate__c.field-meta.xml
<CustomField>
    <fullName>AbbottAwarenessDate__c</fullName>
    <label>Abbott Awareness Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/CallRegarding__c.field-meta.xml
<CustomField>
    <fullName>CallRegarding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filter to show only Contacts within the Case Contact&apos;s Household</description>
    <label>Call Regarding</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Call Regarding)</relationshipLabel>
    <relationshipName>CallRegarding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of Awareness will capture as campaign as well</description>
    <label>Call Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/LastReminderSentDate__c.field-meta.xml
<CustomField>
    <fullName>LastReminderSentDate__c</fullName>
    <description>Technical Field. Do not display in layout</description>
    <inlineHelpText>Technical Field. Do not display in layout</inlineHelpText>
    <label>Last Reminder Sent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/LastReminderSentDateCount__c.field-meta.xml
<CustomField>
    <fullName>LastReminderSentDateCount__c</fullName>
    <formula>TODAY() - LastReminderSentDate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Reminder Sent Date Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/ReminderStatus__c.field-meta.xml
<CustomField>
    <fullName>ReminderStatus__c</fullName>
    <label>Reminder Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Response</fullName>
            </value>
            <value>
                <fullName>First Reminder</fullName>
            </value>
            <value>
                <fullName>Second Reminder</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Pending - Uncontactable</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed - Reassigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Feedback.recordType-meta.xml
<RecordType>
    <fullName>Feedback</fullName>
    <active>true</active>
    <businessProcess>Feedback</businessProcess>
    <description>Cases for customers who have raised feedback or a grievance requiring action by one or more Abbott teams</description>
    <label>Feedback</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailToCaseReminder_Test.cls
@isTest
public class EmailToCaseReminder_Test {
    @testsetup
    static void setup() {
    	User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'IN');
        insert sysad;
    	User datamigration = TestDataFactory.createUser('System Administrator', 'datami' , 'IN');
		datamigration.username = 'datamigration@tigerani.abbott.comtest';
        insert datamigration;
        
        System.runAs(sysad) {
			
	        Campaign camp = TestDataFactory.createCampaign('Test Campaign 1', 'Ensure', 'IN');
			insert camp;

			List<Account> lAccount = TestDataFactory.createTestHousehold(1);
            lAccount[0].Market__c = 'IN';
            update lAccount;

			List<Contact> lContact = TestDataFactory.createTestAdultContact(1, lAccount.get(0).Id);
	        
		    Id RTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Feedback').getRecordTypeId();

			Case c = new Case();
            c.RecordtypeId = RTId;
            c.ContactId = lContact[0].Id;
            c.CallType__c = 'Outbound';
            c.Status = 'New';
            c.AccountId = lAccount[0].Id;
            c.CallRegarding__c = lContact[0].Id;
			c.Campaign__c = camp.Id;
            c.ReminderStatus__c = 'Initial Response';
            c.AbbottAwarenessDate__c = Date.Today().addDays(-2);
            c.SuppliedEmail = 'test@email.com';
            insert c;
			c.LastReminderSentDate__c = Date.Today().addDays(-2);
            update c;
		}
    }

    static testmethod void testOther() {
        Test.startTest();
            EmailToCaseReminder_Batch b = new EmailToCaseReminder_Batch('PH');
            System.assert(!b.conditionMatch('Text', 'Not Equal', '1', '1'));
            System.assert(b.conditionMatch('Text', 'Not Equal', '1', '2'));
            System.assert(!b.conditionMatch('Number', 'Equal', '1', '2'));
            System.assert(b.conditionMatch('Number', 'Not Equal', '1', '2'));
            System.assert(!b.conditionMatch('Number', 'Greater Than', '1', '2'));
            System.assert(!b.conditionMatch('Number', 'Greater Than or Equal', '1', '2'));
            System.assert(b.conditionMatch('Number', 'Less Than', '1', '2'));
            System.assert(b.conditionMatch('Number', 'Less Than or Equal', '1', '2'));

            System.assertEquals(' = ', b.queryConditonTranslator('Equal'));
            System.assertEquals(' != ', b.queryConditonTranslator('Not Equal'));
            System.assertEquals(' > ', b.queryConditonTranslator('Greater Than'));
            System.assertEquals(' >= ', b.queryConditonTranslator('Greater Than or Equal'));
            System.assertEquals(' < ', b.queryConditonTranslator('Less Than'));
            System.assertEquals(' <= ', b.queryConditonTranslator('Less Than or Equal'));
        Test.stopTest();
    }

    static testmethod void sendEmail() {
        List<Case> caseList = new List<Case>([SELECT RecordType.Name, ReminderStatus__c, LastReminderSentDateCount__c FROM Case]);

        Test.startTest();
			EmailToCaseReminder_Batch b = new EmailToCaseReminder_Batch('IN');
            Database.executeBatch(b, 200);

            String sch = '0 0 23 * * ?'; 
            system.schedule('Spam sched', sch, new EmailToCaseReminder_Sched('IN') );
    	Test.stopTest();

        caseList = new List<Case>([SELECT ReminderStatus__c FROM Case]);
        System.assertEquals('First Reminder', caseList[0].ReminderStatus__c);
    }

    static testmethod void uncontactable() {
        Case c = [SELECT RecordType.Name, ReminderStatus__c, LastReminderSentDateCount__c FROM Case];

        Test.startTest();
            c.ReminderStatus__c = 'Pending - Uncontactable';
            update c;
    	Test.stopTest();
    }
}