force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Latest_Contacted_Date__c.field-meta.xml
<CustomField>
    <fullName>Latest_Contacted_Date__c</fullName>
    <label>Latest Contacted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LineOptOut__c.field-meta.xml
<CustomField>
    <fullName>LineOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Line Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MasterOptOut__c.field-meta.xml
<CustomField>
    <fullName>MasterOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Master Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MC_Contact_SyncEligibilityTWBatchTest.cls
/***********************************************************************
* @author        Monika Parihar    
* @date          8/10/2021
* @description   Test class for Batch MC_Contact_SyncEligibilityTWBatch
* @revision(s)
**************************************************************************/
@isTest
public with sharing class MC_Contact_SyncEligibilityTWBatchTest {
    
    @TestSetup
    static void setupData(){
        User sysadTW = TestDataFactory.createUser('System Administrator', 'tstAdTW' , 'TW');
        insert sysadTW;

        
       System.runAs(sysadTW){
                //create Household
                List<Account> accList = TestDataFactory.createTestHousehold(1);
                accList[0].Market__c = 'TW';
                update accList;
                //create Primary adultContact
                List<Contact> conList = TestDataFactory.createTestAdultContact(1, accList.get(0).Id);
       }
        
    }
    static testmethod void MC_Contact_SyncEligibilityTWBatchTest(){
        Account household = [SELECT Id, Market__c FROM Account WHERE Market__c = :CommonConstant.MARKET_TW LIMIT 1];
        Contact primaryCon = [SELECT Id, Market__c, Active__c, Latest_Contacted_Date__c FROM Contact WHERE Type__c = :CommonConstant.CONTACT_ADULT_TYPE AND Market__c = :CommonConstant.MARKET_TW LIMIT 1];
        primaryCon.Active__c = true;
        primaryCon.LineOptOut__c = false;
        primaryCon.Active__c = true;
        primaryCon.Blacklisted__c = false;
        primaryCon.MasterOptOut__c = false;
        primaryCon.PrimaryContact__c =true;
        //primaryCon.Latest_Contacted_Date__c = Date.today().addMonths(-2); //set not eligible date
        update primaryCon;

        Test.startTest();
        Id batchJobId = Database.executeBatch(new MC_Contact_SyncEligibilityTWBatch(),200);
        Test.stopTest();
    }
}