force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IsSocialCase__c.field-meta.xml
<CustomField>
    <fullName>IsSocialCase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Social Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Feedback.recordType-meta.xml
<RecordType>
    <fullName>Feedback</fullName>
    <active>true</active>
    <businessProcess>Feedback</businessProcess>
    <description>Cases for customers who have raised feedback or a grievance requiring action by one or more Abbott teams</description>
    <label>Feedback</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Inquiry.recordType-meta.xml
<RecordType>
    <fullName>Inquiry</fullName>
    <active>true</active>
    <businessProcess>Inquiry</businessProcess>
    <description>Cases for customers who have raised an inquiry or question requiring a response by one or more Abbott teams</description>
    <label>Inquiry</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SocialPersonaTriggerHandlerTest.cls
@isTest
private class SocialPersonaTriggerHandlerTest {
	public static Id fbRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Feedback').getRecordTypeId();
    public static Id iqRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Inquiry').getRecordTypeId();
    
    @testsetup
    static void setupData() {
        User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'SG');
        insert sysad;
        
        
        System.runAs(sysad) { 
        List<Case> caseList = new List<Case>();
        Account a1 = new Account(Name = 'SG Social Contacts', Market__c = 'SG');
        insert a1;
        
		Contact c1 = new Contact(FirstName = 'Social', LastName = 'Person', AccountId = a1.Id, Phone = '47129472');
        insert c1;
        
        Case cas1 = new Case(RecordTypeId = fbRTId, AccountId = a1.Id, ContactId = c1.Id, Status = 'New', Origin = 'Facebook', IsSocialCase__c = true);
        insert cas1;
        
        SocialPersona persona = new SocialPersona();
        persona.ParentId = c1.Id;
        persona.Name = 'Author';
        persona.RealName = 'Social Persona';
        persona.Provider = 'Facebook';
        persona.MediaProvider = 'Facebook';
        persona.ExternalId = 'ExternalUserId';
        persona.AuthorLabels = 'SG';
        insert persona;
        
        SocialPost post = new SocialPost();
        post.ParentId = cas1.Id;
        post.PersonaId = persona.Id;
       	post.Name = 'source1';
        post.Content = 'content1';
        post.Posted = System.today();
        post.PostUrl = 'PostUrl1';
        post.Provider = 'Facebook';
        post.MessageType = 'Private';
        post.ExternalPostId = 'ExternalPostId1';
        post.R6PostId = 'R6PostId1';
        post.Classification = 'Product / Service Complaints';
        post.PostPriority = 'High';
        insert post;
        }
    }
    
    @isTest
    static void testForAcceptCase() {
        User sysad = [SELECT Id FROM User WHERE alias = 'tstSysAd'];
        
        System.runAs(sysad) { 
        Set<Id> caseIds = new Set<Id>();
        Account a1 = new Account(Name = 'Person', Market__c = 'SG');
        insert a1;
        
		Contact c1 = new Contact(FirstName = 'Social2', LastName = 'Person2', AccountId = a1.Id, Phone = '47129474');
        insert c1;
        
        SocialPersona persona = [select Id, ParentId from SocialPersona limit 1];
        persona.ParentId = c1.Id;
        Test.startTest();
        update persona;
        Test.stopTest();
        
        for(SocialPost sposRec : [select Id, ParentId from SocialPost where PersonaId = :persona.Id]) {
            caseIds.add(sposRec.ParentId);
        }
        
        List<Case> caseList = [select Id, ContactId, AccountId from Case where Id in :caseIds];
        
        System.assertEquals(a1.Id, caseList[0].AccountId);
        System.assertEquals(c1.Id, caseList[0].ContactId);
        }
    }
}