force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <formula>TEXT(BrandRelationship__r.KeyBrand__c)</formula>
    <label>Key Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Will Buy</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Non_User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCEnsureEndUser__c.field-meta.xml
<CustomField>
    <fullName>MCEnsureEndUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Ensure End User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCEnsureMainContact__c.field-meta.xml
<CustomField>
    <fullName>MCEnsureMainContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Ensure Main Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCGrowEndUser__c.field-meta.xml
<CustomField>
    <fullName>MCGrowEndUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Grow End User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCGrowMainContact__c.field-meta.xml
<CustomField>
    <fullName>MCGrowMainContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Grow Main Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCOthersEndUser__c.field-meta.xml
<CustomField>
    <fullName>MCOthersEndUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Others End User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCOthersMainContact__c.field-meta.xml
<CustomField>
    <fullName>MCOthersMainContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Others Main Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <label>Key Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abbott General</fullName>
            </value>
            <value>
                <fullName>Abound</fullName>
            </value>
            <value>
                <fullName>Alitraq</fullName>
            </value>
            <value>
                <fullName>Bonesure</fullName>
            </value>
            <value>
                <fullName>Bright Choice</fullName>
            </value>
            <value>
                <fullName>Caltrate</fullName>
            </value>
            <value>
                <fullName>Diabetamill</fullName>
            </value>
            <value>
                <fullName>Elecare</fullName>
            </value>
            <value>
                <fullName>Ensure</fullName>
            </value>
            <value>
                <fullName>Ensure Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Flexiflo</fullName>
            </value>
            <value>
                <fullName>Freego</fullName>
            </value>
            <value>
                <fullName>Glucerna</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Isomil</fullName>
            </value>
            <value>
                <fullName>Jevity</fullName>
            </value>
            <value>
                <fullName>Kidneysure</fullName>
            </value>
            <value>
                <fullName>Nepro</fullName>
            </value>
            <value>
                <fullName>Nutr Accessories</fullName>
            </value>
            <value>
                <fullName>Osmolite</fullName>
            </value>
            <value>
                <fullName>Other MND</fullName>
            </value>
            <value>
                <fullName>Pediasure</fullName>
            </value>
            <value>
                <fullName>Polycose</fullName>
            </value>
            <value>
                <fullName>Prosure</fullName>
            </value>
            <value>
                <fullName>Pulmocare</fullName>
            </value>
            <value>
                <fullName>RCF</fullName>
            </value>
            <value>
                <fullName>Similac</fullName>
            </value>
            <value>
                <fullName>Similac Core</fullName>
            </value>
            <value>
                <fullName>Similac Mom</fullName>
            </value>
            <value>
                <fullName>Similac Total Comfort</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BrandRelationshipBatchTest.cls
// @isTest for deletion
public class BrandRelationshipBatchTest {} /*
	@testsetup
    static void setupData() {
    	
    	User sysad = new User();
    	
        sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'VN');      
        insert sysad;
    	

        System.runAs(sysad) {	  
	    	List<Product2> lProduct = TestDataFactory.createTestBrandProduct(1);
            lProduct.get(0).Market__c = 'VN';
            update lProduct;

			List<Account> lAccount = TestDataFactory.createTestHousehold(1);
            lAccount.get(0).Market__c = 'VN';
            Update lAccount;

			List<Contact> lContact = TestDataFactory.createTestAdultContact(2, lAccount.get(0).Id);		
			List<BrandRelationship__c> lBrand = TestDataFactory.createTestBrandRelationShip(1, lContact.get(0).Id, lProduct.get(0).Id);	
		}
    }

	@isTest
	static void test_CreationOfBrand() {
		
		
		User sysad = [Select Id From User where LastName = 'tstSysAd'];
		System.runAs(sysad) {   
            List<Product2> lProduct = TestDataFactory.createTestBrandProduct(1);
            lProduct[0].Name = 'ProductName - 2';
            lProduct[0].Market__c = 'VN';
            update lProduct;

            BrandRelationship__c brand = new BrandRelationship__c();                
            brand.Type__c = 'Lead';
            brand.Status__c = 'Contacted';            
            brand.BrandRelationship__c = lProduct[0].Id;
            brand.User__c =  [Select Id from Contact Limit 1].Id;
            brand.PrimaryContact__c = [Select Id from Contact order by Name desc Limit 1].Id;   
            brand.Active__c = true;   

			insert brand;			
			//Test.setCreatedDate(brand.Id, DateTime.newInstance(2019,06,29));
			Test.setCreatedDate(brand.Id, DateTime.now());

			test.StartTest();

				BrandRelationshipBatch umd = new BrandRelationshipBatch();
            	Database.executeBatch(umd, 200);


			test.StopTest();

			Contact updatedContact = [Select MCEnsureEndUser__c, MCEnsureMainContact__c  From Contact where id =: brand.PrimaryContact__c];
			System.assertEquals(true, updatedContact.MCEnsureMainContact__c);
			
			updatedContact = [Select MCEnsureEndUser__c,MCEnsureMainContact__c  From Contact Limit 1];
			//should still be true because there is still existing brand with the same keybrand for the contact
			System.assertEquals(true, updatedContact.MCEnsureEndUser__c);
			
		}
	}

	@isTest
	static void test_CreationOfBrandOthers() {
		
		
		User sysad = [Select Id From User where LastName = 'tstSysAd'];
		System.runAs(sysad) {   
            List<Product2> lProduct = TestDataFactory.createTestBrandProduct(1);
            lProduct[0].Name = 'ProductName - 2';
            lProduct[0].Keybrand__c = CommonConstant.PRODUCT_KEYBRAND_OTHERS;
            lProduct[0].Market__c = 'VN';
            update lProduct;


            BrandRelationship__c brand = new BrandRelationship__c();                
            brand.Type__c = 'Lead';
            brand.Status__c = 'Contacted';            
            brand.BrandRelationship__c = lProduct[0].Id;
            brand.User__c =  [Select Id from Contact Limit 1].Id;
            brand.PrimaryContact__c = [Select Id from Contact Limit 1].Id;   
            brand.Active__c = true;   

			insert brand;
				//Test.setCreatedDate(brand.Id, DateTime.newInstance(2019,06,29));
				Test.setCreatedDate(brand.Id, DateTime.now());

			test.StartTest();
				
				BrandRelationshipBatch umd = new BrandRelationshipBatch();
            	Database.executeBatch(umd, 200);

				
			test.StopTest();

			Contact updatedContact = [Select MCOthersEndUser__c,MCOthersMainContact__c  From Contact Limit 1];

			System.assertEquals(true, updatedContact.MCOthersEndUser__c);				
			System.assertEquals(true, updatedContact.MCOthersMainContact__c);
		}
	}

	@isTest
	static void test_CreationOfBrandGrow() {
		
		
		User sysad = [Select Id From User where LastName = 'tstSysAd'];
		System.runAs(sysad) {   
            List<Product2> lProduct = TestDataFactory.createTestBrandProduct(1);
            lProduct[0].Name = 'ProductName - 2';
            lProduct[0].Keybrand__c = CommonConstant.PRODUCT_KEYBRAND_GROW;
            lProduct[0].Market__c = 'VN';
            update lProduct;

            BrandRelationship__c brand = new BrandRelationship__c();                
            brand.Type__c = 'Lead';
            brand.Status__c = 'Contacted';            
            brand.BrandRelationship__c = lProduct[0].Id;
            brand.User__c =  [Select Id from Contact Limit 1].Id;
            brand.PrimaryContact__c = [Select Id from Contact Limit 1].Id;   
            brand.Active__c = true;   
			insert brand;
				//Test.setCreatedDate(brand.Id, DateTime.newInstance(2019,06,29));
				Test.setCreatedDate(brand.Id, DateTime.now());
			test.StartTest();
				
				BrandRelationshipBatch umd = new BrandRelationshipBatch();
            	Database.executeBatch(umd, 200);

				
			test.StopTest();

			Contact updatedContact = [Select MCGrowEndUser__c,MCGrowMainContact__c  From Contact Limit 1];

			System.assertEquals(true, updatedContact.MCGrowEndUser__c);				
			System.assertEquals(true, updatedContact.MCGrowMainContact__c);
		}
	}
	
}*/