force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Affiliate Values (Product)</relationshipLabel>
    <relationshipName>Affiliate_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/Region.recordType-meta.xml
<RecordType>
    <fullName>Region</fullName>
    <active>true</active>
    <description>Defines the geographical regions within a given market used during address creation and updates for a contact</description>
    <label>Region</label>
</RecordType>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/State.recordType-meta.xml
<RecordType>
    <fullName>State</fullName>
    <active>true</active>
    <description>Defines the state available for selection while creating and updating addresses.</description>
    <label>State</label>
</RecordType>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/Trade.recordType-meta.xml
<RecordType>
    <fullName>Trade</fullName>
    <active>true</active>
    <label>Trade</label>
</RecordType>

force-app/main/default/objects/Case/fields/AbbottAwarenessDate__c.field-meta.xml
<CustomField>
    <fullName>AbbottAwarenessDate__c</fullName>
    <label>Abbott Awareness Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Cases (Channel)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/DaysOpen__c.field-meta.xml
<CustomField>
    <fullName>DaysOpen__c</fullName>
    <formula>IF(
    IsClosed,
    DATEVALUE(ClosedDate) - DATEVALUE(CreatedDate),
    TODAY() - DATEVALUE(CreatedDate)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day(s) Open</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/LevelofEscalation__c.field-meta.xml
<CustomField>
    <fullName>LevelofEscalation__c</fullName>
    <label>Level of Escalation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level 2</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND ((2 OR 3) OR (4 AND 5))) OR 6 OR 7</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>State</value>
        </filterItems>
        <infoMessage>Value should have a record type of State</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Cases (State)</relationshipLabel>
    <relationshipName>Cases_State</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/StoreWherePurchased__c.field-meta.xml
<CustomField>
    <fullName>StoreWherePurchased__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store Where Purchased</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Feedback.recordType-meta.xml
<RecordType>
    <fullName>Feedback</fullName>
    <active>true</active>
    <businessProcess>Feedback</businessProcess>
    <description>Cases for customers who have raised feedback or a grievance requiring action by one or more Abbott teams</description>
    <label>Feedback</label>
</RecordType>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Website</fullName>
            </value>
            <value>
                <fullName>Campaign Website</fullName>
            </value>
            <value>
                <fullName>Corporate Website</fullName>
            </value>
            <value>
                <fullName>Web - Others</fullName>
            </value>
            <value>
                <fullName>Modern</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Trade - Others</fullName>
            </value>
            <value>
                <fullName>Hospital/Clinic</fullName>
                <label>Hospital</label>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Ethical - Others</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Social - Others</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>Drug Store</fullName>
            </value>
            <value>
                <fullName>EC</fullName>
            </value>
            <value>
                <fullName>Ethical</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>MMC</fullName>
            </value>
            <value>
                <fullName>PX</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>MKT - Others</fullName>
                <isActive>false</isActive>
                <label>MKT - Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/recordTypes/Trade.recordType-meta.xml
<RecordType>
    <fullName>Trade</fullName>
    <active>true</active>
    <label>Trade</label>
</RecordType>

force-app/main/default/objects/PricebookEntry/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[25-Jul-21 Khai] To extract out the product market for troubleshooting purposes</description>
    <formula>TEXT( Product2.Market__c )</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductHierarchyLevel__c.field-meta.xml
<CustomField>
    <fullName>ProductHierarchyLevel__c</fullName>
    <label>Product Hierarchy Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Brand</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Sub - Brand</fullName>
            </value>
            <value>
                <fullName>Product Group</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/classes/CaseFeedbackEscalation_Test.cls
@isTest
public class CaseFeedbackEscalation_Test {

    @testsetup
    static void setup() {

        Id caseRId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Feedback').getRecordTypeId();
        Id channelRId = Schema.SObjectType.Channel__c.getRecordTypeInfosByName().get('Trade').getRecordTypeId();

        User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'IN');
        insert sysad;

        System.runAs(sysad) {

            // create Account
			Account lAccount = TestDataFactory.createTestHousehold(1)[0];
            lAccount.Market__c = 'IN';

            // create product
            PricebookEntry entry = TestDataFactory.createPricebookEntry('IN');
            Insert entry;

            Product2 lProductbr = TestDataFactory.createTestBrandProduct(1)[0];
            lProductbr.Market__c = 'IN';	
            lProductbr.ProductHierarchyLevel__c = 'Brand';	

            // create state
            Affiliate_Value__c region = TestDataFactory.createTestState(1)[0];
            region.Market__c = 'IN';

            // create email escalation
            TestDataFactory.createTestEscalation(3, 'IN', region.Id, lProductbr.Id);

            // create channel StoreWherePurchased__c
            Channel__c channel = TestDataFactory.createTestChannel(1)[0];
            channel.Market__c = 'IN';
            channel.RecordTypeId = channelRId;
            channel.Type__c = 'Traditional';    

            List<Sobject> objList = new List<Sobject>();
            objList.add(lAccount);
            objList.add(region);
            objList.add(channel);
            objList.add(lProductbr);
            update objList;

            // Create Case
            Case c = new Case();
            c.RecordtypeId = caseRId;
            c.Status = 'New';
            c.AccountId = lAccount.Id;
            c.StoreWherePurchased__c = channel.Id;
            c.Product__c = lProductbr.Id;
            c.State__c = region.Id;
            c.AbbottAwarenessDate__c = Date.Today().addDays(-1);
            insert c;
        }
    }

    static testMethod void testEscalation1() {
        User usr = [SELECT Id FROM User WHERE Username = 'tstSysAd@test.com'];

        Case c = [SELECT id FROM Case];

        System.runAs(usr) {
            Test.startTest();

                c.Status = 'Escalated';
                update c;
            Test.stopTest();

        }

        c = [SELECT LevelofEscalation__c FROM Case];
        System.assertEquals('Level 1', c.LevelofEscalation__c);
    }

    static testMethod void testEscalation2() {
        User usr = [SELECT Id FROM User WHERE Username = 'tstSysAd@test.com'];

        Case c = [SELECT id FROM Case];

        System.runAs(usr) {
            Test.startTest();
                CaseFeedbackEscalation_Batch b = new CaseFeedbackEscalation_Batch('IN');
                Database.executeBatch(b);

                String sch = '0 0 23 * * ?'; 
                system.schedule('test feedback', sch, new CaseFeedbackEscalation_Sched('IN') );
            Test.stopTest();
        }

        c = [SELECT DaysOpen__c , LevelofEscalation__c FROM Case];
        System.debug(c.DaysOpen__c);
        System.assertEquals('Level 2', c.LevelofEscalation__c);
    }

    
}