force-app/main/default/objects/Account/fields/NumberOfAdults__c.field-meta.xml
<CustomField>
    <fullName>NumberOfAdults__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of contacts marked as adults in the household</description>
    <label>Number of Adults</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfChildren__c.field-meta.xml
<CustomField>
    <fullName>NumberOfChildren__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of contacts marked as children in the household</description>
    <label>Number of Children</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfHouseholdMembers__c.field-meta.xml
<CustomField>
    <fullName>NumberOfHouseholdMembers__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total number of contacts in the household</description>
    <label>Number of Household Members</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfPrimaryContacts__c.field-meta.xml
<CustomField>
    <fullName>NumberOfPrimaryContacts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of contacts marked as primary in the household</description>
    <label>Number of Primary Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContactEmail__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContactEmail__c</fullName>
    <label>Primary Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContactPhone__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContactPhone__c</fullName>
    <label>Primary Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ChildrenUnderMilkCodeRestriction__c.field-meta.xml
<CustomField>
    <fullName>ChildrenUnderMilkCodeRestriction__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Children Under Milk Code Restriction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MilkCodeRestriction__c.field-meta.xml
<CustomField>
    <fullName>MilkCodeRestriction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milk Code Restriction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/classes/HouseholdBatchProcessTest.cls
@isTest 
public class HouseholdBatchProcessTest{

    @testsetup
    static void setupData() {
        List<Account> lAccount = TestDataFactory.createTestHousehold(1);
        
        //Create Child with Milk Code Restriction Enabled
        List<Contact> lChildContact = TestDataFactory.createTestChildContact(1, lAccount.get(0).Id);
        lChildContact[0].Birthdate = Date.today();
        lChildContact[0].MilkCodeRestriction__c = TRUE;
        update lChildContact;

        //Create Primary Adult Contact
        List<Contact> lPrimaryContact = TestDataFactory.createTestAdultContact(1, lAccount.get(0).Id);
        lPrimaryContact[0].PrimaryContact__c = TRUE;
        lPrimaryContact[0].Email = 'testdata@test.com';
        update lPrimaryContact;

        //Update Account details
        lAccount[0].NumberOfHouseholdMembers__c = 0;
        lAccount[0].NumberOfPrimaryContacts__c = 0;
        lAccount[0].NumberOfAdults__c = 0;
        lAccount[0].NumberOfChildren__c = 0;
        lAccount[0].ChildrenUnderMilkCodeRestriction__c = 0;
        lAccount[0].PrimaryContact__c = '';
        lAccount[0].PrimaryContactEmail__c = '';
        lAccount[0].PrimaryContactPhone__c = '';
        update lAccount;

    }

    public static testMethod  void testBatchJob() {
        System.Test.startTest();
            HouseholdBatchProcess hbp = new HouseholdBatchProcess();
            Database.executeBatch(hbp, 200);
        System.Test.stopTest();

        List<Account> lAccountAfterUpdate = [SELECT NumberOfHouseholdMembers__c, NumberOfPrimaryContacts__c, NumberOfAdults__c, NumberOfChildren__c, 
                                            ChildrenUnderMilkCodeRestriction__c, PrimaryContact__c, PrimaryContactEmail__c, PrimaryContactPhone__c
                                            FROM Account LIMIT 1];

        System.assertEquals(2, lAccountAfterUpdate[0].NumberOfHouseholdMembers__c, 'Number of Household Members should be 2');
        System.assertEquals(1, lAccountAfterUpdate[0].NumberOfPrimaryContacts__c, 'Number of Primary Contacts should be 1');
        System.assertEquals(1, lAccountAfterUpdate[0].NumberOfAdults__c, 'Number of Adults should be 1');
        System.assertEquals(1, lAccountAfterUpdate[0].NumberOfChildren__c, 'Number of Children should be 1');
        System.assertEquals(1, lAccountAfterUpdate[0].ChildrenUnderMilkCodeRestriction__c, 'Children Under Milk Code Restriction should be 1');
        System.assertNotEquals(null, lAccountAfterUpdate[0].PrimaryContact__c, 'Primary Contact should be populated');
        System.assertNotEquals(null, lAccountAfterUpdate[0].PrimaryContactEmail__c, 'Primary Contact Email should be populated');
        System.assertNotEquals(null, lAccountAfterUpdate[0].PrimaryContactPhone__c, 'Primary Contact Phone should be populated');
    }
}