force-app/main/default/objects/Account/fields/NumberOfAdults__c.field-meta.xml
<CustomField>
    <fullName>NumberOfAdults__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of contacts marked as adults in the household</description>
    <label>Number of Adults</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfChildren__c.field-meta.xml
<CustomField>
    <fullName>NumberOfChildren__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of contacts marked as children in the household</description>
    <label>Number of Children</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfHouseholdMembers__c.field-meta.xml
<CustomField>
    <fullName>NumberOfHouseholdMembers__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total number of contacts in the household</description>
    <label>Number of Household Members</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumberOfPrimaryContacts__c.field-meta.xml
<CustomField>
    <fullName>NumberOfPrimaryContacts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of contacts marked as primary in the household</description>
    <label>Number of Primary Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContactEmail__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContactEmail__c</fullName>
    <label>Primary Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContactPhone__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContactPhone__c</fullName>
    <label>Primary Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ChildrenUnderMilkCodeRestriction__c.field-meta.xml
<CustomField>
    <fullName>ChildrenUnderMilkCodeRestriction__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Children Under Milk Code Restriction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/HouseholdBatchProcessed__c.field-meta.xml
<CustomField>
    <fullName>HouseholdBatchProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HouseholdBatchProcessed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MilkCodeRestriction__c.field-meta.xml
<CustomField>
    <fullName>MilkCodeRestriction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milk Code Restriction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/classes/HouseholdBatchProcess.cls
/*----------------------------------------------------------------------------------------
* Script to calcute Household tracking fields in Household which are as follows:
*   - Number of Primary Contacts
*   - Number of Children
*   - Number of Household Members
*   - Number of Adults
-------------------------------------------------------------------------------------------*/

global class HouseholdBatchProcess implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id,'
                            + ' AccountId,'
                            + ' PrimaryContact__c,'
                            + ' Type__c,'
                            + ' HouseholdBatchProcessed__c,'
                            + ' Email,'
                            + ' Phone,'
                            + ' FirstName,'
                            + ' LastName,'
                            + ' MilkCodeRestriction__c'
                            + ' FROM Contact WHERE AccountId != null AND HouseholdBatchProcessed__c = FALSE'
                            + ' ORDER BY AccountId';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        Set<Id> accIdSet = new Set<Id>();
        List<Contact> processedContactList = new List<Contact>();

        for(Contact con : scope) {
            if(con.AccountId != null) {
                accIdSet.add(con.AccountId);
            }
        }

        Map<Id,Account> accMap = new Map<Id,Account>([SELECT NumberOfHouseholdMembers__c, NumberOfPrimaryContacts__c, 
                                                    NumberOfAdults__c, NumberOfChildren__c,ChildrenUnderMilkCodeRestriction__c,
                                                    PrimaryContact__c, PrimaryContactEmail__c, PrimaryContactPhone__c
                                                    FROM Account 
                                                    WHERE Id IN :accIdSet]);

        for(Contact con : scope) {
            if(accMap.containsKey(con.AccountId)) {
                accMap.get(con.AccountId).NumberOfHouseholdMembers__c = accMap.get(con.AccountId).NumberOfHouseholdMembers__c == null ? 0 : accMap.get(con.AccountId).NumberOfHouseholdMembers__c;
                accMap.get(con.AccountId).NumberOfPrimaryContacts__c = accMap.get(con.AccountId).NumberOfPrimaryContacts__c == null ? 0 : accMap.get(con.AccountId).NumberOfPrimaryContacts__c;
                accMap.get(con.AccountId).NumberOfAdults__c = accMap.get(con.AccountId).NumberOfAdults__c == null ? 0 : accMap.get(con.AccountId).NumberOfAdults__c;
                accMap.get(con.AccountId).NumberOfChildren__c = accMap.get(con.AccountId).NumberOfChildren__c == null ? 0 : accMap.get(con.AccountId).NumberOfChildren__c;
                accMap.get(con.AccountId).ChildrenUnderMilkCodeRestriction__c = accMap.get(con.AccountId).ChildrenUnderMilkCodeRestriction__c == null ? 0 : accMap.get(con.AccountId).ChildrenUnderMilkCodeRestriction__c;
                String firstName = (con.FirstName == null || con.FirstName == '') ? '' : con.FirstName + ' ';
                String lastName = (con.LastName == null || con.LastName == '') ? '' : con.LastName;
                
                accMap.get(con.AccountId).NumberOfHouseholdMembers__c++;

                if(con.PrimaryContact__c == TRUE) {
                    accMap.get(con.AccountId).NumberOfPrimaryContacts__c++;
                    accMap.get(con.AccountId).PrimaryContact__c = firstName + lastName;
                    
                    if(con.Email != null) {
                        accMap.get(con.AccountId).PrimaryContactEmail__c = con.Email;
                    }

                    if(con.Phone != null) {
                        accMap.get(con.AccountId).PrimaryContactPhone__c = con.Phone;
                    }
                }   
                
                if(con.MilkCodeRestriction__c == TRUE) {
                    accMap.get(con.AccountId).ChildrenUnderMilkCodeRestriction__c++;
                }

                if(con.Type__c == 'Adult') {
                    accMap.get(con.AccountId).NumberOfAdults__c++;
                }
                
                else if(con.Type__c == 'Child') {
                    accMap.get(con.AccountId).NumberOfChildren__c++;
                }
                
                con.HouseholdBatchProcessed__c = TRUE;
                accMap.put(con.AccountId, accMap.get(con.AccountId));
                processedContactList.add(con);
            }   
        }

        Database.update(accMap.values(), false);
        Database.update(processedContactList, false);
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}