force-app/main/default/objects/Account/fields/NumberOfPrimaryContacts__c.field-meta.xml
<CustomField>
    <fullName>NumberOfPrimaryContacts__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of contacts marked as primary in the household</description>
    <label>Number of Primary Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateHouseholdDetails_Batch.cls
/*
Author: Jennifer
Description: One-time batch to update Household's primary contact details
Date:
June 20, 2020 Created
*/
public class UpdateHouseholdDetails_Batch Implements Database.Batchable<sObject> {
    String overrideQuery = '';
    public UpdateHouseholdDetails_Batch(String q) {
        overrideQuery = q;
    }
    public Database.QueryLocator start(Database.BatchableContext BC) {

        String query = 'SELECT ID, PrimaryContact__c,AccountId'                           
            + ' FROM Contact'
            + ' WHERE'
            + ' PrimaryContact__c = true'
            + ' AND Account.NumberofPrimaryContacts__c = 0';

        if(overrideQuery != '') {
            query = overrideQuery;
        }

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Contact> scope) {
        
        Set<Id> conIds = new Set<Id>();
        for(Contact con: scope){
            conIds.add(con.Id);
        }
        if(!conIds.isEmpty()) ContactEventHandler.updateAccountTrackingFields(conIds);
    }
    public void finish(Database.BatchableContext BC) {}
}