force-app/main/default/objects/Account/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Website</fullName>
            </value>
            <value>
                <fullName>Campaign Website</fullName>
            </value>
            <value>
                <fullName>Corporate Website</fullName>
            </value>
            <value>
                <fullName>Web - Others</fullName>
            </value>
            <value>
                <fullName>Modern</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Trade - Others</fullName>
            </value>
            <value>
                <fullName>Hospital/Clinic</fullName>
                <label>Hospital</label>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Ethical - Others</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Social - Others</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>Drug Store</fullName>
            </value>
            <value>
                <fullName>EC</fullName>
            </value>
            <value>
                <fullName>Ethical</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>MMC</fullName>
            </value>
            <value>
                <fullName>PX</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>MKT - Others</fullName>
                <isActive>false</isActive>
                <label>MKT - Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EstimatedDueDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDueDate__c</fullName>
    <label>Estimated Due Date (EDD)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Fill in the Main Contact for this person (e.g. child or elderly person) under the main contact&apos;s care. This field is not required if this person is a Primary Contact.</inlineHelpText>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/classes/ContactEstimatedDueDateBatchTest.cls
@isTest
private class ContactEstimatedDueDateBatchTest {
	@testsetup
    static void setupData() {
    	User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'SG');
        insert sysad;
        
        System.runAs(sysad) {	    	
	    	List<Channel__c> lChannel = TestDataFactory.createTestChannel(1);
			List<Account> lAccount = TestDataFactory.createTestHousehold(1, 'SG');
			List<Contact> lContact = TestDataFactory.createTestAdultContact(1, lAccount.get(0).Id);
            PricebookEntry pbe = TestDataFactory.createPricebookEntry('SG', 'SGD');
            Product2 prod = TestDataFactory.createProductDiffBrand('SG', 'SGD', pbe.Pricebook2Id, 'Similac Mom', 'SIMILAC MOM CHILD', 'SG_BR_ABSM_CHILD');
		}
    }

	@isTest static void test_creationRecordBatch() {
		Contact con = [Select Id,EstimatedDueDate__c from Contact Limit 1];
		con.EstimatedDueDate__c = Date.today();
		con.PrimaryContact__c = true;
		Update con;

		System.Test.startTest();
    		ContactEstimatedDueDateBatch ucs = new ContactEstimatedDueDateBatch();
    		Database.executeBatch(ucs, 200);
    	System.Test.stopTest();

    	List<Contact> childContactList = [Select Id from Contact where Type__c =: CommonConstant.CONTACT_CHILD_TYPE];
    	System.assertEquals(1, childContactList.size());    	
	}
	
	@isTest static void test_withExistingChild() {
		Contact con = [Select Id,EstimatedDueDate__c,AccountId from Contact Limit 1];
		con.EstimatedDueDate__c = Date.today();
		con.PrimaryContact__c = true;
		Update con;

		Contact child = new Contact();
		child.LastName = 'CHild 1';
		child.Parent__c = con.Id;
		child.Birthdate = Date.today().addDays(-1);
		child.Type__c = CommonConstant.CONTACT_CHILD_TYPE;
		child.AccountId = con.AccountId;
		insert child;

		System.Test.startTest();
    		ContactEstimatedDueDateBatch ucs = new ContactEstimatedDueDateBatch();
    		Database.executeBatch(ucs, 200);
    	System.Test.stopTest();

    	List<Contact> childContactList = [Select Id from Contact where Type__c =: CommonConstant.CONTACT_CHILD_TYPE];
    	System.assertEquals(2, childContactList.size());    	
	}

	@isTest static void test_withSameBirthdate() {
		Contact con = [Select Id,EstimatedDueDate__c,AccountId from Contact Limit 1];
		con.EstimatedDueDate__c = Date.today();
		con.PrimaryContact__c = true;
		Update con;

		Contact child = new Contact();
		child.LastName = 'CHild 1';
		child.Parent__c = con.Id;
		child.Birthdate = Date.today();
		child.Type__c = CommonConstant.CONTACT_CHILD_TYPE;
		child.AccountId = con.AccountId;
		insert child;

		System.Test.startTest();
    		ContactEstimatedDueDateBatch ucs = new ContactEstimatedDueDateBatch();
    		Database.executeBatch(ucs, 200);
    	System.Test.stopTest();

    	List<Contact> childContactList = [Select Id from Contact where Type__c =: CommonConstant.CONTACT_CHILD_TYPE];
    	//cannot be more than 1 , no new child should be created
    	System.assertEquals(1, childContactList.size());    	
	}

	@isTest static void test_scheduler() {
		// Implement test code
		ContactEstimatedDueDateSchedule job = new ContactEstimatedDueDateSchedule();
		String sch = '0 0 23 * * ?'; 
		Id scID = System.schedule('Test Cost Estimate Batch Job', sch, job);

		CronTrigger ct = [SELECT Id,
                          CronExpression,
                          TimesTriggered,
                          NextFireTime                          
                          FROM CronTrigger
                          WHERE Id = : scID];

        //asserting the schedule job values        
        System.assertEquals(0, ct.TimesTriggered);        
        System.assertEquals('0 0 23 * * ?', ct.CronExpression);        
        
	}
	
}