force-app/main/default/objects/Account/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Will Buy</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Non_User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Brand_Relationship_EndUser_Child_Count__c.field-meta.xml
<CustomField>
    <fullName>Brand_Relationship_EndUser_Child_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Custom rollup field for counting BRs related to Contact through BR EndUser field</description>
    <label>Brand Relationship EndUser Child Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/classes/UpdateChildEndUserCountBatchTest.cls
@isTest
public class UpdateChildEndUserCountBatchTest {
    @testsetup
    static void setupData() {
        User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'PH');
        insert sysad;
        
        System.runAs(sysad) {	  
            List<Product2> lProduct = TestDataFactory.createTestBrandProduct(1);
            List<Account> lAccount = TestDataFactory.createTestHousehold(1);
            List<Contact> lContact = TestDataFactory.createTestAdultContact(2, lAccount.get(0).Id);		
            List<Contact> lContactChild = TestDataFactory.createTestChildContact(1, lAccount.get(0).Id);		
            List<BrandRelationship__c> lBrand = TestDataFactory.createTestBrandRelationShip(1, lContact.get(0).Id, lProduct.get(0).Id);	
        }
    }
    
    static testmethod void test_UpdateChildEndUserCountBatch() {
        Test.enableChangeDataCapture();
        List<Product2> lProduct = TestDataFactory.createTestBrandProduct(2);
        lProduct[0].Name = 'ProductName - 2';
        lProduct[1].Name = 'ProductName - 3';
        update lProduct;
        
        Contact conAdult = [Select Id from Contact WHERE RecordType.Name = 'Adult' Limit 1][0];
        Contact conChild = [Select Id from Contact WHERE RecordType.Name = 'Child' LIMIT 1][0];		
        
        BrandRelationship__c brand1 = new BrandRelationship__c();                
        brand1.Type__c = 'Lead';
        brand1.Status__c = 'Contacted';            
        brand1.BrandRelationship__c = lProduct[0].Id;
        brand1.User__c =  conChild.Id;
        brand1.PrimaryContact__c = conAdult.Id;   
        brand1.Active__c = true;   
        
        BrandRelationship__c brand2 = new BrandRelationship__c();                
        brand2.Type__c = 'Lead';
        brand2.Status__c = 'Contacted';            
        brand2.BrandRelationship__c = lProduct[1].Id;
        brand2.User__c =  conChild.Id;
        brand2.PrimaryContact__c = conAdult.Id;   
        brand2.Active__c = true;   
        List<BrandRelationship__c> brandInsertList = new List<BrandRelationship__c>{brand1, brand2};
            
        User sysad = [Select Id From User where LastName = 'tstSysAd'];
        System.runAs(sysad) {   
            insert brandInsertList;
            Contact conCheck = [SELECT Brand_Relationship_EndUser_Child_Count__c FROM Contact WHERE Id =: conChild.id];
            System.assertEquals(conCheck.Brand_Relationship_EndUser_Child_Count__c, 0);
            
            Test.startTest();
            UpdateChildEndUserCountBatch batch = new UpdateChildEndUserCountBatch('PH', 0, 60); 
            System.schedule('jobName', '0 5 * * * ?', batch);
            Database.executebatch(batch, 50);
            Test.stopTest();
            
            Contact conCheck1 = [SELECT Brand_Relationship_EndUser_Child_Count__c FROM Contact WHERE Id =: conChild.id];
            System.assertEquals(conCheck1.Brand_Relationship_EndUser_Child_Count__c, 2);
        }
    }
}