force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[1-Sep-21 Khai] This field is for troubleshooting by extracting out the market of the Contact</description>
    <formula>Contact__r.Market__c</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/MC_Sync_Eligibility_ID__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/MC_Sync_Eligibility_MY__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_MY__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility MY</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/MC_Sync_Eligibility_PH__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_PH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility PH</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MC_Sync_Eligibility_MY__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_MY__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility MY</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MC_Sync_Eligibility_PH__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_PH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility PH</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MC_CR_SyncEligibilityBatch.cls
/**
* @author        Jennifer Alviz    
* @date          12.18.2020
* @description   Batch job to update CHANNEL RESPONSE Sync Eligibility Fields
* @revision(s)
*/
global class MC_CR_SyncEligibilityBatch Implements Database.Batchable<sObject>, Database.Stateful {
    
    Set<Id> contactIds = new Set<Id>();
    Set<Id> eligibleContacts = new Set<Id>();
    String queryOverride;
    
    global MC_CR_SyncEligibilityBatch(Set<Id> conIds, String newScope){
        contactIds =  (Set<Id>) conIds;
        queryOverride = newScope;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT ID, Contact__c ,'
            + 'MC_Sync_Eligibility_ANZ__c, MC_Sync_Eligibility_ID__c, MC_Sync_Eligibility_IN__c, MC_Sync_Eligibility_MY__c,'
            + 'MC_Sync_Eligibility_PH__c, MC_Sync_Eligibility_SG__c, MC_Sync_Eligibility_TH__c, MC_Sync_Eligibility_VN__c'                        
            + ' FROM ChannelResponse__c'
            + ' WHERE'
            + ' Contact__c IN :contactIds';

        if(String.isNotBlank(queryOverride)){
            query = queryOverride;
        } 

        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<ChannelResponse__c> scope) {
        Map<Id, Contact> contactMap = new Map<Id,Contact>();
        List<ChannelResponse__c> crToUpdate = new List<ChannelResponse__c>();
        Set<Id> crIds = new set<Id>();
        for(ChannelResponse__c cr: scope){
            crIds.add(cr.Id);
        }
        
        //ChannelResponseEventHandler.updateMCEligibility(crIds);

        contactMap = new Map<Id,Contact>([SELECT Id, Market__c,MC_Sync_Eligibility_ANZ__c,MC_Sync_Eligibility_ID__c,MC_Sync_Eligibility_IN__c, 
                                        MC_Sync_Eligibility_MY__c, MC_Sync_Eligibility_PH__c, MC_Sync_Eligibility_SG__c, MC_Sync_Eligibility_TH__c,
                                        MC_Sync_Eligibility_VN__c
                                        FROM Contact 
                                        WHERE Id IN (SELECT Contact__c FROM ChannelResponse__c WHERE Id IN: crIds)]);
        
        for(ChannelResponse__c cr: scope ) {  
                  
            String Market = contactMap.get(cr.Contact__c).Market__c;
            Boolean forUpdate = false; 
                      
            if(Market == CommonConstant.MARKET_ANZ){
                cr.MC_Sync_Eligibility_ANZ__c = contactMap.get(cr.Contact__c).MC_Sync_Eligibility_ANZ__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_ID){
                cr.MC_Sync_Eligibility_ID__c = contactMap.get(cr.Contact__c).MC_Sync_Eligibility_ID__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_IN){
                cr.MC_Sync_Eligibility_IN__c = contactMap.get(cr.Contact__c).MC_Sync_Eligibility_IN__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_MY){
                cr.MC_Sync_Eligibility_MY__c = contactMap.get(cr.Contact__c).MC_Sync_Eligibility_MY__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_PH){
                cr.MC_Sync_Eligibility_PH__c = contactMap.get(cr.Contact__c).MC_Sync_Eligibility_PH__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_SG){
                cr.MC_Sync_Eligibility_SG__c = contactMap.get(cr.Contact__c).MC_Sync_Eligibility_SG__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_TH){
                cr.MC_Sync_Eligibility_TH__c = contactMap.get(cr.Contact__c).MC_Sync_Eligibility_TH__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_VN){
                cr.MC_Sync_Eligibility_VN__c = contactMap.get(cr.Contact__c).MC_Sync_Eligibility_VN__c;
                forUpdate = true;

            }
            
            if(forUpdate) crToUpdate.add(cr);
        }
        
        if(!crToUpdate.isEmpty()) UtilityClass.updateList(crToUpdate);
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}