force-app/main/default/objects/LookupRollupSummary__mdt/LookupRollupSummary__mdt.object-meta.xml
<CustomObject>
    <description>This table is the setting to run ProcessLREngineBatch for lookup fields to be rolled up by using Batch Job</description>
    <label>Lookup Rollup Summary</label>
    <pluralLabel>Lookup Rollup Summaries</pluralLabel>
</CustomObject>

force-app/main/default/objects/LookupRollupSummary__mdt/fields/ChildFieldname__c.field-meta.xml
<CustomField>
    <fullName>ChildFieldname__c</fullName>
    <description>The Child Object&apos;s Fieldname for rollup summary</description>
    <label>Child Fieldname</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LookupRollupSummary__mdt/fields/ChildObject__c.field-meta.xml
<CustomField>
    <fullName>ChildObject__c</fullName>
    <description>The Child Object of the rollup summary</description>
    <label>Child Object</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LookupRollupSummary__mdt/fields/History_Filter__c.field-meta.xml
<CustomField>
    <fullName>History_Filter__c</fullName>
    <label>History Filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LookupRollupSummary__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>The Lookup Rollup Summary settings are active for use or not</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LookupRollupSummary__mdt/fields/No_of_Days__c.field-meta.xml
<CustomField>
    <fullName>No_of_Days__c</fullName>
    <description>The Last_N_Days of the records that were created or deleted for rollup summary</description>
    <label>No of Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LookupRollupSummary__mdt/fields/ParentFieldname__c.field-meta.xml
<CustomField>
    <fullName>ParentFieldname__c</fullName>
    <description>The Parent Object&apos;s Fieldname for rollup summary</description>
    <label>Parent Fieldname</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LookupRollupSummary__mdt/fields/ParentObject__c.field-meta.xml
<CustomField>
    <fullName>ParentObject__c</fullName>
    <description>The Parent Object of the rollup summary</description>
    <label>Parent Object</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LookupRollupSummary__mdt/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <description>The query to process specific criteria for the lookup summary. WHERE clause in SOQL</description>
    <label>Query</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LookupRollupSummary__mdt/fields/RollupFieldname__c.field-meta.xml
<CustomField>
    <fullName>RollupFieldname__c</fullName>
    <description>The fieldname of the child object that will be referred for rollup operation</description>
    <label>Rollup Fieldname</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LookupRollupSummary__mdt/fields/RollupOperation__c.field-meta.xml
<CustomField>
    <fullName>RollupOperation__c</fullName>
    <description>The rollup operation that will be done based on the parent and child object</description>
    <label>Rollup Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sum</fullName>
                <default>true</default>
                <label>Sum</label>
            </value>
            <value>
                <fullName>Max</fullName>
            </value>
            <value>
                <fullName>Min</fullName>
            </value>
            <value>
                <fullName>Avg</fullName>
            </value>
            <value>
                <fullName>Count</fullName>
            </value>
            <value>
                <fullName>Count_Distinct</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProcessLREngineBatch_Sched.cls
public class ProcessLREngineBatch_Sched implements Schedulable {
    
    public void execute(SchedulableContext sc) {
        
        List<LookupRollupSummary__mdt> lrSummary = [SELECT ChildFieldname__c,ChildObject__c,ParentFieldname__c,ParentObject__c,Query__c,History_Filter__c,
                                                    RollupFieldname__c, RollupOperation__c,No_of_Days__c FROM LookupRollupSummary__mdt WHERE Is_Active__c=true];
        
        Database.executebatch(new ProcessLREngineBatch(lrSummary));

    }
    

}