force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/MembershipExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipExpiryDate__c</fullName>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Membership Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/NumberOfDaysDormant__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysDormant__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Days Dormant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/NumberOfTransactions__c.field-meta.xml
<CustomField>
    <fullName>NumberOfTransactions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FirstRepeatOrderName__c.field-meta.xml
<CustomField>
    <fullName>FirstRepeatOrderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[9-Jul-21 KSK] Used in TW Market Data Migration; Dynamics CRM</description>
    <label>First Repeat Order Name</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (First Repeat Order Name)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ParentMembership__c.field-meta.xml
<CustomField>
    <fullName>ParentMembership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateMembershipDetailsBatch.cls
/*----------------------------------------------------------------------------------------
Author:      Viana Flor Mirandilla
Description: Batch Class to update Memebership Details on a daily basis

History
04/09/2019   vmirandilla   Created
05/15/2019   raustral      Remove sub query causing cpu limit when result is too large
-------------------------------------------------------------------------------------------*/
global class UpdateMembershipDetailsBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT NumberOfDaysDormant__c,'
                            + ' NumberOfTransactions__c,'
                            + ' MembershipStartDate__c'
                            //+ ' (SELECT EndDate'
                            //+ ' From Orders__r'
                            //+ ' ORDER BY EndDate DESC LIMIT 1)'
                            + ' FROM Membership__c WHERE Status__c != \'Expired\'';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Membership__c> scope) {
        List<Membership__c> membershipList = new List<Membership__c>();

        List<Membership__c> scopeList = [Select NumberOfDaysDormant__c, NumberOfTransactions__c, MembershipStartDate__c,
                                        (SELECT EndDate From Orders__r ORDER BY EndDate DESC LIMIT 1)
                                        FROM Membership__c WHERE ID IN: scope];

        for(Membership__c mem : scopeList) {
            if(!mem.Orders__r.isEmpty()) {
                for(Order order : mem.Orders__r) {
                    if(order.EndDate != null) {
                        if(order.EndDate == Date.valueOf(System.today())) {
                            mem.NumberOfDaysDormant__c = 0;    
                        } else {
                            mem.NumberOfDaysDormant__c = order.EndDate.daysBetween(System.today());
                        }
                        
                        if(mem.NumberOfDaysDormant__c >= 90) {
                            mem.Status__c = CommonConstant.MEMBERSHIP_STATUS_EXPIRED;
                            mem.MembershipExpiryDate__c = order.EndDate.addDays(90);
                        }
                    }
                }
            } else {
                if(mem.MembershipStartDate__c != null) {
                    if(mem.MembershipStartDate__c == Date.valueOf(System.today())) {
                        mem.NumberOfDaysDormant__c = 0;    
                    } else {
                        mem.NumberOfDaysDormant__c = mem.MembershipStartDate__c.daysBetween(System.today());
                    }
                    
                    if(mem.NumberOfDaysDormant__c >= 90) {
                        mem.Status__c = CommonConstant.MEMBERSHIP_STATUS_EXPIRED;
                        mem.MembershipExpiryDate__c = mem.MembershipStartDate__c.addDays(90);
                    }
                }
            }

            if (mem.NumberOfDaysDormant__c < 0) {
                mem.NumberOfDaysDormant__c = 0;
            }

            membershipList.add(mem);
        }

        if(!membershipList.isEmpty()) {
            Database.update(membershipList, false);
        }
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}