force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/NumberOfTransactions__c.field-meta.xml
<CustomField>
    <fullName>NumberOfTransactions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/FirstRepeatOrderName__c.field-meta.xml
<CustomField>
    <fullName>FirstRepeatOrderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[9-Jul-21 KSK] Used in TW Market Data Migration; Dynamics CRM</description>
    <label>First Repeat Order Name</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (First Repeat Order Name)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ParentMembership__c.field-meta.xml
<CustomField>
    <fullName>ParentMembership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MembershipNumberOfTransactionsBatch.cls
/*----------------------------------------------------------------------------------------
Author:      Viana Flor Mirandilla
Description: Batch Class that will Membership Number Of Transactions. 

History
09/26/2019   vmirandilla   Created
-------------------------------------------------------------------------------------------*/
global class MembershipNumberOfTransactionsBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, NumberOfTransactions__c'
                            // + ' (SELECT Id, EndDate'
                            // + ' From Orders__r'
                            // + ' WHERE Status != \'Cancelled - New Order Created\''
                            // + ' AND Status != \'Cancelled - Before Delivery\''
                            // + ' AND Status != \'Cancelled - Upon Delivery\''
                            // + ' AND Status != \'Cancelled - Abandoned\''
                            // + ' ORDER BY EndDate DESC)'
                            + ' FROM Membership__c WHERE Status__c != \'Expired\'';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Membership__c> scope) {
        List<Membership__c> membershipList = new List<Membership__c>();
        
        List<Membership__c> scopeList = [Select  NumberOfTransactions__c, 
                                        (SELECT Id, EndDate From Orders__r WHERE Status != 'Cancelled - New Order Created' 
                                        AND Status != 'Cancelled - Before Delivery'
                                        AND Status != 'Cancelled - Upon Delivery'
                                        AND Status != 'Cancelled - Abandoned'
                                        ORDER BY EndDate DESC)
                                        FROM Membership__c WHERE ID IN: scope];

        for(Membership__c mem : scopeList) {
            if(!mem.Orders__r.isEmpty()) {
                mem.NumberOfTransactions__c = mem.Orders__r.size();
            }
            else {
                mem.NumberOfTransactions__c = 0;
            }
            membershipList.add(mem);
        }
        
        if(!membershipList.isEmpty()) {
            Database.update(membershipList, false);
        }
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}