force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipId__c.field-meta.xml
<CustomField>
    <fullName>MembershipId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderedBy__c.field-meta.xml
<CustomField>
    <fullName>OrderedBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordered By</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Adult</value>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ParentMembership__c.field-meta.xml
<CustomField>
    <fullName>ParentMembership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateOrderedByBatchTest.cls
@isTest 
public class UpdateOrderedByBatchTest{

    @testsetup
    static void setupData() {
        List<Account> lAccount = TestDataFactory.createTestHousehold(1);
        lAccount[0].External_Id__c = 'ph-orphan-tangent-orders';
        update lAccount;

        List<Contact> lContact = TestDataFactory.createTestAdultContact(1, lAccount.get(0).Id);
        
        List<Membership__c> lMembership = TestDataFactory.createMembership(1, lContact.get(0).Id, -90);
        lMembership[0].MembershipId__c = 'TESTMEM1';
        update lMembership[0];

        List<Order> lOrder = TestDataFactory.createOrder(2, lAccount.get(0).Id, lContact.get(0).Id, Test.getStandardPricebookId());
        insert lOrder; 
        
        PricebookEntry entry = TestDataFactory.createPricebookEntry();
        insert entry;

        OrderItem orderItem = TestDataFactory.createOrderItem(lOrder.get(0).Id, entry.Id);
        insert orderItem;
        lOrder[0].ParentMembership__c = lMembership.get(0).Id;
        lOrder[0].Status = 'Submitted';
        update lOrder[0];
    }

    public static testMethod  void testBatchJob() {
        List<Membership__c> lMembership = [SELECT Id, Contact__c FROM Membership__c LIMIT 1];

        System.Test.startTest();
            UpdateOrderedByBatch uob = new UpdateOrderedByBatch();
            Database.executeBatch(uob, 200);

            UpdateOrderedBySchedule job = new UpdateOrderedBySchedule();
            String sch = '0 0 23 * * ?'; 
            system.schedule('Link Orders to Contacts via Membership Test', sch, job);
            
        System.Test.stopTest();

        List<Order> lOrderAfterUpdate = [SELECT Id, OrderedBy__c FROM Order LIMIT 1];
        System.assertEquals(lMembership[0].Contact__c, lOrderAfterUpdate[0].OrderedBy__c, 'Ordered By field should be updated after batch run');
    }
}