force-app/main/default/objects/ExternalId__mdt/ExternalId__mdt.object-meta.xml
<CustomObject>
    <label>External ID</label>
    <pluralLabel>External IDs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ExternalId__mdt/fields/ExternalIdValue__c.field-meta.xml
<CustomField>
    <fullName>ExternalIdValue__c</fullName>
    <label>External Id Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderedBy__c.field-meta.xml
<CustomField>
    <fullName>OrderedBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordered By</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Adult</value>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ParentMembership__c.field-meta.xml
<CustomField>
    <fullName>ParentMembership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateOrderedByBatch.cls
/*----------------------------------------------------------------------------------------
Author:      Viana Flor Mirandilla
Description: Batch Class to update Order records with no Ordered By value specified on a daily basis

History
04/17/2019   vmirandilla   Created
-------------------------------------------------------------------------------------------*/
global class UpdateOrderedByBatch implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String eId = [SELECT Id, ExternalIdValue__c FROM ExternalId__mdt WHERE DeveloperName = :CommonConstant.PH_ORPHAN_TANGENT_ORDERS].ExternalIdValue__c;

        String query = 'SELECT Id,'
                            + ' OrderedBy__c,'
                            + ' ParentMembership__c,'
                            + ' ParentMembership__r.Contact__c,'
                            + ' Status,'
                            + ' Account.External_Id__c'
                            + ' FROM Order WHERE Account.External_Id__c = :eId AND ParentMembership__r.Contact__c != null';

        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Order> scope) {
        List<Order> orderList = new List<Order>();
        List<Order> orderChangeStatusList = new List<Order>();
        List<Order> orderUpdateStatusList = new List<Order>();
        Map<Id,String> orderStatusMap = new Map<Id,String>();

        for(Order orderRec : scope) {
            orderRec.OrderedBy__c = orderRec.ParentMembership__r.Contact__c;
            if (orderRec.Status != CommonConstant.ORDER_STATUS_DRAFT && orderRec.Status != CommonConstant.ORDER_STATUS_CANCELLED_ABANDONED) {
                orderStatusMap.put(orderRec.Id, orderRec.Status);
                orderRec.Status = CommonConstant.ORDER_STATUS_DRAFT;
                orderChangeStatusList.add(orderRec);
            }
            orderList.add(orderRec);
        }

        if(!orderList.isEmpty()) {
            Database.update(orderList, false);
        }

        if(!orderChangeStatusList.isEmpty()) {
            for(Order o : orderChangeStatusList) {
                o.Status = orderStatusMap.get(o.Id);
                orderUpdateStatusList.add(o);
            }
        }

        if(!orderUpdateStatusList.isEmpty()) {
            Database.update(orderUpdateStatusList, false);
        }
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}