force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City2__c.field-meta.xml
<CustomField>
    <fullName>City2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>City</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (City)</relationshipLabel>
    <relationshipName>AddressesCity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>IF($UserRole.Name = &quot;ANI - Malaysia&quot;, &quot;Malaysia&quot;, 
    IF($UserRole.Name = &quot;ANI - Philippines&quot;, &quot;Philippines&quot;, 
    IF($UserRole.Name = &quot;ANI - Singapore&quot;, &quot;Singapore&quot;,
    IF($UserRole.Name = &quot;ANI - Thailand&quot;, &quot;Thailand&quot;,
    IF($UserRole.Name = &quot;ANI - Vietnam&quot;, &quot;Vietnam&quot;,
    IF($UserRole.Name = &quot;ANI - India&quot;, &quot;India&quot;,
    IF($UserRole.Name = &quot;ANI - ANZ&quot;, &quot;Australia&quot;,
    IF($UserRole.Name = &quot;ANI - Indonesia&quot;, &quot;Indonesia&quot;, 
    IF($UserRole.Name = &quot;ANI - Taiwan&quot;, &quot;Taiwan&quot;, &quot;&quot;)))))))))</defaultValue>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Saint Barthélemy</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Brunei Darussalam</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR 4 OR 5</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>District</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.ParentAffiliateValue__c</field>
            <operation>equals</operation>
            <valueField>$Source.City2__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (District)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Region</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Ward2__c.field-meta.xml
<CustomField>
    <fullName>Ward2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ward</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR 4 OR 5</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Ward</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.ParentAffiliateValue__c</field>
            <operation>equals</operation>
            <valueField>$Source.District__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (Ward)</relationshipLabel>
    <relationshipName>AddressesWard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/RelatedCampaign__c.field-meta.xml
<CustomField>
    <fullName>RelatedCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases (Related Campaign)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ContactRefNo__c.field-meta.xml
<CustomField>
    <fullName>ContactRefNo__c</fullName>
    <formula>Market__c &amp; &quot;-C-&quot; &amp;  AutoNumber__c</formula>
    <label>Contact Ref No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FileExportDate__c.field-meta.xml
<CustomField>
    <fullName>FileExportDate__c</fullName>
    <label>File Export Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderedBy__c.field-meta.xml
<CustomField>
    <fullName>OrderedBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordered By</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Adult</value>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderNotes__c.field-meta.xml
<CustomField>
    <fullName>OrderNotes__c</fullName>
    <label>Order Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Cash on Delivery</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Online Payment - FPX</fullName>
            </value>
            <value>
                <fullName>E-Wallet</fullName>
            </value>
            <value>
                <fullName>Third Party Payment Vendor</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>No Charge Order</fullName>
            </value>
            <value>
                <fullName>EFT</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>MoneyOrder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/RelatedCampaign__c.field-meta.xml
<CustomField>
    <fullName>RelatedCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingAddress__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/TotalQuantitySummary__c.field-meta.xml
<CustomField>
    <fullName>TotalQuantitySummary__c</fullName>
    <label>Total Quantity</label>
    <summarizedField>OrderItem.Quantity</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/SummarizedOrderReportGeneratorController.cls
/**
* @author        Viana Mirandilla
* @date          4.26.2019
* @description   Controller of SummarizedOrderReportGenerator (Lightning Component)
* @testClass     SummarizedOrderReportGeneratorTest 
* @revision(s)
*/
public with sharing class SummarizedOrderReportGeneratorController {
    public List<CommonObjectWrapper.cls_SummarizedOrder> combinedOrderList { get; set; }

    public SummarizedOrderReportGeneratorController () {
        //will be called when the excel is being loaded from Order Export (Combined Line Items) button
        combinedOrderList = queryOrderReport();
    }

    @AuraEnabled
    public static List<CommonObjectWrapper.cls_SummarizedOrder> queryOrderReport() {
        List<CommonObjectWrapper.cls_SummarizedOrder> combinedOrderList = new List<CommonObjectWrapper.cls_SummarizedOrder>() ;

        List<Order> orderList = [SELECT OrderedBy__r.Name, OrderedBy__r.ContactRefNo__c, OrderedBy__r.HomePhone, OrderedBy__r.Phone, OrderedBy__r.OtherPhone, Type,
                       RelatedCampaign__r.Name, EffectiveDate, Status, PaymentMethod__c, FileExportDate__c, Case__r.CaseNumber, CurrencyIsoCode, TotalAmount, 
                       TotalQuantitySummary__c, OrderNotes__c, ShippingAddress__r.Name, ShippingAddress__r.Country__c, ShippingAddress__r.City2__r.Name, 
                       ShippingAddress__r.Ward2__r.Name, ShippingAddress__r.District__r.Name, ShippingAddress__r.Region__r.Name, ShippingAddress__r.Street1__c, 
                       ShippingAddress__r.Street2__c, OrderNumber, CreatedBy.Name, 
                       (SELECT Promotion__r.Name, OrderItemNumber, PricebookEntry.Product2.Name, PricebookEntry.ProductCode, Quantity, CurrencyIsoCode, UnitPrice, 
                       TotalPrice, PricebookEntry.Product2.KeyBrand__c, OrderedFor__r.Name, Category__c FROM OrderItems) 
                FROM Order WHERE Status =: CommonConstant.ORDER_STATUS_SUBMITTED ORDER BY OrderNumber LIMIT 500]; 

        for (Order orderRec: orderList) {
            Integer ctr = 0;
            Integer oiSize = (orderRec.OrderItems).size();
            CommonObjectWrapper.cls_SummarizedOrder sOrderWrapper = new CommonObjectWrapper.cls_SummarizedOrder();
            sOrderWrapper.sOrderNumber = orderRec.OrderNumber;
            sOrderWrapper.sOrderContactRefNo = orderRec.OrderedBy__r.ContactRefNo__c;
            sOrderWrapper.sOrderName = orderRec.OrderedBy__r.Name;
            sOrderWrapper.sOrderStreet1 = orderRec.ShippingAddress__r.Street1__c;
            sOrderWrapper.sOrderStreet2 = orderRec.ShippingAddress__r.Street2__c;
            sOrderWrapper.sOrderWard = orderRec.ShippingAddress__r.Ward2__r.Name;
            sOrderWrapper.sOrderDistrict = orderRec.ShippingAddress__r.District__r.Name;
            sOrderWrapper.sOrderCity = orderRec.ShippingAddress__r.City2__r.Name;
            sOrderWrapper.sOrderHomePhone = orderRec.OrderedBy__r.HomePhone;
            sOrderWrapper.sOrderMobile = orderRec.OrderedBy__r.Phone;
            sOrderWrapper.sOrderOtherPhone = orderRec.OrderedBy__r.OtherPhone;
            sOrderWrapper.sOrderRelatedCampaign = orderRec.RelatedCampaign__r.Name;
            sOrderWrapper.sOrderAmount = orderRec.TotalAmount;
            sOrderWrapper.sOrderStartDate = orderRec.EffectiveDate;
            sOrderWrapper.sOrderExportDate = orderRec.FileExportDate__c;
            sOrderWrapper.sOrderCreatedBy = orderRec.CreatedBy.Name;
            sOrderWrapper.sOrderNotes = orderRec.OrderNotes__c;
            sOrderWrapper.sOrderRegion = orderRec.ShippingAddress__r.Region__r.Name;
            sOrderWrapper.sOrderType = orderRec.Type;
            sOrderWrapper.sOrderStatus = orderRec.Status;
            sOrderWrapper.sOrderPaymentMethod = orderRec.PaymentMethod__c;
            sOrderWrapper.sOrderCaseNumber = orderRec.Case__r.CaseNumber;

            //Initialize value to not null
            sOrderWrapper.sOrderTotalQuantity = 0;
            sOrderWrapper.sOrderPromotion = '';
            sOrderWrapper.sOrderKeyBrand = '';
            sOrderWrapper.sOrderOrderedFor = '';
            sOrderWrapper.sOrderCategory = '';
            sOrderWrapper.sOrderProductNumber = '';
            sOrderWrapper.sOrderProductCode = '';
            sOrderWrapper.sOrderProductName = '';
            sOrderWrapper.sOrderUnitPrice = '';

            
            for(OrderItem oi : orderRec.OrderItems) {
                ctr++;
                String strDelimiter = '; ';
                
                /**
                if(orderRec.OrderItems.size() == 1) {
                    sOrderWrapper.sOrderProductNumber = oi.OrderItemNumber;
                    sOrderWrapper.sOrderProductCode = oi.PricebookEntry.ProductCode;
                    sOrderWrapper.sOrderTotalQuantity = oi.Quantity;
                    sOrderWrapper.sOrderProductName = Integer.valueOf(oi.Quantity) + ' ' + oi.PricebookEntry.Product2.Name;
                    sOrderWrapper.sOrderPromotion = oi.Promotion__r.Name;
                    sOrderWrapper.sOrderUnitPrice = String.valueOf(oi.UnitPrice);
                    sOrderWrapper.sOrderKeyBrand = oi.PricebookEntry.Product2.KeyBrand__c;
                    sOrderWrapper.sOrderOrderedFor = oi.OrderedFor__r.Name;
                    sOrderWrapper.sOrderCategory = oi.Category__c;
                }
                **/

                if(ctr == oiSize){
                    sOrderWrapper.sOrderPromotion = sOrderWrapper.sOrderPromotion + (oi.Promotion__r.Name == null ? '' : oi.Promotion__r.Name);
                    sOrderWrapper.sOrderKeyBrand = sOrderWrapper.sOrderKeyBrand + oi.PricebookEntry.Product2.KeyBrand__c;
                    sOrderWrapper.sOrderOrderedFor = sOrderWrapper.sOrderOrderedFor + (oi.OrderedFor__r.Name == null ? '' : oi.OrderedFor__r.Name);
                    sOrderWrapper.sOrderCategory = sOrderWrapper.sOrderCategory + (oi.Category__c == null ? '' : oi.Category__c);
                    sOrderWrapper.sOrderProductNumber = sOrderWrapper.sOrderProductNumber + oi.OrderItemNumber;
                    sOrderWrapper.sOrderProductCode = sOrderWrapper.sOrderProductCode + oi.PricebookEntry.ProductCode;
                    sOrderWrapper.sOrderTotalQuantity = sOrderWrapper.sOrderTotalQuantity + oi.Quantity;
                    sOrderWrapper.sOrderProductName = sOrderWrapper.sOrderProductName + Integer.valueOf(oi.Quantity) + ' ' + oi.PricebookEntry.Product2.Name;
                    sOrderWrapper.sOrderUnitPrice = sOrderWrapper.sOrderUnitPrice + oi.UnitPrice;
                }

                else if(ctr < oiSize) {
                    sOrderWrapper.sOrderPromotion = sOrderWrapper.sOrderPromotion + (oi.Promotion__r.Name == null ? '' : oi.Promotion__r.Name + strDelimiter);
                    sOrderWrapper.sOrderKeyBrand = sOrderWrapper.sOrderKeyBrand + oi.PricebookEntry.Product2.KeyBrand__c + strDelimiter;
                    sOrderWrapper.sOrderOrderedFor = sOrderWrapper.sOrderOrderedFor + (oi.OrderedFor__r.Name == null ? '' : oi.OrderedFor__r.Name + strDelimiter);
                    sOrderWrapper.sOrderCategory = sOrderWrapper.sOrderCategory + (oi.Category__c == null ? '' : oi.Category__c + strDelimiter);
                    sOrderWrapper.sOrderProductNumber = sOrderWrapper.sOrderProductNumber + oi.OrderItemNumber + strDelimiter;
                    sOrderWrapper.sOrderProductCode = sOrderWrapper.sOrderProductCode + oi.PricebookEntry.ProductCode + strDelimiter;
                    sOrderWrapper.sOrderTotalQuantity = sOrderWrapper.sOrderTotalQuantity + oi.Quantity;
                    sOrderWrapper.sOrderProductName = sOrderWrapper.sOrderProductName + Integer.valueOf(oi.Quantity) + ' ' + oi.PricebookEntry.Product2.Name + strDelimiter;
                    sOrderWrapper.sOrderUnitPrice = sOrderWrapper.sOrderUnitPrice + oi.UnitPrice + strDelimiter;
                }
            }

            combinedOrderList.add(sOrderWrapper);
        }
        return combinedOrderList;
    }

    @AuraEnabled 
    public static OrderReportWrapper getExcelFileAsBase64String() {
        PageReference excelPage = Page.SummarizedOrderExportReport;
        //excelPage.getParameters().put('cid',contactId);
        Blob excelBlob;
        if(System.Test.isRunningTest()) { 
          excelBlob = blob.valueOf('Unit.Test');
        } else {
          excelBlob = excelPage.getContent();
        }
        String base64Excel = EncodingUtil.base64Encode(excelBlob);
        User usr = [Select Id, Market__c from User where Id=: UserInfo.getUserId()];

        Datetime now = Datetime.now(); Integer offset = UserInfo.getTimezone().getOffset(now); 
        Datetime local = now.addSeconds(offset/1000);
        createFile('ExtractedOrderReport_' + usr.Market__c + '_' + local + '.xls', excelBlob, usr.Market__c);

        OrderReportWrapper result = new OrderReportWrapper();
        result.userMarket =  usr.Market__c;
        result.fileContent = base64Excel;
        return result;
    }  

    public static void createFile (String filename, Blob content, String market) {
        String libraryName = 'Order Export Library - ' + market;
        
        try { 
            ContentVersion cv = new ContentVersion();
            cv.ContentLocation = 'S';
            cv.VersionData = content;
            cv.Title = filename;
            cv.PathOnClient = filename;     
            insert cv;

            cv = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id LIMIT 1];
            
            if(System.Test.isRunningTest()) { 
                libraryName = 'Asset Library';
            }
            System.debug(libraryName);
            ContentWorkspace ws = [SELECT Id, RootContentFolderId FROM ContentWorkspace WHERE Name =: libraryName LIMIT 1];

            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = cv.ContentDocumentId;
            cdl.ShareType = 'I';
            cdl.Visibility = 'AllUsers';
            cdl.LinkedEntityId  = ws.Id;
            insert cdl;
           
            List<ContentFolderMember> memberFolder = new List<ContentFolderMember>();
            for (ContentFolderMember cfm : [SELECT Id, ChildRecordId, ParentContentFolderId
                                      FROM ContentFolderMember
                                      WHERE ChildRecordId = :cv.ContentDocumentId
                                      LIMIT 1]) {
                ContentFolderMember updatedCfm = new ContentFolderMember(Id = cfm.Id,
                                                                     ChildRecordId = cdl.ContentDocumentId,
                                                                     ParentContentFolderId = ws.RootContentFolderId);
                memberFolder.add(updatedCfm);

            }                          
            if (!memberFolder.isEmpty()) {
                update memberFolder;    
            }
            
            updateOrderStatus();
        } catch(QueryException qex) {
            throw new AuraHandledException('You have no access to the "' + libraryName + '" folder');      
        } catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
        
    }

    public static void updateOrderStatus() {
        List<Order> orderList = [Select Id, Status from Order where Status =: CommonConstant.ORDER_STATUS_SUBMITTED ORDER BY OrderNumber LIMIT 500];
        for(Order order : orderList) {
            order.Status = CommonConstant.ORDER_STATUS_TRANSFERRED;         
            order.Extracted__c = true;
            order.FileExportDate__c = Date.today();
        }

        update orderList;
    }

    public class OrderReportWrapper {
        @AuraEnabled
        public string userMarket { get; set; }
        @AuraEnabled
        public string fileContent { get; set; }
    }
}