force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City2__c.field-meta.xml
<CustomField>
    <fullName>City2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>City</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (City)</relationshipLabel>
    <relationshipName>AddressesCity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR 4 OR 5</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>District</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.ParentAffiliateValue__c</field>
            <operation>equals</operation>
            <valueField>$Source.City2__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (District)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/CallOutcome__c.field-meta.xml
<CustomField>
    <fullName>CallOutcome__c</fullName>
    <label>Call Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Uncontactable</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LatestCallOutcome__c.field-meta.xml
<CustomField>
    <fullName>LatestCallOutcome__c</fullName>
    <label>Previous Call Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Uncontactable</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Default_Address__c.field-meta.xml
<CustomField>
    <fullName>Default_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestCall__c.field-meta.xml
<CustomField>
    <fullName>LatestCall__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Call</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Latest Call</relationshipLabel>
    <relationshipName>LatestCall</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CaseFieldPatch.cls
// for deletion 1 time use
global class CaseFieldPatch {} /* Implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {        
        
        String query = 'SELECT ID , ContactId, City__c, District__c, LatestCallOutcome__c'                           
            + ' FROM Case where ContactId != null';
     
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Case> scope) {
      Set<Id> contactIds = new Set<Id>();
        for (Case c: scope) {            
            contactIds.add(c.ContactId);                           
        }
       
        Map<Id, Contact> contactMap = new Map<Id, Contact>([Select Id, Default_Address__r.City2__r.Name, Default_Address__r.District__r.Name, LatestCall__r.CallOutcome__c from Contact Where Id in: contactIds]);
        for (Case c: scope) { 
            Contact con = contactMap.get(c.ContactId);
            if (con != null) {
                if (con.Default_Address__c != null && con.Default_Address__r.City2__c != null)
                    c.City__c = con.Default_Address__r.City2__r.Name;
                
                if (con.Default_Address__c != null && con.Default_Address__r.District__c != null)
                    c.District__c = con.Default_Address__r.District__r.Name;

                if (con.LatestCall__c != null)
                    c.LatestCallOutcome__c = con.LatestCall__r.CallOutcome__c;
            }
        }

        Database.update(scope, false);
         
    }    
    
    global void finish(Database.BatchableContext BC) {
    }
} */