force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City2__c.field-meta.xml
<CustomField>
    <fullName>City2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>City</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (City)</relationshipLabel>
    <relationshipName>AddressesCity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>IF($UserRole.Name = &quot;ANI - Malaysia&quot;, &quot;Malaysia&quot;, 
    IF($UserRole.Name = &quot;ANI - Philippines&quot;, &quot;Philippines&quot;, 
    IF($UserRole.Name = &quot;ANI - Singapore&quot;, &quot;Singapore&quot;,
    IF($UserRole.Name = &quot;ANI - Thailand&quot;, &quot;Thailand&quot;,
    IF($UserRole.Name = &quot;ANI - Vietnam&quot;, &quot;Vietnam&quot;,
    IF($UserRole.Name = &quot;ANI - India&quot;, &quot;India&quot;,
    IF($UserRole.Name = &quot;ANI - ANZ&quot;, &quot;Australia&quot;,
    IF($UserRole.Name = &quot;ANI - Indonesia&quot;, &quot;Indonesia&quot;, 
    IF($UserRole.Name = &quot;ANI - Taiwan&quot;, &quot;Taiwan&quot;, &quot;&quot;)))))))))</defaultValue>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Saint Barthélemy</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Brunei Darussalam</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddressTriggerHandler.cls
/*------------------------------------------------------------
Author:      Viana Flor Mirandilla
Description: Handler class for Address object
                  - Auto-populates Parent Household derived from current Contact's Household value
History
01/18/2019   vmirandilla    Created
11/06/2020   malviz         Added updateProvince
-------------------------------------------------------------------------------------------*/

public class AddressTriggerHandler implements ITriggerHandler{
	
    public static boolean DoNotRunTest = false; //for AddressExternalReferenceBatchTest
    public void BeforeInsert(List<SObject> newList) {
        AddressTriggerHelper.getHousehold(newList);
        
        //filter PH Address
        List<Address__c> addressList = (List<Address__c>) newList;
        List<Address__c> addressPHList = new List<Address__c>();
        for(Address__c address: addressList ){
           If(address.Country__c == 'Philippines' && address.City2__c != null){
               addressPHList.add(address);
           }
       	}
        if(!addressPHList.isEmpty()) AddressTriggerHelper.updateProvince(addressPHList);
    }
    
    public void BeforeUpdate(List<SObject> newList, Map<Id, SObject> newMapItems, List<SObject> oldList, Map<Id, SObject> oldMapItems) { 
        AddressTriggerHelper.getHousehold(newList);
        
        //filter PH Address
        List<Address__c> addressList = (List<Address__c>) newList;
        List<Address__c> addressPHList = new List<Address__c>();
        for(Address__c address: addressList ){
           If(address.Country__c == 'Philippines' && address.City2__c != null){
               addressPHList.add(address);
           }
       	}
        if(!addressPHList.isEmpty()) AddressTriggerHelper.updateProvince(addressPHList);
    }
    
    public void BeforeDelete(List<SObject> oldList, Map<Id, SObject> oldItems){ 
       List<Address__c> oldAddress = (List<Address__c>) oldList;
       List<Address__c> addressToProcess = new List<Address__c>();
       
       for(Address__c address: oldAddress ){
           If(address.To_be_Archived__c == false){
               addressToProcess.add(address);
           }
       }
       
       if(!addressToProcess.isEmpty()) AddressTriggerHelper.checkDefaultAddress(addressToProcess, null);
    }
    
    public void AfterInsert(List<SObject> newList, Map<Id, SObject> newMapItems){ 
        AddressTriggerHelper.checkDefaultAddress(newList, null);
        if(!DoNotRunTest){
            AddressTriggerHelper.checkExternalId(newList, null);   
        }
    }
    
    public void AfterUpdate(List<SObject> newList , Map<Id, SObject> newMapItems, List<SObject> oldList, Map<Id, SObject> oldMapItems){ 
        AddressTriggerHelper.checkDefaultAddress(newList, oldMapItems);
    }
    
    public void AfterDelete(List<SObject> oldList, Map<Id, SObject> oldMapItems){ }
}