force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City2__c.field-meta.xml
<CustomField>
    <fullName>City2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>City</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (City)</relationshipLabel>
    <relationshipName>AddressesCity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR 4 OR 5</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>District</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.ParentAffiliateValue__c</field>
            <operation>equals</operation>
            <valueField>$Source.City2__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (District)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Region</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/SubDistrict__c.field-meta.xml
<CustomField>
    <fullName>SubDistrict__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub-District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub-District</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.ParentAffiliateValue__c</field>
            <operation>equals</operation>
            <valueField>$Source.District__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (Sub-District)</relationshipLabel>
    <relationshipName>Addresses2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Ward2__c.field-meta.xml
<CustomField>
    <fullName>Ward2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ward</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR 4 OR 5</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Ward</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.ParentAffiliateValue__c</field>
            <operation>equals</operation>
            <valueField>$Source.District__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (Ward)</relationshipLabel>
    <relationshipName>AddressesWard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/City.recordType-meta.xml
<RecordType>
    <fullName>City</fullName>
    <active>true</active>
    <description>Defines cities within a given market, to be selected during address creation and updates for a contact</description>
    <label>City</label>
</RecordType>

force-app/main/default/objects/AuthenticationToken__mdt/AuthenticationToken__mdt.object-meta.xml
<CustomObject>
    <label>Authentication Token</label>
    <pluralLabel>Authentication Tokens</pluralLabel>
</CustomObject>

force-app/main/default/classes/AddressFormController.cls
/*----------------------------------------------------------------------------------------
Author:      Viana Flor Mirandilla
Description: Controller for AddressForm Lightning Component

History
08/02/2019   vmirandilla   Created
-------------------------------------------------------------------------------------------*/
public class AddressFormController {
    /**
    * Get login User details
    **/
    @AuraEnabled
    public static User fetchUserDetails() {
		User currentUser = [SELECT Id, Market__c FROM User WHERE Id =: userInfo.getUserId()];
		return currentUser;
    }

    /**
    * Get Address details (text fields) by making an API Call
    **/
    @AuraEnabled
    public static CommonObjectWrapper.cls_ExperianAddress getAddressDetails(String postalCode, String unitNumber) {
		HttpResponse formatResponse =  ExperianCallout.getInfoFromExternalService(postalCode, unitNumber);
        CommonObjectWrapper.cls_ExperianAddress expAddress = ExperianResponseProcessor.processReponse(formatResponse);
        return expAddress;
    }
    
    /**
    * Identify if user has access to a record
    **/
    @AuraEnabled
    public static Boolean getRecordAccess(String addressId) {
		UserRecordAccess userAccess = [SELECT RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId = :userInfo.getUserId() AND RecordId = :addressId];
        return userAccess.HasEditAccess;
    }

    /**
    * Get Experian token
    **/
    @AuraEnabled
    public static String getExperianToken() {
		String token = [SELECT MasterLabel, DeveloperName, Token__c FROM AuthenticationToken__mdt WHERE DeveloperName = 'Experian_Token'].Token__c; 
        return token;
    }
    
    /**
    * Get Singapore City Affiliate Value
    **/
    @AuraEnabled
    public static String getAffiliateSingaporeCity() {
		Id singaporeId = [SELECT Id FROM Affiliate_Value__c WHERE RecordType.Name = :CommonConstant.AFFILIATE_CITY_RECORDTYPE AND Active__c = TRUE AND Name = 'Singapore' AND Market__c = :CommonConstant.MARKET_SG].Id; 
        return singaporeId;
    }
    
    /**
    * Get Address Details
    **/
    @AuraEnabled
    public static Address__c getAddressRecordDetails(String addressId) {
		Address__c addressRecord = [SELECT Id, Region__c, City2__c, District__c, SubDistrict__c, Ward2__c FROM Address__c WHERE Id =: addressId]; 
        return addressRecord;
    }
}