force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/City.recordType-meta.xml
<RecordType>
    <fullName>City</fullName>
    <active>true</active>
    <description>Defines cities within a given market, to be selected during address creation and updates for a contact</description>
    <label>City</label>
</RecordType>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/District.recordType-meta.xml
<RecordType>
    <fullName>District</fullName>
    <active>true</active>
    <description>Defines the districts within a given market (usually defined by city), used during address creation and updates for a contact</description>
    <label>District</label>
</RecordType>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <label>Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ExpiredPoints__c.field-meta.xml
<CustomField>
    <fullName>ExpiredPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Expired Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LifetimePoints__c.field-meta.xml
<CustomField>
    <fullName>LifetimePoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lifetime Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Monthly_Earned_Points__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Earned_Points__c</fullName>
    <formula>LifetimePoints__c -  Start_Earn_Points__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Earned Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Monthly_Expired_Points__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Expired_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Expired Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Monthly_Redeemed_Points__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Redeemed_Points__c</fullName>
    <formula>TotalPointsRedeemed__c - Start_Redeem_Points__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Redeemed Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Start_Earn_Points__c.field-meta.xml
<CustomField>
    <fullName>Start_Earn_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Start Earn Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Start_Redeem_Points__c.field-meta.xml
<CustomField>
    <fullName>Start_Redeem_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Start Redeem Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TotalPointsRedeemed__c.field-meta.xml
<CustomField>
    <fullName>TotalPointsRedeemed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Points Redeemed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactLoyaltyIntegrationBatchTest.cls
@isTest
private class ContactLoyaltyIntegrationBatchTest {
    @testsetup
    static void setupData() {
        Account acc = TestDataFactory.createTestHouseholdSG(1)[0];
        Contact con = TestDataFactory.createTestAdultContactSGPoints(1, acc.Id, 100, 50, 10, 5, 30)[0];
        Affiliate_Value__c city = TestDataFactory.createAffiliateValue('City', 'TEST_CITY', 'SG', null);
        Affiliate_Value__c district = TestDataFactory.createAffiliateValue('District', 'TEST_DISTRICT', 'SG', city.Id);
        String streetName = 'TEST_STREET';
		Address__c address = TestDataFactory.createAddress(true, con.Id, 'Singapore', city.Id, district.Id, null, streetName);
        PricebookEntry pbe = TestDataFactory.createPricebookEntry('SG', 'SGD');
        Product2 p = [SELECT Id FROM Product2 WHERE Id =: pbe.Product2Id];
        BrandRelationship__c br = TestDataFactory.createTestBrandRelationShip(1, con.Id, p.Id)[0];
        Channel__c channel = TestDataFactory.createTestChannel(1, 'SG', 'Abbott Family Rewards SG')[0];
        List<ChannelResponse__c> crList = TestDataFactory.createTestChannelResponseMultiple(5, br, channel, address, p, false, 'Pending');
        System.debug(crList[0].Channel__r.Name);
    }
    
    @isTest
    static void sgLoyaltyMonthly() {
        System.Test.startTest();
        
        ContactLoyaltyIntegrationMonthlyBatch ucs = new ContactLoyaltyIntegrationMonthlyBatch();
        Database.executeBatch(ucs, 200);
        
        ContactLoyaltyIntegrationSchedulable job = new ContactLoyaltyIntegrationSchedulable();
        String sch = '0 30 6 1 * ?';
        System.schedule('Monthly Batch Job', sch, job);
        
        System.Test.stopTest();            
        
        Contact con = [SELECT Id, LifetimePoints__c, Start_Earn_Points__c, Start_Redeem_Points__c, TotalPointsRedeemed__c, Monthly_Expired_Points__c, Monthly_Earned_Points__c, Monthly_Redeemed_Points__c FROM Contact][0];
        System.assertEquals(con.Start_Earn_Points__c, con.LifetimePoints__c, 'not same earned points'); 
        System.assertEquals(con.Start_Redeem_Points__c, con.TotalPointsRedeemed__c, 'not same redeemed points'); 
        System.assertEquals(con.Monthly_Expired_Points__c, 0);
        System.assertEquals(con.Monthly_Earned_Points__c, 0);
        //System.assertEquals(con.Monthly_Redeemed_Points__c, 0);
    }
    
    @isTest
    static void sgLoyaltyDaily() {
        Contact con = [SELECT Id, ExpiredPoints__c, Monthly_Expired_Points__c FROM Contact][0];
        con.ExpiredPoints__c = 20;
        update con;
        
        System.Test.startTest();
        
        ContactLoyaltyIntegrationDailyBatch ucs = new ContactLoyaltyIntegrationDailyBatch();
        Database.executeBatch(ucs, 200);
        
        ContactLoyaltyIntegrationDailyBatch job = new ContactLoyaltyIntegrationDailyBatch();
        String sch = '0 30 7 * * ?'; 
        System.schedule('Daily Batch Job', sch, job);
        
        System.Test.stopTest();            
        
        Contact conUpdated = [SELECT Id, ExpiredPoints__c, Monthly_Expired_Points__c FROM Contact WHERE Id =: con.Id];
        System.assertEquals(conUpdated.Monthly_Expired_Points__c, 50, 'not same earned points'); 
    }
}