force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/AddressValidationStatus__c.field-meta.xml
<CustomField>
    <fullName>AddressValidationStatus__c</fullName>
    <label>Address Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Valid Address</fullName>
            </value>
            <value>
                <fullName>Invalid Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/City2__c.field-meta.xml
<CustomField>
    <fullName>City2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>City</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>City</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (City)</relationshipLabel>
    <relationshipName>AddressesCity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR 4 OR 5</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>District</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.ParentAffiliateValue__c</field>
            <operation>equals</operation>
            <valueField>$Source.City2__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (District)</relationshipLabel>
    <relationshipName>Addresses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/FullAddress__c.field-meta.xml
<CustomField>
    <fullName>FullAddress__c</fullName>
    <formula>IF(TEXT(Country__c) != &apos;Philippines&apos;,(
IF(LEN(Street1__c)&gt;0, Street1__c&amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(TEXT(Country__c) != &apos;Singapore&apos; &amp;&amp; LEN(Building__c)&gt;0, Building__c&amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(Street2__c)&gt;0, Street2__c&amp; &quot;, &quot;  &amp;  BR(), &quot;&quot; )&amp;
IF(TEXT(Country__c) == &apos;Singapore&apos; &amp;&amp; LEN(UnitNumber__c)&gt;0 &amp;&amp; LEN(Building__c)&gt;0, UnitNumber__c&amp; &quot; &quot; &amp; Building__c&amp;&quot;, &quot; , &quot;&quot; )&amp;
IF(TEXT(Country__c) == &apos;Singapore&apos; &amp;&amp; LEN(UnitNumber__c)&gt;0 &amp;&amp; LEN(Building__c)==0, UnitNumber__c&amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(TEXT(Country__c) == &apos;Singapore&apos; &amp;&amp; LEN(UnitNumber__c)==0 &amp;&amp; LEN(Building__c)&gt;0, Building__c&amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(VillageNo__c)&gt;0, VillageNo__c &amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(VillageName__c)&gt;0, VillageName__c &amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(StateProvince__c)&gt;0, StateProvince__c&amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(SuburbTown__c)&gt;0, SuburbTown__r.Name&amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(State__c)&gt;0, State__r.Name&amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(Ward2__c)&gt;0, Ward2__r.Name &amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(Road__c)&gt;0, Road__c&amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(SubDistrict__c)&gt;0, SubDistrict__r.Name&amp; &quot;, &quot; &amp;  BR(), &quot;&quot; )&amp;
IF(LEN(District__c)&gt;0, District__r.Name &amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(City2__c)&gt;0, City2__r.Name &amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(PostalCode__c)&gt;0, PostalCode__c&amp; &quot;, &quot; &amp; BR(), &quot;&quot; )&amp;
IF(LEN(TEXT(Country__c)) &gt;0, TEXT(Country__c)&amp; &quot; &quot; , &quot;&quot; )),

(IF(LEN(Street1__c)&gt;0, Street1__c&amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(Street2__c)&gt;0, Street2__c&amp; &quot;, &quot;  &amp;  BR(), &quot;&quot; )&amp;
IF(LEN(City2__c)&gt;0, City2__r.Name &amp; &quot;, &quot; , &quot;&quot; )&amp;
IF(LEN(StateProvince__c)&gt;0, StateProvince__c&amp; &quot;, &quot;  &amp; BR(), &quot;&quot; )&amp;
IF(LEN(TEXT(Country__c)) &gt;0, TEXT(Country__c)&amp; &quot; , &quot; , &quot;&quot; ) &amp;
IF(LEN(PostalCode__c)&gt;0, PostalCode__c , &quot;&quot; )))</formula>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street1__c.field-meta.xml
<CustomField>
    <fullName>Street1__c</fullName>
    <label>Street 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street2__c.field-meta.xml
<CustomField>
    <fullName>Street2__c</fullName>
    <label>Street 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/SubDistrict__c.field-meta.xml
<CustomField>
    <fullName>SubDistrict__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub-District</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub-District</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.ParentAffiliateValue__c</field>
            <operation>equals</operation>
            <valueField>$Source.District__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (Sub-District)</relationshipLabel>
    <relationshipName>Addresses2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/VillageName__c.field-meta.xml
<CustomField>
    <fullName>VillageName__c</fullName>
    <label>Village Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/VillageNo__c.field-meta.xml
<CustomField>
    <fullName>VillageNo__c</fullName>
    <label>Village No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Ward2__c.field-meta.xml
<CustomField>
    <fullName>Ward2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ward</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR 4 OR 5</booleanFilter>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Ward</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.ParentAffiliateValue__c</field>
            <operation>equals</operation>
            <valueField>$Source.District__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses (Ward)</relationshipLabel>
    <relationshipName>AddressesWard</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ContactRefNo__c.field-meta.xml
<CustomField>
    <fullName>ContactRefNo__c</fullName>
    <formula>Market__c &amp; &quot;-C-&quot; &amp;  AutoNumber__c</formula>
    <label>Contact Ref No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FullAddress__c.field-meta.xml
<CustomField>
    <fullName>FullAddress__c</fullName>
    <formula>Default_Address__r.FullAddress__c</formula>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/Order/fields/OrderedBy__c.field-meta.xml
<CustomField>
    <fullName>OrderedBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordered By</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Adult</value>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippingAddress__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddress__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/OrderedFor__c.field-meta.xml
<CustomField>
    <fullName>OrderedFor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordered For</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AgeinMonths__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>$Source.Product_Min_Birth_Month__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.AgeinMonths__c</field>
            <operation>lessOrEqual</operation>
            <valueField>$Source.Product_Max_Birth_Month__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderReportCSVGenerator.cls
public with sharing class OrderReportCSVGenerator {
    public static String generateCSV(List<OrderItem> itemList) {
        String generatedCSVFile ='';
        generatedCSVFile = genereateHeader().removeEnd(',') + '\n';
        String fileRow = '';
        for (OrderItem orderItem : itemList) {
            fileRow = '';
            fileRow = orderItem.Order.OrderNumber;
            fileRow = fileRow +','+ orderItem.Order.OrderedBy__r.ContactRefNo__c;
            fileRow = fileRow +','+ orderItem.Order.OrderedBy__r.Name;
            fileRow = fileRow +','+ orderItem.OrderedFor__r.Name;
            fileRow = fileRow +','+ orderItem.Order.ShippingAddress__r.AddressValidationStatus__c;
            fileRow = fileRow +','+ formatString(orderItem.Order.ShippingAddress__r.FullAddress__c);
            fileRow = fileRow +','+ forceString( orderItem.Order.ShippingAddress__r.Street1__c);
            fileRow = fileRow +','+ forceString( orderItem.Order.ShippingAddress__r.Street2__c );
            fileRow = fileRow +','+ forceString(orderItem.Order.ShippingAddress__r.UnitNumber__c);
            fileRow = fileRow +','+ orderItem.Order.ShippingAddress__r.City2__r.Name;
            fileRow = fileRow +','+ forceString( orderItem.Order.ShippingAddress__r.Building__c );
            fileRow = fileRow +','+ formatString( orderItem.Order.ShippingAddress__r.District__r.Name);
            fileRow = fileRow +','+ formatString( orderItem.Order.ShippingAddress__r.SubDistrict__r.Name );
            fileRow = fileRow +','+ forceString( orderItem.Order.ShippingAddress__r.VillageNo__c );
            fileRow = fileRow +','+ formatString( orderItem.Order.ShippingAddress__r.VillageName__c );
            fileRow = fileRow +','+ formatString( orderItem.Order.ShippingAddress__r.Ward2__r.Name );
            fileRow = fileRow +','+ formatString( orderItem.Order.ShippingAddress__r.Road__c );
            fileRow = fileRow +','+ formatString( orderItem.Order.ShippingAddress__r.PostalCode__c );
            fileRow = fileRow +','+ forceString( orderItem.Order.OrderedBy__r.HomePhone );
            fileRow = fileRow +','+ forceString( orderItem.Order.OrderedBy__r.Phone );
            fileRow = fileRow +','+ forceString( orderItem.Order.OrderedBy__r.OtherPhone );
            fileRow = fileRow +','+ formatString( orderItem.Order.RelatedCampaign__r.Name );
            fileRow = fileRow +','+ forceString( orderItem.OrderItemNumber );
            fileRow = fileRow +','+ orderItem.PricebookEntry.ProductCode;
            fileRow = fileRow +','+ orderItem.Quantity;
            fileRow = fileRow +','+ orderItem.PricebookEntry.Product2.Name;
            fileRow = fileRow +','+ orderItem.Promotion__r.Name;
            fileRow = fileRow +','+ orderItem.UnitPriceExclGst__c;
            fileRow = fileRow +','+ orderItem.TotalPriceExclGst__c;
            fileRow = fileRow +','+ orderItem.Order.TotalAmountExclGst__c;
            fileRow = fileRow +','+ (orderItem.Order.PreferredDeliveryDate__c == null ? '' : formatCSVDate( orderItem.Order.PreferredDeliveryDate__c) );
            fileRow = fileRow +','+ orderItem.Order.PreferredDeliveryTime__c;
            fileRow = fileRow +','+ (orderItem.Order.EffectiveDate == null ? '' : formatCSVDate( orderItem.Order.EffectiveDate));            
            fileRow = fileRow +','+ formatCSVDate(Date.today());
            fileRow = fileRow +','+ orderItem.Order.CreatedBy.Name;
            fileRow = fileRow +','+ orderItem.PricebookEntry.Product2.KeyBrand__c;
            fileRow = fileRow +','+ (String.isEmpty(orderItem.Order.OrderNotes__c) ? '' : orderItem.Order.OrderNotes__c.replace('\r','').replace('\n', ' ').escapeCsv());
            fileRow = fileRow +','+ orderItem.Order.ShippingAddress__r.Region__r.Name;
            fileRow = fileRow +','+ orderItem.Order.Type;
            fileRow = fileRow +','+ orderItem.Status__c;
            fileRow = fileRow +','+ orderItem.Id;
            fileRow = fileRow +','+ orderItem.Order.Status;
            fileRow = fileRow +','+ orderItem.Order.OrderCacellationReason__r.Name;
            fileRow = fileRow +',';
            fileRow = fileRow +','+ orderItem.Order.PaymentMethod__c;
            fileRow = fileRow +','+ orderItem.Order.Case__r.CaseNumber;
            fileRow = fileRow +','+ orderItem.OrderId;

            generatedCSVFile = generatedCSVFile + fileRow.replace('null', '') + '\n';
        }
        return generatedCSVFile = '\uFEFF' + generatedCSVFile.removeEnd('\n');
    }

    public static String formatCSVDate(date value) {
        String result;
        result = String.valueOf( value.day() ).length() == 1 ? '0' + value.day() :  String.valueOf( value.day() );
        result = String.valueOf( value.month() ).length() == 1 ? result + '/0' + value.month() : result + '/' + value.month();
        result = result + '/' + String.valueOf( value.year() );
        return result;
    }

    public static String formatString(String value) {
        return String.isEmpty(value) ? '' : value.replace('\r','').replace('\n', ' ').replace('<br>', ' ').escapeCsv();
    }

    public static String forceString(String value) {
        String result = '';
        if (!String.isEmpty(value) && value.contains(','))   {
            result =  value.replace('\r','').replace('\n', ' ').replace('<br>', ' ').escapeCsv();
        } else if (!String.isEmpty(value)){
            result = '\'' + value.replace('\r','').replace('\n', ' ').replace('<br>', ' ').escapeCsv();
        }  
        return result;
    }

    public static String genereateHeader() {
        List<String> headerArray = new List<String>();
        headerArray.add('Order Number');
        headerArray.add('Contact Ref No');
        headerArray.add('Name');
        headerArray.add('Related Contact/Child');
        headerArray.add('Address Validation Status');
        headerArray.add('Full Address');
        headerArray.add('Street 1');
        headerArray.add('Street 2');
        headerArray.add('Unit Number');
        headerArray.add('City');
        headerArray.add('Building');
        headerArray.add('District');
        headerArray.add('Sub-District');
        headerArray.add('Village No');
        headerArray.add('Village Name');
        headerArray.add('Ward');
        headerArray.add('Road');
        headerArray.add('Postal Code');
        headerArray.add('Home Phone');
        headerArray.add('Mobile');
        headerArray.add('Other Phone');
        headerArray.add('Related Campaign');
        headerArray.add('Order Product Number');
        headerArray.add('Product Code');
        headerArray.add('Quantity');
        headerArray.add('Product Name');
        headerArray.add('Promotion');
        headerArray.add('Unit Price');
        headerArray.add('Order Amount');
        headerArray.add('Total Price');
        headerArray.add('Preferred Delivery Date');
        headerArray.add('Preferred Delivery Time');
        headerArray.add('Order Start Date');
        headerArray.add('File Export Date');
        headerArray.add('Created By');
        headerArray.add('Key Brand');
        headerArray.add('Order Notes');
        headerArray.add('Region');
        headerArray.add('Order Type');
        headerArray.add('Order Product Status');
        headerArray.add('Order Product Id');
        headerArray.add('Status');
        headerArray.add('Cancellation Reason');
        headerArray.add('Order End Date');
        headerArray.add('Payment Method');
        headerArray.add('Case Number');
        headerArray.add('Salesforce Id');


        return string.join(headerArray, ',');
    }

}