force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/AddressValidationStatus__c.field-meta.xml
<CustomField>
    <fullName>AddressValidationStatus__c</fullName>
    <label>Address Validation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Valid Address</fullName>
            </value>
            <value>
                <fullName>Invalid Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>IF($UserRole.Name = &quot;ANI - Malaysia&quot;, &quot;Malaysia&quot;, 
    IF($UserRole.Name = &quot;ANI - Philippines&quot;, &quot;Philippines&quot;, 
    IF($UserRole.Name = &quot;ANI - Singapore&quot;, &quot;Singapore&quot;,
    IF($UserRole.Name = &quot;ANI - Thailand&quot;, &quot;Thailand&quot;,
    IF($UserRole.Name = &quot;ANI - Vietnam&quot;, &quot;Vietnam&quot;,
    IF($UserRole.Name = &quot;ANI - India&quot;, &quot;India&quot;,
    IF($UserRole.Name = &quot;ANI - ANZ&quot;, &quot;Australia&quot;,
    IF($UserRole.Name = &quot;ANI - Indonesia&quot;, &quot;Indonesia&quot;, 
    IF($UserRole.Name = &quot;ANI - Taiwan&quot;, &quot;Taiwan&quot;, &quot;&quot;)))))))))</defaultValue>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Saint Barthélemy</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Brunei Darussalam</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/ParentContact__c.field-meta.xml
<CustomField>
    <fullName>ParentContact__c</fullName>
    <label>Parent Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/StateProvince__c.field-meta.xml
<CustomField>
    <fullName>StateProvince__c</fullName>
    <label>State / Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street1__c.field-meta.xml
<CustomField>
    <fullName>Street1__c</fullName>
    <label>Street 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Street2__c.field-meta.xml
<CustomField>
    <fullName>Street2__c</fullName>
    <label>Street 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuthenticationToken__mdt/AuthenticationToken__mdt.object-meta.xml
<CustomObject>
    <label>Authentication Token</label>
    <pluralLabel>Authentication Tokens</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExperianAddressValidationBatch.cls
/*------------------------------------------------------------
Author:      Viana Flor Mirandilla
Description: This batch will validate with Experian if the Address record created from Heroku are valid or not

History
07/31/2019   vmirandilla   Created
04/14/2021   malviz        TKT-003976: added unit number checking
09/07/2021   malviz        TKT-004526: remove # on unit number search
04/06/2022	 fgomendoza	   optimized query
-------------------------------------------------------------------------------------------*/

global class ExperianAddressValidationBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Id userId = [SELECT Id FROM User WHERE Name = 'Data Integration' AND IsActive = true][0].Id;
        String query = 'SELECT Id'
            + ' FROM Address__c WHERE ParentContact__r.Market__c = \'' + CommonConstant.MARKET_SG + '\''
            + ' AND Country__c = \'Singapore\''
            + ' AND AddressValidationStatus__c = \'' + CommonConstant.ADDRESS_VALIDATION_PENDING + '\''
            + ' AND CreatedById =: userId';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Address__c> scope) {
        List<Address__c> execAddressList = [SELECT Id, Street1__c, Street2__c, UnitNumber__c, Building__c, StateProvince__c, PostalCode__c, ParentContact__r.Market__c, 
                                            AddressValidationStatus__c, CreatedById, CreatedBy.Name FROM Address__c WHERE Id IN: scope AND PostalCode__c != null AND PostalCode__c != ''];
        
        if(!execAddressList.isEmpty()){
            String token = [SELECT MasterLabel, DeveloperName, Token__c FROM AuthenticationToken__mdt WHERE DeveloperName = 'Experian_Token'].Token__c;
            List<Address__c> addressList = new List<Address__c>();
            for(Address__c address : execAddressList) {
                String postalCode = address.PostalCode__c;
                String unitNumber = address.UnitNumber__c;
                
                //remove if unit number contains #
                if(unitnumber != null && unitnumber != ''){
                    if(unitNumber.contains('#')){
                        unitnumber = unitnumber.replace('#','');        
                    }
                }
                
                if(!System.Test.isRunningTest() && token != null) {
                    HttpResponse formatResponse;
                    formatResponse =  ExperianCallout.getInfoFromExternalService(postalCode, unitNumber);
                    
                    if (formatResponse != null) {
                        CommonObjectWrapper.cls_ExperianAddress expAddress = ExperianResponseProcessor.processReponse(formatResponse);            
                        
                        if(expAddress != null) {
                            if(unitNumber != null && unitNumber != ''){
                                if((expAddress.expPostCode == address.PostalCode__c) && (expAddress.expSubBuilding == unitnumber)) {
                                    address.AddressValidationStatus__c = CommonConstant.ADDRESS_VALIDATION_VALID;
                                    
                                    if( (address.Street1__c == '' || address.Street1__c == null) && (address.Street2__c == '' || address.Street2__c == null)){
                                        address.Street1__c = expAddress.expStreet1;
                                    }
                                } else {
                                    address.AddressValidationStatus__c = CommonConstant.ADDRESS_VALIDATION_INVALID;
                                }
                            }
                            else{
                                if(expAddress.expPostCode == address.PostalCode__c) {
                                    address.AddressValidationStatus__c = CommonConstant.ADDRESS_VALIDATION_VALID;
                                    
                                    if( (address.Street1__c == '' || address.Street1__c == null) && (address.Street2__c == '' || address.Street2__c == null)){
                                        address.Street1__c = expAddress.expStreet1;
                                    }
                                } else {
                                    address.AddressValidationStatus__c = CommonConstant.ADDRESS_VALIDATION_INVALID;
                                }
                            }  
                        } 
                    } else {
                        address.AddressValidationStatus__c = CommonConstant.ADDRESS_VALIDATION_INVALID;
                    }
                    addressList.add(address);
                }
            } 
            
            if(!addressList.isEmpty()) {
                Database.update(addressList, false);
            }
        }
        
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}