force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <defaultValue>IF($UserRole.Name = &quot;ANI - Malaysia&quot;, &quot;Malaysia&quot;, 
    IF($UserRole.Name = &quot;ANI - Philippines&quot;, &quot;Philippines&quot;, 
    IF($UserRole.Name = &quot;ANI - Singapore&quot;, &quot;Singapore&quot;,
    IF($UserRole.Name = &quot;ANI - Thailand&quot;, &quot;Thailand&quot;,
    IF($UserRole.Name = &quot;ANI - Vietnam&quot;, &quot;Vietnam&quot;,
    IF($UserRole.Name = &quot;ANI - India&quot;, &quot;India&quot;,
    IF($UserRole.Name = &quot;ANI - ANZ&quot;, &quot;Australia&quot;,
    IF($UserRole.Name = &quot;ANI - Indonesia&quot;, &quot;Indonesia&quot;, 
    IF($UserRole.Name = &quot;ANI - Taiwan&quot;, &quot;Taiwan&quot;, &quot;&quot;)))))))))</defaultValue>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Saint Barthélemy</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Brunei Darussalam</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/External_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>External_Reference_Number__c</fullName>
    <externalId>true</externalId>
    <label>External Reference Number</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AddressExternalReferenceBatch.cls
global class AddressExternalReferenceBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
	String market;
    Integer startRange;
    Integer endRange;
    
    global AddressExternalReferenceBatch (String inputMarket, Integer inputStartRange, Integer inputEndRange){
        if(!String.isBlank(inputMarket)) market = inputMarket;
        if(inputStartRange != null) startRange = inputStartRange;
        if(inputEndRange != null) endRange = inputEndRange;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, External_Reference_Number__c'
            + ' FROM Address__c'
            + ' WHERE External_Reference_Number__c = null';   
        if(!String.isBlank(market)){
            query += ' AND Country__c = \'' + market + '\'';
        }
        if(endRange != null && startRange != null){
            query += ' AND (CreatedDate >= LAST_N_DAYS: ' + endRange
                + ' AND CreatedDate <= LAST_N_DAYS: ' + startRange +') ';
        }
        else {
            if(endRange != null){
                query += ' AND (CreatedDate >= LAST_N_DAYS: ' + endRange +') ';
            }
            else if(startRange != null){
                query += ' AND (CreatedDate <= LAST_N_DAYS: ' + startRange +') ';
            }
        }
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Address__c> scope) {
        List<Address__c> addressUpdateList = new List<Address__c>();
        System.debug(scope);
        if(!scope.isEmpty()){
            for(Address__c addr : scope){
                Blob requestBlob = Blob.valueOf(addr.Id);
                Blob hash = Crypto.generateDigest('MD5', requestBlob);
                String requestSignature = EncodingUtil.convertToHex(hash);
                addr.External_Reference_Number__c = 'SFMD5-'+requestSignature;
                addressUpdateList.add(addr);
            }
            System.debug('FGG');
            if(!addressUpdateList.isEmpty()) UtilityClass.updateList(addressUpdateList);
            System.debug('FGG');
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :BC.getJobId()]; 
        System.debug('>>>> finish ' + job.Status);
    }
    
    global void execute(SchedulableContext sc) {
        AddressExternalReferenceBatch batch = new AddressExternalReferenceBatch('Taiwan', null, null); 
        Database.executebatch(batch, 100);
    }

}