force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/ParentContact__c.field-meta.xml
<CustomField>
    <fullName>ParentContact__c</fullName>
    <label>Parent Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Region</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/Region.recordType-meta.xml
<RecordType>
    <fullName>Region</fullName>
    <active>true</active>
    <description>Defines the geographical regions within a given market used during address creation and updates for a contact</description>
    <label>Region</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Region</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Contacts (Region)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/classes/AddressBatchProcessTest.cls
// @isTest  for deletion
public class AddressBatchProcessTest{} /*

    @testsetup
    static void setupData() {
        List<Account> lAccount = TestDataFactory.createTestHousehold(1);    

        //Create Primary Adult Contact
        List<Contact> lPrimaryContact = TestDataFactory.createTestAdultContact(1, lAccount.get(0).Id);

        //Create Address
        List<Affiliate_Value__c> lRegion = TestDataFactory.createTestRegion(1);
        List<Affiliate_Value__c> lCity = TestDataFactory.createTestCity(1);
        List<Address__c> lAddress = TestDataFactory.createTestDefaultAddress(1, lPrimaryContact.get(0).Id, lRegion.get(0).Id, lCity.get(0).Id);

        lPrimaryContact[0].Region__c = null;
        update lPrimaryContact[0];
    }

    public static testMethod  void testBatchJob() {
        List<Contact> lContactBeforeUpdate = [SELECT Id, Region__c FROM Contact LIMIT 1];
        List<Address__c> lAddress = [SELECT Id, ParentContact__c, Region__c FROM Address__c LIMIT 1];

        System.Test.startTest();
            AddressBatchProcess abp = new AddressBatchProcess();
            Database.executeBatch(abp, 200);
        System.Test.stopTest();

        List<Contact> lContactAfterUpdate = [SELECT Id, Region__c FROM Contact LIMIT 1];
        System.assertEquals(null, lContactBeforeUpdate[0].Region__c, 'Contact\'s Region is not populated');
        System.assertEquals(lAddress[0].Region__c, lContactAfterUpdate[0].Region__c, 'Contact\'s Region should be populated with the Default Address Region');
    }
} */