force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/DefaultAddress__c.field-meta.xml
<CustomField>
    <fullName>DefaultAddress__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Default Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ParentContact__c.field-meta.xml
<CustomField>
    <fullName>ParentContact__c</fullName>
    <label>Parent Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case/fields/CallOutcome__c.field-meta.xml
<CustomField>
    <fullName>CallOutcome__c</fullName>
    <label>Call Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Uncontactable</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/LatestCallOutcome__c.field-meta.xml
<CustomField>
    <fullName>LatestCallOutcome__c</fullName>
    <label>Previous Call Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Uncontactable</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Default_Address__c.field-meta.xml
<CustomField>
    <fullName>Default_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EstimatedDueDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDueDate__c</fullName>
    <label>Estimated Due Date (EDD)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Initial_Estimated_Due_Date_IEDD__c.field-meta.xml
<CustomField>
    <fullName>Initial_Estimated_Due_Date_IEDD__c</fullName>
    <label>Initial Estimated Due Date (IEDD)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Latest_Call_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Latest_Call_Outcome__c</fullName>
    <label>Latest Call Outcome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestCall2__c.field-meta.xml
<CustomField>
    <fullName>LatestCall2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Call (Technical)</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Contacts (Latest Call)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactCleanUp.cls
// for deletion
public class ContactCleanUp {} /* implements Database.Batchable<sObject>, Database.Stateful {
    
    public Database.QueryLocator start(Database.BatchableContext BC){

        String queryStr = 'SELECT EstimatedDueDate__c,'
                                + ' (SELECT Id FROM Addresses__r WHERE DefaultAddress__c = true LIMIT 1),'
                                + ' (SELECT CallOutcome__c FROM Cases WHERE RecordType.Name = \'Call\' Order By CaseNumber)'
                         + ' FROM Contact';
        if(Test.isRunningTest()){
            queryStr = 'SELECT Id, EstimatedDueDate__c,(SELECT CallOutcome__c FROM Cases Order By CaseNumber), (SELECT Id FROM Addresses__r WHERE DefaultAddress__c = true LIMIT 1) FROM Contact';
        }
        return Database.getQueryLocator(queryStr);
    }

    public void execute(Database.BatchableContext BC, List<Contact> contactList){
        List<Contact> conUpdate = new List<Contact>();
        List<Case> caseUpdate = new List<Case>();

        for(Contact c: contactList){
            Boolean forUpdate = false;
        
            // update case's call outcome
            if(!c.Cases.isEmpty() && c.Cases.size() > 1){
                String callOutcome = '';
                for(Case ca: c.Cases) {

                    if(String.isNotBlank(callOutcome)) {
                        ca.LatestCallOutcome__c = callOutcome;
                        caseUpdate.add(ca);
                    }

                    if(String.isNotBlank(ca.CallOutcome__c)) {
                        callOutcome = ca.CallOutcome__c;
                        c.LatestCall2__c = ca.Id;
                        c.Latest_Call_Outcome__c = ca.CallOutCome__c;
                        forUpdate = true;
                    }
                }
            }

            //update contact's address
            if(!c.Addresses__r.isEmpty()){
                c.Default_Address__c = c.Addresses__r[0].Id;
                forUpdate = true;
            }
            if(c.EstimatedDueDate__c != null) {
                c.Initial_Estimated_Due_Date_IEDD__c = c.EstimatedDueDate__c;
                forUpdate = true;
            }

            if(forUpdate) { conUpdate.add(c); }

        }

        if(!conUpdate.isEmpty()){ Database.update(conUpdate, false); }
        if(!caseUpdate.isEmpty()){ Database.update(caseUpdate, false); }
    }
    
    public void finish(Database.BatchableContext BC){}
}*/