force-app/main/default/objects/MY_Name_Ethnicity_Mapping__mdt/MY_Name_Ethnicity_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Name and Ethnicity (Malay, Chinese, Indian) Mapping</description>
    <label>MY Name Ethnicity Mapping</label>
    <pluralLabel>MY Name Ethnicity Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/MY_Name_Ethnicity_Mapping__mdt/fields/Ethnicity__c.field-meta.xml
<CustomField>
    <fullName>Ethnicity__c</fullName>
    <description>MY Ethnicity</description>
    <label>Ethnicity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MALAY</fullName>
                <default>true</default>
                <label>MALAY</label>
            </value>
            <value>
                <fullName>CHINESE</fullName>
            </value>
            <value>
                <fullName>INDIAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NameComparisonLoopActionTest.cls
@IsTest
public class NameComparisonLoopActionTest {
    
    @testVisible static List<MY_Name_Ethnicity_Mapping__mdt> dummyMapping { 
    get {
        if ( dummyMapping == null )
            dummyMapping = [ SELECT DeveloperName, Ethnicity__c FROM MY_Name_Ethnicity_Mapping__mdt ]; 
        return dummyMapping;
    } set; }
    
    @IsTest
    static void nameComparisonLoopTest(){
        NameComparisonLoopAction.ActionInput[] actionInputs = getFlowActionInputs(
        dummyMapping,
        'test',
        new String[]{'Abu', 'Ali'},
        'DeveloperName',
        'Ethnicity__c'    
        );
        
        Test.startTest();
        NameComparisonLoopAction.ActionOutput[] outputs = NameComparisonLoopAction.getNameComparison(actionInputs);
        Test.stopTest();
    }
    
    static NameComparisonLoopAction.ActionInput[] getFlowActionInputs(
        SObject[] records,
        String firstName,
        String[] lastName,
        String comparisonApiName,
        String resultApiName        
    ){
        NameComparisonLoopAction.ActionInput[] actionInputs = new NameComparisonLoopAction.ActionInput[]{};
            
            for(String lname : lastName){
                NameComparisonLoopAction.ActionInput input = new NameComparisonLoopAction.ActionInput();
                input.lastName = lname;
                input.firstName = firstName;
                input.records = records;
                input.comparisonApiName = comparisonApiName;
                input.resultApiName = resultApiName;
                
                actionInputs.add(input);
            }
        return actionInputs;
    }

}