force-app/main/default/objects/AffiliateMetadata__mdt/AffiliateMetadata__mdt.object-meta.xml
<CustomObject>
    <label>Affiliate Metadata</label>
    <pluralLabel>Affiliate Metadatas</pluralLabel>
</CustomObject>

force-app/main/default/objects/AffiliateMetadata__mdt/fields/MilkCodeRestrictionPeriod__c.field-meta.xml
<CustomField>
    <fullName>MilkCodeRestrictionPeriod__c</fullName>
    <label>Milk Code Restriction Period (in Months)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ContactBatchProcessed__c.field-meta.xml
<CustomField>
    <fullName>ContactBatchProcessed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ContactBatchProcessed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MilkCodeRestriction__c.field-meta.xml
<CustomField>
    <fullName>MilkCodeRestriction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milk Code Restriction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/classes/ContactBatchProcess.cls
/*----------------------------------------------------------------------------------------
* Script to Enable Milk Restriction Code on Contact
-------------------------------------------------------------------------------------------*/
// for deletion
global class ContactBatchProcess {} /* implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id,'
                            + ' AccountId,'
                            + ' Birthdate,'
                            + ' MilkCodeRestriction__c,'
                            + ' Market__c'
                            + ' FROM Contact WHERE Type__c = \'Child\' AND Birthdate != null AND ContactBatchProcessed__c = FALSE'
                            + ' ORDER BY AccountId';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        List<AffiliateMetadata__mdt> amList = [SELECT MasterLabel, MilkCodeRestrictionPeriod__c FROM AffiliateMetadata__mdt];
        Map<String, String> acs = UtilityClass.convertObjToMap(amList, CommonConstant.AFFILIATE_MASTERLABEL , CommonConstant.AFFILIATE_MILKRESTRICTION);
        List<Contact> contactList = new List<Contact>();

        for(Contact con : scope) {
            if(acs.containsKey(con.Market__c)) {
                String settings = acs.get(con.Market__c);
                Date computedDate = con.Birthdate.addMonths(Integer.valueOf(settings));

                if (Date.Today() >= con.Birthdate && Date.Today() <= computedDate) {
                    con.MilkCodeRestriction__c = true;
                } 
            }

            con.ContactBatchProcessed__c = TRUE;
            contactList.add(con);
        }

        Database.update(contactList, false);
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}*/