force-app/main/default/objects/AffiliateMetadata__mdt/AffiliateMetadata__mdt.object-meta.xml
<CustomObject>
    <label>Affiliate Metadata</label>
    <pluralLabel>Affiliate Metadatas</pluralLabel>
</CustomObject>

force-app/main/default/objects/AffiliateMetadata__mdt/fields/ChannelNewRegistrationValidity__c.field-meta.xml
<CustomField>
    <fullName>ChannelNewRegistrationValidity__c</fullName>
    <inlineHelpText>In Months</inlineHelpText>
    <label>Channel New Registration Validity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/NewtoBrand__c.field-meta.xml
<CustomField>
    <fullName>NewtoBrand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New to Brand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/NewtoBrandDate__c.field-meta.xml
<CustomField>
    <fullName>NewtoBrandDate__c</fullName>
    <label>New to Brand Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BrandNewRegistrationBatch.cls
/**
* @author        Rey Austral
* @date          7.23.2019
* @description   Batch job to run daily to update the New to Brand Checkbox
* @revision(s)
*/
global class BrandNewRegistrationBatch Implements Database.Batchable<sObject> {
    String country;
    Date beginDate;
    Integer interval;
    
    global BrandNewRegistrationBatch (String inputCountry, String inputBeginDateStr, Integer inputMonthsInterval){
        if(!String.isBlank(inputCountry)) country = inputCountry;
        if(!String.isBlank(inputBeginDateStr)) beginDate = Date.valueOf(inputBeginDateStr);
        if(inputMonthsInterval != null) interval = inputMonthsInterval;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String amQueryStr = 'SELECT MasterLabel, ChannelNewRegistrationValidity__c FROM AffiliateMetadata__mdt' 
            + ' WHERE ChannelNewRegistrationValidity__c != null';
        if(!String.isBlank(country)) amQueryStr += ' AND MasterLabel =: country';
        amQueryStr += ' ORDER BY ChannelNewRegistrationValidity__c LIMIT 1';
        List<AffiliateMetadata__mdt> am = Database.query(amQueryStr);
        String query;
        
        if(!am.isEmpty()){
            Date referenceDate = Date.today();
            if(beginDate != null) referenceDate = beginDate;
            String stringStartDate;
            if(interval != null) {
                Date startDate = referenceDate.addMonths(-(am.get(0).ChannelNewRegistrationValidity__c.intValue() + interval) );
                stringStartDate = String.valueOf(startDate).replace(' 00:00:00','');
            }
            Date endDate = referenceDate.addMonths(-am.get(0).ChannelNewRegistrationValidity__c.intValue());
            String stringEndDate = String.valueOf(endDate).replace(' 00:00:00','');
            
            query = 'SELECT ID , NewtoBrand__c, NewtoBrandDate__c, PrimaryContact__r.Market__c'                           
                + ' FROM BrandRelationship__c'
                + ' WHERE';
            if(!String.isBlank(country)) query += ' Market__c = \'' + country + '\' AND';
            if(!String.isBlank(stringStartDate)) query += ' NewtoBrandDate__c >= ' + stringStartDate + ' AND';
            query += ' NewtoBrandDate__c < ' + stringEndDate
                + ' AND NewtoBrand__c = true'
                + ' Order by NewtoBrandDate__c asc';
        }
        else{
            query = 'SELECT ID FROM BrandRelationship__c LIMIT 0';
        }
        System.debug(query);
        return Database.getQueryLocator(query); 
    }
    
    global void execute(Database.BatchableContext BC, List<BrandRelationship__c> scope) {
        //need to compare per country
        List<AffiliateMetadata__mdt> am = [Select MasterLabel, ChannelNewRegistrationValidity__c 
                                           From AffiliateMetadata__mdt Where ChannelNewRegistrationValidity__c != null];
        Map<String, String> acs = UtilityClass.convertObjToMap(am, CommonConstant.AFFILIATE_MASTERLABEL , 'ChannelNewRegistrationValidity__c');
        
        Map<Id, BrandRelationship__c> brToUpdateMap = New Map<Id, BrandRelationship__c>();
        for(BrandRelationship__c br : scope) {  
            if (acs.containsKey(br.PrimaryContact__r.Market__c)) {
                String settings = acs.get(br.PrimaryContact__r.Market__c);
                Date computedDate = Date.today().addMonths(-Integer.valueOf(settings));
                //the current date should be outside of the (bday+custom settings)
                if (br.NewtoBrandDate__c < computedDate) {                    
                    br.NewtoBrand__c = false;
                    brToUpdateMap.put(br.Id, br);
                }
            }			
        }
        
        if(!brToUpdateMap.isEmpty()) {
            // Update brToUpdateMap.values();
            
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.allowSave = true;
            dml.DuplicateRuleHeader.runAsCurrentUser = true; 
            
            List<Database.SaveResult> sr = Database.update(brToUpdateMap.values(), dml);
        }
    }    
    
    global void finish(Database.BatchableContext BC) {
    }
}