force-app/main/default/objects/OrderExport2__c/OrderExport2__c.object-meta.xml
<CustomObject>
    <label>Order Export</label>
    <nameField>
        <displayFormat>OE2-{000000000}</displayFormat>
        <label>Order Export Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Exports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderExport2__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Exports</relationshipLabel>
    <relationshipName>Order_Exports2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ExportOrderBatch_Cleanup.cls
public class ExportOrderBatch_Cleanup implements Database.Batchable<sObject>, Database.Stateful {

    public Database.QueryLocator start(Database.BatchableContext BC){
        Set<String> statusList = new Set<String> {'Submitted','Transferred'};

        String queryStr = 'SELECT Id FROM OrderExport2__c WHERE Order__r.Status NOT IN: statusList';

        if(Test.isRunningTest()){
            queryStr = 'SELECT Id FROM OrderExport2__c';
        }

        return Database.getQueryLocator(queryStr);
    }
    
    public void execute(Database.BatchableContext BC, List<OrderExport2__c> oList){
        DELETE oList;
    }

    public void finish(Database.BatchableContext BC){}
}