force-app/main/default/objects/Contact/fields/Anniversary_Month__c.field-meta.xml
<CustomField>
    <fullName>Anniversary_Month__c</fullName>
    <formula>MONTH(FirstTransactionDate__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Anniversary Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Anniversary_Promo__c.field-meta.xml
<CustomField>
    <fullName>Anniversary_Promo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Anniversary Promo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Birthday_Promo_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Birthday_Promo_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Birthday Promo Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Purchase_Anniversary_Amount_Adult__c.field-meta.xml
<CustomField>
    <fullName>Total_Purchase_Anniversary_Amount_Adult__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Total Purchase Anniversary Amount Adult</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AnniversaryPromoBatch.cls
/**
* @author        
* @date          
* @description   Batch job to run monthly to update the Anniversary Promo
* @revision(s)
*/
global class AnniversaryPromoBatch Implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Integer month = Date.Today().Month();
        String query = 'SELECT id,Total_Purchase_Anniversary_Amount_Adult__c,Anniversary_Promo__c,FirstTransactionDate__c, Anniversary_Month__c from Contact'
        + ' WHERE Total_Purchase_Anniversary_Amount_Adult__c >= 2000 AND Market__c = \'TW\' AND Anniversary_Month__c =: month';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        List<Contact> updateConList = new List<Contact>();
        for(Contact con: scope){
            if(!con.Anniversary_Promo__c){
                con.Birthday_Promo_Eligible__c = false;
                con.Anniversary_Promo__c = true;
                updateConList.add(con);
            }
        }
        if(!updateConList.isEmpty()){
            update updateConList;
        }
        
    }    
    
    global void finish(Database.BatchableContext BC) {
    }
}