force-app/main/default/objects/Contact/fields/Anniversary_Promo__c.field-meta.xml
<CustomField>
    <fullName>Anniversary_Promo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Anniversary Promo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Birthdate_Month__c.field-meta.xml
<CustomField>
    <fullName>Birthdate_Month__c</fullName>
    <formula>MONTH(Birthdate)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Birthdate Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Birthday_Promo_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Birthday_Promo_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Birthday Promo Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Purchase_Amount_Adult_Brand__c.field-meta.xml
<CustomField>
    <fullName>Total_Purchase_Amount_Adult_Brand__c</fullName>
    <defaultValue>0.0</defaultValue>
    <label>Total Purchase Amount Adult Brand</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BirthdayPromoBatch.cls
/**
* @author        
* @date          
* @description   Batch job to run monthly to update the Birthday Promo
* @revision(s)
*/
global class BirthdayPromoBatch Implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Integer month = Date.Today().Month();
        String query = 'SELECT id,Total_Purchase_Amount_Adult_Brand__c,Birthdate_Month__c,Birthday_Promo_Eligible__c,Birthdate FROM Contact'
        + ' WHERE Total_Purchase_Amount_Adult_Brand__c >= 2000 AND Market__c = \'TW\' AND Birthdate_Month__c =: month';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        List<Contact> updateConList = new List<Contact>();
        for(Contact con: scope){
            if(!con.Birthday_Promo_Eligible__c){
                con.Anniversary_Promo__c = false;
                con.Birthday_Promo_Eligible__c = true;
                updateConList.add(con);
            }
        }
        if(!updateConList.isEmpty()){
            update updateConList;
        }
        
    }    
    
    global void finish(Database.BatchableContext BC) {
    }
}