force-app/main/default/objects/Contact/fields/DataSharingOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>DataSharingOptOutDate__c</fullName>
    <label>Data Sharing Opt Out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DataSharingWithThirdPartyOptOut__c.field-meta.xml
<CustomField>
    <fullName>DataSharingWithThirdPartyOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Data Sharing Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DoNotCallDate__c.field-meta.xml
<CustomField>
    <fullName>DoNotCallDate__c</fullName>
    <label>Do Not Call Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EmailOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>EmailOptOutDate__c</fullName>
    <label>Email Opt Out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SMSOptOut__c.field-meta.xml
<CustomField>
    <fullName>SMSOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SMSOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>SMSOptOutDate__c</fullName>
    <label>SMS Opt Out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/WhatsappOptOut__c.field-meta.xml
<CustomField>
    <fullName>WhatsappOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Whatsapp Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WhatsappOptOutDate__c.field-meta.xml
<CustomField>
    <fullName>WhatsappOptOutDate__c</fullName>
    <label>Whatsapp Opt Out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/classes/Contact_ClearOptOutDates.cls
/**
* @author        Jennifer Alviz    
* @date          5.12.2021
* @description   Batch job to clear opt out dates on contacts where opt out checkbox is unchecked, 
*                affected contacts are prepopulated with the date values upon creation and did not trigger the existing validation rule
* @revision(s)
*/
global class Contact_ClearOptOutDates implements Database.Batchable<sObject> {

    String queryOverride;
    
    global Contact_ClearOptOutDates(String newScope){
        queryOverride = newScope;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
         String query = 'SELECT id,DoNotCall,DoNotCallDate__c,HasOptedOutOfEmail,EmailOptOutDate__c,WhatsappOptOut__c,WhatsappOptOutDate__c,SMSOptOut__c,SMSOptOutDate__c,'
            + 'DataSharingWithThirdPartyOptOut__c,DataSharingOptOutDate__c'                           
            + ' FROM Contact'
            + ' WHERE'
            + ' Type__c = \'Adult\''
            + ' AND Market__c = \'SG\'';

        if(String.isNotBlank(queryOverride)){
        query = queryOverride;
        }

        return Database.getQueryLocator(query);
        
    }

    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        List<Contact> contactToUpdate = new List<Contact>();
        
        for(Contact con : scope){
            Boolean forUpdate = false;

            If(!con.DoNotCall && con.DoNotCallDate__c != null){
                con.DoNotCallDate__c = null;
                forUpdate = true;
            }
            If(!con.HasOptedOutOfEmail && con.EmailOptOutDate__c != null){
                con.EmailOptOutDate__c = null;
                forUpdate = true;
            }
            If(!con.WhatsappOptOut__c && con.WhatsappOptOutDate__c != null){
                con.WhatsappOptOutDate__c = null;
                forUpdate = true;
            }
            If(!con.SMSOptOut__c && con.SMSOptOutDate__c != null){
                con.SMSOptOutDate__c = null;
                forUpdate = true;
            }
            If(!con.DataSharingWithThirdPartyOptOut__c && con.DataSharingOptOutDate__c != null){
                con.DataSharingOptOutDate__c = null;
                forUpdate = true;
            }
            
            if(forUpdate){
                contactToUpdate.add(con);
            }
            
        }
        
        if(!contactToUpdate.isEmpty()) Utilityclass.updateList(contactToUpdate);
    }
        
    global void finish(Database.BatchableContext BC) {
        
    }
    
}