force-app/main/default/objects/Contact/fields/Integration_Src__c.field-meta.xml
<CustomField>
    <fullName>Integration_Src__c</fullName>
    <label>Integration Src</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SourceCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>SourceCreatedDate__c</fullName>
    <label>Source Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tangent</fullName>
                <default>true</default>
                <label>Tangent</label>
            </value>
            <value>
                <fullName>Capillary</fullName>
            </value>
            <value>
                <fullName>AbbottMall</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipExpiryDate__c</fullName>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipId__c.field-meta.xml
<CustomField>
    <fullName>MembershipId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Membership Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/NumberOfDaysDormant__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysDormant__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Days Dormant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/NumberOfTransactions__c.field-meta.xml
<CustomField>
    <fullName>NumberOfTransactions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Recent_Product_Purchased__c.field-meta.xml
<CustomField>
    <fullName>Recent_Product_Purchased__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recent Product Purchased</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactMembershipBatch.cls
/*
Author: Frank Gomendoza
Description: Batch class for copying Membership details to Contact
*/
global class ContactMembershipBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    public static Map<String, String> brandCodeMap = new Map<String, String>{'92221' => 'Ensure', '92222' => 'Glucerna', '92224' => 'Pediasure', '92225' => 'Similac'};
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String contactAdultRectypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Adult').getRecordTypeId();
        String query = 'SELECT Id, Name, CreatedDate, LastModifiedDate, Contact__c, MembershipExpiryDate__c, MembershipId__c, MembershipStartDate__c, NumberOfDaysDormant__c, '
            + 'NumberOfTransactions__c, Status__c, SourceCreatedDate__c, Integration_Src__c, Recent_Product_Purchased__c, Membership_Type__c '
            + 'FROM Membership__c '
            + 'WHERE Contact__c != null AND Contact__r.Market__c = \'PH\' AND Contact__r.Active__c = true AND Contact__r.RecordTypeId =: contactAdultRectypeId AND MembershipId__c != null '
            + 'ORDER BY Contact__c ASC';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Membership__c> scope) {
        if(!scope.isEmpty()){
            Map<Id, Map<String, Membership__c>> brandMembershipMap = new Map<Id, Map<String, Membership__c>>();
            Set<Id> conIdSet = new Set<Id>();
            List<Membership__c> membershipList = new List<Membership__c>();
            Map<Id, Contact> conUpdateMap = new Map<Id, Contact>();  
            
            for(Membership__c newMem : scope){
                membershipList.add(newMem);
                conIdSet.add(newMem.Contact__c);
            }
            for(Membership__c existingMem : [SELECT Id, MembershipId__c, NumberOfDaysDormant__c, NumberOfTransactions__c, MembershipStartDate__c, Contact__c, Status__c, Recent_Product_Purchased__c, CreatedDate FROM Membership__c WHERE Contact__c IN : conIdSet AND Id NOT IN: scope AND MembershipId__c != null]){
                membershipList.add(existingMem);
            }
            for(Membership__c member : membershipList){
                brandMembershipMap = MembershipTriggerHelper.createBrandMembershipMap(brandMembershipMap, member);
            }
            
            for(Membership__c mem : membershipList){
                String rawMembershipId = mem.MembershipId__c.replaceAll('(\\s+)', '');
                String brand = brandCodeMap.get(rawMembershipId.left(5));
                if(brandMembershipMap.containsKey(mem.Contact__c)){
                    if(brandMembershipMap.get(mem.Contact__c).containsKey(brand)){
                        Membership__c brandMem = brandMembershipMap.get(mem.Contact__c).get(brand);
                        conUpdateMap = MembershipTriggerHelper.processContactUpdateMap(brandMem, brand);
                    }
                }
            }
            
            if(!conUpdateMap.keySet().isEmpty()){
                update conUpdateMap.values();
            }
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        AsyncApexJob job = [SELECT Id, Status FROM AsyncApexJob WHERE Id = :BC.getJobId()]; 
        System.debug('>>>> finish ' + job.Status);
    }
    
    global void execute(SchedulableContext sc) {
        ContactMembershipBatch batch = new ContactMembershipBatch(); 
        Database.executebatch(batch, 30);
    }
}