force-app/main/default/objects/Contact/fields/LineOptOut__c.field-meta.xml
<CustomField>
    <fullName>LineOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Line Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LineUIDAdult__c.field-meta.xml
<CustomField>
    <fullName>LineUIDAdult__c</fullName>
    <label>Line UID Adult</label>
    <length>33</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LineUIDPediatric__c.field-meta.xml
<CustomField>
    <fullName>LineUIDPediatric__c</fullName>
    <label>Line UID Pediatric</label>
    <length>33</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MasterOptOut__c.field-meta.xml
<CustomField>
    <fullName>MasterOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Master Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MC_Sync_Eligibility_TW__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_TW__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility TW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/classes/MC_Contact_SyncEligibilityTWBatch.cls
/***********************************************************************
* @author        Monika Parihar    
* @date          8/10/2021
* @description   Batch job to update MC Sync Eligibility Fields for TW
* @revision(s)
**************************************************************************/

global class MC_Contact_SyncEligibilityTWBatch Implements Database.Batchable<sObject>, Database.Stateful{
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT ID , Name, AccountId, Market__c, Active__c, Phone, Email, HasOptedOutOfEmail,LineUIDPediatric__c,LineUIDAdult__c,LineOptOut__c,MC_Sync_Eligibility_TW__c FROM CONTACT WHERE'
            + ' (Phone != null'
            + ' OR Email != null'
            + ' OR LineUIDPediatric__c != null'
            + ' OR LineUIDAdult__c != null)'
            + ' AND PrimaryContact__c = True'
            + ' AND LineOptOut__c = False'
            + ' AND Active__c = True'
            + ' AND Blacklisted__c = False'
            + ' AND MasterOptOut__c = False'
            + ' AND RecordType.Name = \'Adult\''
            + ' AND Market__c =  \'TW\'';
       
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        List<Contact> contactsToUpdate = new List<Contact>();

        for(Contact con: scope){
            if(!con.MC_Sync_Eligibility_TW__c){
                con.MC_Sync_Eligibility_TW__c = True;
            }
            contactsToUpdate.add(con);
        }
        
        if(!contactsToUpdate.isEmpty()) Utilityclass.updateList(contactsToUpdate);

    }

    global void finish(Database.BatchableContext BC) {

    }
}