force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MC_Sync_Eligibility_MY__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_MY__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility MY</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MC_Sync_Eligibility_PH__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_PH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility PH</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MC_Sync_Eligibility_Batch_Size__mdt/MC_Sync_Eligibility_Batch_Size__mdt.object-meta.xml
<CustomObject>
    <label>MC Sync Eligibility Batch Size</label>
    <pluralLabel>MC Sync Eligibility Batch Size</pluralLabel>
</CustomObject>

force-app/main/default/objects/Order/fields/MC_Sync_Eligibility_ID__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/MC_Sync_Eligibility_SG__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_SG__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility SG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/MC_Sync_Eligibility_VN__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_VN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility VN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderedBy__c.field-meta.xml
<CustomField>
    <fullName>OrderedBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordered By</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Adult</value>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MC_Order_SyncEligibilityBatch.cls
/**
* @author        Jennifer Alviz    
* @date          01.27.2021
* @description   Batch job to update ORDER PRODUCT Sync Eligibility Fields
* @revision(s)
*/
global class MC_Order_SyncEligibilityBatch Implements Database.Batchable<sObject>, Database.Stateful {
    
    global Set<Id> contactIds = new Set<Id>();
    global Set<Id> orderIds = new set<Id>();
    Set<Id> eligibleContacts = new Set<Id>();
    String queryOverride;

    global MC_Order_SyncEligibilityBatch(Set<Id> conIds, String newScope){
        contactIds =  (Set<Id>) conIds;
        queryOverride = newScope;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT ID, Orderedby__c ,'
            + 'MC_Sync_Eligibility_ANZ__c, MC_Sync_Eligibility_ID__c, MC_Sync_Eligibility_IN__c, MC_Sync_Eligibility_MY__c,'
            + 'MC_Sync_Eligibility_PH__c, MC_Sync_Eligibility_SG__c, MC_Sync_Eligibility_TH__c, MC_Sync_Eligibility_VN__c'                        
            + ' FROM Order'
            + ' WHERE'
            + ' Orderedby__c IN :contactIds';

        if(String.isNotBlank(queryOverride)){
            query = queryOverride;
        } 
            
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Order> scope) {
        Map<Id, Contact> contactMap = new Map<Id,Contact>();
        List<Order> ordersToUpdate = new List<Order>();
        for(Order o: scope){
            orderIds.add(o.Id);
        }
        
        //OrderEventHandler.updateMCEligibility(orderIds);

        contactMap = new Map<Id,Contact>([SELECT Id, Market__c,MC_Sync_Eligibility_ANZ__c,MC_Sync_Eligibility_ID__c,MC_Sync_Eligibility_IN__c, 
                                        MC_Sync_Eligibility_MY__c, MC_Sync_Eligibility_PH__c, MC_Sync_Eligibility_SG__c, MC_Sync_Eligibility_TH__c,
                                        MC_Sync_Eligibility_VN__c
                                        FROM Contact 
                                        WHERE Id IN (SELECT Orderedby__c FROM Order WHERE Id IN: orderIds)]);
        
        for(Order o: scope ) {  
               
            String Market = contactMap.get(o.Orderedby__c).Market__c;
            Boolean forUpdate = false; 
                    
            if(Market == CommonConstant.MARKET_ANZ){
                o.MC_Sync_Eligibility_ANZ__c = contactMap.get(o.Orderedby__c).MC_Sync_Eligibility_ANZ__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_ID){
                o.MC_Sync_Eligibility_ID__c = contactMap.get(o.Orderedby__c).MC_Sync_Eligibility_ID__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_IN){
                o.MC_Sync_Eligibility_IN__c = contactMap.get(o.Orderedby__c).MC_Sync_Eligibility_IN__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_MY){
                o.MC_Sync_Eligibility_MY__c = contactMap.get(o.Orderedby__c).MC_Sync_Eligibility_MY__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_PH){
                o.MC_Sync_Eligibility_PH__c = contactMap.get(o.Orderedby__c).MC_Sync_Eligibility_PH__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_SG){
                o.MC_Sync_Eligibility_SG__c = contactMap.get(o.Orderedby__c).MC_Sync_Eligibility_SG__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_TH){
                o.MC_Sync_Eligibility_TH__c = contactMap.get(o.Orderedby__c).MC_Sync_Eligibility_TH__c;
                forUpdate = true;

            }else if(Market == CommonConstant.MARKET_VN){
                o.MC_Sync_Eligibility_VN__c = contactMap.get(o.Orderedby__c).MC_Sync_Eligibility_VN__c;
                forUpdate = true;

            }
            
            if(forUpdate) ordersToUpdate.add(o);
        }
        
        if(!ordersToUpdate.isEmpty()) UtilityClass.updateList(ordersToUpdate);
    }
    
    global void finish(Database.BatchableContext BC) {
         if(!orderIds.isEmpty()){
            Database.executebatch(new MC_OrderProduct_SyncEligibilityBatch(orderIds,''), (Integer)MC_Sync_Eligibility_Batch_Size__mdt.getInstance('Order_Product').Batch_Size__c);
         }
    }
}