force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MC_Sync_Eligibility_MY__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_MY__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility MY</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MC_Sync_Eligibility_PH__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_PH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility PH</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/et4ae5__IndividualEmailResult__c/et4ae5__IndividualEmailResult__c.object-meta.xml
<CustomObject>
    <label>Individual Email Result</label>
    <nameField>
        <label>Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individual Email Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/et4ae5__IndividualEmailResult__c/fields/MC_Sync_Eligibility_ID__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/et4ae5__IndividualEmailResult__c/fields/MC_Sync_Eligibility_SG__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_SG__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility SG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/et4ae5__IndividualEmailResult__c/fields/MC_Sync_Eligibility_VN__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_VN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility VN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MC_IER_SyncEligibilityBatch.cls
/**
* @author        Jennifer Alviz    
* @date          01.27.2021
* @description   Batch job to update INDIVIDUAL EMAIL RESULT Sync Eligibility Fields
* @revision(s)
*/
global class MC_IER_SyncEligibilityBatch Implements Database.Batchable<sObject>, Database.Stateful {
    
    global Set<Id> contactIds = new Set<Id>();
    String queryOverride;
    
    global MC_IER_SyncEligibilityBatch(Set<Id> conIds,String newScope){
        contactIds =  (Set<Id>) conIds;
        queryOverride = newScope;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT ID, et4ae5__Contact__c,'
            + 'MC_Sync_Eligibility_ANZ__c, MC_Sync_Eligibility_ID__c, MC_Sync_Eligibility_IN__c, MC_Sync_Eligibility_MY__c,'
            + 'MC_Sync_Eligibility_PH__c, MC_Sync_Eligibility_SG__c, MC_Sync_Eligibility_TH__c, MC_Sync_Eligibility_VN__c'                    
            + ' FROM et4ae5__IndividualEmailResult__c'
            + ' WHERE'
            + ' et4ae5__Contact__c IN :contactIds';

        if(String.isNotBlank(queryOverride)){
            query = queryOverride;
        }   

        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<et4ae5__IndividualEmailResult__c> scope) {
        Map<Id, Contact> contactMap = new Map<Id,Contact>();
        List<et4ae5__IndividualEmailResult__c> ierToUpdate = new List<et4ae5__IndividualEmailResult__c>();
        Set<Id> relevantContactIds = new Set<Id>();
        for(et4ae5__IndividualEmailResult__c ier : scope){
            relevantContactIds.add(ier.et4ae5__Contact__c );
        }
        
        contactMap = new Map<Id,Contact>([SELECT Id, Market__c,MC_Sync_Eligibility_ANZ__c,MC_Sync_Eligibility_ID__c,MC_Sync_Eligibility_IN__c, 
                                        MC_Sync_Eligibility_MY__c, MC_Sync_Eligibility_PH__c, MC_Sync_Eligibility_SG__c, MC_Sync_Eligibility_TH__c,
                                        MC_Sync_Eligibility_VN__c
                                        FROM Contact 
                                        WHERE Id IN :relevantContactIds]);
        
        for(et4ae5__IndividualEmailResult__c  ier: scope) {  
                         
            String Market = contactMap.get(ier.et4ae5__Contact__c ).Market__c;
            Boolean forUpdate = true; 
                         
            if(Market == CommonConstant.MARKET_ANZ){
                ier.MC_Sync_Eligibility_ANZ__c = contactMap.get(ier.et4ae5__Contact__c ).MC_Sync_Eligibility_ANZ__c;
            }else if(Market == CommonConstant.MARKET_ID){
                ier.MC_Sync_Eligibility_ID__c = contactMap.get(ier.et4ae5__Contact__c ).MC_Sync_Eligibility_ID__c;
            }else if(Market == CommonConstant.MARKET_IN){
                ier.MC_Sync_Eligibility_IN__c = contactMap.get(ier.et4ae5__Contact__c ).MC_Sync_Eligibility_IN__c;
            }else if(Market == CommonConstant.MARKET_MY){
                ier.MC_Sync_Eligibility_MY__c = contactMap.get(ier.et4ae5__Contact__c ).MC_Sync_Eligibility_MY__c;
            }else if(Market == CommonConstant.MARKET_PH){
                ier.MC_Sync_Eligibility_PH__c = contactMap.get(ier.et4ae5__Contact__c ).MC_Sync_Eligibility_PH__c;
            }else if(Market == CommonConstant.MARKET_SG){
                ier.MC_Sync_Eligibility_SG__c = contactMap.get(ier.et4ae5__Contact__c ).MC_Sync_Eligibility_SG__c;
            }else if(Market == CommonConstant.MARKET_TH){
                ier.MC_Sync_Eligibility_TH__c = contactMap.get(ier.et4ae5__Contact__c ).MC_Sync_Eligibility_TH__c;
            }else if(Market == CommonConstant.MARKET_VN){
                ier.MC_Sync_Eligibility_VN__c = contactMap.get(ier.et4ae5__Contact__c ).MC_Sync_Eligibility_VN__c;
            }else{
                forUpdate = false;
            }
            
            if(forUpdate) ierToUpdate.add(ier);
        }
        
        if(!ierToUpdate.isEmpty()) UtilityClass.updateList(ierToUpdate);
    }
    
    global void finish(Database.BatchableContext BC) {
    }
}