force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MC_Sync_Eligibility_MY__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_MY__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility MY</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MC_Sync_Eligibility_PH__c.field-meta.xml
<CustomField>
    <fullName>MC_Sync_Eligibility_PH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Sync Eligibility PH</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Fill in the Main Contact for this person (e.g. child or elderly person) under the main contact&apos;s care. This field is not required if this person is a Primary Contact.</inlineHelpText>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/classes/MC_ChildContact_SyncEligibilityBatch.cls
/**
* @author        Jennifer Alviz    
* @date          03.25.2021
* @description   Batch job to update Child Contacts Sync Eligibility Fields - for VN
* @revision(s)
*/
global class MC_ChildContact_SyncEligibilityBatch Implements Database.Batchable<sObject>, Database.Stateful {
    
    String market;
    Set<Id> contactIds = new Set<Id>();
    String queryOverride;
    
    global MC_ChildContact_SyncEligibilityBatch(String m, Set<Id> conIds,String newScope){
        market = m;
        contactIds =  (Set<Id>) conIds;
        queryOverride = newScope;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT ID, Parent__c,PrimaryContact__c ,'
            + 'MC_Sync_Eligibility_ANZ__c, MC_Sync_Eligibility_ID__c, MC_Sync_Eligibility_IN__c, MC_Sync_Eligibility_MY__c,'
            + 'MC_Sync_Eligibility_PH__c, MC_Sync_Eligibility_SG__c, MC_Sync_Eligibility_TH__c, MC_Sync_Eligibility_VN__c'                        
            + ' FROM Contact'
            + ' WHERE'
            + ' Parent__c != null'
            + ' AND Type__c = \'Child\''
            + ' AND Parent__c IN :contactIds ';

        if(String.isNotBlank(queryOverride)){
            query = queryOverride;
        }

        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        Map<Id, Contact> parentContactMap = new Map<Id,Contact>();
        List<Contact> conToUpdate = new List<Contact>();
        Set<Id> parentIds = new Set<Id>();
        for(Contact con : scope){
            parentIds.add(con.Parent__c);
        }
        
        parentContactMap = new Map<Id,Contact>([SELECT Id, Market__c,MC_Sync_Eligibility_ANZ__c,MC_Sync_Eligibility_ID__c,MC_Sync_Eligibility_IN__c, 
                                                MC_Sync_Eligibility_MY__c, MC_Sync_Eligibility_PH__c, MC_Sync_Eligibility_SG__c, MC_Sync_Eligibility_TH__c,
                                                MC_Sync_Eligibility_VN__c
                                                FROM Contact 
                                                WHERE Id IN :parentIds]);
    
        for(Contact con : scope) {  
                         
            Boolean forUpdate = true; 
                         
            if(Market == CommonConstant.MARKET_ANZ){
                con.MC_Sync_Eligibility_ANZ__c = parentContactMap.get(con.Parent__c).MC_Sync_Eligibility_ANZ__c;
            }else if(Market == CommonConstant.MARKET_ID){
                con.MC_Sync_Eligibility_ID__c = parentContactMap.get(con.Parent__c).MC_Sync_Eligibility_ID__c;
            }else if(Market == CommonConstant.MARKET_IN){
                con.MC_Sync_Eligibility_IN__c = parentContactMap.get(con.Parent__c).MC_Sync_Eligibility_IN__c;
            }else if(Market == CommonConstant.MARKET_MY){
                con.MC_Sync_Eligibility_MY__c = parentContactMap.get(con.Parent__c).MC_Sync_Eligibility_MY__c;
            }else if(Market == CommonConstant.MARKET_PH){
                con.MC_Sync_Eligibility_PH__c = parentContactMap.get(con.Parent__c).MC_Sync_Eligibility_PH__c;
            }else if(Market == CommonConstant.MARKET_SG){
                con.MC_Sync_Eligibility_SG__c = parentContactMap.get(con.Parent__c).MC_Sync_Eligibility_SG__c;
            }else if(Market == CommonConstant.MARKET_TH){
                con.MC_Sync_Eligibility_TH__c = parentContactMap.get(con.Parent__c).MC_Sync_Eligibility_TH__c;
            }else if(Market == CommonConstant.MARKET_VN){
                con.MC_Sync_Eligibility_VN__c = parentContactMap.get(con.Parent__c).MC_Sync_Eligibility_VN__c;
            }else{
                forUpdate = false;
            }
            
            if(forUpdate) conToUpdate.add(con);
        }
        if(!conToUpdate.isEmpty()) Utilityclass.updateList(conToUpdate);

    }
    
    global void finish(Database.BatchableContext BC) {
    }
}