force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipExpiryDate__c</fullName>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipId__c.field-meta.xml
<CustomField>
    <fullName>MembershipId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Membership Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/NumberOfDaysDormant__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysDormant__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Days Dormant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/NumberOfTransactions__c.field-meta.xml
<CustomField>
    <fullName>NumberOfTransactions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Recent_Product_Purchased__c.field-meta.xml
<CustomField>
    <fullName>Recent_Product_Purchased__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recent Product Purchased</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MembershipTriggerHandler.cls
public class MembershipTriggerHandler implements ITriggerHandler{

    public void BeforeInsert(List<SObject> newList) {}
    
    public void BeforeUpdate(List<SObject> newList, Map<Id, SObject> newMapItems, List<SObject> oldList, Map<Id, SObject> oldMapItems) {}

    public void BeforeDelete(List<SObject> oldList, Map<Id, SObject> oldItems){}
    
    public void AfterInsert(List<SObject> newList, Map<Id, SObject> newMapItems){
        Map<Id, List<Membership__c>> conMembershipMap = new Map<Id, List<Membership__c>>();
        List<Membership__c> processPHMemList = new List<Membership__c>();
        Map<Id, Membership__c> processPHMemMap = new Map<Id, Membership__c>();
        
        for(Membership__c mem : (List<Membership__c>) newList){
            if(conMembershipMap.containsKey(mem.Contact__c)){
                conMembershipMap.get(mem.Contact__c).add(mem);
            }
            else{
                conMembershipMap.put(mem.Contact__c, new List<Membership__c>{mem});
            }
        }
        for(Contact con : [SELECT Id, Market__c FROM Contact WHERE Id IN: conMembershipMap.keySet() AND Market__c = 'PH']){
            processPHMemList.addAll(conMembershipMap.get(con.Id));
        }
        for(Membership__c mem : processPHMemList){
            processPHMemMap.put(mem.Id, mem);
        }
        System.debug('INSERT MembershipTriggerHandler');
        if(!processPHMemMap.keySet().isEmpty()){
            MembershipTriggerHelper.copyMembershipToContact(null, processPHMemMap);
        }
    }
    
    public void AfterUpdate(List<SObject> newList , Map<Id, SObject> newMapItems, List<SObject> oldList, Map<Id, SObject> oldMapItems){
        Map<Id, List<Membership__c>> conMembershipMap = new Map<Id, List<Membership__c>>();
        List<Membership__c> processPHMemList = new List<Membership__c>();
        Map<Id, Membership__c> processPHMemMap = new Map<Id, Membership__c>();
        
        for(Membership__c mem : (List<Membership__c>) newList){
            if(conMembershipMap.containsKey(mem.Contact__c)){
                conMembershipMap.get(mem.Contact__c).add(mem);
            }
            else{
                conMembershipMap.put(mem.Contact__c, new List<Membership__c>{mem});
            }
        }
        for(Contact con : [SELECT Id, Market__c FROM Contact WHERE Id IN: conMembershipMap.keySet() AND Market__c = 'PH']){
            processPHMemList.addAll(conMembershipMap.get(con.Id));
        }
        for(Membership__c mem : processPHMemList){
            Membership__c oldItem = (Membership__c) oldMapItems.get(mem.Id);
            if(mem.Status__c != oldItem.Status__c || mem.MembershipStartDate__c != oldItem.MembershipStartDate__c || mem.MembershipExpiryDate__c != oldItem.MembershipExpiryDate__c || mem.Contact__c != oldItem.Contact__c ||
               mem.Recent_Product_Purchased__c != oldItem.Recent_Product_Purchased__c || mem.NumberOfDaysDormant__c != oldItem.NumberOfDaysDormant__c || mem.NumberOfTransactions__c != oldItem.NumberOfTransactions__c ||
               mem.MembershipId__c != oldItem.MembershipId__c)
            {
                processPHMemMap.put(mem.Id, mem);
            }
        }
        System.debug('UPDATE MembershipTriggerHandler');
        if(!processPHMemMap.keySet().isEmpty()){
            MembershipTriggerHelper.copyMembershipToContact(oldMapItems, processPHMemMap);
        }
    }
    
    public void AfterDelete(List<SObject> oldList, Map<Id, SObject> oldMapItems){}
}