force-app/main/default/objects/Contact/fields/MembershipId_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipId_Ensure__c</fullName>
    <label>Membership Id Ensure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipId_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipId_Glucerna__c</fullName>
    <label>Membership Id Glucerna</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipId_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipId_Pediasure__c</fullName>
    <label>Membership Id Pediasure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipId_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipId_Similac__c</fullName>
    <label>Membership Id Similac</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfDaysDormant_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfDaysDormant_Ensure__c</fullName>
    <label>MembershipNumberOfDaysDormant Ensure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfDaysDormant_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfDaysDormant_Glucerna__c</fullName>
    <label>MembershipNumberOfDaysDormant Glucerna</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfDaysDormant_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfDaysDormant_Pediasure__c</fullName>
    <label>MembershipNumberOfDaysDormant Pediasure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfDaysDormant_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfDaysDormant_Similac__c</fullName>
    <label>MembershipNumberOfDaysDormant Similac</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfTransactions_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfTransactions_Ensure__c</fullName>
    <label>MembershipNumberOfTransactions Ensure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfTransactions_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfTransactions_Glucerna__c</fullName>
    <label>MembershipNumberOfTransactions Glucerna</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfTransactions_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfTransactions_Pediasure__c</fullName>
    <label>MembershipNumberOfTransactions Pediasure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfTransactions_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfTransactions_Similac__c</fullName>
    <label>MembershipNumberOfTransactions Similac</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipRecentProduct_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipRecentProduct_Ensure__c</fullName>
    <label>Membership Recent Product Ensure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipRecentProduct_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipRecentProduct_Glucerna__c</fullName>
    <label>Membership Recent Product Glucerna</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipRecentProduct_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipRecentProduct_Pediasure__c</fullName>
    <label>Membership Recent Product Pediasure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipRecentProduct_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipRecentProduct_Similac__c</fullName>
    <label>Membership Recent Product Similac</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate_Ensure__c</fullName>
    <label>Membership Start Date Ensure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate_Glucerna__c</fullName>
    <label>Membership Start Date Glucerna</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate_Pediasure__c</fullName>
    <label>Membership Start Date Pediasure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate_Similac__c</fullName>
    <label>Membership Start Date Similac</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStatus_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipStatus_Ensure__c</fullName>
    <label>Membership Status Ensure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStatus_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipStatus_Glucerna__c</fullName>
    <label>Membership Status Glucerna</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStatus_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipStatus_Pediasure__c</fullName>
    <label>Membership Status Pediasure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStatus_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipStatus_Similac__c</fullName>
    <label>Membership Status Similac</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/MembershipId__c.field-meta.xml
<CustomField>
    <fullName>MembershipId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Membership Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/NumberOfTransactions__c.field-meta.xml
<CustomField>
    <fullName>NumberOfTransactions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <label>Key Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abbott General</fullName>
            </value>
            <value>
                <fullName>Abound</fullName>
            </value>
            <value>
                <fullName>Alitraq</fullName>
            </value>
            <value>
                <fullName>Bonesure</fullName>
            </value>
            <value>
                <fullName>Bright Choice</fullName>
            </value>
            <value>
                <fullName>Caltrate</fullName>
            </value>
            <value>
                <fullName>Diabetamill</fullName>
            </value>
            <value>
                <fullName>Elecare</fullName>
            </value>
            <value>
                <fullName>Ensure</fullName>
            </value>
            <value>
                <fullName>Ensure Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Flexiflo</fullName>
            </value>
            <value>
                <fullName>Freego</fullName>
            </value>
            <value>
                <fullName>Glucerna</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Isomil</fullName>
            </value>
            <value>
                <fullName>Jevity</fullName>
            </value>
            <value>
                <fullName>Kidneysure</fullName>
            </value>
            <value>
                <fullName>Nepro</fullName>
            </value>
            <value>
                <fullName>Nutr Accessories</fullName>
            </value>
            <value>
                <fullName>Osmolite</fullName>
            </value>
            <value>
                <fullName>Other MND</fullName>
            </value>
            <value>
                <fullName>Pediasure</fullName>
            </value>
            <value>
                <fullName>Polycose</fullName>
            </value>
            <value>
                <fullName>Prosure</fullName>
            </value>
            <value>
                <fullName>Pulmocare</fullName>
            </value>
            <value>
                <fullName>RCF</fullName>
            </value>
            <value>
                <fullName>Similac</fullName>
            </value>
            <value>
                <fullName>Similac Core</fullName>
            </value>
            <value>
                <fullName>Similac Mom</fullName>
            </value>
            <value>
                <fullName>Similac Total Comfort</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MembershipTriggerTest.cls
@isTest
public class MembershipTriggerTest {
    @testSetup
    static void setUp(){
        Account a = TestDataFactory.createTestHousehold(1, 'PH')[0];
        Contact con = TestDataFactory.createContact(true, a.Id, null, Date.valueOf('1990-01-01'), '0999999999');
        PricebookEntry pbeEnsure = TestDataFactory.createPricebookEntry('PH', 'USD');
        PricebookEntry pbeGlucerna = TestDataFactory.createProductAndPricebookEntryDiffBrand('PH', 'USD', pbeEnsure.Pricebook2Id, 'Glucerna');
        PricebookEntry pbePediasure = TestDataFactory.createProductAndPricebookEntryDiffBrand('PH', 'USD', pbeEnsure.Pricebook2Id, 'Pediasure');
        PricebookEntry pbeSimilac = TestDataFactory.createProductAndPricebookEntryDiffBrand('PH', 'USD', pbeEnsure.Pricebook2Id, 'Similac');
        List<Membership__c> membershipInsertList = new List<Membership__c>();
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(-2), Date.Today().addDays(-1), '9222 1111 1111 11111 1', pbeEnsure.Product2Id, 'Expired'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(-2), Date.Today().addDays(-1), '9222 2111 1111 11111 1', pbeGlucerna.Product2Id, 'Expired'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(-2), Date.Today().addDays(-1), '9222 4111 1111 11111 1', pbePediasure.Product2Id, 'Expired'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(-2), Date.Today().addDays(-1), '9222 5111 1111 11111 1', pbeSimilac.Product2Id, 'Expired'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 1111 1111 11111 2', pbeEnsure.Product2Id, 'New'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 2111 1111 11111 2', pbeGlucerna.Product2Id, 'New'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 4111 1111 11111 2', pbePediasure.Product2Id, 'New'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 5111 1111 11111 2', pbeSimilac.Product2Id, 'New'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 1111 1111 11111 3', pbeEnsure.Product2Id, 'New'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 2111 1111 11111 3', pbeGlucerna.Product2Id, 'New'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 4111 1111 11111 3', pbePediasure.Product2Id, 'New'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 5111 1111 11111 3', pbeSimilac.Product2Id, 'New'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 1111 1111 11111 4', null, 'New'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 2111 1111 11111 4', null, 'New'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 4111 1111 11111 4', null, 'New'));
        membershipInsertList.add(TestDataFactory.createMembershipRecord(con.Id, Date.Today().addDays(1), Date.Today().addDays(2), '9222 5111 1111 11111 4', null, 'New'));
        insert membershipInsertList;
        for(Membership__c mem : [SELECT Id FROM Membership__c WHERE MembershipId__c like '%111 2']){
            Test.setCreatedDate(mem.id, Date.Today().addDays(-1));
        }
    }
    static testmethod void testcopyMembershipToContact_Insert(){
        Contact con = [SELECT Id FROM Contact WHERE Phone = '0999999999'][0];
        List<Membership__c> membershipInsertList = new List<Membership__c>();
        for(PricebookEntry pbe : [SELECT Id, Product2Id, Product2.Keybrand__c FROM PricebookEntry]){
            Membership__c mem = new Membership__c();
            if(pbe.Product2.Keybrand__c == 'Ensure') mem = TestDataFactory.createMembershipRecord(con.Id, Date.Today(), Date.Today().addDays(1), '9222 1111 1111 11111 5', pbe.Product2Id, 'Activated');
            else if(pbe.Product2.Keybrand__c == 'Glucerna') mem = TestDataFactory.createMembershipRecord(con.Id, Date.Today(), Date.Today().addDays(1), '9222 2111 1111 11111 5', pbe.Product2Id, 'Activated');
            else if(pbe.Product2.Keybrand__c == 'Pediasure') mem = TestDataFactory.createMembershipRecord(con.Id, Date.Today(), Date.Today().addDays(1), '9222 4111 1111 11111 5', pbe.Product2Id, 'Activated');
            else if(pbe.Product2.Keybrand__c == 'Similac') mem = TestDataFactory.createMembershipRecord(con.Id, Date.Today(), Date.Today().addDays(1), '9222 5111 1111 11111 5', pbe.Product2Id, 'Activated');
            membershipInsertList.add(mem);
        }
        Test.startTest();
        insert membershipInsertList;
        Test.stopTest();
        Contact conCheck = [SELECT Id, MembershipId_Ensure__c, MembershipId_Glucerna__c, MembershipId_Pediasure__c, MembershipId_Similac__c, 
                            MembershipNumberOfDaysDormant_Ensure__c, MembershipNumberOfDaysDormant_Glucerna__c, MembershipNumberOfDaysDormant_Pediasure__c, MembershipNumberOfDaysDormant_Similac__c,
                            MembershipNumberOfTransactions_Ensure__c, MembershipNumberOfTransactions_Glucerna__c, MembershipNumberOfTransactions_Pediasure__c, MembershipNumberOfTransactions_Similac__c,
                            MembershipRecentProduct_Ensure__c, MembershipRecentProduct_Glucerna__c, MembershipRecentProduct_Pediasure__c, MembershipRecentProduct_Similac__c,
                            MembershipStartDate_Ensure__c, MembershipStartDate_Glucerna__c, MembershipStartDate_Pediasure__c, MembershipStartDate_Similac__c, 
                            MembershipStatus_Ensure__c, MembershipStatus_Glucerna__c, MembershipStatus_Pediasure__c, MembershipStatus_Similac__c FROM Contact WHERE Id =: con.Id][0];
        System.assertEquals(conCheck.MembershipId_Ensure__c, '9222 1111 1111 11111 5');
        System.assertEquals(conCheck.MembershipId_Glucerna__c, '9222 2111 1111 11111 5');
        System.assertEquals(conCheck.MembershipId_Pediasure__c, '9222 4111 1111 11111 5');
        System.assertEquals(conCheck.MembershipId_Similac__c, '9222 5111 1111 11111 5');
        System.assertEquals(conCheck.MembershipStatus_Ensure__c, 'Activated');
        System.assertEquals(conCheck.MembershipStatus_Glucerna__c, 'Activated');
        System.assertEquals(conCheck.MembershipStatus_Pediasure__c, 'Activated');
        System.assertEquals(conCheck.MembershipStatus_Similac__c, 'Activated');
    }
    static testmethod void testcopyMembershipToContact_Update(){
        Contact con = [SELECT Id FROM Contact WHERE Phone = '0999999999'][0];
        List<Membership__c> membershipUpdateList = new List<Membership__c>();
        for(Membership__c mem : [SELECT Id FROM Membership__c WHERE MembershipId__c like '%111 3']){
            mem.Status__c = 'Activated';
            mem.MembershipStartDate__c = Date.Today();
            mem.NumberOfTransactions__c = 1;
            membershipUpdateList.add(mem);
        }
        Test.startTest();
        update membershipUpdateList;
        Test.stopTest();
        Contact conCheck = [SELECT Id, MembershipId_Ensure__c, MembershipId_Glucerna__c, MembershipId_Pediasure__c, MembershipId_Similac__c, 
                            MembershipNumberOfDaysDormant_Ensure__c, MembershipNumberOfDaysDormant_Glucerna__c, MembershipNumberOfDaysDormant_Pediasure__c, MembershipNumberOfDaysDormant_Similac__c,
                            MembershipNumberOfTransactions_Ensure__c, MembershipNumberOfTransactions_Glucerna__c, MembershipNumberOfTransactions_Pediasure__c, MembershipNumberOfTransactions_Similac__c,
                            MembershipRecentProduct_Ensure__c, MembershipRecentProduct_Glucerna__c, MembershipRecentProduct_Pediasure__c, MembershipRecentProduct_Similac__c,
                            MembershipStartDate_Ensure__c, MembershipStartDate_Glucerna__c, MembershipStartDate_Pediasure__c, MembershipStartDate_Similac__c, 
                            MembershipStatus_Ensure__c, MembershipStatus_Glucerna__c, MembershipStatus_Pediasure__c, MembershipStatus_Similac__c FROM Contact WHERE Id =: con.Id][0];
        System.assertEquals(conCheck.MembershipId_Ensure__c, '9222 1111 1111 11111 3');
        System.assertEquals(conCheck.MembershipId_Glucerna__c, '9222 2111 1111 11111 3');
        System.assertEquals(conCheck.MembershipId_Pediasure__c, '9222 4111 1111 11111 3');
        System.assertEquals(conCheck.MembershipId_Similac__c, '9222 5111 1111 11111 3');
        System.assertEquals(conCheck.MembershipStatus_Ensure__c, 'Activated');
        System.assertEquals(conCheck.MembershipStatus_Glucerna__c, 'Activated');
        System.assertEquals(conCheck.MembershipStatus_Pediasure__c, 'Activated');
        System.assertEquals(conCheck.MembershipStatus_Similac__c, 'Activated');
        System.assertEquals(conCheck.MembershipStartDate_Ensure__c, Date.Today());
        System.assertEquals(conCheck.MembershipStartDate_Glucerna__c, Date.Today());
        System.assertEquals(conCheck.MembershipStartDate_Pediasure__c, Date.Today());
        System.assertEquals(conCheck.MembershipStartDate_Similac__c, Date.Today());
        System.assertEquals(conCheck.MembershipNumberOfTransactions_Ensure__c, 1);
        System.assertEquals(conCheck.MembershipNumberOfTransactions_Glucerna__c, 1);
        System.assertEquals(conCheck.MembershipNumberOfTransactions_Pediasure__c, 1);
        System.assertEquals(conCheck.MembershipNumberOfTransactions_Similac__c, 1);
    }
}