force-app/main/default/objects/Contact/fields/MembershipId_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipId_Ensure__c</fullName>
    <label>Membership Id Ensure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipId_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipId_Glucerna__c</fullName>
    <label>Membership Id Glucerna</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipId_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipId_Pediasure__c</fullName>
    <label>Membership Id Pediasure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipId_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipId_Similac__c</fullName>
    <label>Membership Id Similac</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfDaysDormant_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfDaysDormant_Ensure__c</fullName>
    <label>MembershipNumberOfDaysDormant Ensure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfDaysDormant_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfDaysDormant_Glucerna__c</fullName>
    <label>MembershipNumberOfDaysDormant Glucerna</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfDaysDormant_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfDaysDormant_Pediasure__c</fullName>
    <label>MembershipNumberOfDaysDormant Pediasure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfDaysDormant_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfDaysDormant_Similac__c</fullName>
    <label>MembershipNumberOfDaysDormant Similac</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfTransactions_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfTransactions_Ensure__c</fullName>
    <label>MembershipNumberOfTransactions Ensure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfTransactions_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfTransactions_Glucerna__c</fullName>
    <label>MembershipNumberOfTransactions Glucerna</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfTransactions_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfTransactions_Pediasure__c</fullName>
    <label>MembershipNumberOfTransactions Pediasure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipNumberOfTransactions_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipNumberOfTransactions_Similac__c</fullName>
    <label>MembershipNumberOfTransactions Similac</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipRecentProduct_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipRecentProduct_Ensure__c</fullName>
    <label>Membership Recent Product Ensure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipRecentProduct_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipRecentProduct_Glucerna__c</fullName>
    <label>Membership Recent Product Glucerna</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipRecentProduct_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipRecentProduct_Pediasure__c</fullName>
    <label>Membership Recent Product Pediasure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipRecentProduct_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipRecentProduct_Similac__c</fullName>
    <label>Membership Recent Product Similac</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate_Ensure__c</fullName>
    <label>Membership Start Date Ensure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate_Glucerna__c</fullName>
    <label>Membership Start Date Glucerna</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate_Pediasure__c</fullName>
    <label>Membership Start Date Pediasure</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate_Similac__c</fullName>
    <label>Membership Start Date Similac</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStatus_Ensure__c.field-meta.xml
<CustomField>
    <fullName>MembershipStatus_Ensure__c</fullName>
    <label>Membership Status Ensure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStatus_Glucerna__c.field-meta.xml
<CustomField>
    <fullName>MembershipStatus_Glucerna__c</fullName>
    <label>Membership Status Glucerna</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStatus_Pediasure__c.field-meta.xml
<CustomField>
    <fullName>MembershipStatus_Pediasure__c</fullName>
    <label>Membership Status Pediasure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStatus_Similac__c.field-meta.xml
<CustomField>
    <fullName>MembershipStatus_Similac__c</fullName>
    <label>Membership Status Similac</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipId__c.field-meta.xml
<CustomField>
    <fullName>MembershipId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Membership Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/NumberOfDaysDormant__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysDormant__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Days Dormant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/NumberOfTransactions__c.field-meta.xml
<CustomField>
    <fullName>NumberOfTransactions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Recent_Product_Purchased__c.field-meta.xml
<CustomField>
    <fullName>Recent_Product_Purchased__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recent Product Purchased</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MembershipTriggerHelper.cls
/*
Author: Frank Gomendoza
Description: Helper class for Membership object
History:
08/04/2022   fgomendoza    Created copyMembershipToContact and all method dependencies
*/
public class MembershipTriggerHelper {
    public static Map<String, String> brandCodeMap = new Map<String, String>{'92221' => 'Ensure', '92222' => 'Glucerna', '92224' => 'Pediasure', '92225' => 'Similac'};
    public static Map<Id, Product2> productMap = new Map<Id, Product2>();
    public static Map<Id, Contact> conUpdateMap = new Map<Id, Contact>();  
    
    public static void copyMembershipToContact(Map<Id, SObject> oldMap, Map<Id, Membership__c> newMap){
        if(Trigger.isInsert || Trigger.isUpdate){
            Set<Id> productIdSet = new Set<Id>();
            List<Membership__c> membershipList = new List<Membership__c>();
            Map<Id, Map<String, Membership__c>> contactNewBrandMembershipMap = new Map<Id, Map<String, Membership__c>>();
            Map<Id, Map<String, Membership__c>> contactExistingBrandMembershipMap = new Map<Id, Map<String, Membership__c>>();
            System.debug('newMap: '+newMap);
            System.debug('oldMap: '+oldMap);
            //Get New Valid Membership records
            for(Membership__c memNew : newMap.values()){
                if(!String.isBlank(memNew.MembershipId__c) && memNew.Contact__c != null){
                    contactNewBrandMembershipMap = createBrandMembershipMap(contactNewBrandMembershipMap, memNew);
                    if(memNew.Recent_Product_Purchased__c != null){
                        productIdSet.add(memNew.Recent_Product_Purchased__c);
                    }
                }
            }
            //Get Existing Membership records to compare 
            for(Membership__c existingMem : [SELECT Id, Contact__c, MembershipId__c, Status__c, NumberOfDaysDormant__c, NumberOfTransactions__c, MembershipStartDate__c, Recent_Product_Purchased__c, CreatedDate FROM Membership__c 
                                             WHERE Contact__c IN: contactNewBrandMembershipMap.keySet() AND Id NOT IN: newMap.keySet() AND MembershipId__c != null])
            {
                contactExistingBrandMembershipMap = createBrandMembershipMap(contactExistingBrandMembershipMap, existingMem);
                if(existingMem.Recent_Product_Purchased__c != null){
                    productIdSet.add(existingMem.Recent_Product_Purchased__c);
                }
            }
            for(Product2 p : [SELECT Id, Name FROM Product2 WHERE Id IN: productIdSet]){
                productMap.put(p.Id, p);
            }
            for(Id conId : contactNewBrandMembershipMap.keySet()){
                Map<String, Membership__c> memMap = contactNewBrandMembershipMap.get(conId);
                membershipList.addAll(memMap.values());
            }
            //Compare incoming membership to existing membership
            for(Membership__c mem : membershipList){
                String rawMembershipId = mem.MembershipId__c.replaceAll('(\\s+)', '');
                String brand = brandCodeMap.get(rawMembershipId.left(5));
                if(contactExistingBrandMembershipMap.containsKey(mem.Contact__c)){
                    if(contactExistingBrandMembershipMap.get(mem.Contact__c).containsKey(brand)){
                        Membership__c existingMem = contactExistingBrandMembershipMap.get(mem.Contact__c).get(brand);
                        if(existingMem.Status__c == 'Expired' && mem.Status__c != 'Expired'){
                            conUpdateMap = processContactUpdateMap(mem, brand);
                        }
                        else if(existingMem.Status__c != 'Expired' && mem.Status__c == 'Expired'){
                            conUpdateMap = processContactUpdateMap(existingMem, brand);
                        }
                        else if( (existingMem.Status__c == 'Activated' || existingMem.Status__c == 'New') && 
                                (mem.Status__c == 'Activated' || mem.Status__c == 'New') && existingMem.CreatedDate < mem.CreatedDate){
                            conUpdateMap = processContactUpdateMap(mem, brand);
                        }
                        else if( (existingMem.Status__c == 'Activated' || existingMem.Status__c == 'New') && 
                                (mem.Status__c == 'Activated' || mem.Status__c == 'New') && existingMem.CreatedDate > mem.CreatedDate){
                            conUpdateMap = processContactUpdateMap(existingMem, brand);
                        }
                        else if( (existingMem.Status__c == 'Activated' || existingMem.Status__c == 'New') && 
                                (mem.Status__c == 'Activated' || mem.Status__c == 'New') && existingMem.CreatedDate == mem.CreatedDate 
                                && String.isBlank(existingMem.Recent_Product_Purchased__c) && !String.isBlank(mem.Recent_Product_Purchased__c))
                        {
                            conUpdateMap = processContactUpdateMap(mem, brand);
                        }
                        
                    }
                    else{
                        conUpdateMap = processContactUpdateMap(mem, brand);
                    }
                }
                else{
                    conUpdateMap = processContactUpdateMap(mem, brand);
                }
            }
            
        }
        else if(Trigger.isDelete){
        }
        
        if(!conUpdateMap.keySet().isEmpty()){
            update conUpdateMap.values();
        }
    }
    
    public static Map<Id, Contact> processContactUpdateMap(Membership__c mem, String brand){
        if(conUpdateMap.containsKey(mem.Contact__c)){
            Contact con = conUpdateMap.get(mem.Contact__c);
            conUpdateMap.put(mem.Contact__c, updateContactMembershipInfo(mem, brand, con));
        }
        else{
            conUpdateMap.put(mem.Contact__c, updateContactMembershipInfo(mem, brand, null));
        }
        return conUpdateMap;
    }
    
    public static Contact updateContactMembershipInfo(Membership__c member, String brand, Contact con){
        Contact c = new Contact();
        if(con == null){
            c.Id = member.Contact__c;
        }
        else{
            c = con;
        }
        if(brand == 'Ensure'){
            c.MembershipId_Ensure__c = member.MembershipId__c;
            c.MembershipNumberOfDaysDormant_Ensure__c = member.NumberOfDaysDormant__c;
            c.MembershipNumberOfTransactions_Ensure__c = member.NumberOfTransactions__c;
            c.MembershipStartDate_Ensure__c = member.MembershipStartDate__c;
            c.MembershipStatus_Ensure__c = member.Status__c;
            c.MembershipRecentProduct_Ensure__c = productMap.containsKey(member.Recent_Product_Purchased__c) ? productMap.get(member.Recent_Product_Purchased__c).Name : null;
        }
        else if(brand == 'Glucerna'){
            c.MembershipId_Glucerna__c = member.MembershipId__c;
            c.MembershipNumberOfDaysDormant_Glucerna__c = member.NumberOfDaysDormant__c;
            c.MembershipNumberOfTransactions_Glucerna__c = member.NumberOfTransactions__c;
            c.MembershipStartDate_Glucerna__c = member.MembershipStartDate__c;
            c.MembershipStatus_Glucerna__c = member.Status__c;
            c.MembershipRecentProduct_Glucerna__c = productMap.containsKey(member.Recent_Product_Purchased__c) ? productMap.get(member.Recent_Product_Purchased__c).Name : null;
        }
        else if(brand == 'Pediasure'){
            c.MembershipId_Pediasure__c = member.MembershipId__c;
            c.MembershipNumberOfDaysDormant_Pediasure__c = member.NumberOfDaysDormant__c;
            c.MembershipNumberOfTransactions_Pediasure__c = member.NumberOfTransactions__c;
            c.MembershipStartDate_Pediasure__c = member.MembershipStartDate__c;
            c.MembershipStatus_Pediasure__c = member.Status__c;
            c.MembershipRecentProduct_Pediasure__c = productMap.containsKey(member.Recent_Product_Purchased__c) ? productMap.get(member.Recent_Product_Purchased__c).Name : null;
        }
        else if(brand == 'Similac'){
            c.MembershipId_Similac__c = member.MembershipId__c;
            c.MembershipNumberOfDaysDormant_Similac__c = member.NumberOfDaysDormant__c;
            c.MembershipNumberOfTransactions_Similac__c = member.NumberOfTransactions__c;
            c.MembershipStartDate_Similac__c = member.MembershipStartDate__c;
            c.MembershipStatus_Similac__c = member.Status__c;
            c.MembershipRecentProduct_Similac__c = productMap.containsKey(member.Recent_Product_Purchased__c) ? productMap.get(member.Recent_Product_Purchased__c).Name : null;
        }
        return c;
    }
    
    public static Map<Id, Map<String, Membership__c>> createBrandMembershipMap(Map<Id, Map<String, Membership__c>> contactBrandMembershipMap, Membership__c mem){
        String rawMembershipId = mem.MembershipId__c.replaceAll('(\\s+)', '');
        if(brandCodeMap.keySet().contains(rawMembershipId.left(5)) ){
            String brand = brandCodeMap.get(rawMembershipId.left(5));
            if(!contactBrandMembershipMap.containsKey(mem.Contact__c)){
                contactBrandMembershipMap.put(mem.Contact__c, new Map<String, Membership__c>());
            }
            if(contactBrandMembershipMap.get(mem.Contact__c).containsKey(brand)){
                Membership__c memberBrand = contactBrandMembershipMap.get(mem.Contact__c).get(brand);
                if(memberBrand.Status__c == 'Expired' && mem.Status__c != 'Expired'){
                    contactBrandMembershipMap.get(mem.Contact__c).put(brand, mem);
                }
                else if( (memberBrand.Status__c == 'Activated' || memberBrand.Status__c == 'New') && 
                        (mem.Status__c == 'Activated' || mem.Status__c == 'New') && memberBrand.CreatedDate < mem.CreatedDate){
                            contactBrandMembershipMap.get(mem.Contact__c).put(brand, mem);
                        }
                else if((memberBrand.Status__c == 'Activated' || memberBrand.Status__c == 'New') && 
                        (mem.Status__c == 'Activated' || mem.Status__c == 'New') && memberBrand.CreatedDate == mem.CreatedDate 
                        && String.isBlank(memberBrand.Recent_Product_Purchased__c) && !String.isBlank(mem.Recent_Product_Purchased__c))
                {
                    contactBrandMembershipMap.get(mem.Contact__c).put(brand, mem);
                }
            }
            else{
                contactBrandMembershipMap.get(mem.Contact__c).put(brand, mem);
            }
        }
        return contactBrandMembershipMap;
    }
    
}