force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RewardPoints__c.field-meta.xml
<CustomField>
    <fullName>RewardPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Reward Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>Customers are able to earn and redeem rewards based on their points</description>
    <label>Reward</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Reward Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Default value is &quot;TRUE&quot;</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reward__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reward__c/fields/ExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>ExpiryDate__c</fullName>
    <formula>IF(Contact__r.Market__c != &apos;&apos;, 
ADDMONTHS(IF(MONTH(IF(RecordType.DeveloperName = &apos;Earn&apos;, AwardDate__c, IF(RecordType.DeveloperName = &apos;Adjust_Add&apos;, AdjustmentDate__c, null))) = 12, DATE(YEAR(IF(RecordType.DeveloperName = &apos;Earn&apos;, AwardDate__c, IF(RecordType.DeveloperName = &apos;Adjust_Add&apos;, AdjustmentDate__c, null))), 12, 31 ), DATE(YEAR(IF(RecordType.DeveloperName = &apos;Earn&apos;, AwardDate__c, IF(RecordType.DeveloperName = &apos;Adjust_Add&apos;, AdjustmentDate__c, null))), MONTH(IF(RecordType.DeveloperName = &apos;Earn&apos;, AwardDate__c, IF(RecordType.DeveloperName = &apos;Adjust_Add&apos;, AdjustmentDate__c, null))) + 1, 1) - 1), 
IF(Contact__r.Market__c = &quot;MY&quot;, $CustomMetadata.AffiliateMetadata__mdt.MY.RewardPointsValidPeriod__c, 
IF(Contact__r.Market__c = &quot;PH&quot;, $CustomMetadata.AffiliateMetadata__mdt.PH.RewardPointsValidPeriod__c, 
IF(Contact__r.Market__c = &quot;SG&quot;, $CustomMetadata.AffiliateMetadata__mdt.SG.RewardPointsValidPeriod__c, 
IF(Contact__r.Market__c = &quot;TH&quot;, $CustomMetadata.AffiliateMetadata__mdt.TH.RewardPointsValidPeriod__c, 
IF(Contact__r.Market__c = &quot;VN&quot;, $CustomMetadata.AffiliateMetadata__mdt.VN.RewardPointsValidPeriod__c, 0)))))), 
null 
)</formula>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reward__c/fields/PointsAmount__c.field-meta.xml
<CustomField>
    <fullName>PointsAmount__c</fullName>
    <label>Points Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reward__c/recordTypes/Earn.recordType-meta.xml
<RecordType>
    <fullName>Earn</fullName>
    <active>true</active>
    <label>Earn</label>
</RecordType>

force-app/main/default/classes/DeactivateRewardsBatch.cls
/*----------------------------------------------------------------------------------------
Author:      Viana Flor Mirandilla
Description: Batch Class to Deactivate Rewards based on Expiry Date value

History
01/15/2019   vmirandilla   Created
02/22/2021   malviz        TKT-003431: Added checking on primary contact mobile
-------------------------------------------------------------------------------------------*/
public class DeactivateRewardsBatch implements Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Active__c,'
                            + ' ExpiryDate__c,'
                            + ' Contact__c,Contact__r.Phone,Contact__r.PrimaryContact__c,'
                            + ' RecordType.Name,'
                            + ' PointsAmount__c'
                            + ' FROM Reward__c'
                            + ' WHERE'
                            + ' (RecordType.Name = \'Earn\' OR RecordType.Name = \'Adjust (Add)\') AND Active__c = TRUE AND ExpiryDate__c <= TODAY';
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Reward__c > scope) {
        
        Set<Id> conIdSet = new Set<Id>();
        Boolean hasMobile = true;
        for(Reward__c rec : scope) {
            //phone is mandatory for primary contacts
            //check if primary contact has mobile to prevent validation error upon saving contact
            if(rec.Contact__r.PrimaryContact__c = true && rec.Contact__r.Phone == null){
                hasMobile = false;
            }
            if(rec.Contact__c != null && hasMobile) {
                conIdSet.add(rec.Contact__c);
            }
        }
        
        Map<Id,Contact> conMap = new Map<Id,Contact>([Select Id, RewardPoints__c
                                                            FROM Contact
                                                            WHERE Id IN :conIdSet]);
        Map<Id, Contact> conUpdateMap = new Map<Id, Contact>();
        List<Reward__c> rewardUpdateList = new List<Reward__c>();
        for(Reward__c reward : scope) {
            if(conMap.containsKey(reward.Contact__c)) {
                Decimal rewardPointsAmount;
                Decimal conRewardPoints;
                Contact updatedCon;
                Contact con = conMap.get(reward.Contact__c);
                if(!conUpdateMap.containsKey(con.Id)){
                    updatedCon = con;
                }
                else{
                    updatedCon = conUpdateMap.get(con.Id);
                }

                rewardPointsAmount = reward.PointsAmount__c != null ? reward.PointsAmount__c : 0;
                conRewardPoints = updatedCon.RewardPoints__c != null ? updatedCon.RewardPoints__c : 0;
                if(rewardPointsAmount > conRewardPoints) {
                    updatedCon.RewardPoints__c = 0;
                } else {
                    updatedCon.RewardPoints__c = conRewardPoints - rewardPointsAmount;
                }
                reward.Active__c = FALSE;
                conUpdateMap.put(updatedCon.Id, updatedCon);
                rewardUpdateList.add(reward);
            }
        }

        if(!rewardUpdateList.isEmpty()) UtilityClass.updateList(rewardUpdateList);
        if(!conUpdateMap.keySet().isEmpty()) UtilityClass.updateList(conUpdateMap.values());
    }
    
    public void finish(Database.BatchableContext BC) {
    }
}