force-app/main/default/objects/Contact/fields/RewardPoints__c.field-meta.xml
<CustomField>
    <fullName>RewardPoints__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Reward Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AvailableForRewardRedemption__c.field-meta.xml
<CustomField>
    <fullName>AvailableForRewardRedemption__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available for Reward Redemption</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/RewardsPointsRequired__c.field-meta.xml
<CustomField>
    <fullName>RewardsPointsRequired__c</fullName>
    <description>Reward points required for redemption</description>
    <label>Rewards Points Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>Customers are able to earn and redeem rewards based on their points</description>
    <label>Reward</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Reward Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reward__c/fields/DeliveryStatus__c.field-meta.xml
<CustomField>
    <fullName>DeliveryStatus__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
                <label>Submitted</label>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Out For Delivery</fullName>
            </value>
            <value>
                <fullName>Cancelled Before Delivery</fullName>
            </value>
            <value>
                <fullName>Cancelled Upon Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reward__c/fields/ProductForRedemption__c.field-meta.xml
<CustomField>
    <fullName>ProductForRedemption__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filter lookup to show only Product records where &quot;Available for Reward Redemption&quot; checkbox is TRUE</description>
    <label>Product for Redemption</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND ((3 OR 4) OR (5 AND 6))</booleanFilter>
        <filterItems>
            <field>Product2.AvailableForRewardRedemption__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RewardReportGeneratorControllerTest.cls
/*
* @author        Rey Austral
* @date          4.17.2019
* @description   Test class for RewardReportGeneratorController
* @revision(s) 
*/
@isTest
private class RewardReportGeneratorControllerTest {
	
	@testsetup
    static void setupData() {
    	User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'PH');
        insert sysad;
        
        System.runAs(sysad) {	    		    	
			List<Account> lAccount = TestDataFactory.createTestHousehold(1);
			List<Contact> lContact = TestDataFactory.createTestAdultContact(1, lAccount.get(0).Id);
			lContact.get(0).RewardPoints__c = 1000;
			Update lContact;

			List<Reward__c> lReward = TestDataFactory.createReward(4,lContact.get(0).Id, Date.today());
			List<Reward__c> lRedeemReward = TestDataFactory.createReward(2,lContact.get(0).Id, Date.today());
			
			List<Product2> lProduct = TestDataFactory.createTestBrandProduct(1);	      
	        lProduct[0].AvailableForRewardRedemption__c = TRUE;
	        lProduct[0].RewardsPointsRequired__c = 200;
	        update lProduct[0];

			Id recTypeId = Schema.SObjectType.Reward__c.getRecordTypeInfosByName().get(CommonConstant.REWARD_REDEEM_RECORDTYPE).getRecordTypeId();
			for(Reward__c rew : lRedeemReward) {
				rew.RecordTypeId = recTypeId;
				rew.DeliveryStatus__c =  CommonConstant.ORDER_STATUS_SUBMITTED;
				rew.Quantity__c = 1;
				rew.ProductForRedemption__c = lProduct.get(0).Id;
			}

			Update lRedeemReward;
		}
    }

	@isTest
	static void test_queryOrderItemReport() {
		User sysad = [Select id from User where Alias='tstSysAd' Limit 1];
		System.runAs(sysad) {	    	
			System.Test.startTest();
			System.debug([SELECT Id, Name FROM ContentWorkspace]);
				List<Reward__c> rewardList = RewardReportGeneratorController.queryRewardItemReport();
				RewardReportGeneratorController controller = new RewardReportGeneratorController();
				RewardReportGeneratorController.RewardReportWrapper filestring = RewardReportGeneratorController.getExcelFileAsBase64String();
			System.Test.stopTest();
		

			System.assertEquals(2 , rewardList.size());
			System.assertEquals('VW5pdC5UZXN0', filestring.fileContent);
		}
	}
	
}