force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/fields/AdditionalEscalationPointEmail1__c.field-meta.xml
<CustomField>
    <fullName>AdditionalEscalationPointEmail1__c</fullName>
    <label>Additional Escalation Point Email 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/fields/AdditionalEscalationPointEmail2__c.field-meta.xml
<CustomField>
    <fullName>AdditionalEscalationPointEmail2__c</fullName>
    <label>Additional Escalation Point Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/fields/AdditionalEscalationPointEmail3__c.field-meta.xml
<CustomField>
    <fullName>AdditionalEscalationPointEmail3__c</fullName>
    <label>Additional Escalation Point Email 3</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/fields/AdditionalEscalationPointEmail4__c.field-meta.xml
<CustomField>
    <fullName>AdditionalEscalationPointEmail4__c</fullName>
    <label>Additional Escalation Point Email 4</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/fields/ChannelType__c.field-meta.xml
<CustomField>
    <fullName>ChannelType__c</fullName>
    <label>Channel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/fields/EscalationLevel__c.field-meta.xml
<CustomField>
    <fullName>EscalationLevel__c</fullName>
    <label>Escalation Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/fields/MainEscalationPointEmail2__c.field-meta.xml
<CustomField>
    <fullName>MainEscalationPointEmail2__c</fullName>
    <label>Main Escalation Point Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/fields/MainEscalationPointEmail__c.field-meta.xml
<CustomField>
    <fullName>MainEscalationPointEmail__c</fullName>
    <label>Main Escalation Point Email 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Affiliate Values (Product)</relationshipLabel>
    <relationshipName>Affiliate_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/State.recordType-meta.xml
<RecordType>
    <fullName>State</fullName>
    <active>true</active>
    <description>Defines the state available for selection while creating and updating addresses.</description>
    <label>State</label>
</RecordType>

force-app/main/default/objects/AffiliateMetadata__mdt/AffiliateMetadata__mdt.object-meta.xml
<CustomObject>
    <label>Affiliate Metadata</label>
    <pluralLabel>Affiliate Metadatas</pluralLabel>
</CustomObject>

force-app/main/default/objects/AffiliateMetadata__mdt/fields/FeedbackEscalationOrgWideEmail__c.field-meta.xml
<CustomField>
    <fullName>FeedbackEscalationOrgWideEmail__c</fullName>
    <label>Feedback Escalation Org Wide Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/AdditionalEscalationPointEmail1__c.field-meta.xml
<CustomField>
    <fullName>AdditionalEscalationPointEmail1__c</fullName>
    <label>Additional Escalation Point Email 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/AdditionalEscalationPointEmail2__c.field-meta.xml
<CustomField>
    <fullName>AdditionalEscalationPointEmail2__c</fullName>
    <label>Additional Escalation Point Email 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/AdditionalEscalationPointEmail3__c.field-meta.xml
<CustomField>
    <fullName>AdditionalEscalationPointEmail3__c</fullName>
    <label>Additional Escalation Point Email 3</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/ChannelType__c.field-meta.xml
<CustomField>
    <fullName>ChannelType__c</fullName>
    <formula>TEXT(Channel__r.Type__c)</formula>
    <label>Channel Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DaysOpen__c.field-meta.xml
<CustomField>
    <fullName>DaysOpen__c</fullName>
    <formula>IF(
    IsClosed,
    DATEVALUE(ClosedDate) - DATEVALUE(CreatedDate),
    TODAY() - DATEVALUE(CreatedDate)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day(s) Open</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND ((2 OR 3) OR (4 AND 5))) OR 6 OR 7</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>State</value>
        </filterItems>
        <infoMessage>Value should have a record type of State</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Cases (State)</relationshipLabel>
    <relationshipName>Cases_State</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/StoreWherePurchased__c.field-meta.xml
<CustomField>
    <fullName>StoreWherePurchased__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store Where Purchased</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseEscalation__mdt/CaseEscalation__mdt.object-meta.xml
<CustomObject>
    <label>Case Escalation</label>
    <pluralLabel>Case Escalations</pluralLabel>
</CustomObject>

force-app/main/default/objects/CaseEscalation__mdt/fields/DaysPassed__c.field-meta.xml
<CustomField>
    <fullName>DaysPassed__c</fullName>
    <label>Days Passed</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CaseEscalation__mdt/fields/EmailTemplatetoSend__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplatetoSend__c</fullName>
    <label>Email Template to Send</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseEscalation__mdt/fields/EscalationLevel__c.field-meta.xml
<CustomField>
    <fullName>EscalationLevel__c</fullName>
    <label>Escalation Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 2</fullName>
                <default>true</default>
                <label>Level 2</label>
            </value>
            <value>
                <fullName>Level 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseEscalation__mdt/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <referenceTo>AffiliateMetadata__mdt</referenceTo>
    <relationshipLabel>Case Escalations</relationshipLabel>
    <relationshipName>Case_Escalations</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Website</fullName>
            </value>
            <value>
                <fullName>Campaign Website</fullName>
            </value>
            <value>
                <fullName>Corporate Website</fullName>
            </value>
            <value>
                <fullName>Web - Others</fullName>
            </value>
            <value>
                <fullName>Modern</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Trade - Others</fullName>
            </value>
            <value>
                <fullName>Hospital/Clinic</fullName>
                <label>Hospital</label>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Ethical - Others</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Social - Others</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>Drug Store</fullName>
            </value>
            <value>
                <fullName>EC</fullName>
            </value>
            <value>
                <fullName>Ethical</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>MMC</fullName>
            </value>
            <value>
                <fullName>PX</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>MKT - Others</fullName>
                <isActive>false</isActive>
                <label>MKT - Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Channel_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Traditional</fullName>
    </customValue>
    <customValue>
        <fullName>Modern</fullName>
    </customValue>
    <masterLabel>Channel Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CaseFeedbackEscalation_Batch.cls
public class CaseFeedbackEscalation_Batch implements Database.Batchable<sObject>, Database.Stateful {
    
    private String market;
    private OrgWideEmailAddress owea = new OrgWideEmailAddress();
    private Id feedbackRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(CommonConstant.CASE_FEEDBACK_RECORDTYPE).getRecordTypeId();
    private Map<String, EmailTemplate> escalationTemplateMap = new Map<String, EmailTemplate>();
    private EmailTemplate escalationEmailTemplate = new EmailTemplate();
    private AffiliateMetadata__mdt country;
    private Contact dummyContact = new Contact();

    public CaseFeedbackEscalation_Batch(String m) {
        market = m;
        country = [SELECT MasterLabel, FeedbackEscalationOrgWideEmail__c,
                                                (SELECT EscalationLevel__c, EmailTemplatetoSend__c, DaysPassed__c FROM Case_Escalations__r WHERE isActive__c = true)
                                           FROM AffiliateMetadata__mdt
                                          WHERE MasterLabel =: m];

        // Set Org Wide Email -- Expecting only 1 since specific to market
        if(country.FeedbackEscalationOrgWideEmail__c != ''
            && country.FeedbackEscalationOrgWideEmail__c != null){
            owea = [SELECT Address, DisplayName FROM OrgWideEmailAddress WHERE Address =: country.FeedbackEscalationOrgWideEmail__c];
        }

        List<String> emailSet = new List<String>();
        for(CaseEscalation__mdt rules: country.Case_Escalations__r) {
            emailSet.add(rules.EmailTemplatetoSend__c);
        }

        // Setup email templates per level
        for(EmailTemplate template: [SELECT DeveloperName, Body, Subject FROM EmailTemplate WHERE DeveloperName IN: emailSet]) {
            for(CaseEscalation__mdt rules: country.Case_Escalations__r) {
                if(rules.EmailTemplatetoSend__c == template.DeveloperName) {
                    escalationTemplateMap.put(rules.EscalationLevel__c, template);
                }
            }
            escalationEmailTemplate = template;
        }

        try{
            dummyContact = [SELECT Id FROM Contact WHERE LastName =: 'Dummy Contact'];
        } catch (exception e) {
            dummyContact.LastName = 'Dummy Contact';
            insert dummyContact;
        }
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        Set<String> statusList = new Set<String> {'Closed - Resolved', 'Closed - Unresolved','Closed-Resolved', 'Closed-Unresolved'};
        
        String queryStr = 'SELECT CaseNumber, State__c, Product__c, StoreWherePurchased__r.Type__c, DaysOpen__c'
                        +  ' FROM Case'
                        + ' WHERE Market__c =: market'
                        + '   AND RecordTypeId =: feedbackRTId'
                        + '   AND Status NOT IN: statusList'
                        + '   AND (';
        
        Integer x = 0;
        Integer numberOfRules = country.Case_Escalations__r.size();

        for(CaseEscalation__mdt rules: country.Case_Escalations__r) {

            queryStr += 'DaysOpen__c = ' + rules.DaysPassed__c;

            x++;
            if(x != numberOfRules) {
                queryStr += ' OR ';
            }
        }

        if(Test.isRunningTest()) {
            queryStr += ' OR DaysOpen__c = 0';
        }

        queryStr += ')';

        return Database.getQueryLocator(queryStr);
    }
    
    public void execute(Database.BatchableContext BC, List<Case> cList) {

        List<Messaging.SingleEmailMessage> messages = new List<Messaging.SingleEmailMessage>();

        Set<Id> stateIDs = new Set<Id>();

        for(Case c: cList) {
            stateIDs.add(c.State__c);
        }

        // Key --> state|product|channelType|escalationLevel -- always level 1, create dynamic utility for this
        Map<String, Affiliate_Value__c> escalationMap = new Map<String, Affiliate_Value__c>();
        for(Affiliate_Value__c state: [SELECT (SELECT MainEscalationPointEmail__c, MainEscalationPointEmail2__c, EscalationLevel__c, ChannelType__c, Product__c,
                                                        AdditionalEscalationPointEmail1__c, AdditionalEscalationPointEmail2__c, AdditionalEscalationPointEmail3__c,
                                                        AdditionalEscalationPointEmail4__c, AdditionalEscalationPointEmail5__c, AdditionalEscalationPointEmail6__c
                                                    FROM Affiliate_Values__r
                                                WHERE Active__c = true)
                                        FROM Affiliate_Value__c
                                        WHERE Id IN: stateIDs]) {
            for(Affiliate_Value__c d: state.Affiliate_Values__r) {
                String key = state.Id + '|' + d.product__c + '|' + d.ChannelType__c + '|' + d.EscalationLevel__c;
                escalationMap.put(key, d);
            }
        }

        for(Case c: cList) {
            // loop custom metadata to compare level

            for(CaseEscalation__mdt rules: country.Case_Escalations__r) {
                String key = c.State__c + '|' + c.Product__c + '|' + c.StoreWherePurchased__r.Type__c + '|' + rules.EscalationLevel__c.right(1);
                
                // check if the has all it needed to send email
                if( escalationMap.containsKey(key)
                    && escalationTemplateMap.containsKey(rules.EscalationLevel__c)
                    && ( Test.isRunningTest()
                        || c.DaysOpen__c == rules.DaysPassed__c)
                    ){

                    c.LevelofEscalation__c = rules.EscalationLevel__c;

                    //set all emails addresses to send to
                    Affiliate_Value__c recipientTo = escalationMap.get(key);
                    List<String> toAddresses = new List<String>();
                    List<String> ccAddresses = new List<String>();

                    if(recipientTo.MainEscalationPointEmail__c != null) toAddresses.add(recipientTo.MainEscalationPointEmail__c);
                    if(recipientTo.MainEscalationPointEmail2__c != null) toAddresses.add(recipientTo.MainEscalationPointEmail2__c);

                    if(recipientTo.AdditionalEscalationPointEmail1__c != null) ccAddresses.add(recipientTo.AdditionalEscalationPointEmail1__c);
                    if(recipientTo.AdditionalEscalationPointEmail2__c != null) ccAddresses.add(recipientTo.AdditionalEscalationPointEmail2__c);
                    if(recipientTo.AdditionalEscalationPointEmail3__c != null) ccAddresses.add(recipientTo.AdditionalEscalationPointEmail3__c);
                    if(recipientTo.AdditionalEscalationPointEmail4__c != null) ccAddresses.add(recipientTo.AdditionalEscalationPointEmail4__c);
                    if(recipientTo.AdditionalEscalationPointEmail5__c != null) ccAddresses.add(recipientTo.AdditionalEscalationPointEmail5__c);
                    if(recipientTo.AdditionalEscalationPointEmail6__c != null) ccAddresses.add(recipientTo.AdditionalEscalationPointEmail6__c);

                    // set email template
                    EmailTemplate tempTemplate = escalationTemplateMap.get(c.LevelofEscalation__c);

                    // add email
                    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                    if(owea != null) { message.setOrgWideEmailAddressId(owea.Id); } // set sender if specified
                    message.settoAddresses(toAddresses);
                    message.setccAddresses(ccAddresses);
                    message.setTargetObjectId(dummyContact.Id);
                    message.setWhatId(c.Id);
                    message.setTemplateId(tempTemplate.Id);
                    message.setTreatTargetObjectAsRecipient(false);
                    message.saveAsActivity = true;
                    messages.add(message);

                    break;
                }
            }
        }

        UtilityClass.updateList(cList);

        if(!messages.isEmpty()){
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        }
    }

    public void finish(Database.BatchableContext BC){}
}