force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <formula>TEXT(BrandRelationship__r.KeyBrand__c)</formula>
    <label>Key Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Brand Relationships (Latest Channel Response)</relationshipLabel>
    <relationshipName>LatestChannelResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponseDate__c</fullName>
    <label>Latest Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Key Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elecare</fullName>
            </value>
            <value>
                <fullName>Ensure</fullName>
            </value>
            <value>
                <fullName>Ensure Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Flexifo</fullName>
            </value>
            <value>
                <fullName>Freego</fullName>
            </value>
            <value>
                <fullName>Glucerna</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>IMF</fullName>
            </value>
            <value>
                <fullName>Jevity</fullName>
            </value>
            <value>
                <fullName>Multi-Brand</fullName>
            </value>
            <value>
                <fullName>Pediasure</fullName>
            </value>
            <value>
                <fullName>Similac</fullName>
            </value>
            <value>
                <fullName>Similac Core</fullName>
            </value>
            <value>
                <fullName>Similac Mom</fullName>
            </value>
            <value>
                <fullName>Similac Total Comfort</fullName>
            </value>
            <value>
                <fullName>Nepro</fullName>
            </value>
            <value>
                <fullName>Osmolite</fullName>
            </value>
            <value>
                <fullName>RCF</fullName>
            </value>
            <value>
                <fullName>Twocal</fullName>
            </value>
            <value>
                <fullName>Vital 1.5Kcal</fullName>
            </value>
            <value>
                <fullName>Other MND</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Isomil</fullName>
            </value>
            <value>
                <fullName>Prosure</fullName>
            </value>
            <value>
                <fullName>Nepro HP</fullName>
                <isActive>false</isActive>
                <label>Nepro HP</label>
            </value>
            <value>
                <fullName>Nepro LP</fullName>
                <isActive>false</isActive>
                <label>Nepro LP</label>
            </value>
            <value>
                <fullName>Similac 3</fullName>
                <isActive>false</isActive>
                <label>Similac 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of Awareness will capture as campaign as well</description>
    <label>Call Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>TEXT(Channel__r.Category__c)</formula>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>LatestChannelResponse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponseDate__c</fullName>
    <label>Latest Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PreferredLanguage__c.field-meta.xml
<CustomField>
    <fullName>PreferredLanguage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred Language</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Preferred Language</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Contacts (Preferred Language)</relationshipLabel>
    <relationshipName>PreferredLanguages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SkillsBasedCriteriaMY.cls
/**
* @author        Rey Austral
* @date          1.29.2019           
* @description   Class responsible for getting the criteria needed for the skills routing
* @revision(s)
*/
public with sharing class SkillsBasedCriteriaMY {
	/*
    Consolidated to SkillsBaseCriteria class - Jeric
	public static Map<Id, Set<String>> determineRequiredSkills(List<Case> casesToDetermine) {		
        //get the contact of the case
        Set<Id> contactSet = new Set<Id>();
        for(Case cse : casesToDetermine) {
        	contactSet.add(cse.ContactId);
        }

        //query all the brand relationship, then get the latest channel response
        //this map will be used to get the channel of the case
        List<BrandRelationship__c> brandList = new LIst<BrandRelationship__c>();
        //Map<contactId, Map<keybrand, latest channel response value> >
        Map<Id, Map<String, String>> contactBrandMap = new Map<Id, Map<String, String>>();
        if (!contactSet.isEmpty()) {
        	
			for (Contact con : [Select Id, (Select Id, KeyBrand__c, LatestChannelResponse__r.Category__c From MainBrandRelationships__r order by LatestChannelResponseDate__c) 
                                From Contact Where Id in :contactSet]) {
				Map<String, String> brandChannelMap = new Map<String, String>();
				for (BrandRelationship__c brand : con.MainBrandRelationships__r) {
                    if ( String.isNotEmpty(brand.LatestChannelResponse__r.Category__c ) ) {
					   brandChannelMap.put(brand.KeyBrand__c, brand.LatestChannelResponse__r.Category__c);
                    }
				}
				contactBrandMap.put(con.Id, brandChannelMap);
			}

        }
        System.debug(contactBrandMap);
        
        Map<Id, Set<String>> callSkillsToReturn = new Map<Id, Set<String>>();
        for(Case caseRec : casesToDetermine) {           
        	Set<String> skillSet = new Set<String>();

            if(!callSkillsToReturn.containsKey(caseRec.Id)) {
            	//get the preferred language of the contact
                if(caseRec.ContactId != null && caseRec.Contact.PreferredLanguage__c != null) {
                    skillSet.add(CommonConstant.SKILL_LANGUAGE + caseRec.Contact.PreferredLanguage__r.Name);
                } 

                if (contactBrandMap.containsKey(caseRec.ContactId) && caseRec.Campaign__c != null) {
                	//since there are multiple brand in a contact
                	//get only the channel that belongs to the same brand of the campaign
                	Map<String, String> brandChannelMap = contactBrandMap.get(caseRec.ContactId);
                	if (brandChannelMap.containsKey(caseRec.Campaign__r.Brand__c)) {
                		skillSet.add(CommonConstant.SKILL_CHANNEL + brandChannelMap.get(caseRec.Campaign__r.Brand__c) );
                	}
                }
                //get the value of the brand in the campaign record
                if(caseRec.Campaign__c != null && String.isNotBlank( caseRec.Campaign__r.Brand__c ) ) {
                    if (caseRec.Campaign__r.Brand__c != 'Multi-Brand' && caseRec.Campaign__r.Brand__c != 'Others') {
                        skillSet.add(CommonConstant.SKILL_BRAND + caseRec.Campaign__r.Brand__c);
                    }                    
                } 

                if(caseRec.Campaign__c != null && String.isNotBlank(caseRec.Campaign__r.Market__c ) ) {
                    skillSet.add(CommonConstant.SKILL_MARKET + caseRec.Campaign__r.Market__c);
                }

                callSkillsToReturn.put(caseRec.Id, skillSet);
            }
        }
        System.debug(callSkillsToReturn);
        return callSkillsToReturn;
	}*/
}