force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>72</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Channel_Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Channel_Ref_No__c</fullName>
    <externalId>true</externalId>
    <label>Channel Ref No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>72</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/TH_Contact_Manual__c/TH_Contact_Manual__c.object-meta.xml
<CustomObject>
    <label>TH Contact Manual</label>
    <nameField>
        <label>TH  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TH Contact Manuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TH_Contact_Manual__c/fields/Addr_Country__c.field-meta.xml
<CustomField>
    <fullName>Addr_Country__c</fullName>
    <label>Addr_Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/BR_BrandID__c.field-meta.xml
<CustomField>
    <fullName>BR_BrandID__c</fullName>
    <label>BR_BrandID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/BR_RelationStatus__c.field-meta.xml
<CustomField>
    <fullName>BR_RelationStatus__c</fullName>
    <label>BR_RelationStatus</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/BR_RelationType__c.field-meta.xml
<CustomField>
    <fullName>BR_RelationType__c</fullName>
    <label>BR_RelationType</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/Child_DOB__c.field-meta.xml
<CustomField>
    <fullName>Child_DOB__c</fullName>
    <label>Child_DOB</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/Contact_DOB__c.field-meta.xml
<CustomField>
    <fullName>Contact_DOB__c</fullName>
    <label>Contact_DOB</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/Contact_EDD__c.field-meta.xml
<CustomField>
    <fullName>Contact_EDD__c</fullName>
    <label>Contact_EDD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/Contact_HomePhone__c.field-meta.xml
<CustomField>
    <fullName>Contact_HomePhone__c</fullName>
    <label>Contact_HomePhone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/Contact_LastName__c.field-meta.xml
<CustomField>
    <fullName>Contact_LastName__c</fullName>
    <label>Contact_LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/Contact_MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>Contact_MobilePhone__c</fullName>
    <label>Contact_MobilePhone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/Contact_OtherPhone__c.field-meta.xml
<CustomField>
    <fullName>Contact_OtherPhone__c</fullName>
    <label>Contact_OtherPhone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/Contact_PreferredLanguage__c.field-meta.xml
<CustomField>
    <fullName>Contact_PreferredLanguage__c</fullName>
    <label>Contact_PreferredLanguage</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/CR_CampaignID__c.field-meta.xml
<CustomField>
    <fullName>CR_CampaignID__c</fullName>
    <label>CR_CampaignID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/CR_ChannelID__c.field-meta.xml
<CustomField>
    <fullName>CR_ChannelID__c</fullName>
    <label>CR_ChannelID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TH_Contact_Manual__c/fields/CR_ChannelName__c.field-meta.xml
<CustomField>
    <fullName>CR_ChannelName__c</fullName>
    <label>CR_ChannelName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/THContactTriggerHandlerTest.cls
@isTest
private class THContactTriggerHandlerTest {
	@testsetup
    static void setupData() {
    	User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'TH');
        insert sysad;
        
        System.runAs(sysad) {
	    	List<Product2> lProduct = TestDataFactory.createTestBrandProduct(1);
	    	lProduct.get(0).Market__c = 'TH';
	    	lProduct.get(0).ProductCode = '123';
	    	Update lProduct;

			Id idRecType = Schema.sObjectType.Channel__c.getRecordTypeInfosByName().get(CommonConstant.CHANNEL_SOCIAL_RECORDTYPE).getRecordTypeId();
	    	List<Channel__c>  lChannel = TestDataFactory.createTestChannel(1);
	    	lChannel.get(0).Market__c = 'TH';
	    	lChannel.get(0).Channel_Ref_No__c = 'FB';
	    	lChannel.get(0).Name = 'FB';
			lChannel.get(0).RecordTypeId = idRecType;
	    	update lChannel;

	        TestDataFactory.createAffiliate('TH','English');
	        TestDataFactory.createAffiliate('TH','Malay');

	        Campaign cam = TestDataFactory.createCampaign('Cam','Similac','TH');
	        cam.ExternalId__c = '123';
	        Insert cam;

	       
	        List<Affiliate_Value__c> lRegion = TestDataFactory.createTestRegion(1);
	        lRegion.get(0).Market__c = 'TH';
	        update lRegion;

	        TestDataFactory.createTestWard(1, 'TH');
	        TestDataFactory.createTestDistrict(1, 'TH');
	        TestDataFactory.createTestEthnicity(1, 'TH');
	        TestDataFactory.createTestSwitchReason(1, 'TH');
	      
		}
    }

	@isTest static void test_insertRecord() {
		User sysad = [Select Id From User where LastName = 'tstSysAd'];
		System.runAs(sysad) {
			System.Test.startTest();
				//validate language
				TH_Contact_Manual__c rec = new TH_Contact_Manual__c();
				rec.contact_preferredlanguage__c = 'Tagalog';
				Boolean hasError = false;
				try {
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}
				//validate product
				rec = validData();
				try {
					rec.cr_sampleproductid__c = '1234';
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				rec = validData();		
				//validate brand
				try {
					rec.br_brandid__c = '1235';
					rec.br_brandname__c = 'ProductName -12';
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				//validate campaign
				rec = validData();
				try {
					rec.cr_campaignid__c = '1234';
					rec.cr_campaignname__c = 'Invalid';
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				try {
					rec.cr_campaignid__c = '1234';
					rec.cr_campaignname__c = '';
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				//validate dates
				rec = validData();		
				try {
					rec.contact_dob__c = '23/23/2015';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}
				/*
				rec = validData();		
				try {
					rec.child_dob__c = '23/23/2015';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}*/
				
				rec = validData();		
				try {
					rec.contact_edd__c = '23/23/2015';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				
				/*
				rec = validData();		
				try {
					rec.cr_registrationdate__c = '23/23/2015';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}*/

				//validate channel
				rec = validData();		
				try {
					rec.cr_channelid__c = '';
					rec.cr_channelname__c = 'Invalid';
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				//validate channel
				rec = validData();		
				try {
					rec.cr_channelid__c = 'FB';
					rec.cr_channelname__c = 'Invalid';
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}


				rec = validData();		
				try {
					rec.addr_district__c = 'Invalid';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				rec = validData();		
				try {
					rec.addr_region__c = 'Invalid';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				
				//validate phone
				rec = validData();		
				try {
					rec.contact_homephone__c = 'Invalid';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				try {
					rec.contact_homephone__c = 'ph:Invalid';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				rec = validData();		
				try {
					rec.contact_mobilephone__c = 'Invalid';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				rec = validData();		
				try {
					rec.contact_mobilephone__c = 'ph:Invalid';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				rec = validData();		
				try {
					rec.contact_otherphone__c = 'Invalid';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				rec = validData();		
				try {
					rec.contact_otherphone__c = 'ph:Invalid';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				//validate email
				rec = validData();		
				try {
					rec.contact_email__c = 'Invalid';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				//validate lastname
				rec = validData();		
				try {
					rec.contact_lastname__c = '';				
					
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}


				rec = validData();		
				try {
					rec.br_brandid__c = 'Invalid';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				//validate contact_ethnicity__c
				rec = validData();		
				try {
					rec.contact_ethnicity__c = 'Invalid';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}

				//validate status
				rec = validData();		
				try {
					rec.br_relationstatus__c = 'Contacted';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}
				//validate type
				rec = validData();		
				try {
					rec.br_relationtype__c = 'Lead';				
					insert rec;
				} catch(Exception ex) {
					hasError = true;
				}
               
				System.assertEquals(true, hasError,'There should be an error');

                 //test other dml
                rec = validData();		
                try {
                    insert rec;
                    update rec;
                    delete rec;
                }catch(Exception ex) {
					hasError = false;
				}

                System.assertEquals(true, hasError,'There should be no error');
			System.Test.stopTest();
		}
	}

	public 	static TH_Contact_Manual__c validData() {
		TH_Contact_Manual__c rec = new TH_Contact_Manual__c();
		rec.br_brandid__c = '123';
		rec.br_brandname__c = 'ProductName -1';
		rec.cr_channelid__c = 'FB' ;
		rec.cr_channelname__c = 'FB';
		rec.contact_lastname__c = 'Last';
		rec.br_relationstatus__c = 'New';		
		rec.addr_country__c = 'country';
		rec.contact_mobilephone__c = 'ph:09053444444';
		rec.br_relationtype__c = 'User';
		rec.cr_registrationdate__c = '10/01/2020';
		rec.contact_email__c = 'test@test.com';
		rec.cr_sampleproductid__c = '123';

		return rec;
	}
	
}