force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/CallTransferReason__c.field-meta.xml
<CustomField>
    <fullName>CallTransferReason__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Call Transfer Reason</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Call Transfer Reason</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Cases (Call Transfer Reason)</relationshipLabel>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PreferredLanguage__c.field-meta.xml
<CustomField>
    <fullName>PreferredLanguage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Preferred Language</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Preferred Language</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Contacts (Preferred Language)</relationshipLabel>
    <relationshipName>PreferredLanguages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TransferCallPageController.cls
/*------------------------------------------------------------
Author:      Viana Flor Mirandilla
Description: Controller Class for TransferCallPage

History
07/03/2019   vmirandilla   Created
-------------------------------------------------------------------------------------------*/

public without sharing class TransferCallPageController {

    /***
    This method gets the login user's market to be used on query filters.
    ***/
	@AuraEnabled
    public static String fetchUserMarket() {
        String userMarket = [SELECT Id, Market__c FROM User WHERE Id =: userInfo.getUserId()].Market__c;
        return userMarket;
    }

    /***
    This method gets the Preferred Language associated to the Case's Contact.
    Preferred Language will be used as filter to the list of User wherein the user can transfer the call.
    ***/
    @AuraEnabled
    public static Case fetchContact(String caseId) {
        Case caseRec = [SELECT Id, ContactId, Contact.PreferredLanguage__r.Name FROM Case WHERE Id =: caseId];
        return caseRec;
    }

    /***
    Returns the actual Affiliated Value Id of the Preferred Language
    ***/
    @AuraEnabled
    public static String fetchLanguage(String affiliateId) {
        String language = [SELECT Id, Name FROM Affiliate_Value__c WHERE Id =: affiliateId].Name;
        return language;
    }

    /***
    This method updates the Case Owner and Contact's Preferred Language based on user input.
    ***/
    @AuraEnabled
    public static void transferCall(String caseId, String ownerId, String reason, String contactId, String contactLanguage) {
        try {
            Contact conRec = new Contact();
            conRec.Id = contactId;
            conRec.PreferredLanguage__c = contactLanguage;
            update conRec;

            Case caseRec = new Case();
            caseRec.Id = caseId;
            caseRec.OwnerId = ownerId;
            caseRec.CallTransferReason__c = reason;
            update caseRec;
        } catch(DmlException dex) {
            throw new AuraHandledException(dex.getDmlMessage(0));
        } catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }

}