force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/City.recordType-meta.xml
<RecordType>
    <fullName>City</fullName>
    <active>true</active>
    <description>Defines cities within a given market, to be selected during address creation and updates for a contact</description>
    <label>City</label>
</RecordType>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/District.recordType-meta.xml
<RecordType>
    <fullName>District</fullName>
    <active>true</active>
    <description>Defines the districts within a given market (usually defined by city), used during address creation and updates for a contact</description>
    <label>District</label>
</RecordType>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/Ethnicity.recordType-meta.xml
<RecordType>
    <fullName>Ethnicity</fullName>
    <active>true</active>
    <description>Defines the ethnicities available for selection while creating and updating contact (optional field)</description>
    <label>Ethnicity</label>
</RecordType>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/Region.recordType-meta.xml
<RecordType>
    <fullName>Region</fullName>
    <active>true</active>
    <description>Defines the geographical regions within a given market used during address creation and updates for a contact</description>
    <label>Region</label>
</RecordType>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/Trade.recordType-meta.xml
<RecordType>
    <fullName>Trade</fullName>
    <active>true</active>
    <label>Trade</label>
</RecordType>

force-app/main/default/objects/Affiliate_Value__c/recordTypes/Ward.recordType-meta.xml
<RecordType>
    <fullName>Ward</fullName>
    <active>true</active>
    <description>Defines the wards within a city within a given market (only used in Vietnam), used during address creation and updates for a contact</description>
    <label>Ward</label>
</RecordType>

force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/ExternalCampaignReference__c.field-meta.xml
<CustomField>
    <fullName>ExternalCampaignReference__c</fullName>
    <description>External campaign reference for tagging with Salesforce ID</description>
    <externalId>true</externalId>
    <label>External Campaign Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Channel_Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Channel_Ref_No__c</fullName>
    <externalId>true</externalId>
    <label>Channel Ref No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/recordTypes/Trade.recordType-meta.xml
<RecordType>
    <fullName>Trade</fullName>
    <active>true</active>
    <label>Trade</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SourceCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>SourceCreatedDate__c</fullName>
    <label>Source Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/User/fields/SourceCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>SourceCreatedDate__c</fullName>
    <label>Source Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/VN_contact_manual__c.object-meta.xml
<CustomObject>
    <label>VN contact manual</label>
    <nameField>
        <label>VN contact manual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VN contact manuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VN_contact_manual__c/fields/addr_city__c.field-meta.xml
<CustomField>
    <fullName>addr_city__c</fullName>
    <label>Addr City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/addr_district__c.field-meta.xml
<CustomField>
    <fullName>addr_district__c</fullName>
    <label>Addr District</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/addr_region__c.field-meta.xml
<CustomField>
    <fullName>addr_region__c</fullName>
    <label>Addr Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/addr_ward__c.field-meta.xml
<CustomField>
    <fullName>addr_ward__c</fullName>
    <label>Addr Ward</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/br_brandid__c.field-meta.xml
<CustomField>
    <fullName>br_brandid__c</fullName>
    <label>BR BrandID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/br_brandname__c.field-meta.xml
<CustomField>
    <fullName>br_brandname__c</fullName>
    <label>BR BrandName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/br_brandswitchreason__c.field-meta.xml
<CustomField>
    <fullName>br_brandswitchreason__c</fullName>
    <label>BR BrandSwitchReason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/br_currbrandid__c.field-meta.xml
<CustomField>
    <fullName>br_currbrandid__c</fullName>
    <label>br_currbrandid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/br_memberstartdate__c.field-meta.xml
<CustomField>
    <fullName>br_memberstartdate__c</fullName>
    <label>BR MemberStartDate</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/br_relationstatus__c.field-meta.xml
<CustomField>
    <fullName>br_relationstatus__c</fullName>
    <label>BR RelationStatus</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/br_relationtype__c.field-meta.xml
<CustomField>
    <fullName>br_relationtype__c</fullName>
    <label>BR RelationType</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/child_dob__c.field-meta.xml
<CustomField>
    <fullName>child_dob__c</fullName>
    <label>Child DOB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/contact_dob__c.field-meta.xml
<CustomField>
    <fullName>contact_dob__c</fullName>
    <label>Contact DOB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/contact_edd__c.field-meta.xml
<CustomField>
    <fullName>contact_edd__c</fullName>
    <description>Estimated Due Date. yyyy-mm-dd</description>
    <label>Contact EDD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/contact_email__c.field-meta.xml
<CustomField>
    <fullName>contact_email__c</fullName>
    <label>Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/contact_ethnicity__c.field-meta.xml
<CustomField>
    <fullName>contact_ethnicity__c</fullName>
    <label>Contact Ethnicity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/contact_fullname__c.field-meta.xml
<CustomField>
    <fullName>contact_fullname__c</fullName>
    <label>Contact FullName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/contact_homephone__c.field-meta.xml
<CustomField>
    <fullName>contact_homephone__c</fullName>
    <label>Contact HomePhone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/contact_lastname__c.field-meta.xml
<CustomField>
    <fullName>contact_lastname__c</fullName>
    <label>Contact LastName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/contact_mobilephone__c.field-meta.xml
<CustomField>
    <fullName>contact_mobilephone__c</fullName>
    <label>Contact MobilePhone</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/contact_otherphone__c.field-meta.xml
<CustomField>
    <fullName>contact_otherphone__c</fullName>
    <label>Contact OtherPhone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/contact_preferredlanguage__c.field-meta.xml
<CustomField>
    <fullName>contact_preferredlanguage__c</fullName>
    <label>Contact PreferredLanguage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/cr_campaignid__c.field-meta.xml
<CustomField>
    <fullName>cr_campaignid__c</fullName>
    <label>CR CampaignID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/cr_campaignname__c.field-meta.xml
<CustomField>
    <fullName>cr_campaignname__c</fullName>
    <label>CR CampaignName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/cr_channelid__c.field-meta.xml
<CustomField>
    <fullName>cr_channelid__c</fullName>
    <label>CR ChannelID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/cr_channelname__c.field-meta.xml
<CustomField>
    <fullName>cr_channelname__c</fullName>
    <label>CR ChannelName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/cr_registrationdate__c.field-meta.xml
<CustomField>
    <fullName>cr_registrationdate__c</fullName>
    <label>CR RegistrationDate</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/cr_sampleproductid__c.field-meta.xml
<CustomField>
    <fullName>cr_sampleproductid__c</fullName>
    <label>CR SampleProductID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VN_contact_manual__c/fields/sourcecreateddate__c.field-meta.xml
<CustomField>
    <fullName>sourcecreateddate__c</fullName>
    <label>Source Created Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VNContactManualTriggerHelper.cls
/*------------------------------------------------------------
Author:      Rayson Landeta
Description: Helper class for VN_Contact_Manual__c object
History
04/01/2019   rlandeta    Created
-------------------------------------------------------------------------------------------*/

public class VNContactManualTriggerHelper {

    /* This method get all Affialite Values and check the duplicate;
    */
    public static void validateAffiliateValue(List<VN_Contact_Manual__c> vnContactList) {
        Integer row = 1;
        //Set<String> channelRecTypeSet = new Set<String>{CommonConstant.CHANNEL_SOCIAL_RECORDTYPE, CommonConstant.CHANNEL_OTHER_ONLINE_RECORDTYPE, CommonConstant.CHANNEL_WEB_RECORDTYPE};

        List<Product2> productList = new List<Product2>();
        productList = [SELECT ProductCode, Name FROM Product2 WHERE Market__c = 'VN' AND IsActive = True];
        Set<String> productCodeSet = new Set<String>();
        Set<String> productNameSet = new Set<String>();
        for(Product2 p : productList){      
            productCodeSet.add(p.ProductCode);
            productNameSet.add(p.Name);
        }
        
        List<Channel__c> chanList = new List<Channel__c>();
        chanList = [SELECT Channel_Ref_No__c, Name FROM Channel__c WHERE Market__c = 'VN' AND RecordType.Name != 'Trade'];// AND RecordType.Name IN :channelRecTypeSet];
        Set<String> chanCodeSet = new Set<String>();
        Set<String> chanNameSet = new Set<String>();
        for(Channel__c c : chanList){      
            chanCodeSet.add(c.Channel_Ref_No__c);
            chanNameSet.add(c.Name);
        }
        
        List<Campaign> campList = new List<Campaign>();
        campList = [SELECT ExternalCampaignReference__c, Name FROM Campaign WHERE Market__c = 'VN' AND IsActive = True];
        Set<String> campCodeSet = new Set<String>();
        Set<String> campNameSet = new Set<String>();
        for(Campaign c : campList){      
            campCodeSet.add(c.ExternalCampaignReference__c);
            campNameSet.add(c.Name);
        }
        
        List<Affiliate_Value__c> avList = new List<Affiliate_Value__c>();
        avList = [SELECT recordtypeID,RecordType.Name, Name FROM Affiliate_Value__c WHERE Market__c = 'VN'];
        Map<String, Set<String>> avMap = new Map<String, Set<String>>();
        for(Affiliate_Value__c av : avList){
            if(avMap.containsKey(av.RecordType.Name)){
                avMap.get(av.RecordType.Name).add(av.Name.toLowerCase());
            } else {
                Set<String> avnameSet = new Set<String>();
                avnameSet.add(av.Name.toLowerCase());
                avMap.put(av.RecordType.Name,avnameSet);
            }
        }
        
        for(VN_Contact_Manual__c vnContact : vnContactList){
            row++;
            Set<String> avnames = new Set<String>();
            if(String.isNotBlank(vnContact.Contact_PreferredLanguage__c)){
                avnames = avMap.get('Preferred Language');
                if(!avnames.contains(vnContact.Contact_PreferredLanguage__c.toLowerCase())){
                    vnContact.addError(vnContact.Contact_PreferredLanguage__c + ' Preferred Language not exists');
                    continue;
                }
            }
            
           /* if(String.isNotBlank(vnContact.BR_BrandID__c)){
                if(!productCodeSet.contains(vnContact.BR_BrandID__c)){
                    if(!productNameSet.contains(vnContact.BR_BrandName__c)){
                        vnContact.addError(' BR Brand ID or Name does not exist at row ' + row); 
                        continue;
                    }
                }
            }*/
            
           if(String.isNotBlank(vnContact.br_brandid__c)){
                if(!productCodeSet.contains(vnContact.br_brandid__c)){
                    if(String.isNotBlank(vnContact.br_brandname__c)){
                        if(!productNameSet.contains(vnContact.br_brandname__c)){
                            vnContact.addError(' Brand ID and Name does not exist at row ' + row); 
                            continue;
                        }
                    } else {
                        vnContact.addError(' Brand ID does not exist at row ' + row); 
                        continue;
                    }
                }
            } else {
                if(String.isNotBlank(vnContact.br_brandname__c)){
                    if(!productNameSet.contains(vnContact.br_brandname__c)){
                        vnContact.addError(' Brand Name does not exist at row ' + row); 
                        continue;
                    }
                } else {
                    vnContact.addError(' Brand ID or Brand Name is required at row ' + row); 
                    continue;
                }
            }
            
             if(String.isNotBlank(vnContact.CR_ChannelID__c)){
                if(!chanCodeSet.contains(vnContact.CR_ChannelID__c)){
                    if(String.isNotBlank(vnContact.CR_ChannelName__c)){
                        if(!chanNameSet.contains(vnContact.CR_ChannelName__c)){
                            vnContact.addError(' Channel ID and Name does not exist at row ' + row); 
                            continue;
                        }
                    } else {
                        vnContact.addError(' Channel ID does not exist at row ' + row); 
                        continue;
                    }
                }
            } else {
                if(String.isNotBlank(vnContact.CR_ChannelName__c)){
                    if(!chanNameSet.contains(vnContact.CR_ChannelName__c)){
                        vnContact.addError(' Channel Name does not exist at row ' + row); 
                        continue;
                    }
                } else {
                    vnContact.addError(' Channel ID or Channel Name is required at row ' + row); 
                    continue;
                }
            }
            
            if(String.isNotBlank(vnContact.CR_CampaignID__c)){
                if(!campCodeSet.contains(vnContact.CR_CampaignID__c)){
                    if(String.isNotBlank(vnContact.CR_CampaignName__c)){
                        if(!campNameSet.contains(vnContact.CR_CampaignName__c)){
                            vnContact.addError(' Campaign ID and Name does not exist at row ' + row); 
                            continue;
                        }
                    } else {
                        vnContact.addError(' Campaign ID does not exist at row ' + row); 
                        continue;
                    }
                }
            } else {
                if(String.isNotBlank(vnContact.CR_CampaignName__c)){
                    if(!campNameSet.contains(vnContact.CR_CampaignName__c)){
                        vnContact.addError(' Campaign Name does not exist at row ' + row); 
                        continue;
                    }
                }
            }
            
            if(String.isNotBlank(vnContact.Addr_Ward__c)){
                avnames = avMap.get('Ward');
                if(!avnames.contains(vnContact.Addr_Ward__c.toLowerCase())){
                    vnContact.addError(vnContact.Addr_Ward__c + ' Ward not exists at row ' + row);
                    continue;
                }
            }
            
            if(String.isNotBlank(vnContact.Addr_District__c)){
                avnames = avMap.get('District');
                if(!avnames.contains(vnContact.Addr_District__c.toLowerCase())){
                    vnContact.addError(vnContact.Addr_District__c + ' District not exists at row ' + row);
                    continue;
                }
            }
            if(String.isNotBlank(vnContact.Addr_City__c)){
                avnames = avMap.get('City');
                if(!avnames.contains(vnContact.Addr_City__c.toLowerCase())){
                    vnContact.addError(vnContact.Addr_City__c + ' City not exists at row ' + row);
                    continue;
                }
            }
            if(String.isNotBlank(vnContact.Contact_Ethnicity__c)){
                avnames = avMap.get('Ethnicity');
                if(!avnames.contains(vnContact.Contact_Ethnicity__c.toLowerCase())){
                    vnContact.addError(vnContact.Contact_Ethnicity__c + ' Ethnicity not exists at row ' + row);
                    continue;
                }
            }
            
            if(String.isNotBlank(vnContact.Addr_Region__c)){
                avnames = avMap.get('Region');
                if(!avnames.contains(vnContact.Addr_Region__c.toLowerCase())){
                    vnContact.addError(vnContact.Addr_Region__c + ' Region not exists at row ' + row);
                    continue;
                }
            }
            
            if(String.isNotBlank(vnContact.BR_BrandSwitchReason__c)){
                avnames = avMap.get('Brand Switch Reason');
                if(!avnames.contains(vnContact.BR_BrandSwitchReason__c.toLowerCase())){
                    vnContact.addError(vnContact.BR_BrandSwitchReason__c + ' Brand Switch Reason not exists at row ' + row);
                    continue;
                }
            }
            
            /*if(String.isNotBlank( vnContact.BR_MemberStartDate__c) ) {
                if(!checkDate(vnContact.BR_MemberStartDate__c)){
                    vnContact.addError(vnContact.BR_MemberStartDate__c + ' is Invalid date, use dd/mm/yyyy at row ' + row);
                    continue;
                }     
            }*/
            
            if(String.isNotBlank( vnContact.Child_DOB__c) ) {
                if(!checkDate(vnContact.Child_DOB__c)){
                    vnContact.addError(vnContact.Child_DOB__c + ' is Invalid date, use dd/mm/yyyy at row ' + row);
                    continue;
                }     
            }
            
            if(String.isNotBlank( vnContact.Contact_DOB__c) ) {
                if(!checkDate(vnContact.Contact_DOB__c)){
                    vnContact.addError(vnContact.Contact_DOB__c + ' is Invalid date, use dd/mm/yyyy at row ' + row);
                    continue;
                }     
            }
            
            if(String.isNotBlank( vnContact.Contact_EDD__c) ) {
                if(!checkDate(vnContact.Contact_EDD__c)){
                    vnContact.addError(vnContact.Contact_EDD__c + ' is Invalid date, use dd/mm/yyyy at row ' + row);
                    continue;
                }     
            }
            
            if(String.isNotBlank( vnContact.cr_registrationdate__c) ) {
                if(!checkDate(vnContact.cr_registrationdate__c)){
                    vnContact.addError(vnContact.cr_registrationdate__c + ' is Invalid date, use dd/mm/yyyy at row ' + row);
                    continue;
                }     
            }
            
            if(String.isNotBlank( vnContact.SourceCreatedDate__c) ) {
                if(!checkDate(vnContact.SourceCreatedDate__c)){
                    vnContact.addError(vnContact.SourceCreatedDate__c + ' is Invalid date, use dd/mm/yyyy at row ' + row);
                    continue;
                }     
            }
            if(String.isNotBlank( vnContact.BR_RelationType__c) ){
                if(String.isNotBlank(vnContact.BR_RelationStatus__c)) {
                    if(vnContact.BR_RelationType__c.equalsIgnoreCase('Lead')) {
                        if(!(vnContact.BR_RelationStatus__c == 'Contacted' || vnContact.BR_RelationStatus__c == 'Uncontacted' || vnContact.BR_RelationStatus__c == 'Qualified')){
                            vnContact.addError(vnContact.BR_RelationStatus__c + ' is not valid Relation Status, select from Contacted|Uncontacted|Qualified at row ' + row);
                            continue;
                        }     
                    } else if(vnContact.BR_RelationType__c.equalsIgnoreCase('User')){
                        if(!(vnContact.BR_RelationStatus__c == 'New' || vnContact.BR_RelationStatus__c == 'Existing' || vnContact.BR_RelationStatus__c == 'Lapsed')){
                            vnContact.addError(vnContact.BR_RelationStatus__c + ' is not valid Relation Status, select from New|Existing|Lapsed at row ' + row);
                            continue;
                        } 
                    }
                } else {
                    vnContact.addError('BR RelationStatus is required at row ' + row);
                	continue;
                }
            } else {
                vnContact.addError('BR RelationType is required at row ' + row);
                continue;
            }
            
       /*     if (String.isNotBlank( vnContact.Contact_Homephone__c) ) {
                if(vnContact.Contact_Homephone__c.contains('vn:')){  
                    vnContact.Contact_Homephone__c = vnContact.Contact_Homephone__c.remove('ph:').trim();
                    if(!checkphone(vnContact.Contact_Homephone__c)){
                        vnContact.addError(vnContact.Contact_Homephone__c + ' Main Contact Home phone is not a valid phone at row ' + row);
                    continue;
                    }
                } else {
                    vnContact.addError('Please put ph: in front of Main Contact Home phone Column at row ' + row);
                    continue;
                }       
            }
            
            if(String.isBlank(vnContact.Contact_Mobilephone__c.remove('ph:').trim())){
                vnContact.addError('Contact Mobile is required at row ' + row);
                continue;
            }
            if (String.isNotBlank( vnContact.Contact_Mobilephone__c) ) {
                if(vnContact.Contact_Mobilephone__c.contains('ph:')){  
                    vnContact.Contact_Mobilephone__c = vnContact.Contact_Mobilephone__c.remove('ph:').trim();
                    if(!checkphone(vnContact.Contact_Mobilephone__c)){
                        vnContact.addError(vnContact.Contact_Mobilephone__c + ' Main Contact Mobile phone is not a valid phone at row ' + row);
                        continue;
                    }
                } else {
                    vnContact.addError('Please put ph: in front of Main Contact Mobile phone Column at row ' + row);
                    continue;
                }       
            }
            
            if (String.isNotBlank( vnContact.Contact_Otherphone__c) ) {
                if(vnContact.Contact_Otherphone__c.contains('ph:')){  
                    vnContact.Contact_Otherphone__c = vnContact.Contact_Otherphone__c.remove('ph:').trim();
                    if(!checkphone(vnContact.Contact_Otherphone__c)){
                        vnContact.addError(vnContact.Contact_Otherphone__c + ' Main Contact Other phone is not a valid phone at row ' + row);
                    continue;
                    }
                } else {
                    vnContact.addError('Please put ph: in front of Main Contact Other phone Column at row ' + row);
                    continue;
                }       
            }
            */
            
            if (String.isNotBlank( vnContact.Contact_Homephone__c) ) {
                if(!checkPhone(vnContact.Contact_Homephone__c)){
                    vnContact.addError(vnContact.Contact_Homephone__c + ' Contact Home Phone is not a valid Phone at row ' + row);
                    continue;
                }
            }
            if (String.isNotBlank( vnContact.Contact_Mobilephone__c) ) {
                if(!checkPhone(vnContact.Contact_Mobilephone__c)){
                    vnContact.addError(vnContact.Contact_Mobilephone__c + ' Main Contact Mobile Phone is not a valid Phone at row ' + row);
                    continue;
                }
            }
            if (String.isNotBlank( vnContact.Contact_Otherphone__c) ) {
                if(!checkPhone(vnContact.Contact_Otherphone__c)){
                    vnContact.addError(vnContact.Contact_Otherphone__c + ' Main Contact Other Phone is not a valid Phone at row ' + row);
                    continue;
                }
            }
            if(String.isNotBlank(vnContact.contact_email__c)){
                if(!checkEmail(vnContact.contact_email__c)){
                    vnContact.addError('Invalid Contact Email at row ' + row);
                    continue;
                }
            }
            
             if(String.isBlank(vnContact.contact_lastname__c)){
                if(String.isNotBlank( vnContact.contact_fullname__c)){
                    vnContact.addError('Please copy the full name to last name. Can\'t keep last name unfilled at row ' + row);
                    continue;
                }
                vnContact.addError('Contact Last Name are required at row ' + row);
                continue;
            }
            
            if(String.isNotBlank(vnContact.br_currbrandid__c)){
                if(!productCodeSet.contains(vnContact.br_currbrandid__c)){
                    vnContact.addError(vnContact.br_currbrandid__c + ' BR CurrBrandID does not exist at row ' + row); 
                    continue;
                }
            }
            if(String.isNotBlank(vnContact.br_brandid__c )){
                if(!productCodeSet.contains(vnContact.br_brandid__c )){
                    vnContact.addError(vnContact.br_brandid__c  + ' BR BrandID does not exist at row ' + row); 
                    continue;
                }
            }
            if(String.isNotBlank(vnContact.cr_sampleproductid__c )){
                if(!productCodeSet.contains(vnContact.cr_sampleproductid__c )){
                    vnContact.addError(vnContact.cr_sampleproductid__c  + ' Sample Product ID does not exist at row ' + row); 
                    continue;
                }
            }
        }
    }
    
    public static Boolean checkDate(String checkDate) {
        String datePattern = '(0?[1-9]|[12][0-9]|3[01])/(0?[1-9]|1[012])/((11|12|13|14|15|16|17|18|19|20)\\d\\d)';
        Pattern pat = Pattern.compile(datePattern);
        Matcher mat = pat.matcher(checkDate);
        return mat.matches();
    }
    
    public static Boolean checkEmail(String checkemail) {
        String eMailPattern = '^[a-z0-9!#$%&\'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&\'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$';
        Pattern pat = Pattern.compile(eMailPattern);
        Matcher mat = pat.matcher(checkEMail.toLowerCase());
        return mat.matches();
    }
    public static Boolean checkphone(String checkphone) {
        String phonePattern = '^0[0-9]{6,11}$';
        Pattern pat = Pattern.compile(phonePattern);
        Matcher mat = pat.matcher(checkphone);
        if(String.isNotBlank(checkphone )){
            return mat.matches();
        } else {
            return True;
        }
    }
}