force-app/main/default/objects/Affiliate_Value__c/Affiliate_Value__c.object-meta.xml
<CustomObject>
    <label>Affiliate Value</label>
    <nameField>
        <label>Affiliate Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliate Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Key Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elecare</fullName>
            </value>
            <value>
                <fullName>Ensure</fullName>
            </value>
            <value>
                <fullName>Ensure Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Flexifo</fullName>
            </value>
            <value>
                <fullName>Freego</fullName>
            </value>
            <value>
                <fullName>Glucerna</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>IMF</fullName>
            </value>
            <value>
                <fullName>Jevity</fullName>
            </value>
            <value>
                <fullName>Multi-Brand</fullName>
            </value>
            <value>
                <fullName>Pediasure</fullName>
            </value>
            <value>
                <fullName>Similac</fullName>
            </value>
            <value>
                <fullName>Similac Core</fullName>
            </value>
            <value>
                <fullName>Similac Mom</fullName>
            </value>
            <value>
                <fullName>Similac Total Comfort</fullName>
            </value>
            <value>
                <fullName>Nepro</fullName>
            </value>
            <value>
                <fullName>Osmolite</fullName>
            </value>
            <value>
                <fullName>RCF</fullName>
            </value>
            <value>
                <fullName>Twocal</fullName>
            </value>
            <value>
                <fullName>Vital 1.5Kcal</fullName>
            </value>
            <value>
                <fullName>Other MND</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Isomil</fullName>
            </value>
            <value>
                <fullName>Prosure</fullName>
            </value>
            <value>
                <fullName>Nepro HP</fullName>
                <isActive>false</isActive>
                <label>Nepro HP</label>
            </value>
            <value>
                <fullName>Nepro LP</fullName>
                <isActive>false</isActive>
                <label>Nepro LP</label>
            </value>
            <value>
                <fullName>Similac 3</fullName>
                <isActive>false</isActive>
                <label>Similac 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of Awareness will capture as campaign as well</description>
    <label>Call Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Affiliate_Value__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Region</value>
        </filterItems>
        <filterItems>
            <field>Affiliate_Value__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Affiliate_Value__c</referenceTo>
    <relationshipLabel>Contacts (Region)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SkillsBasedCriteriaVN.cls
public class SkillsBasedCriteriaVN {

	/*
    Consolidated to SkillsBaseCriteria class - Jeric
    public static Map<Id, Set<String>> determineRequiredSkills(List<Case> casesToDetermine) {
        Map<Id, Set<String>> callSkillsToReturn = new Map<Id, Set<String>>();
        
        for(Case caseRec : casesToDetermine) {
            if(!callSkillsToReturn.containsKey(caseRec.Id)) {
                if(caseRec.Campaign__c != null) {
                    callSkillsToReturn.put(caseRec.Id, new Set<String>{CommonConstant.SKILL_MARKET + caseRec.Campaign__r.Market__c});
                    if(String.IsNotBlank(caseRec.Campaign__r.Brand__c)) {
                        if(caseRec.Campaign__r.Brand__c != 'Multi-Brand' && caseRec.Campaign__r.Brand__c != 'Others') {
                        	callSkillsToReturn.get(caseRec.Id).add(CommonConstant.SKILL_BRAND + caseRec.Campaign__r.Brand__c);   
                        }
                    }
                }
                
                if(caseRec.Contact.Region__c != null) {
                    callSkillsToReturn.get(caseRec.Id).add(CommonConstant.SKILL_REGION + caseRec.Contact.Region__r.Name);
                }
            }
        }
        
        return callSkillsToReturn;
    }*/
}