force-app/main/default/objects/MY_Manual_Delivery_Status__c/MY_Manual_Delivery_Status__c.object-meta.xml
<CustomObject>
    <label>MY Manual Delivery Status</label>
    <nameField>
        <label>MY Manual Delivery Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MY Manual Delivery Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MY_Manual_Delivery_Status__c/fields/order_delivery_date__c.field-meta.xml
<CustomField>
    <fullName>order_delivery_date__c</fullName>
    <label>Order Delivery Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MY_Manual_Delivery_Status__c/fields/order_status__c.field-meta.xml
<CustomField>
    <fullName>order_status__c</fullName>
    <label>Order Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MY_Manual_Delivery_Status__c/fields/source_created_date__c.field-meta.xml
<CustomField>
    <fullName>source_created_date__c</fullName>
    <label>Source Created Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MYManualDeliveryStatusTriggerHelperTest.cls
@isTest
private class MYManualDeliveryStatusTriggerHelperTest {
	@testsetup
    static void setupData() {
    	User sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'MY');
        insert sysad;
        
        System.runAs(sysad) {	    	      

	        TestDataFactory.createTestOrderCancellationReason(1, 'MY');	       
	      
		}
    }

	@isTest static void test_insertRecord() {
		User sysad = [Select Id From User where LastName = 'tstSysAd'];
		System.runAs(sysad) {
			System.Test.startTest();
			Boolean hasError = false;
			MY_Manual_Delivery_Status__c rec = new MY_Manual_Delivery_Status__c();

			//validate address
			rec = new MY_Manual_Delivery_Status__c();
			try {
				rec.order_status__c = 'Cancelled - Upon Delivery';	
				rec.order_cancellation_reason__c = 'Invalid';			
				insert rec;
			} catch(Exception ex) {
				hasError = true;
			}			

			rec = new MY_Manual_Delivery_Status__c();
			try {
				rec.order_status__c = 'Completed';	
				rec.order_delivery_date__c = 'Invalid';
				insert rec;
			} catch(Exception ex) {
				hasError = true;
			}

			rec = new MY_Manual_Delivery_Status__c();
			try {
				rec.order_status__c = 'Completed';	
				rec.order_delivery_date__c = 'Invalid';
				insert rec;
			} catch(Exception ex) {
				hasError = true;
			}

			rec = new MY_Manual_Delivery_Status__c();
			try {
				rec.order_status__c = 'Completed';	
				rec.source_created_date__c = 'Invalid';
				insert rec;
			} catch(Exception ex) {
				hasError = true;
			}		

			
			System.assertEquals(true, hasError,'There should be an error');
			System.Test.stopTest();
		}
	}
	
}