force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of Awareness will capture as campaign as well</description>
    <label>Call Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/RelatedBrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>RelatedBrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateConversionSkillDailyBatch.cls
global class UpdateConversionSkillDailyBatch implements Database.Batchable<sObject>, Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        String query = 'SELECT Id, AccountId, RelatedBrandRelationship__c ' 
                        + 'FROM Case '
                        + 'WHERE RelatedBrandRelationship__c != null AND RelatedBrandRelationship__r.FirstTransactionDate__c != null ' 
                        + 'AND Campaign__c != null AND Campaign__r.Market__c = \'PH\' ';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Case> scope){
        
        // query PendingServiceRouting, Skill, and SkillRequirement records
        List<Skill> postConversionSkill = [SELECT Id FROM Skill WHERE DeveloperName = 'Conversion_Post_Conversion' LIMIT 1];
        
        Map<Id, PendingServiceRouting> psrMap = new Map<Id, PendingServiceRouting>([SELECT Id, WorkItemId FROM PendingServiceRouting WHERE WorkItemId IN: scope AND IsReadyForRouting = false]);
        
        List<SkillRequirement> srRecords = [SELECT RelatedRecordId, SkillId FROM SkillRequirement WHERE Skill.DeveloperName = 'Conversion_Conversion' AND RelatedRecordId IN: psrMap.keySet()];
        
        
        // actual execute statements
        Map<Id, SkillRequirement> srUpdateMap = new Map<Id, SkillRequirement>();
        Map<Id, PendingServiceRouting> psrUpdateMap = new Map<Id, PendingServiceRouting>();
        
        for(SkillRequirement srToUpdate : srRecords){
            if(!srUpdateMap.containsKey(srToUpdate.Id)){
                srToUpdate.SkillId = postConversionSkill[0].Id;
                srUpdateMap.put(srToUpdate.Id, srToUpdate);
            }
            PendingServiceRouting psr = (PendingServiceRouting) psrMap.get(srToUpdate.RelatedRecordId);
            if(!psrUpdateMap.containsKey(psr.Id)){
                psr.isReadyForRouting = true;
                psrUpdateMap.put(psr.Id, psr);
            }
        }
        
        if(!srUpdateMap.values().isEmpty()){
            Savepoint sp = Database.setSavepoint();
            try{
                List<Database.SaveResult> srList = Database.update(srUpdateMap.values(), false);
                for (Integer i=0; i<srList.size(); i++){
                    if (!srList.get(i).isSuccess()){
                        Database.Error e = srList.get(i).getErrors().get(0);
                        System.debug('Update Failed: ' + e.getStatusCode() + ': ' + e.getMessage());
                        System.debug('Fields that affected this error: ' + e.getFields());
                    }  
                }
            } catch(Exception e){
                System.debug(e.getMessage());
                System.debug('Rollback all data for this transaction');
                Database.rollback(sp);
            } 
        }

        if(!psrUpdateMap.values().isEmpty()){
            Savepoint sp = Database.setSavepoint();
            try{
                List<Database.SaveResult> srList = Database.update(psrUpdateMap.values(), false);
                for (Integer i=0; i<srList.size(); i++){
                    if (!srList.get(i).isSuccess()){
                        Database.Error e = srList.get(i).getErrors().get(0);
                        System.debug('Update Failed: ' + e.getStatusCode() + ': ' + e.getMessage());
                        System.debug('Fields that affected this error: ' + e.getFields());
                    }  
                }
            } catch(Exception e){
                System.debug(e.getMessage());
                System.debug('Rollback all data for this transaction');
                Database.rollback(sp);
            }   
        }
    }
    
    global void finish(Database.BatchableContext BC){
        
    }

    global void execute(SchedulableContext sc) {
        UpdateConversionSkillDailyBatch batch = new UpdateConversionSkillDailyBatch(); 
        Database.executebatch(batch, 100);
    }
}