force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/FirstChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>FirstChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>FirstChannelResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/FirstChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>FirstChannelResponseDate__c</fullName>
    <label>First Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestCampaign__c.field-meta.xml
<CustomField>
    <fullName>LatestCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Brand Relationships (Latest Channel Response)</relationshipLabel>
    <relationshipName>LatestChannelResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponseDate__c</fullName>
    <label>Latest Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/NewtoBrand__c.field-meta.xml
<CustomField>
    <fullName>NewtoBrand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New to Brand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/NewtoBrandDate__c.field-meta.xml
<CustomField>
    <fullName>NewtoBrandDate__c</fullName>
    <label>New to Brand Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <label>Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Registration</fullName>
            </value>
            <value>
                <fullName>Previous Registration - Same Brand</fullName>
            </value>
            <value>
                <fullName>Previous Registration - Different Brand</fullName>
                <isActive>false</isActive>
                <label>Previous Registration - Different Brand</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[1-Sep-21 Khai] This field is for troubleshooting by extracting out the market of the Contact</description>
    <formula>Contact__r.Market__c</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>RegistrationDate__c</fullName>
    <label>Registration Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>FirstChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Contacts (First Channel Response)</relationshipLabel>
    <relationshipName>firstchannel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>FirstChannelResponseDate__c</fullName>
    <label>First Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestCampaign__c.field-meta.xml
<CustomField>
    <fullName>LatestCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>LatestChannelResponse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponseDate__c</fullName>
    <label>Latest Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Orders (Channel)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>ChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Response</label>
    <referenceTo>ChannelResponse__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChannelResponseBatch.cls
/*----------------------------------------------------------------------------------------
Author:      Rey Austral
Description: Relicate the function of CR trigger

History
10/14/2019   raustral   Created
-------------------------------------------------------------------------------------------*/
// for deletion
global class ChannelResponseBatch {} /* implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT ID ,  PrimaryContact__c'                       
            + ' FROM BrandRelationship__c '
            + ' WHERE'
            + ' (LastModifiedDate = THIS_MONTH OR LastModifiedDate = LAST_MONTH)'
            + ' AND (FirstChannelResponse__c = null or LatestChannelResponse__c = null)'
            + ' AND PrimaryContact__r.Market__c = \'SG\'';
            
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<BrandRelationship__c> scope) {
        List<BrandRelationship__c> brList = [Select Id, FirstChannelResponse__c, FirstChannelResponseDate__c, LatestChannelResponse__c, LatestChannelResponseDate__c, LatestCampaign__c,PrimaryContact__c,User__c,
                                            (Select Id,RegistrationDate__c,Channel__c,Campaign__c,CreatedDate,Name,Classification__c From  Channel_Responses__r order by RegistrationDate__c,Name) 
                                            From BrandRelationship__c Where Id IN: scope];
        List<BrandRelationship__c> toUpdateList = new List<BrandRelationship__c>();
        Set<Id> conIdSet = New Set<Id>();    
        for (BrandRelationship__c br : brList) {
            Integer ctr=0;
            for (ChannelResponse__c cr:  br.Channel_Responses__r) {
                if (ctr == 0) {
                    br.FirstChannelResponse__c = cr.Channel__c;
                    br.FirstChannelResponseDate__c = cr.RegistrationDate__c;
                }
                ctr = ctr +1;
                 
                br.LatestChannelResponse__c = cr.Channel__c;
                br.LatestChannelResponseDate__c = cr.RegistrationDate__c;
                if (cr.Campaign__c != null) {
                    br.LatestCampaign__c = cr.Campaign__c;
                }                

                if (cr.Classification__c == CommonConstant.CHANNELRESPONSE_CLASSIFICATION_FIRSTTIME) {
                    br.NewtoBrand__c = true;
                    br.NewtoBrandDate__c = date.valueOf( cr.RegistrationDate__c );                    
                }
            }  
            if (ctr != 0) {
                conIdSet.add(br.PrimaryContact__c);
                conIdSet.add(br.User__c);
                toUpdateList.add(br);            
            }            
        }
        if (!toUpdateList.isEmpty()) {
            Update toUpdateList;
            List<Contact> contactList = [Select Id, FirstChannelResponse__c,FirstChannelResponseDate__c, LatestChannelResponseDate__c, LatestChannelResponse__c,LatestCampaign__c,
                                             (Select Id,FirstChannelResponse__c,FirstChannelResponseDate__c,LatestChannelResponseDate__c, LatestChannelResponse__c,LatestCampaign__c from MainBrandRelationships__r) ,
                                             (Select Id, FirstChannelResponse__c,FirstChannelResponseDate__c,LatestChannelResponseDate__c, LatestChannelResponse__c,LatestCampaign__c from BrandRelationships__r)
                                             From Contact Where Id IN: conIdSet AND Type__c =: CommonConstant.CONTACT_ADULT_TYPE];
            List<Contact> toUpdateContactList = new List<Contact>();
            for(Contact con : contactList) {
                Datetime oldFirst = con.FirstChannelResponseDate__c;
                Datetime oldLast = con.LatestChannelResponseDate__c;
                
                for(BrandRelationship__c br : con.MainBrandRelationships__r) {                
                    //Update Contact First Channel with the earliest date
                    if (con.FirstChannelResponseDate__c  == null) {
                        con.FirstChannelResponseDate__c = br.FirstChannelResponseDate__c;
                        con.FirstChannelResponse__c = br.FirstChannelResponse__c;
                    } else if (con.FirstChannelResponseDate__c >  br.FirstChannelResponseDate__c ) {
                        con.FirstChannelResponseDate__c = br.FirstChannelResponseDate__c;
                        con.FirstChannelResponse__c = br.FirstChannelResponse__c;
                    }
                    //Update Contact Latest Channel with the  most recently created
                    if (con.LatestChannelResponseDate__c  == null) {
                        con.LatestChannelResponseDate__c = br.LatestChannelResponseDate__c;
                        con.LatestChannelResponse__c = br.LatestChannelResponse__c;
                        con.LatestCampaign__c = br.LatestCampaign__c;
                    } else if (con.LatestChannelResponseDate__c < br.LatestChannelResponseDate__c) {
                        con.LatestChannelResponseDate__c = br.LatestChannelResponseDate__c;
                        con.LatestChannelResponse__c = br.LatestChannelResponse__c;
                        con.LatestCampaign__c = br.LatestCampaign__c == null ? con.LatestCampaign__c : br.LatestCampaign__c;
                    }
                }
                
                for(BrandRelationship__c br : con.BrandRelationships__r) {                
                    //Update Contact First Channel with the earliest date
                    if (con.FirstChannelResponseDate__c  == null) {
                        con.FirstChannelResponseDate__c = br.FirstChannelResponseDate__c;
                    } else if (con.FirstChannelResponseDate__c >  br.FirstChannelResponseDate__c ) {
                        con.FirstChannelResponseDate__c = br.FirstChannelResponseDate__c;
                    }
                    //Update Contact Latest Channel with the  most recently created
                    if (con.LatestChannelResponseDate__c  == null) {
                        con.LatestChannelResponseDate__c = br.LatestChannelResponseDate__c;
                        con.LatestChannelResponse__c = br.LatestChannelResponse__c;
                        con.LatestCampaign__c = br.LatestCampaign__c;
                    } else if (con.LatestChannelResponseDate__c < br.LatestChannelResponseDate__c) {
                        con.LatestChannelResponseDate__c = br.LatestChannelResponseDate__c;
                        con.LatestChannelResponse__c = br.LatestChannelResponse__c;                        
                        con.LatestCampaign__c = br.LatestCampaign__c == null ? con.LatestCampaign__c : br.LatestCampaign__c;
                    }
                }
                if (oldFirst != con.FirstChannelResponseDate__c || oldLast != con.LatestChannelResponseDate__c)
                    toUpdateContactList.add(con);   
            }

            if (toUpdateContactList.size() != 0 ){
                update toUpdateContactList;
            }
        }
    }
   
    global void finish(Database.BatchableContext BC) {
        
    }
}*/