force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/ConsumingCompetitorBrand__c.field-meta.xml
<CustomField>
    <fullName>ConsumingCompetitorBrand__c</fullName>
    <formula>CurrentBrand__r.CompetitorProduct__c</formula>
    <label>Consuming Competitor Brand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/CurrentBrand__c.field-meta.xml
<CustomField>
    <fullName>CurrentBrand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Brand</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableForCurrentAndPreviousBrand__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships (Current Brand)</relationshipLabel>
    <relationshipName>CurrentBrands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/DuplicateChecker__c.field-meta.xml
<CustomField>
    <fullName>DuplicateChecker__c</fullName>
    <label>Duplicate Checker</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <formula>TEXT(BrandRelationship__r.KeyBrand__c)</formula>
    <label>Key Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCConversionAttemptRequired__c.field-meta.xml
<CustomField>
    <fullName>MCConversionAttemptRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC Conversion Attempt Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCEnsureEndUser__c.field-meta.xml
<CustomField>
    <fullName>MCEnsureEndUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Ensure End User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCEnsureMainContact__c.field-meta.xml
<CustomField>
    <fullName>MCEnsureMainContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Ensure Main Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCGlucernaEndUser__c.field-meta.xml
<CustomField>
    <fullName>MCGlucernaEndUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Glucerna End User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCGlucernaMainContact__c.field-meta.xml
<CustomField>
    <fullName>MCGlucernaMainContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Glucerna  Main Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCGrowEndUser__c.field-meta.xml
<CustomField>
    <fullName>MCGrowEndUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Grow End User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCGrowMainContact__c.field-meta.xml
<CustomField>
    <fullName>MCGrowMainContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Grow Main Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCOthersEndUser__c.field-meta.xml
<CustomField>
    <fullName>MCOthersEndUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Others End User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCOthersMainContact__c.field-meta.xml
<CustomField>
    <fullName>MCOthersMainContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Others Main Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCPediasureEndUser__c.field-meta.xml
<CustomField>
    <fullName>MCPediasureEndUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Pediasure End User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCPediasureMainContact__c.field-meta.xml
<CustomField>
    <fullName>MCPediasureMainContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Pediasure Main Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCSimilacEndUser__c.field-meta.xml
<CustomField>
    <fullName>MCSimilacEndUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Similac End User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCSimilacMainContact__c.field-meta.xml
<CustomField>
    <fullName>MCSimilacMainContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Similac Main Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCSimilacMomEndUser__c.field-meta.xml
<CustomField>
    <fullName>MCSimilacMomEndUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Similac Mom End User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MCSimilacMomMainContact__c.field-meta.xml
<CustomField>
    <fullName>MCSimilacMomMainContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MC - Similac Mom Main Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BrandRelationshipBatch.cls
// for deletion 
public class BrandRelationshipBatch {} /* implements Database.Batchable<sObject> {
	
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		 String query = 'SELECT ID, CurrentBrand__c,Active__c,User__c,PrimaryContact__c,KeyBrand__c,ConsumingCompetitorBrand__c,DuplicateChecker__c,BrandRelationship__c '                           
            + ' FROM BrandRelationship__c'
            + ' WHERE'
            + ' (lastmodifieddate = last_n_days:3)'
            + ' AND PrimaryContact__r.Market__c = \'VN\'';
        return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<BrandRelationship__c> scope) {
    
		Map<Id, Contact> toUpdate = new Map<Id, Contact>();
        List<BrandRelationship__c> allRelatedList = new List<BrandRelationship__c>();
       
		for (BrandRelationship__c brand : scope) {   
            if (brand.PrimaryContact__c == brand.User__c) {
                Contact con = New Contact();
                con.Id = brand.PrimaryContact__c;
                con = procesMarketEndUserBrand(brand, con, allRelatedList);
                con = procesMarketPrimaryContactBrand(brand, con, allRelatedList);
                toUpdate.put(con.Id, con);
            } else {
                Contact conEndUser = New Contact();
                conEndUser.Id = brand.User__c;
                conEndUser = procesMarketEndUserBrand(brand, conEndUser, allRelatedList);
                toUpdate.put(conEndUser.Id, conEndUser);

                Contact con = New Contact();
                con.Id = brand.PrimaryContact__c;
                con = procesMarketPrimaryContactBrand(brand, con, allRelatedList);
                toUpdate.put(con.Id, con);
            }               
			
		}

		if (!toUpdate.isEmpty()) {
            Database.DMLOptions dml = new Database.DMLOptions();
        	dml.DuplicateRuleHeader.allowSave = true;
        	dml.DuplicateRuleHeader.runAsCurrentUser = true; 
        
        	List<Database.SaveResult> sr = Database.update(toUpdate.values(), dml);
		}
    	
	}

	public Contact procesMarketEndUserBrand(BrandRelationship__c brand, Contact con, List<BrandRelationship__c> allRelatedList) {
       
        Boolean activeValue =  brand.Active__c;  
        con = updateEndUserMarketField(con, brand.KeyBrand__c, activeValue);
        return con;
    }

    public Contact procesMarketPrimaryContactBrand(BrandRelationship__c brand, Contact con, List<BrandRelationship__c> allRelatedList) {
        //deleting the record should make the check to false, 
        //for update and insert,  it dependes if the active is true or false
        Boolean activeValuePrimary = brand.Active__c;
        Boolean hasActiveCompetitorPrimary = brand.ConsumingCompetitorBrand__c;
       
        con = updatePrimaryContactMarketField(con, brand.KeyBrand__c, activeValuePrimary);
        
        con.MCConversionAttemptRequired__c = hasActiveCompetitorPrimary;

        return con;
    }   

    public Contact updateEndUserMarketField(Contact con, String keyBrand, Boolean activeValue) {
        if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_SIMILAC) {
            con.MCSimilacEndUser__c = activeValue;
        } else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_GROW) {
            con.MCGrowEndUser__c = activeValue;
        }  else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_PEDIASURE) {
            con.MCPediasureEndUser__c = activeValue;
        }  else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_ENSURE) {
            con.MCEnsureEndUser__c = activeValue;
        }  else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_GLUCERNA) {
            con.MCGlucernaEndUser__c = activeValue;
        } else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_OTHERS) {
            con.MCOthersEndUser__c = activeValue;
        } else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_SIMILACMOM) {
            con.MCSimilacMomEndUser__c = activeValue;
        }

        return con;
    }

    public Contact updatePrimaryContactMarketField(Contact con, String keyBrand, Boolean activeValue) {
        if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_SIMILAC) {
            con.MCSimilacMainContact__c = activeValue;
        } else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_GROW) {
            con.MCGrowMainContact__c = activeValue;
        }  else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_PEDIASURE) {
            con.MCPediasureMainContact__c = activeValue;
        }  else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_ENSURE) {
            con.MCEnsureMainContact__c = activeValue;
        }  else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_GLUCERNA) {
            con.MCGlucernaMainContact__c = activeValue;
        } else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_OTHERS) {
            con.MCOthersMainContact__c = activeValue;
        } else if (keyBrand == CommonConstant.PRODUCT_KEYBRAND_SIMILACMOM) {
            con.MCSimilacMomMainContact__c = activeValue;
        }

        return con;
    }
	global void finish(Database.BatchableContext BC) {
		
	}
	
} */