force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <formula>TEXT(BrandRelationship__r.KeyBrand__c)</formula>
    <label>Key Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Key Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elecare</fullName>
            </value>
            <value>
                <fullName>Ensure</fullName>
            </value>
            <value>
                <fullName>Ensure Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Flexifo</fullName>
            </value>
            <value>
                <fullName>Freego</fullName>
            </value>
            <value>
                <fullName>Glucerna</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>IMF</fullName>
            </value>
            <value>
                <fullName>Jevity</fullName>
            </value>
            <value>
                <fullName>Multi-Brand</fullName>
            </value>
            <value>
                <fullName>Pediasure</fullName>
            </value>
            <value>
                <fullName>Similac</fullName>
            </value>
            <value>
                <fullName>Similac Core</fullName>
            </value>
            <value>
                <fullName>Similac Mom</fullName>
            </value>
            <value>
                <fullName>Similac Total Comfort</fullName>
            </value>
            <value>
                <fullName>Nepro</fullName>
            </value>
            <value>
                <fullName>Osmolite</fullName>
            </value>
            <value>
                <fullName>RCF</fullName>
            </value>
            <value>
                <fullName>Twocal</fullName>
            </value>
            <value>
                <fullName>Vital 1.5Kcal</fullName>
            </value>
            <value>
                <fullName>Other MND</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Isomil</fullName>
            </value>
            <value>
                <fullName>Prosure</fullName>
            </value>
            <value>
                <fullName>Nepro HP</fullName>
                <isActive>false</isActive>
                <label>Nepro HP</label>
            </value>
            <value>
                <fullName>Nepro LP</fullName>
                <isActive>false</isActive>
                <label>Nepro LP</label>
            </value>
            <value>
                <fullName>Similac 3</fullName>
                <isActive>false</isActive>
                <label>Similac 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CallRegarding__c.field-meta.xml
<CustomField>
    <fullName>CallRegarding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Filter to show only Contacts within the Case Contact&apos;s Household</description>
    <label>Call Regarding</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Call Regarding)</relationshipLabel>
    <relationshipName>CallRegarding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CallType__c.field-meta.xml
<CustomField>
    <fullName>CallType__c</fullName>
    <label>Call Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of Awareness will capture as campaign as well</description>
    <label>Call Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>BrandRelationship__r.BrandRelationship__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <label>Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Fill in the Main Contact for this person (e.g. child or elderly person) under the main contact&apos;s care. This field is not required if this person is a Primary Contact.</inlineHelpText>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <label>Key Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abbott General</fullName>
            </value>
            <value>
                <fullName>Abound</fullName>
            </value>
            <value>
                <fullName>Alitraq</fullName>
            </value>
            <value>
                <fullName>Bonesure</fullName>
            </value>
            <value>
                <fullName>Bright Choice</fullName>
            </value>
            <value>
                <fullName>Caltrate</fullName>
            </value>
            <value>
                <fullName>Diabetamill</fullName>
            </value>
            <value>
                <fullName>Elecare</fullName>
            </value>
            <value>
                <fullName>Ensure</fullName>
            </value>
            <value>
                <fullName>Ensure Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Flexiflo</fullName>
            </value>
            <value>
                <fullName>Freego</fullName>
            </value>
            <value>
                <fullName>Glucerna</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Isomil</fullName>
            </value>
            <value>
                <fullName>Jevity</fullName>
            </value>
            <value>
                <fullName>Kidneysure</fullName>
            </value>
            <value>
                <fullName>Nepro</fullName>
            </value>
            <value>
                <fullName>Nutr Accessories</fullName>
            </value>
            <value>
                <fullName>Osmolite</fullName>
            </value>
            <value>
                <fullName>Other MND</fullName>
            </value>
            <value>
                <fullName>Pediasure</fullName>
            </value>
            <value>
                <fullName>Polycose</fullName>
            </value>
            <value>
                <fullName>Prosure</fullName>
            </value>
            <value>
                <fullName>Pulmocare</fullName>
            </value>
            <value>
                <fullName>RCF</fullName>
            </value>
            <value>
                <fullName>Similac</fullName>
            </value>
            <value>
                <fullName>Similac Core</fullName>
            </value>
            <value>
                <fullName>Similac Mom</fullName>
            </value>
            <value>
                <fullName>Similac Total Comfort</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FixCasesIDBatch.cls
/*
Author: Frank Gomendoza
Description: (For Indonesia) Batch job that performs data patch for CR records that has missed Case creation in SFMC
*/
global class FixCasesIDBatch implements Database.Batchable<sObject>, Database.Stateful {
    List<String> crNameList = new List<String>();
    String fixType;
    String campaignName;
    List<Id> caseToInsertSuccess = new List<Id>();
    List<Id> campaignMemberToInsertSuccess = new List<Id>();
    Integer caseToInsertFail = 0;
    Integer campaignMemberToInsertFail = 0;
    
    global FixCasesIDBatch(List<String> inputCRNameList, String inputFixType, String inputCampaignName){
        if(!inputCRNameList.isEmpty()) crNameList = inputCRNameList;
        if(!String.isBlank(inputFixType)) fixType = inputFixType; //Missing or Retention
        if(!String.isBlank(inputCampaignName)) campaignName = inputCampaignName; //Filled if Retention
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String queryStr;
        if(!crNameList.isEmpty()){
            queryStr = 'SELECT Id, Name, Brandrelationship__c, Brandrelationship__r.Primarycontact__c, Brandrelationship__r.User__c, '
                + 'Brandrelationship__r.Primarycontact__r.Donotcall, Brandrelationship__r.User__r.Primarycontact__c, Brandrelationship__r.User__r.Parent__c, '
                + 'Brandrelationship__r.KeyBrand__c, Brand__c '
                + 'FROM ChannelResponse__c '
                + 'WHERE Name IN: crNameList ';
        }
        else{
            queryStr = 'SELECT Id FROM ChannelResponse__c LIMIT 0';
        }
        return Database.getQueryLocator(queryStr);
    }
    
    global void execute(Database.BatchableContext BC, List<ChannelResponse__c> crList){
        List<Case> caseToInsert = new List<Case>();
        List<CampaignMember> campaignMemberToInsert = new List<CampaignMember>();
        
        User u = [SELECT Id FROM User WHERE Name = 'MC Connect-CRM ID' LIMIT 1][0];
        Id callRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Call').getRecordTypeId();
        
        if(fixType == 'Missing'){
            Campaign campaignPediasure = [SELECT Id, Name FROM Campaign WHERE Name = 'ID1.0_Pediasure_Call1_Verificationcall' LIMIT 1][0];
            Campaign campaignEnsure = [SELECT Id, Name FROM Campaign WHERE Name = 'ID2.0_Ensure_Call1_Verificationcall' LIMIT 1][0];
            for(ChannelResponse__c cr : crList){
                if(cr.Brandrelationship__r.KeyBrand__c.contains('Ensure')){
                    Case c = new Case();
                    c.OwnerId = u.Id;
                    c.RecordTypeId = callRTId;
                    c.Status = 'New';
                    c.CallType__c = 'Outbound';
                    c.Campaign__c = campaignEnsure.Id;
                    c.CallRegarding__c = cr.Brandrelationship__r.primarycontact__c;
                    c.ContactId = cr.Brandrelationship__r.primarycontact__c;
                    c.Priority = 'Medium';
                    c.Origin = 'Inbound Call';
                    c.Subject = campaignEnsure.Name;
                    c.Market__c = 'ID';
                    c.RelatedChannelResponse__c = cr.Id;
                    caseToInsert.add(c);
                    
                    CampaignMember cm = new CampaignMember();
                    cm.CampaignId = campaignEnsure.Id;
                    cm.ContactId = cr.Brandrelationship__r.primarycontact__c;
                    cm.Status = 'Sent';
                    campaignMemberToInsert.add(cm);
                }
                else if(cr.Brandrelationship__r.KeyBrand__c.contains('Pediasure')){
                    Case c = new Case();
                    c.OwnerId = u.Id;
                    c.RecordTypeId = callRTId;
                    c.Status = 'New';
                    c.CallType__c = 'Outbound';
                    c.Campaign__c = campaignPediasure.Id;
                    c.CallRegarding__c = cr.Brandrelationship__r.User__c;
                    c.ContactId = cr.Brandrelationship__r.primarycontact__c;
                    c.Priority = 'Medium';
                    c.Origin = 'Inbound Call';
                    c.Subject = campaignPediasure.Name;
                    c.Market__c = 'ID';
                    c.RelatedChannelResponse__c = cr.Id;
                    caseToInsert.add(c);
                    
                    CampaignMember cm = new CampaignMember();
                    cm.CampaignId = campaignPediasure.Id;
                    cm.ContactId = cr.Brandrelationship__r.primarycontact__c;
                    cm.Status = 'Sent';
                    campaignMemberToInsert.add(cm);
                }
            }
            
        }
        else if(fixType == 'Retention' && !String.isBlank(campaignName)){
            Campaign campaignRetention = [SELECT Id, Name FROM Campaign WHERE Name =: campaignName LIMIT 1][0];
            for(ChannelResponse__c cr : crList){
                Case c = new Case();
                c.OwnerId = u.Id;
                c.RecordTypeId = callRTId;
                c.Status = 'New';
                c.CallType__c = 'Outbound';
                c.Campaign__c = campaignRetention.Id;
                c.CallRegarding__c = cr.Brandrelationship__r.User__c;
                c.ContactId = cr.Brandrelationship__r.primarycontact__c;
                c.Priority = 'Medium';
                c.Origin = 'Inbound Call';
                c.Subject = campaignRetention.Name;
                c.Market__c = 'ID';
                c.RelatedChannelResponse__c = cr.Id;
                caseToInsert.add(c);
                
                CampaignMember cm = new CampaignMember();
                cm.CampaignId = campaignRetention.Id;
                cm.ContactId = cr.Brandrelationship__r.primarycontact__c;
                cm.Status = 'Sent';
                campaignMemberToInsert.add(cm);
            }
        }
        
        if(!campaignMemberToInsert.isEmpty()){
            List<Database.SaveResult> srCampaignMemberList = Database.insert(campaignMemberToInsert, false);
            for (Integer i=0; i<srCampaignMemberList.size(); i++){
                if (!srCampaignMemberList.get(i).isSuccess()){
                    Database.Error e = srCampaignMemberList.get(i).getErrors().get(0);
                    System.debug('Insert Failed: ' + e.getStatusCode() + ': ' + e.getMessage());
                    System.debug('Fields that affected this error: ' + e.getFields());
                    campaignMemberToInsertFail++;
                }
                else{
                    campaignMemberToInsertSuccess.add(srCampaignMemberList.get(i).getId());
                }
            }
        }
        
        if(!caseToInsert.isEmpty()){
            List<Database.SaveResult> srCaseList = Database.insert(caseToInsert, false);
            for (Integer i=0; i<srCaseList.size(); i++){
                if (!srCaseList.get(i).isSuccess()){
                    Database.Error e = srCaseList.get(i).getErrors().get(0);
                    System.debug('Insert Failed: ' + e.getStatusCode() + ': ' + e.getMessage());
                    System.debug('Fields that affected this error: ' + e.getFields());
                    caseToInsertFail++;
                }  
                else{
                    caseToInsertSuccess.add(srCaseList.get(i).getId());
                }
            }
        }
        
    }
    
    global void finish(Database.BatchableContext BC){
        System.debug('Number of Inserted Case: ' +caseToInsertSuccess.size());
        System.debug('Number of Failed Case: ' +caseToInsertFail);
        System.debug('Number of Inserted Campaign Members: ' +campaignMemberToInsertSuccess.size());
        System.debug('Number of Failed Campaign Members: ' +campaignMemberToInsertFail);
    }
}