force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <formula>TEXT(BrandRelationship__r.KeyBrand__c)</formula>
    <label>Key Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <label>Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/OrderCreationStatus__c.field-meta.xml
<CustomField>
    <fullName>OrderCreationStatus__c</fullName>
    <label>Order Creation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending - Milk Code Restriction</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful - Product Unavailable</fullName>
            </value>
            <value>
                <fullName>Unsuccessful - Ineligible</fullName>
            </value>
            <value>
                <fullName>Unsuccessful - Missing Address</fullName>
            </value>
            <value>
                <fullName>Successful - Sample Given on Ground</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/ProductSampleRequested__c.field-meta.xml
<CustomField>
    <fullName>ProductSampleRequested__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Sample Requested</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND 2 AND ((3 OR 4) OR (5 AND 6))</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableForSample__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Channel Responses (Product Sample Requested)</relationshipLabel>
    <relationshipName>ProductSampleRequesteds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>RegistrationDate__c</fullName>
    <label>Registration Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/SampleProductCode__c.field-meta.xml
<CustomField>
    <fullName>SampleProductCode__c</fullName>
    <formula>ProductSampleRequested__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>ChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Response</label>
    <referenceTo>ChannelResponse__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SampleOrderCleanupBatch.cls
// for deletion
global class SampleOrderCleanupBatch {} /* implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Name, RegistrationDate__c, SampleProductCode__c, BrandRelationship__c,OrderCreationStatus__c '         
            + 'From ChannelResponse__c Where LastModifiedDate = TODAY and ProductSampleRequested__c != null order by BrandRelationship__c';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<ChannelResponse__c> scope) {
    	if(scope != null) {
            
            Set<Id> brIds = new Set<Id>();

            List<ChannelResponse__c> toDeteleCR = new List<ChannelResponse__c>();
            for (ChannelResponse__c cr : scope) {     
                brIds.add(cr.BrandRelationship__c);
            }

            Map<Id, BrandRelationship__c> brMap = new Map<Id, BrandRelationship__c>([Select Id, PrimaryContact__c,KeyBrand__c,                                                                                      
                                                                                     (Select RegistrationDate__c, SampleProductCode__c, OrderCreationStatus__c,BrandRelationship__c
                                                                                      From Channel_Responses__r Order By RegistrationDate__c,Name asc )
                                                                                     From BrandRelationship__c Where Id IN: brIds]);

            for (BrandRelationship__c br : brMap.values()) {
                Integer crSize = br.Channel_Responses__r.size();
                if (crSize > 1) {
                    Set<String> uniqueCR = new Set<String>();
                    List<ChannelResponse__c> crIneligbleList = new List<ChannelResponse__c>();
                    for (ChannelResponse__c cr : br.Channel_Responses__r) {
                        String keyName = cr.SampleProductCode__c + cr.RegistrationDate__c + cr.OrderCreationStatus__c;
                        if (uniqueCR.contains(keyName)) {
                            toDeteleCR.add(cr);
                        } else {
                            uniqueCR.add(keyName);
                            if (cr.OrderCreationStatus__c == CommonConstant.CHANNELRESPONSE_ORDERSTATUS_INELIGBLE) {
                                crIneligbleList.add(cr);
                            }
                        }
                    }
                    for (ChannelResponse__c cr : crIneligbleList) {
                        String keyName = cr.SampleProductCode__c + cr.RegistrationDate__c + CommonConstant.CHANNELRESPONSE_ORDERSTATUS_SUCCESSFUL;
                        if (uniqueCR.contains(keyName)) {
                            toDeteleCR.add(cr);
                        }
                    }
                }
            }
            if(!toDeteleCR.isEmpty()) {
                List<Order> toDeleteOrder = [Select Id,Status from Order where ChannelResponse__c in: toDeteleCR];
                if (toDeleteOrder.size() != 0) {
                    for (Order o: toDeleteOrder) {
                        o.Status = 'Draft';
                    }
                    Update toDeleteOrder;
                    Delete toDeleteOrder;
                }                
                Delete toDeteleCR;
            }
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
} */