force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/PromotionItem__c.field-meta.xml
<CustomField>
    <fullName>PromotionItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promotion Item</label>
    <referenceTo>PromotionItem__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionItem__c/PromotionItem__c.object-meta.xml
<CustomObject>
    <label>Promotion Item</label>
    <nameField>
        <displayFormat>PI-{000000000}</displayFormat>
        <label>Promotion Item Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PromotionItem__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Promotion Items</relationshipLabel>
    <relationshipName>Promotion_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderProductBatchTest.cls
// for deletion @isTest
public class OrderProductBatchTest {} /*
	
	@testsetup
    static void setupData() {
     	List<User> usrList =  [Select Id From User where LastName = 'Migration'];
    	User sysad = new User();
    	if (usrList.isEmpty()) {
	    	sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'PH');
	    	sysad.FirstName = 'Data';
	    	sysad.LastName = 'Migration';
	        insert sysad;
    	} else {
    		sysad = usrList.get(0);
    	}
        
        System.runAs(sysad) {    
			List<Product2> lProduct = TestDataFactory.createTestBrandProduct(1);           

			List<Account> lAccount = TestDataFactory.createTestHousehold(1);
			List<Contact> lContact = TestDataFactory.createTestAdultContact(1, lAccount.get(0).Id);
			List<BrandRelationship__c> lBrand = TestDataFactory.createTestBrandRelationShip(1, lContact.get(0).Id, lProduct.get(0).Id);

			PricebookEntry entry = TestDataFactory.createPricebookEntry();
			Insert entry;

			List<Order> lOrder = TestDataFactory.createOrder(2, lAccount.get(0).Id, lContact.get(0).Id, Test.getStandardPricebookId());
			Insert lOrder;      

			//Create Promotion Record
			List<Promotion__c> lPromotion = TestDataFactory.createPromotion(1);

			//Create Promotion Item
			List<PromotionItem__c> lPromotionItem = TestDataFactory.createPromotionItem(1,entry.Product2Id ,lpromotion.get(0).Id);

			//Create Order Item
			OrderItem item1 = TestDataFactory.createOrderItem(lOrder.get(0).Id, entry.Id);
			item1.PromotionItem__c =  lPromotionItem.get(0).Id;
			insert item1 ;
    	}
    }
    
    Private static testMethod void getPromotionTest(){   
     	  
    	  test.StartTest();     
	  		OrderProductBatch umd = new OrderProductBatch();
        	Database.executeBatch(umd, 200);
    	  test.StopTest();
         OrderItem item1 = [SELECT Id,Promotion__c,PromotionItem__c FROM OrderItem WHERE PromotionItem__c != null];  
          //update item1;
          PromotionItem__c pi = [SELECT Id, Promotion__c FROM PromotionItem__c LIMIT 1];   
          System.assertEquals(item1.Promotion__c, pi.Promotion__c );
    }
	
}*/