force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/FirstChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>FirstChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>FirstChannelResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/FirstChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>FirstChannelResponseDate__c</fullName>
    <label>First Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestCampaign__c.field-meta.xml
<CustomField>
    <fullName>LatestCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Brand Relationships (Latest Channel Response)</relationshipLabel>
    <relationshipName>LatestChannelResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponseDate__c</fullName>
    <label>Latest Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/NewtoBrand__c.field-meta.xml
<CustomField>
    <fullName>NewtoBrand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New to Brand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/NewtoBrandDate__c.field-meta.xml
<CustomField>
    <fullName>NewtoBrandDate__c</fullName>
    <label>New to Brand Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Website</fullName>
            </value>
            <value>
                <fullName>Campaign Website</fullName>
            </value>
            <value>
                <fullName>Corporate Website</fullName>
            </value>
            <value>
                <fullName>Web - Others</fullName>
            </value>
            <value>
                <fullName>Modern</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Trade - Others</fullName>
            </value>
            <value>
                <fullName>Hospital/Clinic</fullName>
                <label>Hospital</label>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Ethical - Others</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Social - Others</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>Drug Store</fullName>
            </value>
            <value>
                <fullName>EC</fullName>
            </value>
            <value>
                <fullName>Ethical</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>MMC</fullName>
            </value>
            <value>
                <fullName>PX</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>MKT - Others</fullName>
                <isActive>false</isActive>
                <label>MKT - Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <label>Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Registration</fullName>
            </value>
            <value>
                <fullName>Previous Registration - Same Brand</fullName>
            </value>
            <value>
                <fullName>Previous Registration - Different Brand</fullName>
                <isActive>false</isActive>
                <label>Previous Registration - Different Brand</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>RegistrationDate__c</fullName>
    <label>Registration Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>FirstChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Contacts (First Channel Response)</relationshipLabel>
    <relationshipName>firstchannel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>FirstChannelResponseDate__c</fullName>
    <label>First Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestCampaign__c.field-meta.xml
<CustomField>
    <fullName>LatestCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>LatestChannelResponse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponseDate__c</fullName>
    <label>Latest Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/classes/PostChannelResponseTrigger_Batch.cls
/*
Author: Jericson
Description: updates BR and Contact first and last channel response based on CR.
    Moved to batch job since MC is hogging all resources in channel response trigger
NOTE: Do ALL ChannelResponse post transaction here
Date:
    May 13, 2020    Jericson    Created
    May 29, 2020 Jericson Moved to Change Event
*/
public class PostChannelResponseTrigger_Batch {} /*implements Database.Batchable<sObject> {

    static Boolean checkHistory = true;
    static String queryOverride = ''; // should a query of a channel response

    public PostChannelResponseTrigger_Batch(Boolean isHistory, String queryOverrideStr) {
        if(!isHistory) {
            checkHistory = false;
            queryOverride = queryOverrideStr;
        }
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        DateTime minute15 = Datetime.now().addMinutes(-15);
        String query = 'SELECT ParentId,Field,OldValue,NewValue FROM ChannelResponse__History WHERE CreatedDate >: minute15';

        if(!checkHistory) {
            query = queryOverride;
        }

        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<SObject> scope) {
        
        Set<Id> crIds = new Set<Id>();

        if(checkHistory) {
            for (ChannelResponse__History history : (List<ChannelResponse__History>) scope) {
                if(history.Field == 'created'
                    || history.Field == 'RegistrationDate__c')
                    crIds.add(history.parentId);
            }
        }
        // created an override to manually process if this happened to be turned off
        else {
            for(ChannelResponse__c cr: (List<ChannelResponse__c>) scope)
                crIds.add(cr.Id);
        }

        Map<Id, BrandRelationship__c> brToUpdateMap = new Map<Id, BrandRelationship__c>();
        Map<Id, Contact> contactMap = new Map<Id, Contact>();

        for(ChannelResponse__c cr: [SELECT RegistrationDate__c, CreatedDate, Classification__c, Channel__c, Campaign__c,
                                           BrandRelationship__c,
                                           BrandRelationship__r.FirstChannelResponseDate__c, BrandRelationship__r.LatestChannelResponseDate__c,
                                           BrandRelationship__r.PrimaryContact__c,
                                           BrandRelationship__r.PrimaryContact__r.FirstChannelResponseDate__c,
                                           BrandRelationship__r.PrimaryContact__r.LatestChannelResponseDate__c,
                                           BrandRelationship__r.PrimaryContact__r.Type__c
                                      FROM ChannelResponse__c
                                     WHERE Id IN: crIds]) {

            Boolean forUpdate = false;
            BrandRelationship__c br = brToUpdateMap.containsKey(cr.BrandRelationship__c) ?
                                        brToUpdateMap.get(cr.BrandRelationship__c)
                                        : new BrandRelationship__c(
                                            Id = cr.BrandRelationship__c,
                                            PrimaryContact__c = cr.BrandRelationship__r.PrimaryContact__c,
                                            FirstChannelResponseDate__c = cr.BrandRelationship__r.FirstChannelResponseDate__c,
                                            LatestChannelResponseDate__c = cr.BrandRelationship__r.LatestChannelResponseDate__c);

            Datetime registrationDate = cr.RegistrationDate__c == null ? cr.CreatedDate : cr.RegistrationDate__c;

            Boolean TestisRunning = Test.isRunningTest(); // Override | In test class, cr trigger auto populates these fields, none will be met

            /********************************* BRAND RELATIONSHIP ***********************************
            // first CR
            if(TestisRunning
                || br.FirstChannelResponseDate__c  == null
                || registrationDate < br.FirstChannelResponseDate__c) {

                br.FirstChannelResponse__c = cr.Channel__c;
                br.FirstChannelResponseDate__c = registrationDate;

                // retro
                if(cr.Classification__c == CommonConstant.CHANNELRESPONSE_CLASSIFICATION_FIRSTTIME) {
                    br.NewtoBrand__c = true;
                    br.NewtoBrandDate__c = date.valueOf(registrationDate);
                }
                forUpdate = true;
            }

            // last CR
            if(TestisRunning
                || br.LatestChannelResponseDate__c == null
                || registrationDate > br.LatestChannelResponseDate__c) {

                br.LatestCampaign__c = cr.Campaign__c;
                br.LatestChannelResponse__c = cr.Channel__c;
                br.LatestChannelResponseDate__c = registrationDate;
                forUpdate = true;
            }

            if(forUpdate)
                brToUpdateMap.put(br.Id, br);

            /********************************* Contact ***********************************
            // run only for Adult
            if(cr.BrandRelationship__r.PrimaryContact__r.Type__c == 'Adult') {

                forUpdate = false;
                Contact con =   contactMap.containsKey(br.PrimaryContact__c) ?
                                contactMap.get(br.PrimaryContact__c)
                                : new Contact(
                                    Id = cr.BrandRelationship__r.PrimaryContact__c,
                                    FirstChannelResponseDate__c = cr.BrandRelationship__r.PrimaryContact__r.FirstChannelResponseDate__c,
                                    LatestChannelResponseDate__c = cr.BrandRelationship__r.PrimaryContact__r.LatestChannelResponseDate__c);
                // first CR
                if(TestisRunning
                    || con.FirstChannelResponseDate__c  == null
                    || registrationDate < con.FirstChannelResponseDate__c) {
                        
                    con.FirstChannelResponse__c = cr.Channel__c;
                    con.FirstChannelResponseDate__c = registrationDate;
                    forUpdate = true;
                }

                // last CR
                if(TestisRunning
                    || con.LatestChannelResponseDate__c == null
                    || registrationDate > con.LatestChannelResponseDate__c) {

                    con.LatestCampaign__c = cr.Campaign__c;
                    con.LatestChannelResponse__c = cr.Channel__c;
                    con.LatestChannelResponseDate__c = registrationDate;
                    forUpdate = true;
                }

                if(forUpdate)
                    contactMap.put(con.Id, con);
            }
        }

        if(!brToUpdateMap.isEmpty()) { Database.update(brToUpdateMap.values(), false); }
        if(!contactMap.isEmpty()) { Database.update(contactMap.values(), false); }
    }
   
    public void finish(Database.BatchableContext BC) {}
}*/