force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Brand Relationships (Latest Channel Response)</relationshipLabel>
    <relationshipName>LatestChannelResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Key Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elecare</fullName>
            </value>
            <value>
                <fullName>Ensure</fullName>
            </value>
            <value>
                <fullName>Ensure Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Flexifo</fullName>
            </value>
            <value>
                <fullName>Freego</fullName>
            </value>
            <value>
                <fullName>Glucerna</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>IMF</fullName>
            </value>
            <value>
                <fullName>Jevity</fullName>
            </value>
            <value>
                <fullName>Multi-Brand</fullName>
            </value>
            <value>
                <fullName>Pediasure</fullName>
            </value>
            <value>
                <fullName>Similac</fullName>
            </value>
            <value>
                <fullName>Similac Core</fullName>
            </value>
            <value>
                <fullName>Similac Mom</fullName>
            </value>
            <value>
                <fullName>Similac Total Comfort</fullName>
            </value>
            <value>
                <fullName>Nepro</fullName>
            </value>
            <value>
                <fullName>Osmolite</fullName>
            </value>
            <value>
                <fullName>RCF</fullName>
            </value>
            <value>
                <fullName>Twocal</fullName>
            </value>
            <value>
                <fullName>Vital 1.5Kcal</fullName>
            </value>
            <value>
                <fullName>Other MND</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Isomil</fullName>
            </value>
            <value>
                <fullName>Prosure</fullName>
            </value>
            <value>
                <fullName>Nepro HP</fullName>
                <isActive>false</isActive>
                <label>Nepro HP</label>
            </value>
            <value>
                <fullName>Nepro LP</fullName>
                <isActive>false</isActive>
                <label>Nepro LP</label>
            </value>
            <value>
                <fullName>Similac 3</fullName>
                <isActive>false</isActive>
                <label>Similac 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Market identifier</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <label>Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[1-Sep-21 Khai] This field is for troubleshooting by extracting out the market of the Contact</description>
    <formula>Contact__r.Market__c</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AgeinMonths__c.field-meta.xml
<CustomField>
    <fullName>AgeinMonths__c</fullName>
    <formula>IF(NOT(ISBLANK(Birthdate)),
        IF(DAY(Birthdate) &lt;= DAY(TODAY()),
        (YEAR( TODAY())*12+MONTH(TODAY())) - (YEAR(Birthdate)*12+MONTH(Birthdate)),
        (YEAR( TODAY())*12+MONTH(TODAY())) - (YEAR(Birthdate)*12+MONTH(Birthdate))-1
        ),
        0
        )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age (in Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Latest Channel Response</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>LatestChannelResponse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Fill in the Main Contact for this person (e.g. child or elderly person) under the main contact&apos;s care. This field is not required if this person is a Primary Contact.</inlineHelpText>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Related Contacts</relationshipLabel>
    <relationshipName>Parents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml
<RecordType>
    <fullName>Child</fullName>
    <active>true</active>
    <label>Child</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SGSimilacMomBatch.cls
/*
Author: Frank Gomendoza
Description: Batch job for SG that creates Case records for Similac Mom
*/
global class SGSimilacMomBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    
    Set<Id> insertSuccessSet = new Set<Id>();
    List<errorWrap> insertErrorList = new List<errorWrap>();
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Id conChildId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Child').getRecordTypeId();
        String query = 'SELECT Id, Active__c, AgeinMonths__c, AccountId, Parent__c, Parent__r.Active__c, Parent__r.LatestChannelResponse__c, Market__c, Phone, CreatedDate FROM Contact'
            +' WHERE RecordTypeId = \'' + conChildId + '\' AND AgeinMonths__c = 8 AND Market__c = \'' + CommonConstant.MARKET_SG + '\' AND Parent__r.Active__c = TRUE';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        List<Case> newCaseList = new List<Case>();
        if(!scope.isEmpty()){
            Id caseCallId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Call').getRecordTypeId();
            Set<Contact> childConList = new Set<Contact>();
            Set<Id> childConWithSimMomIdSet = new Set<Id>();
            Map<Id, Set<Contact>> parentChildMap = new Map<Id, Set<Contact>>();
            Map<Id, ChannelResponse__c> childCRMap = new Map<Id, ChannelResponse__c>();
            Map<Id, ChannelResponse__c> parentCRMap = new Map<Id, ChannelResponse__c>();
            
            for(Contact con : scope){
                if(parentChildMap.containsKey(con.Parent__c) ){
                    parentChildMap.get(con.Parent__c).add(con);
                }
                else{
                    parentChildMap.put(con.Parent__c, new Set<Contact>{con});
                }
            }
            
            for(ChannelResponse__c cr : [SELECT Id, Contact__c, Contact__r.AccountId, BrandRelationship__c, BrandRelationship__r.Active__c, BrandRelationship__r.User__c, BrandRelationship__r.PrimaryContact__c, BrandRelationship__r.CreatedDate 
                                         FROM ChannelResponse__c WHERE Brand__c = 'SIMILAC MOM' AND Classification__c = 'New Registration' AND Contact__c IN: parentChildMap.keySet() AND BrandRelationship__r.Active__c = true])
            {
                if(cr.BrandRelationship__r.User__c != null){
                    if(childCRMap.containsKey(cr.BrandRelationship__r.User__c)){
                        ChannelResponse__c crPrev = childCRMap.get(cr.BrandRelationship__r.User__c);
                        if(cr.BrandRelationship__r.CreatedDate > crPrev.BrandRelationship__r.CreatedDate){
                            childCRMap.put(cr.BrandRelationship__r.User__c, cr);
                        }
                    }
                    else{
                        childCRMap.put(cr.BrandRelationship__r.User__c, cr);
                    }
                }
                else if(cr.BrandRelationship__r.PrimaryContact__c != null){
                    if(parentCRMap.containsKey(cr.BrandRelationship__r.PrimaryContact__c)){
                        ChannelResponse__c crPrev1 = parentCRMap.get(cr.BrandRelationship__r.PrimaryContact__c);
                        if(cr.BrandRelationship__r.CreatedDate > crPrev1.BrandRelationship__r.CreatedDate){
                            parentCRMap.put(cr.BrandRelationship__r.PrimaryContact__c, cr);
                        }
                    }
                    else{
                        parentCRMap.put(cr.BrandRelationship__r.PrimaryContact__c, cr);
                    }
                }
                childConList.addAll(parentChildMap.get(cr.Contact__c));
            }
            
            //Check if child has Sim Mom Case already
            for(Case c : [SELECT Id, CallRegarding__c, Campaign__c, Campaign__r.Product__r.Name FROM Case WHERE RecordTypeId =: caseCallId AND ProductCampaign__c = 'SIMILAC MOM' AND CallRegarding__c IN: childConList]){
                childConWithSimMomIdSet.add(c.CallRegarding__c); //dont include
            }
            
            //Create Case
            BusinessHours busHrsDefault = [SELECT Id FROM BusinessHours WHERE Name = 'Default' LIMIT 1][0];
            Campaign campaignSimMom = [SELECT Id FROM Campaign WHERE Name = 'SG-SimilacMum-Con&Ren-Call' LIMIT 1][0];
            for(Contact child : childConList){
                //Should not have existing Sim Mom Case
                if(!childConWithSimMomIdSet.contains(child.Id) ){
                    Case newCase = new Case();
                    newCase.RecordtypeId = caseCallId;
                    newCase.Status = 'New';
                    newCase.AccountId = child.AccountId;
                    newCase.ContactId = child.Parent__c;
                    newCase.CallRegarding__c = child.Id;
                    newCase.BusinessHoursId = busHrsDefault.Id;
                    newCase.Subject = 'SG Similac Mom Maternal Con and Ret Call';
                    newCase.Campaign__c = campaignSimMom.Id;
                    newCase.CallType__c = 'Outbound';
                    newCase.Channel__c = child.Parent__r.LatestChannelResponse__c;
                    newCase.Market__c = 'SG';
                    newCase.Survey_Link__c = 'http://cloud.sg.abbottnutrition.com/SimilacMum_EDDSurvey2?Contact_ID='+ child.Parent__c;  
                    if(childCRMap.containsKey(child.Id)){
                        newCase.RelatedChannelResponse__c = childCRMap.get(child.Id).Id;
                        newCase.RelatedBrandRelationship__c = childCRMap.get(child.Id).BrandRelationship__c;
                    }
                    else if(parentCRMap.containsKey(child.Parent__c)){
                        newCase.RelatedChannelResponse__c = parentCRMap.get(child.Parent__c).Id;
                        newCase.RelatedBrandRelationship__c = parentCRMap.get(child.Parent__c).BrandRelationship__c;
                    }
                    newCaseList.add(newCase);
                }
            }
            
            if(!newCaseList.isEmpty()) insertCase(newCaseList);
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        System.debug('Number of Successfully Inserted Case for ' + Date.Today() + ' : ' + insertSuccessSet.size());
        System.debug('Number of Failed Case for ' + Date.Today() + ' : ' + insertErrorList.size());
        Map<Id, Case> insertSuccessMap = new Map<Id, Case>([SELECT Id, Casenumber, ContactId, Contact.Name, Contact.Phone, CallRegarding__r.Name, Channel__r.Name, RelatedCampaign__r.Name FROM Case WHERE Id IN: insertSuccessSet]);
        Id cvIdSuccess;
        Id cvIdError;
        if(!insertSuccessMap.keySet().isEmpty()){
            cvIdSuccess = generateCSVfileSuccess(insertSuccessMap);
        }
        if(!insertErrorList.isEmpty()){
            cvIdError = generateCSVfileError(insertErrorList);
        }
        if(cvIdSuccess != null || cvIdError != null){
            sendEmail(cvIdSuccess, cvIdError, insertSuccessMap.keySet().size(), insertErrorList.size());
        }
    }
    
    global void execute(SchedulableContext sc) {
        SGSimilacMomBatch batch = new SGSimilacMomBatch(); 
        Database.executebatch(batch, 20);
    }
    
    public void insertCase(List<Case> insertList){
        try{
            List<Database.SaveResult> srList = Database.insert(insertList, false);
            for (Integer i=0; i<srList.size(); i++){
                if (srList.get(i).isSuccess()){
                    insertSuccessSet.add(srList.get(i).getId());
                } 
                else if (!srList.get(i).isSuccess()){
                    Database.Error e = srList.get(i).getErrors().get(0);
                    String errorReason = 'Insert Failed: ' + e.getStatusCode() + ': ' + e.getMessage() + '. Case fields that affected this error: ' + e.getFields();
                    errorWrap errRec = new errorWrap();
                    errRec.contactId = (Id) insertList.get(i).get('ContactId');
                    errRec.callRegardingId = (Id) insertList.get(i).get('CallRegarding__c');
                    errRec.relatedCRId = (Id) insertList.get(i).get('RelatedChannelResponse__c');
                    errRec.errorMsg = errorReason;
                    insertErrorList.add(errRec);
                }  
            }
        }
        catch(Exception e){
            System.debug(e);
        }
    }
    
    public Id generateCSVfileSuccess(Map<Id, Case> recSuccessMap) {
        Id contentVersionId;
        if(!recSuccessMap.keySet().isEmpty()){
            String generatedCSVFile ='';
            generatedCSVFile = genereateHeaderSuccess().removeEnd(',') + '\n';
            String fileRow = '';
            for(Id recId : recSuccessMap.keySet()){
                Case c = recSuccessMap.get(recId);
                fileRow = '';
                fileRow = c.CaseNumber;
                fileRow = fileRow +','+ c.Contact.Phone;
                fileRow = fileRow +','+ c.Contact.Name;
                fileRow = fileRow +','+ c.CallRegarding__r.Name;
                fileRow = fileRow +','+ c.Channel__r.Name;
                fileRow = fileRow +','+ c.RelatedCampaign__r.Name;
                generatedCSVFile = generatedCSVFile + fileRow.replace('null', '') + '\n';
            }
            generatedCSVFile = '\uFEFF' + generatedCSVFile.removeEnd('\n');
            Datetime now = Datetime.now(); 
            Integer offset = UserInfo.getTimezone().getOffset(now); 
            Datetime local = now.addSeconds(offset/1000);
            
            contentVersionId = uploadFile(generatedCSVFile, 'SG Successful Insert Case for Similac Mum ' + local , '.csv');
        }
        return contentVersionId;
    }
    
    public Id generateCSVfileError(List<errorWrap> recErrorList) {
        Id contentVersionId;
        if(!recErrorList.isEmpty()){
            String generatedCSVFile ='';
            generatedCSVFile = genereateHeaderError().removeEnd(',') + '\n';
            String fileRow = '';
            for(errorWrap rec : recErrorList){
                fileRow = '';
                fileRow = rec.contactId;
                fileRow = fileRow +','+ rec.callRegardingId;
                fileRow = fileRow +','+ rec.relatedCRId;
                fileRow = fileRow +','+ rec.errorMsg;
                generatedCSVFile = generatedCSVFile + fileRow.replace('null', '') + '\n';
            }
            generatedCSVFile = '\uFEFF' + generatedCSVFile.removeEnd('\n');
            Datetime now = Datetime.now(); 
            Integer offset = UserInfo.getTimezone().getOffset(now); 
            Datetime local = now.addSeconds(offset/1000);
            
            contentVersionId = uploadFile(generatedCSVFile, 'SG Failed Insert Case for Similac Mum ' + local , '.csv');
        }
        return contentVersionId;
    }
    
    public String genereateHeaderSuccess() {
        List<String> headerArray = new List<String>();
        headerArray.add('CaseNumber');
        headerArray.add('Contact Phone');
        headerArray.add('Contact Name');
        headerArray.add('Call Regarding Name');
        headerArray.add('Channel Name');
        headerArray.add('Related Campaign Name');
        return string.join(headerArray, ',');
    }
    public String genereateHeaderError() {
        List<String> headerArray = new List<String>();
        headerArray.add('Contact Id');
        headerArray.add('Call Regarding Id');
        headerArray.add('Related Channel Response Id');
        headerArray.add('Error Message');
        return string.join(headerArray, ',');
    }
    
    public Id uploadFile(String fileContent, String fileName, String fileType) {   
        ContentVersion conVer = new ContentVersion();
        conVer.ContentLocation = 'S'; // S specify this document is in SF, use E for external files
        conVer.PathOnClient = fileName + fileType; // The files name, extension is very important here which will help the file in preview.
        conVer.Title = fileName; // Display name of the files
        conVer.VersionData = blob.valueOf(fileContent); // converting your binary string to Blog
        insert conVer;
        
        conVer = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :conVer.Id LIMIT 1];
        
        String libraryName = 'SimMum_Case_Library_SG';
        if(System.Test.isRunningTest()) { 
            libraryName = 'sfdc_asset_company_assets';
        }
        ContentWorkspace ws = [SELECT Id, RootContentFolderId FROM ContentWorkspace WHERE DeveloperName =: libraryName LIMIT 1];
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = conVer.ContentDocumentId;
        cdl.ShareType = 'I';
        cdl.Visibility = 'AllUsers';
        cdl.LinkedEntityId  = ws.Id;
        insert cdl;
        
        return conVer.Id;
    }
    
    public void sendEmail (Id contentVersionSuccessId, Id contentVersionErrorId, Integer successSize, Integer failedSize) {
        
        List<String> recip = Label.SimMumBatchEmailRecipient.split(',');
        if(!recip.contains(UserInfo.getUserEmail()) ){
            recip.add(UserInfo.getUserEmail());
        }
        
        List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
        
        for(ContentVersion cv : [SELECT Id, Title, FileType, VersionData, isLatest, ContentDocumentId FROM ContentVersion WHERE Id =: contentVersionSuccessId OR Id =: contentVersionErrorId]){
            Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
            attachment.setBody(cv.VersionData);
            attachment.setFileName(cv.Title + '.csv');
            fileAttachments.add(attachment);
        }
        
        String body;
        body = 'Please find the summary of inserted Similac Mom Cases for '+ String.valueOf(Date.today()) + '.\n';
        body += 'Total number of successfully inserted records: ' + successSize + '.\n';
        body += 'Total number of failed inserted records: ' + failedSize + '.\n';
        
        if(!recip.isEmpty()){
            Messaging.SingleEmailMessage semail = new Messaging.SingleEmailMessage();
            semail.setSubject(String.valueOf(Date.today()) + ' Inserted Similac Mom Case Report');
            semail.setToAddresses(recip);
            semail.setPlainTextBody(body);
            if(!fileAttachments.isEmpty()) semail.setFileAttachments(fileAttachments);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{semail});
        }
    }
    
    public class errorWrap {
        public Id contactId {get; set;}
        public Id callRegardingId {get; set;}
		public Id relatedCRId {get; set;}
        public String errorMsg {get; set;}
    }
    
}