force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestMilestone__c.field-meta.xml
<CustomField>
    <fullName>LatestMilestone__c</fullName>
    <label>Latest Milestone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/MilestoneStatus__c.field-meta.xml
<CustomField>
    <fullName>MilestoneStatus__c</fullName>
    <label>Milestone Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Send</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EstimatedDueDate__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDueDate__c</fullName>
    <label>Estimated Due Date (EDD)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WeeksOfPregnancy__c.field-meta.xml
<CustomField>
    <fullName>WeeksOfPregnancy__c</fullName>
    <formula>IF (FLOOR( (TODAY() - (EstimatedDueDate__c  - 280) )/7 ) &gt;= 0 ,
FLOOR( (TODAY() - (EstimatedDueDate__c  - 280) )/7 ),
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weeks of Pregnancy</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactEstimatedDueDateBatch_VN.cls
/**
* @author        Jennifer Alviz
* @date          8.11.2020
* @description   Batch job to run daily to clear EDD on VN Contacts passed due date, MC has a trigger for 40 Weeks milestone, so need to retain EDD
* @revision(s)

4.6.2021    malviz  - TKT-003681: Clear latest milestone on related BR
9.9.2021	malviz	- TKT-005612: Remove Primary Contact filter
*/
global class ContactEstimatedDueDateBatch_VN Implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT ID , EstimatedDueDate__c, AccountId, OwnerId'                           
            + ' FROM Contact'
            + ' WHERE'
            + ' EstimatedDueDate__c < TODAY'
            + ' AND WeeksOfPregnancy__c > 40'
            + ' AND Market__c = \'VN\'';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) {
        List<Contact> lScope = [SELECT ID , EstimatedDueDate__c, Market__c
                                FROM Contact Where ID IN: scope];

        List<BrandRelationship__c> brToUpdate = new List<BrandRelationship__c>();
        Set<Id> conIds = new Set<Id>();

        for(Contact con : lScope) {

            //clear EDD for VN Contacts with more than 40 weeks milestone
            con.EstimatedDueDate__c = null;
            conIds.add(con.Id);
        }

        for(BrandRelationship__c br : [SELECT Id, LatestMilestone__c, MilestoneStatus__c FROM BrandRelationship__c WHERE User__c in :conIds]){
            Boolean toUpdate = false;
            if(br.LatestMilestone__c != null){
                br.LatestMilestone__c = null;
                br.MilestoneStatus__c = null;
                toUpdate = true;
            }
            if(toUpdate) brToUpdate.add(br);
        }


        if (!lScope.isEmpty()) {
            // Update lScope;
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.DuplicateRuleHeader.allowSave = true;
            dml.DuplicateRuleHeader.runAsCurrentUser = true; 
            
            List<Database.SaveResult> sr = Database.update(lScope, dml);
        }

        if (!brToUpdate.isEmpty()){
            UtilityClass.updateList(brToUpdate);
        }
    }

    
    global void finish(Database.BatchableContext BC) {
    }
}