force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>LatestTransactionDate__c</fullName>
    <label>Latest Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Will Buy</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Non_User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/WinBack__c.field-meta.xml
<CustomField>
    <fullName>WinBack__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Win Back</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>LatestTransactionDate__c</fullName>
    <label>Latest Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/MembershipId__c.field-meta.xml
<CustomField>
    <fullName>MembershipId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Membership Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ParentMembership__c.field-meta.xml
<CustomField>
    <fullName>ParentMembership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderTriggerBatchTest.cls
// @isTest for deletion
public class OrderTriggerBatchTest {} /*
	
	@testsetup
    static void setupData() {
    	List<User> usrList =  [Select Id From User where id = '0050o00000VWCHmAAP'];
    	User sysad = new User();
    	if (usrList.isEmpty()) {
	    	sysad = TestDataFactory.createUser('System Administrator', 'tstSysAd' , 'PH');
	    	sysad.FirstName = 'Data';
	    	sysad.LastName = 'Migration';
	        insert sysad;
    	} else {
    		sysad = usrList.get(0);
    	}
        
        System.runAs(sysad) {	  
        	List<Product2> lProduct = TestDataFactory.createTestBrandProduct(1); 		    	
			
			List<Account> lAccount = TestDataFactory.createTestHousehold(1);
			List<Contact> lContact = TestDataFactory.createTestAdultContact(1, lAccount.get(0).Id);
			List<BrandRelationship__c> lBrand = TestDataFactory.createTestBrandRelationShip(1, lContact.get(0).Id, lProduct.get(0).Id);

			PricebookEntry entry = TestDataFactory.createPricebookEntry();
			Insert entry;

			List<Order> lOrder = TestDataFactory.createOrder(2, lAccount.get(0).Id, lContact.get(0).Id, Test.getStandardPricebookId());
			Insert lOrder;			
			
			OrderItem item = TestDataFactory.createOrderItem(lOrder.get(0).Id, entry.Id);
			insert item;

			OrderItem item2 = TestDataFactory.createOrderItem(lOrder.get(0).Id, entry.Id);
			insert item2;

			OrderItem item3 = TestDataFactory.createOrderItem(lOrder.get(1).Id, entry.Id);
			insert item3;
		}
    }

	@isTest
	static void test_updateBrandRelationship_Lead() {
		User sysad = [Select id from User where id = '0050o00000VWCHmAAP' Limit 1];
		System.runAs(sysad) {	  
			Order oRecord = [Select Id, Status from Order Limit 1];
			oRecord.Status = CommonConstant.ORDER_STATUS_COMPLETED;
			update oRecord;
			Test.setCreatedDate(oRecord.Id, DateTime.newInstance(2019,06,01));

			System.Test.startTest();
				
				OrderTriggerBatch umd = new OrderTriggerBatch();
            	Database.executeBatch(umd, 200);
			System.Test.stopTest();
		}

		BrandRelationship__c updatedRecord = [Select Id, Status__c, Type__c from BrandRelationship__c Limit 1];
		System.assertEquals(CommonConstant.BRAND_TYPE_USER, updatedRecord.Type__c );
		System.assertEquals(CommonConstant.BRAND_STATUS_NEW, updatedRecord.Status__c );
	}

	@isTest
	static void test_updateBrandRelationship_User() {
		User sysad = [Select id from User where id = '0050o00000VWCHmAAP' Limit 1];

		System.runAs(sysad) {	
			BrandRelationship__c brand = [Select Id, Status__c, WinBack__c from BrandRelationship__c Limit 1];
			brand.Type__c = CommonConstant.BRAND_TYPE_USER;
			brand.Status__c =  CommonConstant.BRAND_STATUS_LAPSED;
			update brand;
			Order oRecord = [Select Id, Status from Order Limit 1];
			oRecord.Status = CommonConstant.ORDER_STATUS_COMPLETED;
			update oRecord;
			Test.setCreatedDate(oRecord.Id, DateTime.newInstance(2019,06,01));
			System.Test.startTest();
				
				OrderTriggerBatch umd = new OrderTriggerBatch();
            	Database.executeBatch(umd, 200);
			System.Test.stopTest();
		}

		BrandRelationship__c updatedRecord = [Select Id, Status__c, WinBack__c from BrandRelationship__c Limit 1];
		System.assertEquals(true, updatedRecord.WinBack__c );
		System.assertEquals(CommonConstant.BRAND_STATUS_EXISTING, updatedRecord.Status__c );
	}

	@isTest
	static void test_updateContactTransactionDate() {
		User sysad = [Select id from User where id = '0050o00000VWCHmAAP' Limit 1];

		System.runAs(sysad) {	
			Boolean updateFirstRecord = true;
			List<Order> oRecord = [Select Id, Status, EndDate from Order ];
			for (Order rec : oRecord) {
				rec.Status = CommonConstant.ORDER_STATUS_COMPLETED;
				if (updateFirstRecord) {
					rec.EndDate = Date.today().addDays(4);
					updateFirstRecord = false;
				}
			}				
			update oRecord;
			Test.setCreatedDate(oRecord.get(0).Id, DateTime.newInstance(2019,06,01));

			System.Test.startTest();
				
				OrderTriggerBatch umd = new OrderTriggerBatch();
            	Database.executeBatch(umd, 200);
				
			System.Test.stopTest();

			Contact updatedRecord = [Select Id, LatestTransactionDate__c, FirstTransactionDate__c from Contact Limit 1];
			//end date in TestDataFactory.createOrder is Date.today().addDays(2)
			//it should retain the value because the end date we updated is much latest
			System.assertEquals(Date.today().addDays(2), updatedRecord.FirstTransactionDate__c );
			System.assertEquals(Date.today().addDays(4), updatedRecord.LatestTransactionDate__c );
		}
	}

	@isTest
	static void test_updateMembership() {
		
		User sysad = [Select id from User where id = '0050o00000VWCHmAAP' Limit 1];
		System.runAs(sysad) {	
			Membership__c mem = new Membership__c();
			mem.Status__c = 'New'    	;
			mem.MembershipId__c = '111123';
			insert mem;
			
			Order oRecord = [Select Id, Status,ParentMembership__c from Order Limit 1];
			oRecord.Status = CommonConstant.ORDER_STATUS_COMPLETED;
			oRecord.ParentMembership__c = mem.Id;
			update oRecord;
			Test.setCreatedDate(oRecord.Id, DateTime.newInstance(2019,06,01));

			System.Test.startTest();
				
				OrderTriggerBatch umd = new OrderTriggerBatch();
            	Database.executeBatch(umd, 200);
			System.Test.stopTest();
		}
	}

	@isTest
	static void test_updateMembershipCancelOrder() {
		
		User sysad = [Select id from User where id = '0050o00000VWCHmAAP' Limit 1];
		System.runAs(sysad) {	
			Membership__c mem = new Membership__c();
			mem.Status__c = 'New'    	;
			mem.MembershipId__c = '111123';
			mem.MembershipStartDate__c = Date.today().addDays(-91);
			insert mem;

			Order oRecord = [Select Id, Status,ParentMembership__c from Order Limit 1];
			oRecord.Status = 'Cancelled - Abandoned';
			oRecord.ParentMembership__c = mem.Id;
			update oRecord;

			Test.setCreatedDate(oRecord.Id, DateTime.newInstance(2019,06,01));
			System.Test.startTest();
				
			
				OrderTriggerBatch umd = new OrderTriggerBatch();
            	Database.executeBatch(umd, 200);
			System.Test.stopTest();
		}
	}
   
	
}*/