force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Will Buy</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Non_User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BrandRelationship_PathController.cls
/**
* @author        Rey Austral
* @date          1.14.2019
* @description   Class use by the BrandRelationship_Path component
* @testClass     BrandRelationship_PathControllerTest
* @revision(s)
*/
public class BrandRelationship_PathController {
    
    // @author        Rey Austral
    // @date          1.14.2019
    // @description   Method that will return the active value of the status field and will be used in the path
    // @revision(s)
    @AuraEnabled 
    public static List<StatusPathWrapper> getPath(String recId) { 
        BrandRelationship__c brand = [Select Type__c, Status__c From BrandRelationship__c Where Id =: recId];
        
        Map<String, List<String>> rawMap = UtilityClass.getDependentMap(brand, 'Type__c', 'Status__c');
        
        List<StatusPathWrapper> result = new List<StatusPathWrapper>();
        if (rawMap.containskey(brand.Type__c)) {        
            Boolean inactiveOther = false;
            List<String> picklistValueList = rawMap.get(brand.Type__c);
            Integer currentRow = 1;
            for(String depValue : picklistValueList) {
                StatusPathWrapper path = new StatusPathWrapper();
                path.pathName = depvalue;                
                if (depValue == brand.Status__c) {
                    //if the last value is the selected, mark that as completed and not active
                    if (currentRow == picklistValueList.size()) {
                        path.isCompleted = true;                       
                    } else {
                         path.isActive = true;
                    }
                    //the next item should be inactive state
                    inactiveOther = true;
                } else if (inactiveOther == false) {
                    //if the path is not selected then it is already completed
                    path.isCompleted = true;                     
                } 
                currentRow++;
                result.add(path);
            }
        }
        return result;
    }
    
    public class StatusPathWrapper {
        @AuraEnabled
        public String pathName { get; set; }
        @AuraEnabled
        public Boolean isCompleted { get; set; }
        @AuraEnabled
        public Boolean isActive { get; set; }	
        
        public StatusPathWrapper() {
            isCompleted = false;
            isActive = false;
        }
    }
}