force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <formula>TEXT(BrandRelationship__r.KeyBrand__c)</formula>
    <label>Key Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Key Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elecare</fullName>
            </value>
            <value>
                <fullName>Ensure</fullName>
            </value>
            <value>
                <fullName>Ensure Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Flexifo</fullName>
            </value>
            <value>
                <fullName>Freego</fullName>
            </value>
            <value>
                <fullName>Glucerna</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>IMF</fullName>
            </value>
            <value>
                <fullName>Jevity</fullName>
            </value>
            <value>
                <fullName>Multi-Brand</fullName>
            </value>
            <value>
                <fullName>Pediasure</fullName>
            </value>
            <value>
                <fullName>Similac</fullName>
            </value>
            <value>
                <fullName>Similac Core</fullName>
            </value>
            <value>
                <fullName>Similac Mom</fullName>
            </value>
            <value>
                <fullName>Similac Total Comfort</fullName>
            </value>
            <value>
                <fullName>Nepro</fullName>
            </value>
            <value>
                <fullName>Osmolite</fullName>
            </value>
            <value>
                <fullName>RCF</fullName>
            </value>
            <value>
                <fullName>Twocal</fullName>
            </value>
            <value>
                <fullName>Vital 1.5Kcal</fullName>
            </value>
            <value>
                <fullName>Other MND</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Isomil</fullName>
            </value>
            <value>
                <fullName>Prosure</fullName>
            </value>
            <value>
                <fullName>Nepro HP</fullName>
                <isActive>false</isActive>
                <label>Nepro HP</label>
            </value>
            <value>
                <fullName>Nepro LP</fullName>
                <isActive>false</isActive>
                <label>Nepro LP</label>
            </value>
            <value>
                <fullName>Similac 3</fullName>
                <isActive>false</isActive>
                <label>Similac 3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Source of Awareness will capture as campaign as well</description>
    <label>Call Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Cases (Channel)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/RelatedBrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>RelatedBrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/RelatedChannelResponse__c.field-meta.xml
<CustomField>
    <fullName>RelatedChannelResponse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Channel Response</label>
    <referenceTo>ChannelResponse__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>BrandRelationship__r.BrandRelationship__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <label>Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CaseCleanup.cls
/*
Author: Jericson Mercado
Description: Batch job that is created to link all existing cases to the latest channel response based on contact at the time it was created

History
05/17/2021   Binh   	Created
06/09/2021   Jennifer   Comment out entire code, one-time use only
-------------------------------------------------------------------------------------------*/
// for deletion
public class CaseCleanup {} /* implements Database.Batchable<sObject> {
global class CaseCleanup implements Database.Batchable<sObject>, Database.Stateful {
    
    User datamigration;
    global CaseCleanup(){
        String dataStr = Test.isRunningTest() ?  'datamigration@tigerani.abbott.comtest' : 'datamigration@tigerani.abbott.com';
        datamigration = [SELECT Id FROM User WHERE Username =: dataStr];
    }

    global Database.QueryLocator start(Database.BatchableContext BC){

        Id callRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Call').getRecordTypeId();
        String queryStr = 'SELECT Id, ContactId, CreatedDate, Channel__c, Campaign__r.Brand__c FROM Case WHERE RecordTypeId =: callRecordType and lastmodifieddate > 2019-09-15T10:00:00Z and lastmodifieddate <= 2019-09-24T23:00:00Z and channel__c = null and Campaign__c != null';
        if(System.Test.isRunningTest()) { 
            queryStr = 'SELECT Id, ContactId, CreatedDate, Channel__c, Campaign__r.Brand__c FROM Case WHERE RecordTypeId =: callRecordType';
        }
        return Database.getQueryLocator(queryStr);
    }
    
    global void execute(Database.BatchableContext BC, List<Case> caseList){
        
        //get contact ids and create a map out of it.
        Map<Id, List<Case>> contactCaseMap = new Map<Id, List<Case>>();
        for(Case c: caseList){
            if(c.ContactId != null){
                if(!contactCaseMap.containsKey(c.ContactId)){
                    contactCaseMap.put(c.ContactId, new List<Case>());
                }
                contactCaseMap.get(c.ContactId).add(c);
            }
        }

        //get channel from channel response through brand relationship
        Map<Id, Map<String, List<ChannelResponse__c>>> contactChannelMap = new Map<Id, Map<String, List<ChannelResponse__c>>>();

        //exclude from data migration here
        for(BrandRelationship__c br: [SELECT PrimaryContact__c, KeyBrand__c,
                                             (SELECT Id, Name, CreatedDate, Channel__c,BrandRelationship__c
                                                FROM Channel_Responses__r
                                               WHERE Channel__c != null)
                                        FROM BrandRelationship__c
                                       WHERE PrimaryContact__c IN: contactCaseMap.keySet()
                                         AND KeyBrand__c != null]){
            if(!br.Channel_Responses__r.isEmpty()){
                if(!contactChannelMap.containsKey(br.PrimaryContact__c)){
                    contactChannelMap.put(br.PrimaryContact__c, new Map<String, List<ChannelResponse__c>>());
                }
                if(!contactChannelMap.get(br.PrimaryContact__c).containsKey(br.KeyBrand__c)){
                    contactChannelMap.get(br.PrimaryContact__c).put(br.KeyBrand__c, new List<ChannelResponse__c>());
                }
                contactChannelMap.get(br.PrimaryContact__c).get(br.KeyBrand__c).addAll(br.Channel_Responses__r);
            }
        }

        
        Map<Id, Case> caseMap = new Map<Id, Case>();
        for(Case c: caseList){

            //remove initial
            if(c.Channel__c != null || c.Campaign__c == null || String.isBlank(c.Campaign__r.Brand__c)){
                c.Channel__c = null;
                caseMap.put(c.Id, c);
            }
            //check if the contact has a channel response
            if(contactChannelMap.containsKey(c.ContactId)
                && contactChannelMap.get(c.ContactId).containsKey(c.Campaign__r.Brand__c)){
                
                ChannelResponse__c createdBefore = new ChannelResponse__c();
                ChannelResponse__c createdAfter = new ChannelResponse__c();
                for(ChannelResponse__c cr: contactChannelMap.get(c.ContactId).get(c.Campaign__r.Brand__c)){
                    
                    if(c.CreatedDate > cr.CreatedDate){
                        createdBefore = cr;
                    }
                    else if(c.CreatedDate < cr.CreatedDate
                        && createdAfter.Id == null) {
                        createdAfter = cr;
                    }
                }

                ChannelResponse__c correctCR = createdBefore.createdDate == getNearestDate(c.CreatedDate, createdBefore.createdDate, createdAfter.createdDate)
                                ? createdBefore : createdAfter;
                c.Channel__c = correctCR.Channel__c;
                c.RelatedChannelResponse__c = correctCR.Id;
                c.RelatedBrandRelationship__c = correctCR.BrandRelationship__c;

                caseMap.put(c.Id, c);
            }
        }

        if(!caseMap.isEmpty()) Database.update(caseMap.values(), false);
    }
    
    global void finish(Database.BatchableContext BC){}

    public DateTime getNearestDate(DateTime call, DateTime crBefore, DateTime crAfter) {

        DateTime b = DateTime.Now();

        // no CR after case creation
        if(crBefore != null
            && crAfter == null){
            b = crBefore;
        }
        // no CR before case creation
        else if(crBefore == null
            && crAfter != null){
            b = crAfter;
        }
        // there are CR both before and after case creation
        else {

            // set previous CR as default
            b = crBefore;

            Integer daysBetweenBefore = Math.ABS(Date.valueOf(call).DaysBetween(Date.valueOf(crBefore)));
            Integer daysBetweenAfter = Math.ABS(Date.valueOf(call).DaysBetween(Date.valueOf(crAfter)));

            // check if both CR is created as same day of the case
            if(call.isSameDay(crBefore)
                && call.isSameDay(crAfter)){
                
                Long caseTime = call.getTime();
                Long crBeforeTime = crBefore.getTime();
                Long crAfterTime = crAfter.getTime();

                Long crTimeDiffBefore = Math.ABS(caseTime - crBeforeTime);
                Long crTimeDiffAfter = Math.ABS(caseTime - crAfterTime);

                b = crTimeDiffBefore < crTimeDiffAfter ? crBefore : crAfter;
            } else if(daysBetweenBefore > daysBetweenAfter) {
                b = crAfter;
            }
        }

        return b;
    }
}*/