force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>LatestTransactionDate__c</fullName>
    <label>Latest Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>LatestTransactionDate__c</fullName>
    <label>Latest Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderedBy__c.field-meta.xml
<CustomField>
    <fullName>OrderedBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordered By</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Adult</value>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/BrandRelationshipLinkStatus__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationshipLinkStatus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Brand Relationship Link Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BrandRelationshipLink__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationshipLink__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship Link</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND ((3 OR 4) OR (5 AND 6))</booleanFilter>
        <errorMessage>Selected product must be Available for Brand Relationship</errorMessage>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Brand Relationship Link)</relationshipLabel>
    <relationshipName>Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/classes/BrandRelationTransactionMonitor.cls
public class BrandRelationTransactionMonitor implements Database.Batchable<sObject>  {

    private Boolean isHourly = true;
    public BrandRelationTransactionMonitor(Boolean i) {
        isHourly = i;
    }

    public Database.QueryLocator start(Database.BatchableContext BC){

        String status = CommonConstant.ORDER_STATUS_COMPLETED;
        DateTime last2hours = Datetime.now().addhours(-2);
        String query = 'SELECT ParentId,Field,OldValue,NewValue FROM ChannelResponse__History WHERE CreatedDate >: minute15';
        String queryStr = 'SELECT Order.EndDate, Order.OrderedBy__c, Product2.BrandRelationshipLink__c'
                        + ' FROM OrderItem'
                        + ' WHERE Order.Status =: status'
                        + ' AND BrandRelationshipLinkStatus__c = false'
                        + ' AND Product2.BrandRelationshipLink__c != null';

        // will be used to run hourly
        if(isHourly) {
            queryStr += ' AND Order.LastModifiedDate >: last2hours';
        }

        queryStr += ' ORDER BY CreatedDate DESC';

        if(Test.isRunningTest()){
            queryStr = 'SELECT Order.EndDate, Order.OrderedBy__c, Product2.BrandRelationshipLink__c, BrandRelationshipLinkStatus__c'
                        + ' FROM OrderItem'
                        + ' WHERE Order.Status =: status';
        }

        return Database.getQueryLocator(queryStr);
    }

    public void execute(Database.BatchableContext BC, List<OrderItem> oiList){
        
        Set<Id> conIds = new Set<Id>();
        Set<Id> productIds = new Set<Id>();
        // create map of contact and product
        Map<String, List<OrderItem>> contactProductMap = new Map<String, List<OrderItem>>();
        for(OrderItem oi: oiList){
            String key = oi.Order.OrderedBy__c + '-' + oi.Product2.BrandRelationshipLink__c;
            if(!contactProductMap.containsKey(key)){
                contactProductMap.put(key, new List<OrderItem>());
            }
            contactProductMap.get(key).add(oi);

            conIds.add(oi.Order.OrderedBy__c);
            productIds.add(oi.Product2.BrandRelationshipLink__c);
        }

        Map<Id, OrderItem> oiListForUpdate = new Map<Id, OrderItem>();
        Map<Id, BrandRelationship__c> brList = new Map<Id, BrandRelationship__c>();
        for(BrandRelationship__c br: [SELECT FirstTransactionDate__c, LatestTransactionDate__c, PrimaryContact__c, BrandRelationship__c
                                        FROM BrandRelationship__c
                                       WHERE PrimaryContact__c IN: conIds
                                         AND BrandRelationship__c IN: productIds]){
            Boolean forUpdate = false;                                             
            String key = br.PrimaryContact__c + '-' + br.BrandRelationship__c;
            if(contactProductMap.containsKey(key)){
                for(OrderItem oi: contactProductMap.get(key)){

                    // check first transaction date
                    if(br.FirstTransactionDate__c == null
                        || (br.FirstTransactionDate__c != null 
                            && br.FirstTransactionDate__c > oi.Order.EndDate)){
                        br.FirstTransactionDate__c = oi.Order.EndDate;
                        forUpdate = true;
                    }

                    // check latest transaction date
                    if(br.LatestTransactionDate__c == null
                        || (br.LatestTransactionDate__c != null 
                            && br.LatestTransactionDate__c < oi.Order.EndDate)
                        ){
                        br.LatestTransactionDate__c = oi.Order.EndDate;
                        forUpdate = true;
                    }

                    // update order item to prcessed
                    oi.BrandRelationshipLinkStatus__c = true;
                    oiListForUpdate.put(oi.Id, oi);
                }
            }

            if(forUpdate) brList.put(br.Id, br);
        }

        if(!oiListForUpdate.isEmpty()) UtilityClass.updateList(oiListForUpdate.values());
        if(!brList.isEmpty()) UtilityClass.updateList(brList.values());
    }
    
    public void finish(Database.BatchableContext BC){}
}