force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <formula>TEXT(BrandRelationship__r.KeyBrand__c)</formula>
    <label>Key Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>LatestTransactionDate__c</fullName>
    <label>Latest Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Uncontacted</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Retained</fullName>
            </value>
            <value>
                <fullName>Will Buy</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Non_User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Able to link case to order</description>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Order.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Count__c.field-meta.xml
<CustomField>
    <fullName>Order_Count__c</fullName>
    <label>Order Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <businessProcess>Call</businessProcess>
    <description>Outbound or inbound calls handled by Call Center and Customer Service Agents</description>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/Contact/fields/FirstTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>FirstTransactionDate__c</fullName>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestTransactionDate__c.field-meta.xml
<CustomField>
    <fullName>LatestTransactionDate__c</fullName>
    <label>Latest Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Loyalty Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <displayFormat>M-{000000000}</displayFormat>
        <label>Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/MembershipExpiryDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipExpiryDate__c</fullName>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/MembershipStartDate__c.field-meta.xml
<CustomField>
    <fullName>MembershipStartDate__c</fullName>
    <label>Membership Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/NumberOfDaysDormant__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysDormant__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Days Dormant</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/NumberOfTransactions__c.field-meta.xml
<CustomField>
    <fullName>NumberOfTransactions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/FirstRepeatOrderName__c.field-meta.xml
<CustomField>
    <fullName>FirstRepeatOrderName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[9-Jul-21 KSK] Used in TW Market Data Migration; Dynamics CRM</description>
    <label>First Repeat Order Name</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Orders (First Repeat Order Name)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <label>Membership ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_Number_Formula__c.field-meta.xml
<CustomField>
    <fullName>Order_Number_Formula__c</fullName>
    <formula>IF( ISBLANK(Id) , 0, 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number Formula</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/OrderedBy__c.field-meta.xml
<CustomField>
    <fullName>OrderedBy__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordered By</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Adult</value>
        </filterItems>
        <filterItems>
            <field>$Source.To_be_archived__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ParentMembership__c.field-meta.xml
<CustomField>
    <fullName>ParentMembership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/KeyBrand__c.field-meta.xml
<CustomField>
    <fullName>KeyBrand__c</fullName>
    <label>Key Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abbott General</fullName>
            </value>
            <value>
                <fullName>Abound</fullName>
            </value>
            <value>
                <fullName>Alitraq</fullName>
            </value>
            <value>
                <fullName>Bonesure</fullName>
            </value>
            <value>
                <fullName>Bright Choice</fullName>
            </value>
            <value>
                <fullName>Caltrate</fullName>
            </value>
            <value>
                <fullName>Diabetamill</fullName>
            </value>
            <value>
                <fullName>Elecare</fullName>
            </value>
            <value>
                <fullName>Ensure</fullName>
            </value>
            <value>
                <fullName>Ensure Diabetes Care</fullName>
            </value>
            <value>
                <fullName>Flexiflo</fullName>
            </value>
            <value>
                <fullName>Freego</fullName>
            </value>
            <value>
                <fullName>Glucerna</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Isomil</fullName>
            </value>
            <value>
                <fullName>Jevity</fullName>
            </value>
            <value>
                <fullName>Kidneysure</fullName>
            </value>
            <value>
                <fullName>Nepro</fullName>
            </value>
            <value>
                <fullName>Nutr Accessories</fullName>
            </value>
            <value>
                <fullName>Osmolite</fullName>
            </value>
            <value>
                <fullName>Other MND</fullName>
            </value>
            <value>
                <fullName>Pediasure</fullName>
            </value>
            <value>
                <fullName>Polycose</fullName>
            </value>
            <value>
                <fullName>Prosure</fullName>
            </value>
            <value>
                <fullName>Pulmocare</fullName>
            </value>
            <value>
                <fullName>RCF</fullName>
            </value>
            <value>
                <fullName>Similac</fullName>
            </value>
            <value>
                <fullName>Similac Core</fullName>
            </value>
            <value>
                <fullName>Similac Mom</fullName>
            </value>
            <value>
                <fullName>Similac Total Comfort</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderTriggerBatch.cls
// for deletion
public class OrderTriggerBatch {} /* implements Database.Batchable<sObject> {
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		String query = 'SELECT ID, ParentMembership__c,OrderedBy__c, Status '                           
            + ' FROM Order'
            + ' WHERE'
            + ' createddate > 2020-06-18T10:00:00Z and createddate <= 2020-06-19T23:00:00Z'
            + ' AND (Createdby.Name = \'Data Migration\' OR Createdby.Name = \'Data Integration\')';
        return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Order> scope) {
   		Set<Id> conIdSet = new Set<Id>();
        Set<Id> membershipIdSet = new Set<Id>();
        Set<Id> oldMembershipIdSet = new Set<Id>();
        Set<Id> endDateUpdateMembershipIsSet = new Set<Id>();
        String orderStatus;

   		for(Order o : scope) {
   			if(o.ParentMembership__c != null) {
                membershipIdSet.add(o.ParentMembership__c);
            }

            if(o.OrderedBy__c != null && o.Status == CommonConstant.ORDER_STATUS_COMPLETED) {
                conIdSet.add(o.OrderedBy__c);
            }
   		}

   		if (!conIdSet.isEmpty()) {
	   		List<Contact> contactToUpdateList = [Select Id, FirstTransactionDate__c, LatestTransactionDate__c, MembershipStartDate__c, 
	                                             (Select EndDate From Orders__r Where EndDate != null AND Status =: CommonConstant.ORDER_STATUS_COMPLETED
	                                              order by EndDate) 
	                                             From Contact Where Id IN : conIdSet];                                          
	        for (Contact con : contactToUpdateList) {             

	            if (con.Orders__r.isEmpty()) {                               
	                con.FirstTransactionDate__c = null;
	                con.LatestTransactionDate__c = null;
	            } else {
	                //refresh the date        
	                con.FirstTransactionDate__c = null;
	                con.LatestTransactionDate__c = null;
	                
	                for(Order order : con.Orders__r) {
	                    //update loyalty - US-0492
	                    if (con.MembershipStartDate__c == null) {
	                        //MembershipStartDate__c should only be populated with the first completed order
	                        //if MembershipStartDate__c is null it means there is no order with completed status
	                        //if the code execute this function it means the con.Orders__r should only have 1 record
	                        con.MembershipStartDate__c = order.EndDate;
	                    }

	                    if (con.FirstTransactionDate__c == null) {
	                        con.FirstTransactionDate__c = order.EndDate;
	                        con.LatestTransactionDate__c = order.EndDate;
	                    } else {
	                        con.FirstTransactionDate__c = con.FirstTransactionDate__c > order.EndDate ? order.EndDate : con.FirstTransactionDate__c;
	                        con.LatestTransactionDate__c = con.LatestTransactionDate__c < order.EndDate ? order.EndDate : con.LatestTransactionDate__c;
	                    }
	                }
	            }
	        }

	        if (!contactToUpdateList.isEmpty()) {
	            //update contactToUpdateList;
	            Database.DMLOptions dml = new Database.DMLOptions();
	            dml.DuplicateRuleHeader.allowSave = true;
	            dml.DuplicateRuleHeader.runAsCurrentUser = true; 
	        
	            List<Database.SaveResult> sr = Database.update(contactToUpdateList, dml);
        	}
    	}

    	if(!membershipIdSet.isEmpty()) {
            updateMembershipDetails(membershipIdSet);
        }

        orderCount(scope);
        updateBrandRelationship(scope);
	
	}

	public static void updateMembershipDetails(Set<Id> membershipIdSet) {
        List<Membership__c> membershipList = new List<Membership__c>();
        for(Membership__c mem : [SELECT NumberOfDaysDormant__c, NumberOfTransactions__c, MembershipStartDate__c,
                                    (SELECT EndDate From Orders__r WHERE Status != 'Cancelled - New Order Created' AND Status != 'Cancelled - Before Delivery' AND Status != 'Cancelled - Upon Delivery' AND Status != 'Cancelled - Abandoned' 
                                    ORDER BY EndDate DESC LIMIT 1) 
                                    FROM Membership__c
                                    WHERE Id IN :membershipIdSet]) {

            mem.NumberOfTransactions__c = 0;

            if(!mem.Orders__r.isEmpty()) {
            	mem.NumberOfTransactions__c = mem.Orders__r.size();

                for(Order order : mem.Orders__r) {                	

                    if(order.EndDate != null) {
                        if(order.EndDate == Date.valueOf(System.today())) {
                            mem.NumberOfDaysDormant__c = 0;    
                        } else {
                            mem.NumberOfDaysDormant__c = order.EndDate.daysBetween(System.today());
                        }

                        if(mem.NumberOfDaysDormant__c >= 90) {
                            mem.Status__c = CommonConstant.MEMBERSHIP_STATUS_EXPIRED;
                            mem.MembershipExpiryDate__c = order.EndDate.addDays(90);
                        }
                    }
                }
            } else {
                if(mem.MembershipStartDate__c != null) {
                    if(mem.MembershipStartDate__c == Date.valueOf(System.today())) {
                        mem.NumberOfDaysDormant__c = 0;    
                    } else {
                        mem.NumberOfDaysDormant__c = mem.MembershipStartDate__c.daysBetween(System.today());
                    }

                    if(mem.NumberOfDaysDormant__c >= 90) {
                        mem.Status__c = CommonConstant.MEMBERSHIP_STATUS_EXPIRED;
                        mem.MembershipExpiryDate__c = mem.MembershipStartDate__c.addDays(90);
                    }
                }
            }

            if (mem.NumberOfDaysDormant__c < 0) {
                mem.NumberOfDaysDormant__c = 0;
            }

            membershipList.add(mem);
        }

        if(!membershipList.isEmpty()) {
        	update membershipList;
        }
    }

    public static void orderCount(List<Order> orderList) {
        set<id> caseId = new set<id>();
        
        For(Order o: [Select Id, Case__c, Order_Number_Formula__c, ParentMembership__c From order where id in: orderList]) {
            caseId.add(o.Case__c);
        }
        
        Map<Id, Case> caseMaptoUpdate = new Map<Id, Case>();
        for(Case c : [Select Id, Order__c, RecordType.Name From Case Where Recordtype.Name = 'Call' AND id in: caseId]) {
            caseMaptoUpdate.put(c.id, c);
        }
        
        system.debug(caseMaptoUpdate);
        
        for(AggregateResult result:[Select SUM(Order_Number_Formula__c) Qty, Case__c getId From Order Where Case__c in: caseMaptoUpdate.keyset() GROUP by Case__c]) {
            String parentId = (String)result.get('getId');
            Case cas = caseMaptoUpdate.get(parentId);
            Decimal totalQuantity = (decimal)result.get('Qty');
            cas.Order_Count__c = totalQuantity;
            caseMaptoUpdate.put(parentId,cas);
        }
        system.debug(caseMaptoUpdate.values());
        database.update(caseMaptoUpdate.values());
    }

    public static void updateBrandRelationship(List<Order> orderList) {
        Set<Id> conIdSet = new Set<Id>();
        Map<String, String> orderContactMap = new Map<String, String>();
        
        for(Order o : orderList) {           
            if ( o.OrderedBy__c != null && o.Status == CommonConstant.ORDER_STATUS_COMPLETED) {
                conIdSet.add(o.OrderedBy__c);
                orderContactMap.put(o.Id , o.OrderedBy__c);
            }            
        }
        
        if (!conIdSet.isEmpty()) {

        	Map<String, Set<String>> contactProductMap = new Map<String, Set<String>>();
	        for (OrderItem oItem : [Select Product2.KeyBrand__c,OrderId From OrderItem Where OrderId IN: orderContactMap.keySet() ]) {
	            String contactId = orderContactMap.get(oItem.OrderId);
	            if (contactProductMap.containsKey(contactId)) {
	                Set<String> currentBrand = contactProductMap.get(contactId);
	                currentBrand.add(oItem.Product2.KeyBrand__c);
	                contactProductMap.put(contactId, currentBrand);
	            } else {
	                contactProductMap.put(contactId, new Set<String>{ oItem.Product2.KeyBrand__c });
	            }            
	        }
	        
	        List<BrandRelationship__c> toUpdateBrand = new List<BrandRelationship__c>();
	        
	        for (Contact con : [Select Id, (Select Id, KeyBrand__c, Status__c, Type__c, WinBack__c From BrandRelationships__r) From Contact Where Id in :conIdSet]) {
	            Set<String> productBrand = contactProductMap.get(con.Id);
	            for (BrandRelationship__c brand : con.BrandRelationships__r) {
	                if (productBrand.contains(brand.KeyBrand__c)) {
	                    if (brand.Type__c == CommonConstant.BRAND_TYPE_LEAD) {
	                        brand.Type__c = CommonConstant.BRAND_TYPE_USER;
	                        brand.Status__c = CommonConstant.BRAND_STATUS_NEW;
	                        toUpdateBrand.add(brand);
	                    } else if (brand.Type__c ==  CommonConstant.BRAND_TYPE_USER && brand.Status__c == CommonConstant.BRAND_STATUS_LAPSED) {
	                        brand.Status__c = CommonConstant.BRAND_STATUS_EXISTING;
	                        brand.WinBack__c = true;
	                        toUpdateBrand.add(brand);
	                    }
	                }
	            }
	            
	        } 
	        System.debug(toUpdateBrand);
	        if(!toUpdateBrand.isEmpty()) {
	            //update toUpdateBrand;
	            Database.DMLOptions dml = new Database.DMLOptions();
	            dml.DuplicateRuleHeader.allowSave = true;
	            dml.DuplicateRuleHeader.runAsCurrentUser = true; 
	        
	            List<Database.SaveResult> sr = Database.update(toUpdateBrand, dml);
	        }

        }        
    }
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}*/