force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Height_Percentile__c.field-meta.xml
<CustomField>
    <fullName>Height_Percentile__c</fullName>
    <label>Height Percentile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Height_Status__c.field-meta.xml
<CustomField>
    <fullName>Height_Status__c</fullName>
    <label>Height Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Medical_Nutrition_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Medical_Nutrition_Created_Date__c</fullName>
    <label>Medical Nutrition Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Household__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (End User)</relationshipLabel>
    <relationshipName>BrandRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/MedicalDiagnosis__c.field-meta.xml
<CustomField>
    <fullName>MedicalDiagnosis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nutrition History</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.CallRegarding__c</field>
            <operation>equals</operation>
            <valueField>Medical_Diagnosis__c.Contact__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Medical_Diagnosis__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Diagnosis__c/Medical_Diagnosis__c.object-meta.xml
<CustomObject>
    <label>Nutrition History</label>
    <nameField>
        <displayFormat>MD-{000000000}</displayFormat>
        <label>Nutrition History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nutrition Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Diagnosis__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <label>Height (cm)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medical_Diagnosis__c/fields/Height_Percentile__c.field-meta.xml
<CustomField>
    <fullName>Height_Percentile__c</fullName>
    <label>Height Percentile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Below 3rd Percentile</fullName>
            </value>
            <value>
                <fullName>3rd to 15th Percentile</fullName>
            </value>
            <value>
                <fullName>15th to 50th Percentile</fullName>
            </value>
            <value>
                <fullName>50th to 85th Percentile</fullName>
            </value>
            <value>
                <fullName>85th to 97th Percentile</fullName>
            </value>
            <value>
                <fullName>Above 97th Percentile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Diagnosis__c/fields/Height_Status__c.field-meta.xml
<CustomField>
    <fullName>Height_Status__c</fullName>
    <label>Height Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Diagnosis__c/fields/Medical_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Medical_Diagnosis__c</fullName>
    <label>Medical Diagnosis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bed Ridden- Old Age</fullName>
            </value>
            <value>
                <fullName>Cancer (All types of Cancer)</fullName>
            </value>
            <value>
                <fullName>Child with Special Needs</fullName>
            </value>
            <value>
                <fullName>Constipation</fullName>
            </value>
            <value>
                <fullName>Crying</fullName>
            </value>
            <value>
                <fullName>C-section</fullName>
            </value>
            <value>
                <fullName>Diarrhea</fullName>
            </value>
            <value>
                <fullName>Eye, Ears, Nose, Throat Condition</fullName>
            </value>
            <value>
                <fullName>Family History of Diabetes</fullName>
            </value>
            <value>
                <fullName>Flatulence</fullName>
            </value>
            <value>
                <fullName>For Normal &amp; healthy person</fullName>
            </value>
            <value>
                <fullName>Gastrointestinal Disease</fullName>
            </value>
            <value>
                <fullName>Geriatric Conditions (Alzheimer/Parkinson Disease)</fullName>
            </value>
            <value>
                <fullName>Gestational diabetes</fullName>
            </value>
            <value>
                <fullName>Haemotological Diseases</fullName>
            </value>
            <value>
                <fullName>Heart Disease</fullName>
            </value>
            <value>
                <fullName>Hypercholesterolemia (High Cholestrol)</fullName>
            </value>
            <value>
                <fullName>Hypertension (High Blood pressure)</fullName>
            </value>
            <value>
                <fullName>Insulin Dependant (Type 1 Diabetes)</fullName>
            </value>
            <value>
                <fullName>Muscle Disease</fullName>
            </value>
            <value>
                <fullName>Muscle Mass Loss</fullName>
            </value>
            <value>
                <fullName>Neurological Disease</fullName>
            </value>
            <value>
                <fullName>Non-Insulin Dependant (Type 2 Diabetes)</fullName>
            </value>
            <value>
                <fullName>Osteopenia</fullName>
            </value>
            <value>
                <fullName>Osteoporosis</fullName>
            </value>
            <value>
                <fullName>Post- Surgery</fullName>
            </value>
            <value>
                <fullName>Prediabetes</fullName>
            </value>
            <value>
                <fullName>Renal Disease (CAPD)</fullName>
            </value>
            <value>
                <fullName>Renal Disease (Hemodialysis)</fullName>
            </value>
            <value>
                <fullName>Renal Disease (Pre-Dialysis)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NutritionHistoryTriggerHelper.cls
/*------------------------------------------------------------
Author:      Crissar Ibarra
Description: Helper class for Nutrition History object

History
10/25/2021   cribarra     Created
12/17/2021   fgomendoza   Enhancement
-------------------------------------------------------------------------------------------*/

public class NutritionHistoryTriggerHelper{
    
    public static void updateBROnCreateOfNH(Map<Id, Medical_Diagnosis__c> userToMDMap) {        
        List<BrandRelationship__c> brListToUpdate = new List<BrandRelationship__c>();
        for(BrandRelationship__c br: [SELECT ID, User__c, Height__c, Height_Percentile__c, Height_Status__c, Medical_Nutrition_Created_Date__c, Market__c FROM BrandRelationship__c WHERE User__c IN: userToMDMap.keySet() AND Market__c = 'MY'] ){
            br.Height__c = userToMDMap.get(br.User__c).Height__c;
            br.Height_Percentile__c = String.valueof(userToMDMap.get(br.User__c).Height_Percentile__c);
            br.Height_Status__c= String.valueof(userToMDMap.get(br.User__c).Height_Status__c);
            br.Medical_Nutrition_Created_Date__c = userToMDMap.get(br.User__c).CreatedDate.date();
            brListToUpdate.add(br);
        }
        if(!brListToUpdate.IsEmpty()){
            update brListToUpdate;
        }
    }

    public static void updateCaseNH(Map<Id, Id> caseToMDIdMap){
        List<Case> updateCaseList = new List<Case>();
        for(Case c : [SELECT Id, MedicalDiagnosis__c FROM Case WHERE Id IN: caseToMDIdMap.keySet()]){
            c.MedicalDiagnosis__c = caseToMDIdMap.get(c.Id);
            updateCaseList.add(c);
        }
        if(!updateCaseList.isEmpty()){
            update updateCaseList;
        }
    }
}