force-app/main/default/objects/BrandRelationship__c/BrandRelationship__c.object-meta.xml
<CustomObject>
    <label>Brand Relationship</label>
    <nameField>
        <displayFormat>BR-{0000000000}</displayFormat>
        <label>Brand Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BrandRelationship__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Relationship</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3 AND ((4 OR 5) OR (6 AND 7))) OR 8</booleanFilter>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.AvailableBrandRelationship__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Product2.CompetitorProduct__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>notEqual</operation>
            <value>AutomatedProcess</value>
        </filterItems>
        <filterItems>
            <field>$User.Market__c</field>
            <operation>contains</operation>
            <valueField>Product2.Market__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Bypass_Lookup_Filter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Relationships</relationshipLabel>
    <relationshipName>Brand_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/FirstChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>FirstChannelResponseDate__c</fullName>
    <label>First Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/LatestChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponseDate__c</fullName>
    <label>Latest Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>PrimaryContact__r.Market__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <label>Main Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Relationship (Main Contact)</relationshipLabel>
    <relationshipName>MainBrandRelationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BrandRelationship__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <label>Channel</label>
    <nameField>
        <label>Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/Channel_Ref_No__c.field-meta.xml
<CustomField>
    <fullName>Channel_Ref_No__c</fullName>
    <externalId>true</externalId>
    <label>Channel Ref No</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <defaultValue>$User.Market__c</defaultValue>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
                <isActive>false</isActive>
                <label>AU</label>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
                <isActive>false</isActive>
                <label>NZ</label>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>VN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brand Website</fullName>
            </value>
            <value>
                <fullName>Campaign Website</fullName>
            </value>
            <value>
                <fullName>Corporate Website</fullName>
            </value>
            <value>
                <fullName>Web - Others</fullName>
            </value>
            <value>
                <fullName>Modern</fullName>
            </value>
            <value>
                <fullName>Traditional</fullName>
            </value>
            <value>
                <fullName>Trade - Others</fullName>
            </value>
            <value>
                <fullName>Hospital/Clinic</fullName>
                <label>Hospital</label>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Ethical - Others</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Social - Others</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>Drug Store</fullName>
            </value>
            <value>
                <fullName>EC</fullName>
            </value>
            <value>
                <fullName>Ethical</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>HCP</fullName>
            </value>
            <value>
                <fullName>MMC</fullName>
            </value>
            <value>
                <fullName>PX</fullName>
            </value>
            <value>
                <fullName>Trade</fullName>
            </value>
            <value>
                <fullName>MKT - Others</fullName>
                <isActive>false</isActive>
                <label>MKT - Others</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/ChannelResponse__c.object-meta.xml
<CustomObject>
    <label>Channel Response</label>
    <nameField>
        <displayFormat>CR-{0000000000}</displayFormat>
        <label>Channel Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Channel Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelResponse__c/fields/BrandRelationship__c.field-meta.xml
<CustomField>
    <fullName>BrandRelationship__c</fullName>
    <label>Brand Relationship</label>
    <referenceTo>BrandRelationship__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Channel</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Registration</fullName>
            </value>
            <value>
                <fullName>Previous Registration - Same Brand</fullName>
            </value>
            <value>
                <fullName>Previous Registration - Different Brand</fullName>
                <isActive>false</isActive>
                <label>Previous Registration - Different Brand</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Channel Responses</relationshipLabel>
    <relationshipName>Channel_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>[1-Sep-21 Khai] This field is for troubleshooting by extracting out the market of the Contact</description>
    <formula>Contact__r.Market__c</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/PreviousRegistration_SameCampaign__c.field-meta.xml
<CustomField>
    <fullName>PreviousRegistration_SameCampaign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Previous Registration - Same Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/PreviousRegistrationAdult__c.field-meta.xml
<CustomField>
    <fullName>PreviousRegistrationAdult__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Previous Registration - Adult</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/PreviousRegistrationPediatric__c.field-meta.xml
<CustomField>
    <fullName>PreviousRegistrationPediatric__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Previous Registration - Pediatric</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChannelResponse__c/fields/RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>RegistrationDate__c</fullName>
    <label>Registration Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FirstChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>FirstChannelResponseDate__c</fullName>
    <label>First Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LatestChannelResponseDate__c.field-meta.xml
<CustomField>
    <fullName>LatestChannelResponseDate__c</fullName>
    <label>Latest Channel Response Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>TEXT(Account.Market__c)</formula>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SMSOptOut__c.field-meta.xml
<CustomField>
    <fullName>SMSOptOut__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Adult.recordType-meta.xml
<RecordType>
    <fullName>Adult</fullName>
    <active>true</active>
    <label>Adult</label>
</RecordType>

force-app/main/default/classes/ChannelResponseEventHandler.cls
/*
Author: Jericson 
Description: Channel Response post transactional process
Date:
    May 14, 2020 Jericson - Created
	Jan	21, 2021 Jennifer - Added updateMCEligibility
    Mar 31, 2021 Jennifer - Moved updateMCEligibility to ChannelResponseTriggerHandler
    Jun 03, 2021 Jennifer - Added updateANZContact 
	Jan 14, 2022 Paolo - Added re-opt in calls via new channel response [TKT-007465] = Made some updates
*/
public class ChannelResponseEventHandler {

    public static void processEvent(List<ChannelResponse__ChangeEvent> events) {

        Set<Id> crIds = new Set<Id>();
        Set<Id> anzIds = new Set<Id>();

        for(ChannelResponse__ChangeEvent event: events) {

            EventBus.ChangeEventHeader header = event.ChangeEventHeader;
            // CREATE
            if(header.changeType == 'CREATE') {
                crIds.add(header.recordIds[0]);
                if(event.Channel__c != null) {
                    anzIds.add(header.recordIds[0]);
                } 
            }

            // UPDATE
            else if(header.changeType == 'UPDATE') {
                if(header.changedFields.contains('RegistrationDate__c')) {
                    crIds.add(header.recordIds[0]);
                }
            }
        }

        if(!crIds.isEmpty()) updateBRandContact(crIds);
        if(!anzIds.isEmpty()) updateANZContact(anzIds);
    }

    public static void updateBRandContact(Set<Id> crIds) {

        Map<Id, BrandRelationship__c> brToUpdateMap = new Map<Id, BrandRelationship__c>();
        Map<Id, Contact> contactMap = new Map<Id, Contact>();
        Map<Id, ChannelResponse__c> crMap = new Map<Id, ChannelResponse__c>();

        for(ChannelResponse__c cr: [SELECT  Id, Channel__c, Channel__r.Name, Channel__r.Channel_Ref_No__c,
                                            Campaign__c,
                                            CreatedDate,
                                            Classification__c, 
                                            PreviousRegistration_SameCampaign__c,
                                            PreviousRegistrationAdult__c,
                                            PreviousRegistrationPediatric__c,
                                            RegistrationDate__c,
                                            BrandRelationship__c,
                                            BrandRelationship__r.FirstChannelResponseDate__c, 
                                            BrandRelationship__r.LatestChannelResponseDate__c,
                                            BrandRelationship__r.PrimaryContact__c,
                                            BrandRelationship__r.PrimaryContact__r.FirstChannelResponseDate__c,
                                            BrandRelationship__r.PrimaryContact__r.LatestChannelResponseDate__c,
                                            BrandRelationship__r.PrimaryContact__r.Type__c,
                                    		BrandRelationship__r.PrimaryContact__r.DoNotCall,
                                    		BrandRelationship__r.PrimaryContact__r.SMSOptOut__c,
                                    		BrandRelationship__r.PrimaryContact__r.HasOptedOutOfEmail,
											BrandRelationship__r.PrimaryContact__r.Market__c,
                                            BrandRelationship__r.BrandRelationship__r.AvailableBrandRelationship__c,
                                            BrandRelationship__r.BrandRelationship__r.isActive,
                                            BrandRelationship__r.BrandRelationship__r.Market__c,
                                            BrandRelationship__r.BrandRelationship__r.CompetitorProduct__c
                                        FROM ChannelResponse__c
                                        WHERE Id IN: crIds]) {

            Boolean forUpdate = false;
            BrandRelationship__c br = brToUpdateMap.containsKey(cr.BrandRelationship__c) ?
                                        brToUpdateMap.get(cr.BrandRelationship__c)
                                        : new BrandRelationship__c(
                                                Id = cr.BrandRelationship__c,
                                                PrimaryContact__c = cr.BrandRelationship__r.PrimaryContact__c,
                                                FirstChannelResponseDate__c = cr.BrandRelationship__r.FirstChannelResponseDate__c, 
                                                LatestChannelResponseDate__c = cr.BrandRelationship__r.LatestChannelResponseDate__c);

            Datetime registrationDate = cr.RegistrationDate__c == null ? cr.CreatedDate : cr.RegistrationDate__c;

            /********************************* BRAND RELATIONSHIP ***********************************/
            // first CR
            if(br.FirstChannelResponseDate__c  == null
                || registrationDate < br.FirstChannelResponseDate__c) {

                br.FirstChannelResponse__c = cr.Channel__c;
                br.FirstChannelResponseDate__c = registrationDate;

                // retro
                if(cr.Classification__c == CommonConstant.CHANNELRESPONSE_CLASSIFICATION_FIRSTTIME) {
                    br.NewtoBrand__c = true;
                    br.NewtoBrandDate__c = date.valueOf(registrationDate);
                }
                forUpdate = true;
            }

            // last CR
            if(br.LatestChannelResponseDate__c == null
                || registrationDate > br.LatestChannelResponseDate__c) {
                br.LatestChannelResponse__c = cr.Channel__c;
                br.LatestCampaign__c = cr.Campaign__c;
                br.LatestChannelResponseDate__c = registrationDate;
                forUpdate = true;
            }

            if(forUpdate)
                brToUpdateMap.put(br.Id, br);

            /********************************* Contact ***********************************/
            // run only for Adult
            if(cr.BrandRelationship__r.PrimaryContact__r.Type__c == 'Adult') {
                forUpdate = false;
                Contact con = contactMap.containsKey(br.PrimaryContact__c) ?
                            contactMap.get(br.PrimaryContact__c) :
                            new Contact(Id = br.PrimaryContact__c,
                                        FirstChannelResponseDate__c = cr.BrandRelationship__r.PrimaryContact__r.FirstChannelResponseDate__c,
                                        LatestChannelResponseDate__c = cr.BrandRelationship__r.PrimaryContact__r.LatestChannelResponseDate__c);

                // first CR
                if(con.FirstChannelResponseDate__c  == null
                    || registrationDate < con.FirstChannelResponseDate__c) {

                    con.FirstChannelResponse__c = cr.Channel__c;
                    con.FirstChannelResponseDate__c = registrationDate;
                    forUpdate = true;
                }

                // last CR
                if(con.LatestChannelResponseDate__c == null
                    || registrationDate > con.LatestChannelResponseDate__c) {

                    con.LatestChannelResponse__c = cr.Channel__c;
                    con.LatestCampaign__c = cr.Campaign__c;
                    con.LatestChannelResponseDate__c = registrationDate;
                    forUpdate = true;
                }

                //TKT-007963 - HCP_Sampling_T2_PED
                if(cr.Channel__c != null && cr.Channel__r.Channel_Ref_No__c != null && cr.Channel__r.Channel_Ref_No__c.equalsIgnoreCase('TW_HCP_Sampling_T2') ){
                    con.Have_Purchased_Paid_Sample__c = true;
                    forUpdate = true;
                }

                //TKT-009281 - TW_HCP_Sampling_T3_PED
                if(cr.Channel__c != null && cr.Channel__r.Channel_Ref_No__c != null && cr.Channel__r.Channel_Ref_No__c.equalsIgnoreCase('TW_HCP_Sampling_T3') ){
                    con.Have_Purchased_Paid_Sample__c = true;
                    forUpdate = true;
                }

                //TKT-009072 - Abbott Family Rewards SG channel
                if(cr.Channel__c != null && cr.Channel__r.Channel_Ref_No__c != null && cr.Channel__r.Channel_Ref_No__c.equalsIgnoreCase('SG-AFR') ) {
                    cr.Classification__c = '';
                    cr.PreviousRegistration_SameCampaign__c = false;
                    cr.PreviousRegistrationAdult__c = false;
                    cr.PreviousRegistrationPediatric__c = false;
                    crMap.put(cr.Id, cr);
                    forUpdate = true;
                }

				// added by paolo - [TKT-007465]
                if(cr.BrandRelationship__r.PrimaryContact__r.Market__c.equals(CommonConstant.MARKET_TW) && cr.BrandRelationship__r.PrimaryContact__r.DoNotCall == True){
					con.DoNotCall = False;
                    con.SMSOptOut__c = False;
                    con.HasOptedOutOfEmail = False;
                    forUpdate = True;
				}

                if(forUpdate)
                    contactMap.put(con.Id, con);
            }
        }

        if(!brToUpdateMap.isEmpty()) UtilityClass.updateList(brToUpdateMap.values()); 
        if(!contactMap.isEmpty()) UtilityClass.updateList(contactMap.values());
        if(!crMap.isEmpty()) UtilityClass.updateList(crMap.values());
    }

    // TKT-004312: update ANZ contact when HENS And Consumer CR is created
    public static void updateANZContact(Set<Id> crIds) {
        Map<Id, Contact> contactMap = new Map<Id, Contact>();
      
        for(ChannelResponse__c cr: [SELECT Id, is_Hens__c,is_Consumer__c, Contact__c, BrandRelationship__c, 
                                    BrandRelationship__r.PrimaryContact__c,
                                    BrandRelationship__r.PrimaryContact__r.is_HENS__c,
                                    BrandRelationship__r.PrimaryContact__r.is_Consumer__c
                                    FROM ChannelResponse__c 
                                    WHERE Id IN: crIds AND Contact__r.Market__c = 'ANZ']) {   
                                
            Boolean forUpdate = false; 

            Contact con = contactMap.containsKey(cr.Contact__c) ?
            contactMap.get(cr.Contact__c) :
            new Contact(Id = cr.BrandRelationship__r.PrimaryContact__c,
                        is_Hens__c = cr.BrandRelationship__r.PrimaryContact__r.is_HENS__c,
                        is_Consumer__c = cr.BrandRelationship__r.PrimaryContact__r.is_Consumer__c);

            if(cr.is_Hens__c && !con.is_Hens__c){
                con.is_Hens__c = cr.is_Hens__c;
                forUpdate = true;      
            }
            else if(cr.is_Consumer__c && !con.is_Consumer__c){
                con.is_Consumer__c = cr.is_Consumer__c;
                forUpdate = true;   
            }

            if(forUpdate){  
                contactMap.put(con.Id, con);
            }
    	}

        if(!contactMap.isEmpty()) UtilityClass.updateList(contactMap.values());
    }
}