force-app/main/default/objects/Medical_Diagnosis__c/Medical_Diagnosis__c.object-meta.xml
<CustomObject>
    <label>Nutrition History</label>
    <nameField>
        <displayFormat>MD-{000000000}</displayFormat>
        <label>Nutrition History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nutrition Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Diagnosis__c/fields/CreatedforIntegration__c.field-meta.xml
<CustomField>
    <fullName>CreatedforIntegration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created for Integration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medical_Diagnosis__c/fields/EndUser__c.field-meta.xml
<CustomField>
    <fullName>EndUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Nutrition Histories (End User)</relationshipLabel>
    <relationshipName>Nutrition_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Diagnosis__c/fields/Medical_Diagnosis__c.field-meta.xml
<CustomField>
    <fullName>Medical_Diagnosis__c</fullName>
    <label>Medical Diagnosis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bed Ridden- Old Age</fullName>
            </value>
            <value>
                <fullName>Cancer (All types of Cancer)</fullName>
            </value>
            <value>
                <fullName>Child with Special Needs</fullName>
            </value>
            <value>
                <fullName>Constipation</fullName>
            </value>
            <value>
                <fullName>Crying</fullName>
            </value>
            <value>
                <fullName>C-section</fullName>
            </value>
            <value>
                <fullName>Diarrhea</fullName>
            </value>
            <value>
                <fullName>Eye, Ears, Nose, Throat Condition</fullName>
            </value>
            <value>
                <fullName>Family History of Diabetes</fullName>
            </value>
            <value>
                <fullName>Flatulence</fullName>
            </value>
            <value>
                <fullName>For Normal &amp; healthy person</fullName>
            </value>
            <value>
                <fullName>Gastrointestinal Disease</fullName>
            </value>
            <value>
                <fullName>Geriatric Conditions (Alzheimer/Parkinson Disease)</fullName>
            </value>
            <value>
                <fullName>Gestational diabetes</fullName>
            </value>
            <value>
                <fullName>Haemotological Diseases</fullName>
            </value>
            <value>
                <fullName>Heart Disease</fullName>
            </value>
            <value>
                <fullName>Hypercholesterolemia (High Cholestrol)</fullName>
            </value>
            <value>
                <fullName>Hypertension (High Blood pressure)</fullName>
            </value>
            <value>
                <fullName>Insulin Dependant (Type 1 Diabetes)</fullName>
            </value>
            <value>
                <fullName>Muscle Disease</fullName>
            </value>
            <value>
                <fullName>Muscle Mass Loss</fullName>
            </value>
            <value>
                <fullName>Neurological Disease</fullName>
            </value>
            <value>
                <fullName>Non-Insulin Dependant (Type 2 Diabetes)</fullName>
            </value>
            <value>
                <fullName>Osteopenia</fullName>
            </value>
            <value>
                <fullName>Osteoporosis</fullName>
            </value>
            <value>
                <fullName>Post- Surgery</fullName>
            </value>
            <value>
                <fullName>Prediabetes</fullName>
            </value>
            <value>
                <fullName>Renal Disease (CAPD)</fullName>
            </value>
            <value>
                <fullName>Renal Disease (Hemodialysis)</fullName>
            </value>
            <value>
                <fullName>Renal Disease (Pre-Dialysis)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medical_Diagnosis__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Nutrition History</relationshipLabel>
    <relationshipName>Nutrition_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NutritionHistoryTriggerHandler.cls
/*------------------------------------------------------------
Author:      Crissar Ibarra
Description: Handler class for Nutritin History object
                  
10/25/2021   cribarra     Created
-------------------------------------------------------------------------------------------*/

public class NutritionHistoryTriggerHandler implements ITriggerHandler{

    public void BeforeInsert(List<SObject> newList) {}
    
    public void BeforeUpdate(List<SObject> newList, Map<Id, SObject> newMapItems, List<SObject> oldList, Map<Id, SObject> oldMapItems) {}
    
    public void BeforeDelete(List<SObject> oldList, Map<Id, SObject> oldItems){}
    
    public void AfterInsert(List<SObject> newList, Map<Id, SObject> newMapItems){ 
        Map<Id, Medical_Diagnosis__c> userToMDMap = new Map<Id, Medical_Diagnosis__c>();
        Map<Id, Id> caseToMDIdMap = new Map<Id, Id>();
        List<Medical_Diagnosis__c> newMDList = (List<Medical_Diagnosis__c>) newList;
        for(Medical_Diagnosis__c md : newMDList){
            //For updateBROnCreateOfNH method
            if(md.EndUser__c != null) {
                userToMDMap.put(md.EndUser__c, md);
            }
            //For updateCaseNH method
            if(md.Related_Case__c != null && md.CreatedforIntegration__c == true){
                caseToMDIdMap.put(md.Related_Case__c, md.Id);
            }
        }
        if(!userToMDMap.keySet().isEmpty()) NutritionHistoryTriggerHelper.updateBROnCreateOfNH(userToMDMap);
        if(!caseToMDIdMap.keySet().isEmpty()) NutritionHistoryTriggerHelper.updateCaseNH(caseToMDIdMap);
    }
    
    public void AfterUpdate(List<SObject> newList , Map<Id, SObject> newMapItems, List<SObject> oldList, Map<Id, SObject> oldMapItems){
        Map<Id, Id> caseToMDIdMap = new Map<Id, Id>();
        List<Medical_Diagnosis__c> newMDList = (List<Medical_Diagnosis__c>) newList;
        for(Medical_Diagnosis__c md : newMDList){
            Medical_Diagnosis__c oldMd = (Medical_Diagnosis__c) oldMapItems.get(md.Id);
            if(md.Related_Case__c != null && md.CreatedforIntegration__c == true && oldMd.Related_Case__c != md.Related_Case__c){
                caseToMDIdMap.put(md.Related_Case__c, md.Id);
            }
        }
        if(!caseToMDIdMap.keySet().isEmpty()) NutritionHistoryTriggerHelper.updateCaseNH(caseToMDIdMap);
    }
    
    public void AfterDelete(List<SObject> oldList, Map<Id, SObject> oldMapItems){}
}